pixiebrix/pixiebrix-extension

contrib/blocks/google-search.yaml
src/background.ts
src/background/executor.ts
src/background/logging.ts
src/background/navigation.ts
src/background/protocol.ts
src/blocks/combinators.ts
src/blocks/effects/forms.ts
src/blocks/effects/redirectPage.ts
src/blocks/readers/jquery.ts
src/contentScript.ts
src/contentScript/backgroundProtocol.ts
src/contentScript/executor.ts
src/contentScript/lifecycle.ts
src/core.ts
src/extensionPoints/menuItemExtension.ts
src/tests/ConsoleLogger.ts

POC to run an effect on on the opener page

#106: remote effect POC

---

src/background/devtools.ts
src/devTools/Editor.tsx
src/devTools/Panel.scss
src/devTools/editor/ElementWizard.tsx
src/devTools/editor/Sidebar.tsx
src/devTools/editor/editorSlice.ts
src/devTools/editor/extensionPoints/base.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/extensionPoints/panel.ts
src/devTools/editor/extensionPoints/trigger.ts
src/nativeEditor/selector.ts

Some devtools usability improvements:
* Allow placement cancel
* Reset button when editing installed extensions
* Default extension name improvement

#211: devtools usability improvements

---

src/devTools/editor/extensionPoints/base.ts
src/devTools/editor/tabs/ReaderTab.tsx
src/nativeEditor/infer.test.tsx
src/nativeEditor/infer.ts
src/nativeEditor/insertButton.tsx
src/utils.ts

* Ensure unique reader id generation
* Don't include chevron-down icon for icon detection
* Fix caption/icon ordering by considering text position

#211: id generation and button inference improvements

---

src/components/fields/BlockField.tsx
src/components/fields/BlockModal.tsx
src/devTools/editor/tabs/EffectTab.scss

* Block highlight color
* Auto-expand new block configuration
* Forget previous block search

#235: block selection behavior

---

src/auth/token.ts
src/background.ts
src/background/contextMenus.ts
src/background/devtools/internal.ts
src/background/preload.ts
src/background/telemetry.ts
src/contentScript.ts
src/contentScript/contextMenus.ts
src/contentScript/lifecycle.ts
src/core.ts
src/devTools/editor/Sidebar.tsx
src/devTools/editor/useCreate.ts
src/extensionPoints/contextMenu.ts
src/hooks/auth.ts
src/options/App.tsx
src/options/pages/InstalledPage.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/services/PrivateServicesCard.tsx
src/options/slices.ts
src/telemetry/rollbar.ts
src/types.ts
src/types/definitions.ts

* fix content menu lifecycle bugs
* add event reporting in page editor

255: fix content menu lifecycle bugs; add event reporting in page editor

---

src/background/installer.ts
src/devTools/editor/Sidebar.tsx
src/devTools/editor/extensionPoints/contextMenu.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/extensionPoints/panel.ts
src/devTools/editor/extensionPoints/trigger.ts
src/devTools/editor/tabs/ServicesTab.tsx
src/devTools/editor/tabs/contextMenu/AvailabilityTab.tsx
src/devTools/editor/tabs/contextMenu/FoundationTab.tsx
src/devTools/editor/tabs/contextMenu/MenuItemTab.tsx
src/devTools/editor/tabs/reader/ReaderBlockConfig.tsx
src/layout/Sidebar.tsx
src/options/App.tsx
src/options/pages/InstalledPage.tsx
src/options/pages/extensionEditor/ExtensionPointDetail.tsx
src/options/pages/extensionEditor/ServicesFormCard.tsx
src/options/pages/marketplace/ActivateBody.tsx
src/options/pages/marketplace/ActivatePage.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/marketplace/ConfigureBody.tsx
src/options/pages/services/PrivateServicesCard.tsx
src/options/pages/services/ServiceEditorModal.tsx
src/options/pages/services/ServicesEditor.tsx
src/options/pages/templates/TemplatesPage.scss
src/options/pages/templates/TemplatesPage.tsx
src/pages/marketplace/MarketplacePage.scss
src/pages/marketplace/MarketplacePage.tsx

* on-boarding UX improvements
* clean up CSS for template screen
* uninstall flow
* simplify context menu tabs in page editor
* switch from "Services" to "Integrations"

257: UX improvements

---

src/blocks/effects/redirectPage.ts
src/contentScript/backgroundProtocol.ts
src/devTools/editor/tabs/EffectTab.tsx
src/devTools/editor/useCreate.ts
src/frameworks/contrib/ember.ts
src/messaging/chrome.ts
src/messaging/constants.ts
src/nativeEditor/frameworks.ts
src/nativeEditor/infer.ts
src/nativeEditor/selector.ts
src/script.ts
src/utils.ts

* Fix save of dnd buttons
* Selector inference error handling
* Ember reader recursion depth

235: page editor and emberjs bug fixes

---

browsers/chrome/manifests/manifest.template.json
browsers/chrome/webpack/webpack.dev.js
browsers/chrome/webpack/webpack.prod.js
browsers/src/support.html
browsers/webpack/webpack.base.js
package-lock.json
package.json
src/blocks/readers/PageSemanticReader.ts
src/blocks/readers/index.ts
src/blocks/transformers/mapping.ts
src/components/ChatWidget.scss
src/components/ChatWidget.tsx
src/devTools/Editor.tsx
src/devTools/Panel.scss
src/devTools/editor/ElementWizard.tsx
src/devTools/editor/tabs/reader/ReaderBlockConfig.tsx
src/frameworks/component.ts
src/frameworks/contrib/angularjs.ts
src/frameworks/contrib/ember.ts
src/frameworks/contrib/react.ts
src/frameworks/contrib/vue.ts
src/support.js

* Semantic web reader
* WIP: live chat widget, and corresponding CSP changes
* Add "hadData" to framework adapters to speed up element detection

#247, #276: semantic web reader, live chat widget

---

browsers/chrome/manifests/manifest.template.json
src/devTools/editor/editorSlice.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/tabs/menuItem/MenuItemTab.tsx
src/extensionPoints/menuItemExtension.ts
src/options/pages/templates/TemplatesPage.tsx
src/pages/marketplace/MarketplacePage.tsx

- Add shared templates section on templates page
- Add dynamicCaption field for menu items to avoid unnecessary reads

281: shared templates screen, dynamic caption support for menu items

---

contrib/services/automation-anywhere.yaml
schemas/icon.json
src/background/auth.ts
src/background/executor.ts
src/background/requests.ts
src/blocks/combinators.ts
src/blocks/effects/alert.ts
src/blocks/effects/index.ts
src/blocks/renderers/table.ts
src/blocks/transformers/detect.ts
src/blocks/transformers/httpGet.ts
src/blocks/transformers/index.ts
src/blocks/transformers/prompt.ts
src/contentScript/lifecycle.ts
src/contrib/automationanywhere/BotOptions.tsx
src/contrib/automationanywhere/index.ts
src/contrib/automationanywhere/run.ts
src/contrib/editors.ts
src/contrib/index.ts
src/core.ts
src/extensionPoints/dom.tsx
src/extensionPoints/helpers.ts
src/extensionPoints/panelExtension.ts
src/extensionPoints/triggerExtension.ts
src/hooks/common.ts
src/icons/svgIcons.ts
src/services/factory.ts
src/services/registry.ts
src/types.ts

- Panel lifecycle improvements
- New brick to prompt user for string input
- Automation Anywhere Control Center API prototype

290: panel lifecycle; prompt bricks; automation anywhere prototype

---

browsers/chrome/manifests/manifest.template.json
browsers/webpack/webpack.base.js
src/background/auth.ts
src/background/executor.ts
src/background/requests.ts
src/contentScript/uipath.ts
src/contrib/uipath/UiPathRobot.ts
src/contrib/uipath/localProcess.ts
src/contrib/uipath/localProcessOptions.tsx
src/contrib/uipath/process.ts
src/contrib/uipath/processOptions.tsx
src/contrib/uipath/quietLogger.ts

* RobotJS: pass along result of robot JS, show input arguments in page editor
* Orchestrator: support waiting for arguments
* Silence application insights telemetry

294: uipath improvements

---

src/blocks/transformers/remoteMethod.ts
src/extensionPoints/menuItemExtension.ts

- Conditional menu items
- Support relative urls in remoteMethod

305: conditional menu items

---

package.json
src/blocks/effects/index.ts
src/blocks/effects/pageState.ts
src/components/fields/blockOptions.tsx
src/contrib/uipath/process.ts
src/contrib/uipath/processOptions.tsx
src/validators/generic.ts

* Page state set/get actions
* Support orchestrator service alternative for UiPath run process

317: page state actions; service alternatives

---

package-lock.json
src/background/auth.ts
src/contrib/uipath/localProcessOptions.tsx
src/contrib/uipath/process.ts
src/contrib/uipath/processOptions.tsx
src/options/pages/deployments/DeploymentBanner.tsx
src/options/pages/marketplace/ActivateBody.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/marketplace/ConfigureBody.tsx
src/options/pages/services/ServiceEditorModal.tsx
src/permissions/index.ts
src/services/factory.ts
src/services/hooks.ts
src/types/definitions.ts

* Request service permissions on install
* Support alternative UiPath permissions in page editor

#348: request service permissions on install

---

src/background.ts
src/background/deployment.ts
src/options/loader.ts
src/options/pages/InstalledPage.scss
src/options/pages/InstalledPage.tsx

- Show deployment as single line on installed extensions page
- Check for deployment updates every 10 min

#350 deployment maintenance

---

src/background/auth.ts
src/background/deployment.ts
src/background/executor.ts
src/background/logging.ts
src/blocks/available.ts
src/blocks/combinators.ts
src/blocks/effects/forms.ts
src/blocks/effects/pageState.ts
src/blocks/readers/jquery.ts
src/blocks/renderers/dataTable.ts
src/blocks/renderers/table.ts
src/blocks/transformers/mapping.ts
src/blocks/transformers/modal.tsx
src/contentScript.ts
src/contrib/hubspot/upsert.ts
src/contrib/pipedrive/calendar.ts
src/contrib/pipedrive/resolvers.ts
src/contrib/uipath/localProcess.ts
src/contrib/uipath/process.ts
src/contrib/uipath/processOptions.tsx
src/contrib/zapier/push.ts
src/errors.ts
src/options/pages/deployments/hooks.ts
src/script.ts
src/telemetry/rollbar.ts

* Split error hierarchy into business and application errors
* Set rollbar error to debug for enterprise users
* Switch out table component for a react component
* Report activated deployments to the server

#372: split error hierarchy; rollbar levels; table component

---

src/background/installer.ts
src/layout/Banner.scss
src/options/App.tsx
src/options/pages/Settings.tsx
src/options/pages/UpdateBanner.tsx

- Show banner on extension page if extension update is available
- Add button on extensions setting back to check for updates

#384: update extension banner

---

package-lock.json
src/messaging/external.ts
src/options/pages/SetupPage.tsx
src/options/pages/marketplace/ActivatePage.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/marketplace/ConfigureBody.tsx

- Expose method/message to trigger install from the web app
- Clarify which extensions are active during marketplace install

#405: trigger install from web app

---

schemas/service.json
src/services/factory.ts
src/types/definitions.ts

Has a corresponding schema update on app.pixiebrix.com to support saving new service configurations with the option

#433: support baseURL option in key-based authentication

---

.eslintrc
package-lock.json
package.json

The React rules were already in there, just added the React hooks and a Redux rule set. 
Will separately need to create a path toward enforcing the rules as part of the PR process in a way that's not annoying

#429: react hooks and redux rules

---

browsers/webpack.config.js

For #411 
Needs jq-web testing

#411: Drop a few Node polyfills

---

src/background/installer.ts

I think it may skew your analytics (and slightly annoy me 😃)

Don't open uninstall page while debugging

---

browsers/webpack.config.js
package-lock.json
package.json

Closes https://github.com/pixiebrix/pixiebrix-extension/issues/506

Notify on reload

---

browsers/webpack.config.js

Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/518

#518: Fix injection of rollbar path

---

browsers/src/options.html
src/auth/AuthContext.ts
src/core.ts
src/devTools/Panel.tsx
src/devTools/editor/Sidebar.tsx
src/hooks/organization.ts
src/hooks/title.ts
src/layout/Banner.tsx
src/layout/Navbar.tsx
src/layout/Sidebar.tsx
src/options/App.tsx
src/options/pages/InstalledPage.tsx
src/options/pages/MarketplacePage.tsx
src/options/pages/Settings.tsx
src/options/pages/SetupPage.tsx
src/options/pages/brickEditor/CreatePage.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/extensionEditor/ExtensionPointDetail.tsx
src/options/pages/extensionEditor/WorkshopPage.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/services/PrivateServicesCard.tsx
src/options/pages/services/ServiceEditorModal.tsx
src/options/pages/services/ServicesEditor.tsx
src/options/pages/templates/TemplatesPage.tsx

#538: update tab titles; code cleanup

---

src/background/installer.ts

#543: uninstall page for DNT

---

package-lock.json
package.json
src/options/pages/brickEditor/CodeEditor.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/extensionEditor/ExtensionPointDetail.tsx

Closes #545
* Working reliably in the workshop code editor screen
* Inconsistent behavior in workshop extension editor

545: save shortcut poc

---

package-lock.json
package.json
src/components/fields/BlockModal.tsx
src/options/pages/brickEditor/BrickReference.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/extensionEditor/WorkshopPage.scss
src/options/pages/extensionEditor/WorkshopPage.tsx
src/options/slices.ts
src/options/store.ts

#547: workshop search improvements

---

src/blocks/util.ts
src/components/fields/BlockModal.tsx
src/options/pages/brickEditor/BrickReference.tsx
src/options/pages/brickEditor/CodeEditor.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/brickEditor/Editor.tsx
src/options/pages/extensionEditor/WorkshopPage.tsx
src/types/contract.ts

#551: workshop editor navigation

---

src/core.ts
src/devTools/editor/ElementWizard.tsx
src/devTools/editor/Sidebar.tsx
src/devTools/editor/editorSlice.ts
src/devTools/editor/extensionPoints/actionPanel.ts
src/devTools/editor/extensionPoints/adapter.ts
src/devTools/editor/extensionPoints/base.ts
src/devTools/editor/extensionPoints/contextMenu.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/extensionPoints/panel.ts
src/devTools/editor/tabs/EffectTab.tsx
src/devTools/editor/tabs/LockedFoundationTab.tsx
src/devTools/editor/tabs/actionPanel/FoundationTab.tsx
src/devTools/editor/tabs/actionPanel/PanelTab.tsx
src/nativeEditor/dynamic.ts

#559: add side panel support to page editor

---

src/background/protocol.ts

#572: revert externalSendMessage changes

---

package.json
src/options/pages/Settings.tsx

Adds support for revoking optional host permissions from the settings pages
Closes #587

#587: support for revoking host permissions

---

src/options/loader.ts

#610: handle empty options storage

---

.eslintrc
browsers/webpack.config.js
src/devTools/store.ts
src/options/store.ts

#561: disable redux devtools in prod

---

src/devTools/editor/hooks/editorHooks.ts

Follows https://github.com/pixiebrix/pixiebrix-extension/pull/594 and #577

#577: Add confirmation to reset button

---

.github/workflows/integration.yml
package-lock.json
package.json

#635: fix header generation; pin css-selector-generator

---

src/background/requests.ts
src/options/pages/extensionEditor/ServiceAuthSelector.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/validators/validation.ts

#645: support for pixiebrix API in bricks

---

src/components/ConfirmNavigationModal.tsx
src/options/pages/brickEditor/Editor.tsx
src/options/pages/brickEditor/useSubmitBrick.tsx

#555: unsaved changes indicator; confirm navigation on if unsaved changes

---

package-lock.json
package.json

Fixes #671 
Code change to review is in https://github.com/fregante/content-scripts-register-polyfill/pull/27/files

#671: Restore page editor use immediately after granting permanent permission

---

.eslintrc
src/blocks/readers/ArrayCompositeReader.ts
src/nativeEditor/Overlay.tsx
src/nativeEditor/infer.ts

Some small fixes around .reduce

---

src/devTools/editor/hooks/useCreate.ts

#706: fix use of yaml safeDump

---

package-lock.json
package.json

#755: pin react-spinners to 0.9.0

---

src/devTools/ScopeSettings.tsx

Closes #763 
I couldn't immediately get the scroll working on the row, so I just added it to the column

#763: add scrollbar to scope entry screen

---

src/blocks/errors.ts
src/blocks/transformers/jq.ts

#771: translate jq compile errors into `InputValidationError`s

---

src/devTools/editor/ElementWizard.tsx
src/devTools/editor/extensionPoints/actionPanel.tsx
src/devTools/editor/extensionPoints/base.ts
src/devTools/editor/extensionPoints/contextMenu.tsx
src/devTools/editor/extensionPoints/elementConfig.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/extensionPoints/panel.ts
src/devTools/editor/extensionPoints/trigger.tsx
src/devTools/editor/hooks/useCreate.ts
src/devTools/editor/panes/insert/InsertMenuItemPane.tsx
src/devTools/editor/panes/insert/InsertPanelPane.tsx
src/devTools/editor/panes/insert/useAddExisting.ts
src/devTools/editor/tabs/reader/ReaderBlockConfig.tsx
src/devTools/editor/tabs/reader/ReaderConfig.tsx
src/devTools/editor/tabs/reader/ReaderTab.tsx
src/icons/svgIcons.ts

Closes #765
Future work
- Refactor extension point adapters to use base class to ensure consistency/ease code re-use across the adapters

#765: fix use of existing extension points in Page Editor

---

src/components/logViewer/LogTable.stories.tsx
src/vendors/pkce.ts
tsconfig.json

https://www.typescriptlang.org/tsconfig#strictBindCallApply

Turn on strictBindCallApply

---

src/blocks/effects/cancel.ts
src/blocks/effects/error.ts

#787: fix cancel effect; add business error effect

---

.github/dependabot.yml

#799: Limit dependabot PRs

---

src/blocks/effects/highlight.ts
src/blocks/effects/index.ts
src/blocks/effects/show.ts

#833: add brick to show hidden element

---

src/devTools/Editor.tsx
src/devTools/Panel.tsx

@fregante I think this should fix the problem enough. If not, we'll have to look at caching the author scope on the background page
Closes #814

#814: optimistically load main page editor screen

---

src/background/locator.ts

#840: fix locator.refresh options

---

src/manifest.json

Manifest fixes

---

src/background/browserAction.ts
src/components/AsyncButton.stories.tsx
src/components/fields/TextField.stories.tsx
src/components/logViewer/LogTable.stories.tsx

- Required for: https://github.com/pixiebrix/pixiebrix-app/pull/257

Fix issues found when updating the app

---

src/layout/Banner.tsx
src/messaging/external.ts

- For https://github.com/pixiebrix/pixiebrix-app/pull/257

Allow <Banner> usage in app

---

src/actionPanel/ActionPanelApp.tsx
src/actionPanel/DefaultActionPanel.tsx
src/actionPanel/PanelBody.tsx
src/actionPanel/native.tsx
src/actionPanel/protocol.tsx
src/background/contextMenus.ts
src/background/deployment.ts
src/devTools/editor/panes/insert/GenericInsertPane.tsx
src/extensionPoints/contextMenu.ts
src/extensionPoints/menuItemExtension.ts
src/hooks/useExtensionMeta.ts
src/options/pages/deployments/DeploymentBanner.tsx
src/options/pages/deployments/hooks.ts
src/options/pages/marketplace/ActivateBody.tsx
src/options/slices.ts
src/telemetry/deployments.ts

Closes #890 
Fixes some lint from the new rules we added in https://github.com/pixiebrix/pixiebrix-extension/pull/887

#890: improve deployment telemetry; delint some code

---

src/actionPanel/PanelBody.tsx
src/background/logging.ts
src/blocks/combinators.ts
src/components/AsyncButton.tsx
src/components/logViewer/LogToolbar.tsx
src/components/logViewer/useLogEntries.ts
src/core.ts
src/extensionPoints/actionPanelExtension.ts
src/extensionPoints/contextMenu.ts
src/extensionPoints/helpers.ts
src/extensionPoints/menuItemExtension.ts
src/extensionPoints/panelExtension.ts
src/extensionPoints/triggerExtension.ts
src/options/pages/brickEditor/BrickLogs.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/brickEditor/useLogContext.ts
src/telemetry/deployments.ts
src/telemetry/events.ts

Fixes #895 
* Includes the `blueprintId` in log metadata the workshop can query it when showing the logs for a blueprint
* Fixes some lint I came across while tracing down the bug
* Fixes bug in AsyncButton where it'd call setState on an unmounted component

#895: fix blueprint logging

---

src/blocks/effects/redirectPage.ts
src/blocks/transformers/index.ts
src/blocks/transformers/url.ts

#936: add construct URL brick

---

.eslintrc
package-lock.json
package.json
src/actionPanel/DefaultActionPanel.tsx

#933: enable recommended a11y ruleset as warnings

---

src/background.ts
src/background/util.ts
src/layout/ErrorModal.tsx
src/options/App.tsx

This converts ErrorBanner to ErrorModal, which resets the `error` url param upon close.

#915: error banner to modal

---

src/background/__mocks__/protocol.ts
src/background/dataStore.ts
src/background/devtools/internal.ts
src/background/protocol.ts
src/background/requests.ts
src/common.ts
src/contentScript/backgroundProtocol.ts
src/contentScript/externalProtocol.ts
src/messaging/protocol.ts
src/vendors/libraryDetector/detect.ts

I found myself having to make changes around the lifters and the overloads make it easy to make mistakes. This PR avoids the overloads and tightens up the types as a result.

Tighten lifters’ types up

---

.storybook/preview.js
resolve.config.js
src/action.tsx
src/background/auth.ts
src/blocks/transformers/blockFactory.ts
src/common.ts
src/devtoolsPanel.tsx
src/extensionPoints/helpers.ts
src/options/App.tsx
tsconfig.json

`vendors` itself can be a dependency inside `node_modules` so it might cause trouble. Also it's occasionally failing to resolve for me, it's an unnecessary complexity.

Drop unnecessary vendors symlink

---

package-lock.json
package.json

See https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
I don't think this actually does anything though, as we're not running the application using node, we're just building it?

#700: add engine section to package.json

---

package-lock.json
package.json

As suggested in https://github.com/pixiebrix/pixiebrix-extension/pull/960

Remove unused dependency: canvas

---

src/blocks/transformers/remoteMethod.ts

#979: mark data property optional in pixiebrix/http

---

src/background/requests.ts
src/contrib/automationanywhere/BotOptions.tsx
src/contrib/editors.ts
src/contrib/uipath/LocalProcessOptions.tsx
src/contrib/uipath/ProcessOptions.tsx
src/contrib/uipath/localProcess.ts
src/contrib/uipath/process.ts
src/services/useDependency.ts

Closes #987 
The UX still isn't great, because the Select widgets just show blanks while the values are loading (which can take awhile on a slow connection)
TODO:

#987: fix useDependency nullness check; clean some lint

---

src/hooks/useDeployments.ts

#1010: fix NPE in useDeployments for ad-hoc extensions

---

package-lock.json
package.json
src/devTools/editor/components/Effect.tsx

Related:
- https://github.com/pixiebrix/pixiebrix-extension/pull/1016
- #411

Drop single `fast-deep-equal` use

---

src/actionPanel/native.tsx
src/background/browserAction.ts
src/blocks/effects/notification.ts
src/blocks/readers/meta.ts
src/blocks/renderers/iframe.ts
src/contentScript/lifecycle.ts
src/contrib/uipath/embedApp.ts
src/devTools/editor/tabs/AvailabilityTab.tsx
src/devTools/editor/tabs/contextMenu/AvailabilityTab.tsx
src/devTools/editor/tabs/contextMenu/MenuItemTab.tsx
src/messaging/external.ts
src/telemetry/rollbar.ts

Related to:
- #490 
- https://github.com/pixiebrix/pixiebrix-app/issues/350
- https://github.com/pixiebrix/pixiebrix-extension/issues/1029
Changes:
- Avoid using `chrome.*` APIs: only `getManifest` (types issue) and _that special chrome.runtime.sendMessage_ are left
- Replace any public reference to Chrome with "the browser"

Change Chrome-specific code and copy

---

src/options/pages/extensionEditor/ServiceAuthSelector.tsx

Fixes an eslint error that was breaking the build

#931: fix lint error and build

---

src/background/executor.ts
src/blocks/combinators.ts
src/blocks/transformers/blockFactory.ts
src/contentScript/executor.ts
src/core.ts
src/utils.ts

- Adds logging for brick execution errors during broadcast
- Cleans up eslint

#1056: broad cast logging; lint cleanup

---

src/action.html
src/devtools.html
src/devtoolsPanel.html
src/frame.html
src/manifest.json
src/options.html
src/permissionsPopup.html
webpack.config.js

- Fixes #1014 
I love easy wins.
It's hard to make sense of the following static images, but I'll include them for reference:

#1014: Add vendor bundle

---

src/devTools/editor/hooks/useRemove.ts
src/hooks/useDeployments.ts
src/options/pages/installed/InstalledPage.tsx
src/options/slices.ts
src/pages/marketplace/useReinstall.ts
src/selectors.ts
src/store/extensions.ts
src/types/contract.ts

- Extension removal bug in reducer
- Extension lookup bug in useExtension

#1078: fix bugs introduced in #1079

---

src/components/logViewer/LogTable.stories.tsx
src/contrib/automationanywhere/BotOptions.tsx
src/contrib/uipath/process.ts
src/devTools/editor/extensionPoints/base.ts
src/options/pages/extensionEditor/ExtensionEditor.tsx
src/options/pages/extensionEditor/ExtensionPointDetail.tsx
src/selectors.ts
src/services/locator.ts
src/services/registry.ts
src/types.ts
src/types/helpers.ts
src/utils.ts
src/validators/validation.ts

- Fix NPE when navigating from workshop brick to workshop home screen
- Improve castRegistryId method name

Fix NPE when navigating from workshop brick to workshop home screen

---

src/extensionPoints/menuItemExtension.ts
src/extensionPoints/panelExtension.ts
src/icons/IconSelector.tsx

Will cherry pick the merge commit over to create a PR against main

#1103: fix NPE in calls to getSvgIcon

---

src/components/schemaTree/SchemaTree.stories.tsx
src/components/schemaTree/SchemaTree.tsx
src/components/schemaTree/entries/ArrayEntry.tsx
src/components/schemaTree/entries/ObjectEntry.tsx
src/components/schemaTree/entries/PrimitiveEntry.tsx
src/components/schemaTree/types.ts
src/devTools/editor/tabs/reader/ReaderBlockConfig.tsx
src/devTools/editor/tabs/reader/ReaderConfig.tsx
src/options/pages/brickEditor/BrickReference.tsx
src/options/pages/extensionEditor/DataSourceCard.tsx

Extracts the SchemaViewer component its own folder under components

#990: extract schema viewer; create storybook

---

src/options/pages/installed/InstalledPage.tsx

#1106: adding a whitespace at InstalledPage

---

package-lock.json
package.json
src/options/pages/brickEditor/Editor.tsx
src/vendors/AceEditor.tsx

#1114 Enabling Ace Editor search box

---

src/background/devtools/protocol.ts
src/background/logging.ts
src/blocks/combinators.ts
src/blocks/transformers/jq.ts
src/components/logViewer/EntryRow.tsx
src/components/logViewer/LogTable.tsx
src/core.ts
src/errors.ts
src/extensionPoints/helpers.ts
src/nativeEditor/selector.ts
src/services/errors.ts
src/utils.ts

#1145: fix logger.debug calls; add support for label in logs

---

package-lock.json
package.json

Closes #1048 
I created issue https://github.com/pixiebrix/pixiebrix-extension/issues/1148 to update the dependency once the fixed version is published to npm

#1048: temporarily pin to fixed version of webext-detect-page

---

src/blocks/transformers/httpGet.ts
src/blocks/transformers/remoteMethod.ts

Closes #1168: supports other primitives for params

#1168: support primitives for params

---

src/blocks/readers/frameworkReader.ts
src/blocks/readers/jquery.ts
src/blocks/readers/registerReaders.ts
src/devTools/editor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
src/extensionPoints/triggerExtension.ts
src/options/pages/marketplace/AuthWidget.tsx
src/utils.ts

Closes #1172: fixes handling of empty selectors
Closes #1173: fixes registration of framework reader

#1172, #1173: fix reader registration and load trigger saving

---

selenium/readme.md
webpack.config.js

Fix local sourcemaps

---

src/background/contextMenus.ts
src/devTools/editor/sidebar/Sidebar.tsx
src/options/slices.ts

#1169: fix id check bug; defensive programming in context menu update/create logic

---

src/background/contextMenus.ts
src/background/requests.ts
src/baseRegistry.ts
src/hooks/useRefresh.ts
src/options/pages/brickEditor/useSubmitBrick.tsx
src/options/pages/brickEditor/validate.ts
src/options/pages/services/PrivateServicesCard.tsx
src/options/pages/services/ServiceEditorModal.tsx
src/options/pages/services/ServicesEditor.tsx
src/services/locator.ts

#1171: update background service definitions on workshop save

---

package.json

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/1120

#1120: Disable console.log in Jest tests

---

src/options/pages/brickEditor/BlockResult.module.scss
src/options/pages/brickEditor/BlockResult.tsx
src/options/pages/brickEditor/BrickDetail.module.scss
src/options/pages/brickEditor/BrickDetail.tsx
src/options/pages/brickEditor/BrickReference.module.scss
src/options/pages/brickEditor/BrickReference.tsx

Fixing a couple of styles issues plus applying CSS modules.
Let's review the approach to styling in this PR (related to #985 ).
cc @BLoe

#1058 Brick detail. Styles.

---

.github/workflows/ci.yml

Set up Packtracker on CI

---

.eslintrc
src/blocks/available.ts
src/blocks/readers/CompositeReader.ts
src/components/AsyncButton.tsx
src/components/fields/BlockField.tsx
src/components/fields/IconField.tsx
src/devTools/Locator.tsx
src/layout/Navbar.tsx
src/options/App.tsx
src/options/pages/brickEditor/CreatePage.tsx
src/options/pages/brickEditor/Sharing.tsx
src/options/pages/services/ConnectExtensionCard.tsx
src/options/pages/services/SharedServicesCard.tsx
src/pages/marketplace/MarketplacePage.tsx
src/utils/permissions.ts

Suggested in:
- https://github.com/pixiebrix/pixiebrix-extension/issues/480#issue-918940697
This PR only enables one restriction about mocks, but it's mostly to ready it for future suggestions. Do you have any suggestions already?

Restrict imports via eslint 

---

src/options/pages/brickEditor/CodeEditor.tsx
src/options/pages/brickEditor/referenceTab/BrickDetail.tsx
src/vendors/AceEditorSync.tsx

#1221 Lazy load Ace editor

---

src/options/pages/installed/ActiveBricksCard.tsx
src/options/pages/installed/ExtensionGroup.tsx
src/options/pages/installed/ExtensionLogsModal.module.scss
src/options/pages/installed/ExtensionLogsModal.tsx
src/options/pages/installed/ExtensionRows.tsx
src/options/pages/installed/InstalledExtensionRow.tsx
src/options/pages/installed/InstalledPage.tsx
src/options/pages/installed/installedPageSelectors.ts
src/options/pages/installed/installedPageSlice.ts
src/options/store.ts

#1196: active extension logs

---

.github/workflows/ci.yml

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/1253

Disable packtracker on dependabot PRs

---

src/auth/token.ts

Moved to the app project: https://github.com/pixiebrix/pixiebrix-app/pull/542/files#diff-597b924e3c35273be0039f0cd7f0ac068efebd816da634ef9e52fb8efe00852fR4

Remove dead code

---

src/auth/token.ts
src/background/telemetry.ts
src/hooks/fetch.ts
src/services/apiClient.ts
src/services/locator.ts

#1260, #1261: handle missing response object in fetch

---

package-lock.json
package.json
src/__mocks__/webextDetectPage.ts
src/components/fields/BlockModal.tsx
src/components/fields/ServiceModal.tsx
src/options/pages/brickEditor/referenceTab/BlockResult.tsx
src/options/pages/brickEditor/referenceTab/BrickDetail.test.tsx
src/options/pages/brickEditor/referenceTab/BrickDetail.tsx
src/options/pages/brickEditor/referenceTab/BrickReference.tsx
src/options/pages/installed/ExtensionLogsModal.tsx
src/options/pages/services/PrivateServicesCard.tsx
src/options/pages/services/ServicesEditor.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/808
Error example:
```
'./actionPanel/ActionPanelApp' import is restricted from being used by a pattern. Use root-based imports (`import "@/something"`) instead of relative imports. [Error/no-restricted-imports]
```
I made this a warning for now because it finds 201 instances and they require manual intervention. Alternatively the PR can be left open until I fix them.
```
❯ nr lint -- --quiet --format unix
/Users/rico/Dev/pixie/pixiebrix-extension/src/__mocks__/webextDetectPage.ts:20
/Users/rico/Dev/pixie/pixiebrix-extension/src/action.tsx:23
/Users/rico/Dev/pixie/pixiebrix-extension/src/action.tsx:34
/Users/rico/Dev/pixie/pixiebrix-extension/src/background.ts:28
/Users/rico/Dev/pixie/pixiebrix-extension/src/background.ts:29 …
```

Restrict parent imports, use @-imports instead

---

package-lock.json
package.json

This: https://github.com/pixiebrix/pixiebrix-extension/pull/1258#issuecomment-916580694
Changes: https://github.com/pixiebrix/webext-messenger/commit/f009d19448edf2a06455cd0839a163709f45ce33

Serialize Messenger errors

---

src/blocks/readers/meta.ts
src/blocks/readers/registerReaders.ts
src/headers.ts

Closes #632 
Remove Chrome Profile Reader reader b/c it doesn't work and there aren't any compelling use cases

#632: remove chrome profile reader

---

src/options/pages/installed/ShareExtensionModal.test.tsx

It seems to be related to the fix #1268

#1269 Mocking useNotifications and useOrganization

---

src/background/devtools/contract.ts
src/background/devtools/internal.ts
src/background/devtools/protocol.ts
src/background/util.ts
src/contentScript/backgroundProtocol.ts
src/contentScript/devTools.ts
src/types.ts

I saw this type was created in multiple places. It might make sense to standardize it as we move to unify the messaging infra.

Unify Target type

---

src/options/pages/deployments/DeploymentBanner.tsx

#1335: show deployment banner on `/`

---

src/options/pages/workshop/WorkshopPage.tsx

Move the Create Brick button to the standard page toolbar

Move Create Brick button to the page toolbar

---

src/components/form/FieldTemplate.tsx
src/devTools/editor/ElementWizard.module.scss
src/devTools/editor/ElementWizard.tsx
src/devTools/editor/components/UrlMatchPatternWidget.module.scss
src/devTools/editor/components/UrlMatchPatternWidget.tsx
src/devTools/editor/extensionPoints/actionPanel.tsx
src/devTools/editor/extensionPoints/contextMenu.tsx
src/devTools/editor/extensionPoints/elementConfig.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/extensionPoints/panel.ts
src/devTools/editor/extensionPoints/trigger.tsx
src/devTools/editor/tabs/actionPanel/PanelConfiguration.module.scss
src/devTools/editor/tabs/actionPanel/PanelConfiguration.tsx
src/devTools/editor/tabs/editTab/EditTab.module.scss
src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.module.scss

This adds the configuration panel for side panels to the edit tab
_Note: this panel currently shows up regardless of extension type, beta UI only works for side panels right now_

Page Editor beta UI panel configuration

---

src/components/form/ConnectedFieldTemplate.tsx
src/devTools/editor/tabs/EffectTab.tsx
src/devTools/editor/tabs/editTab/EditTab.module.scss
src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/TraceView.module.scss
src/devTools/editor/tabs/editTab/TraceView.tsx
src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.module.scss
src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.module.scss
src/devTools/editor/tabs/effect/BlockConfiguration.tsx

Update Page Editor beta UI to show trace data in a panel

---

src/devTools/editor/extensionPoints/actionPanel.tsx
src/devTools/editor/extensionPoints/elementConfig.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/FoundationTraceView.tsx
src/devTools/editor/tabs/editTab/TraceView.tsx
src/devTools/editor/tabs/menuItem/MenuItemConfiguration.module.scss
src/devTools/editor/tabs/menuItem/MenuItemConfiguration.tsx
src/devTools/editor/tabs/menuItem/TemplateWidget.tsx

Future work to improve:
- Standardize field groups (basic vs. advanced)
- Refactor common code for template widget
- Refactor description for sites widget

#1318: menu item node options

---

src/devTools/editor/tabs/editTab/TraceView.tsx
src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx

Feature/Swap output key and title for editor node, and add a copy button to the data

---

src/components/formBuilder/FieldEditor.tsx

#1356 Updating property name on blur

---

src/components/form/widgets/OptionsWidget.module.scss
src/components/form/widgets/OptionsWidget.tsx
src/components/formBuilder/FieldEditor.tsx
src/components/formBuilder/formBuilderHelpers.ts

Adds Dropdows type to the FormBuilder.

#1188 Dropdown UI Type

---

src/components/formBuilder/FormPreview.tsx
src/components/formBuilder/FormPreviewBooleanField.module.scss
src/components/formBuilder/FormPreviewBooleanField.tsx
src/components/formBuilder/FormPreviewFieldTemplate.module.scss
src/components/formBuilder/FormPreviewFieldTemplate.tsx
src/components/formBuilder/formBuilderHelpers.ts

#1188 Form builder. More field formats

---

src/components/formBuilder/FieldEditor.tsx
src/components/formBuilder/FormEditor.test.tsx
src/components/formBuilder/FormEditor.tsx
src/components/formBuilder/FormPreview.test.tsx
src/components/formBuilder/FormPreview.tsx
src/components/formBuilder/__snapshots__/FormEditor.test.tsx.snap
src/components/formBuilder/__snapshots__/FormPreview.test.tsx.snap
src/components/formBuilder/formBuilderTestHelpers.tsx
src/tests/testItRenders.tsx

Unit tests for `FormBuilder` and `FormPreview`.
Bugfix for property name filed.

#1188 Form builder QA

---

src/components/fields/schemaFields/ServiceField.tsx
src/components/form/widgets/RemoteSelectWidget.tsx
src/contrib/automationanywhere/BotOptions.tsx
src/contrib/automationanywhere/contract.ts
src/core.ts
src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
src/options/slices.ts

- Partially fixes the AA configuration screen. Blocked by inconsistency in how SelectWidget works/what value it expects
- Adds a Formik view tab in DEBUG builds
- Adds a raw brick config view tab in DEBUG builds

AA configuration fixes

---

src/components/fields/schemaFields/ServiceField.tsx
src/components/form/ConnectedFieldTemplate.tsx
src/components/form/FieldTemplate.tsx
src/components/form/Form.stories.tsx
src/components/formBuilder/FieldEditor.tsx
src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
src/contrib/uipath/LocalProcessOptions.tsx
src/contrib/uipath/ProcessOptions.tsx
src/contrib/zapier/pushOptions.tsx
src/devTools/editor/tabs/menuItem/MenuItemConfiguration.tsx

Fixing null value in FieldComponent

---

src/blocks/transformers/component/ComponentReaderOptions.tsx
src/components/fields/schemaFields/BooleanField.tsx
src/components/form/FieldTemplate.tsx
src/components/form/Form.stories.tsx
src/components/form/switchButton/SwitchButton.stories.tsx
src/components/form/switchButton/SwitchButton.tsx
src/options/pages/installed/ShareExtensionModal.tsx
src/options/pages/installed/__snapshots__/ShareExtensionModal.test.tsx.snap

#1424 Making SwitchButton compatible with Formik

---

src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx

Use feature flag for showing data panel tabs

---

src/blocks/transformers/component/ComponentReaderOptions.tsx
src/contrib/editors.ts
src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
src/contrib/google/sheets/TabField.tsx
src/contrib/google/sheets/append.ts
src/contrib/google/sheets/handlers.ts
src/contrib/google/sheets/lookup.ts
src/contrib/google/sheets/sheetsHelpers.ts
src/contrib/registerContribBlocks.ts
src/headers.ts

#1446: sheet lookup brick

---

src/devTools/editor/hooks/useInstallState.ts

This prevents a crash caused by undefined values coming from async state.

Bug fix: Add default values for async state calls in useInstallState()

---

src/blocks/combinators.ts
src/blocks/readers/frameworkReader.ts
src/blocks/transformers/component/ComponentReader.ts
src/blocks/transformers/component/ComponentReaderOptions.tsx
src/contentScript/devTools.ts
src/devTools/editor/fields/SelectorSelectorWidget.tsx
src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
src/devTools/editor/tabs/effect/BlockPreview.tsx
src/frameworks/contrib/ember.ts
src/frameworks/dom.ts
src/nativeEditor/frameworks.ts

#1448: reader ergonomics; fix ember reader

---

src/background/auth.ts
src/blocks/transformers/blockFactory.ts

Closes #1461
Also fixes bug in computing purity of composite bricks

#1461: implicit oauth grant flow

---

src/components/form/switchButton/SwitchButton.tsx
src/components/formBuilder/FieldEditor.tsx
src/components/formBuilder/FormEditor.test.tsx
src/components/formBuilder/__snapshots__/FormEditor.test.tsx.snap
src/components/formBuilder/__snapshots__/FormPreview.test.tsx.snap
src/components/formBuilder/formBuilderTestHelpers.tsx
src/components/formBuilder/formEditor.testCases.ts

Fixes #1458 
Updates `required` array on renaming a property.
Unit tests.

#1458: Fixing required field

---

src/components/brickModal/BrickModal.tsx
src/components/fields/schemaFields/ChildObjectField.tsx
src/components/fields/schemaFields/ServiceField.tsx
src/components/form/widgets/RemoteMultiSelectWidget.tsx
src/components/form/widgets/RemoteSelectWidget.tsx
src/contrib/RequireServiceConfig.tsx
src/contrib/automationanywhere/BotOptions.tsx
src/contrib/remoteOptionUtils.ts
src/contrib/uipath/LocalProcessOptions.tsx
src/contrib/uipath/ProcessOptions.tsx
src/contrib/uipath/embedApp.ts
src/contrib/uipath/process.ts
src/devTools/Editor.tsx
src/devTools/Panel.tsx
src/options/pages/services/PrivateServicesCard.module.scss
src/options/pages/services/PrivateServicesCard.tsx
src/utils.ts

#829: custom options fixes

---

package-lock.json
package.json
src/components/form/widgets/SelectWidget.tsx
src/components/formBuilder/FieldEditor.tsx
src/components/formBuilder/FormEditor.test.tsx
src/components/formBuilder/FormPreview.tsx
src/components/formBuilder/__snapshots__/FormEditor.test.tsx.snap
src/components/formBuilder/formBuilderHelpers.ts
src/components/formBuilder/formEditor.testCases.ts

#1444 FormBuilder. File input

---

src/components/form/FieldTemplate.tsx
src/components/form/Form.stories.tsx
src/components/form/switchButton/SwitchButton.tsx
src/components/formBuilder/__snapshots__/FormEditor.test.tsx.snap
src/options/pages/installed/__snapshots__/ShareExtensionModal.test.tsx.snap

It may make sense to merge this PR after the release

#1429 Do not use FormControl with custom widgets

---

src/background/auth.ts
src/background/requests.ts
src/chrome.ts
src/options/pages/services/PrivateServicesCard.tsx

#1514: fix auth data NPE on new installs

---

src/devTools/store.ts
src/options/store.ts

Closes #1476 
See redux-persist discussion: https://github.com/rt2zz/redux-persist/issues/988#issuecomment-654875104

#1476: fix redux serialization warning

---

src/options/pages/installed/ExtensionGroup.tsx

#1532: control deployment uninstalls via feature flag

---

src/background.ts
src/background/contextMenus.ts
src/background/initContextMenus.ts
src/contentScript/contextMenus.ts
src/extensionPoints/contextMenu.ts
src/options/slices.ts
src/registry/internal.ts

Closes #1537 
I created https://github.com/pixiebrix/pixiebrix-extension/issues/1542 for cleanup, which will require fixing the webext-messenger dependency

#1537: fix context menu runtime bugs

---

src/contrib/automationanywhere/BotOptions.tsx
src/contrib/uipath/LocalProcessOptions.tsx
src/contrib/uipath/ProcessOptions.tsx
src/contrib/uipath/uipathHooks.ts
src/utils/cachePromise.ts

#1465: cache remote options

---

src/layout/Sidebar.tsx
src/options/App.tsx
src/options/pages/installed/ExtensionGroup.tsx
src/options/pages/settings/AdvancedSettings.tsx
src/options/pages/settings/SettingsPage.tsx
src/pages/marketplace/MarketplacePage.tsx

Closes #1536 
Flags to restrict functionality:
- restricted-workshop
- restricted-services
- restricted-marketplace
- restricted-service-url
- restricted-permissions
- restricted-reset
- restricted-uninstall

#1536: feature flag interface

---

src/contentScript/devTools.ts
src/devTools/editor/tabs/effect/BlockConfiguration.tsx
src/devTools/editor/tabs/effect/BlockPreview.tsx

Closes #1766 
Additional:
- Add field description to the Condition field
- Refactor Preview component to use useReducer instead of 3 useStates

#1766: fix preview of bricks using services

---

src/background/executor.ts

- Fixes #1798 
Untested, but this looks identical to https://github.com/pixiebrix/pixiebrix-extension/issues/1585 and therefore I just updated the message initially set in https://github.com/pixiebrix/pixiebrix-extension/pull/1586/files

#1798: fix execute in target retry logic

---

package-lock.json
package.json
src/background/messenger/api.ts
src/contentScript/messenger/api.ts

- Installs https://github.com/pixiebrix/webext-messenger/pull/52
Part of the incremental changes required after https://github.com/pixiebrix/webext-messenger/issues/45
It appears to work correctly with minimal testing. 
This should only be a no-change refactor, I try to merge this kind of changes in order to pick up errors early. Also I've been trying to space out Messenger changes for a similar reason: To be able to pick up and address possible errors I might have made, before building any further on top of them.
I was reviewing the open issues and I don't see anything related to the Messenger except this low-priority issue https://github.com/pixiebrix/pixiebrix-extension/issues/1724

Use Messenger with explicit target

---

src/blocks/effects/forms.ts

- Closes #1715
https://user-images.githubusercontent.com/1402241/140163575-e89939f1-283e-407e-a886-3832c363f35d.mov

#1715: Improve contentEditable "set" support

---

src/runtime/pipelineTests/root.test.ts
src/runtime/reducePipeline.ts
src/runtime/runtimeUtils.ts

#1823: add runtime tests for root mode

---

src/runtime/pipelineTests/implicitDataFlow.test.ts
src/runtime/pipelineTests/pipelineTestHelpers.ts
src/runtime/reducePipeline.ts

#1853: handle passing array as context in v1

---

src/blocks/effects/tour.ts
src/vendors/intro.js/introjs.css
src/vendors/intro.js/introjs.scss

- Removes dark mode theme which appears to have broken layout
- Adds a local CSS file that applies a font color to the tooltip so the default theme works on sites with white font color on the body

#1858: tour font color fix

---

src/blocks/effects/tour.ts
src/blocks/util.ts

#1875: wait for stylesheet to be fetched to avoid FOUC

---

src/nativeEditor/infer.ts
src/nativeEditor/selector.ts

Minor selector inference tweaks

---

package-lock.json
package.json
src/components/form/Form.stories.tsx
src/components/form/widgets/createMenuListWithAddButton.tsx

#1806 Limit height of database selection dropdown

---

src/devTools/editor/hooks/useCreate.ts
src/devTools/editor/panes/save/useSavingWizard.test.tsx
src/devTools/editor/panes/save/useSavingWizard.ts
src/options/slices.ts

#1892 Fixes Saving as New Blueprint also saves extension as Personal Extension

---

schemas/component.json
schemas/effect.json
schemas/extensionPoint.json
schemas/reader.json
schemas/recipe.json
schemas/renderer.json
schemas/service.json
src/Globals.d.ts
src/devTools/editor/extensionPoints/trigger.tsx
src/devTools/editor/tabs/trigger/TriggerConfiguration.tsx
src/extensionPoints/helpers.ts
src/extensionPoints/triggerExtension.ts
src/types.ts

#1920: add attachMode to trigger to support adding triggers when new page elements are added

---

src/devTools/editor/panes/save/useSavingWizard.test.tsx
src/devTools/editor/panes/save/useSavingWizard.ts
src/options/slices.ts

#1891 Saving a blueprint extension as a Personal Extension should uninstall the blueprint version

---

src/components/formBuilder/FieldEditor.tsx
src/components/formBuilder/__snapshots__/FormEditor.test.tsx.snap

#1862 Errors in Page Editor / FieldEditor with "uncontrolled input" and null value

---

src/components/fields/schemaFields/v1/SchemaField.stories.tsx
src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/components/fields/schemaFields/v3/SchemaField.stories.tsx
src/components/fields/schemaFields/widgets/ObjectWidget.tsx
src/components/form/FieldTemplate.module.scss
src/components/form/FieldTemplate.tsx
src/devTools/editor/hooks/useToggleFormField.test.tsx
src/devTools/editor/hooks/useToggleFormField.tsx
src/runtime/pathHelpers.test.ts
src/runtime/pathHelpers.ts

Closes #1916
Adds a bunch more stories, including stories for the v3 runtime.

#1916: Schema field storybook

---

src/devTools/editor/extensionPoints/trigger.tsx
src/devTools/editor/tabs/trigger/TriggerConfiguration.tsx
src/extensionPoints/triggerExtension.ts

Closes #1930
Closes #1928
TODO:

#1930: target mode for triggers

---

src/actionPanel/PanelBody.tsx
src/blocks/renderers/documentView/__snapshots__/documentView.test.tsx.snap
src/blocks/renderers/documentView/documentView.test.tsx
src/blocks/renderers/documentView/documentView.tsx

#1872 Document brick. Card component + Tests.

---

src/devTools/editor/extensionPoints/contextMenu.tsx
src/devTools/editor/tabs/contextMenu/ContextMenuConfiguration.tsx
src/devTools/editor/tabs/effect/v1/BlockConfiguration.tsx
src/devTools/editor/tabs/effect/v3/BlockConfiguration.tsx
src/extensionPoints/contextMenu.ts

Match the terminology of the extensionPoint on trigger

#1947: rename change rootMode to targetMode

---

src/background/executor.ts
src/blocks/effects/registerEffects.ts
src/blocks/effects/wait.ts
src/devTools/context.ts
src/headers.ts
src/utils.ts

#1950: wait brick; maxWaitMillis input for await element brick

---

src/hooks/useDeployments.ts
src/hooks/useNotifications.ts

#1886: fix error toast style

---

src/blocks/effects/wait.ts

Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/1951

#1950: add additional logging to wait

---

src/components/fields/schemaFields/widgets/IntegerWidget.tsx
src/components/fields/schemaFields/widgets/NumberWidget.tsx

fix number widget

---

src/components/fields/schemaFields/v1/ServiceField.tsx
src/components/fields/schemaFields/v3/ServiceField.tsx
src/components/form/widgets/SelectWidget.tsx

#1870: Allow clearing the selected service in page editor service config field

---

src/actionPanel/RendererComponent.tsx
src/blocks/renderers/common.ts
src/blocks/renderers/dataTable.ts
src/blocks/renderers/html.ts
src/blocks/renderers/iframe.ts
src/blocks/renderers/markdown.ts
src/blocks/renderers/propertyTable.tsx
src/blocks/renderers/table.tsx
src/contrib/uipath/embedApp.ts
src/core.ts
src/frame.ts
src/utils/sanitize.ts

Closes #2021 
- Fixes a bug introduced in PanelBody where we were sanitizing the HTML which broke our iframe renderer
- I updated RenderedHTML to have a nominal type so we can track explicitly where we're passing around sanitized HTML

#2021: fix bug in iframe sanitization

---

src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/devTools/editor/tabs/editTab/EditTab.module.scss
src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx

#2030: Fix editor node config panel horizontal scroll

---

src/blocks/effects/event.ts
src/components/fields/schemaFields/fieldInputMode.ts
src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/components/fields/schemaFields/widgets/TextWidget.tsx

Fixes #1985 
This tweaks some stuff with TextWidget when used as a select/dropdown.

#1985: Fix Simulate DOM Event brick and tweak TextWidget for select

---

.eslintrc
src/background/devtools/internal.ts
src/blocks/effects/attachAutocomplete.ts
src/blocks/effects/event.ts
src/blocks/effects/hide.ts
src/blocks/effects/show.ts
src/blocks/effects/tour.ts
src/blocks/readers/jquery.ts
src/blocks/transformers/FormData.ts
src/blocks/transformers/detect.ts
src/blocks/transformers/regex.ts
src/contentScript/devTools.ts
src/contentScript/lifecycle.ts
src/devTools/Locator.tsx
src/devTools/context.ts
src/extensionPoints/helpers.ts
src/extensionPoints/menuItemExtension.ts
src/extensionPoints/triggerExtension.ts
src/helpers.ts
src/nativeEditor/dynamic.ts
src/nativeEditor/infer.test.tsx
src/nativeEditor/infer.ts
src/options/pages/brickEditor/referenceTab/BrickDetail.tsx
src/runtime/runtimeUtils.ts

There were a couple of lint rules that were set to `warn` only due to a couple of situations each. I fixed those places and let the default (`error`) through.

Drop some lint warnings

---

package.json

- Follows https://github.com/pixiebrix/playground/pull/21

Use new playground URL for web-ext

---

src/background/proxyService.test.ts
src/background/requests.ts
src/contrib/google/bigquery/handlers.ts
src/contrib/google/sheets/append.ts
src/devTools/Locator.tsx
tsconfig.json

#779: turn on useUnknownInCatchVariables

---

src/actionPanel/PanelBody.tsx
src/components/documentBuilder/DocumentList.tsx
src/contentScript/messenger/api.ts
src/contentScript/messenger/registration.ts
src/contentScript/pipelineProtocol.ts
src/runtime/mapArgs.ts

#2091: run map args in the content script from document builder

---

package-lock.json
package.json
src/background/activateBrowserActionIcon.ts
src/background/browserAction.ts
src/background/messenger/registration.ts
src/background/util.ts
src/contrib/google/initGoogle.ts
src/development/autoreload.ts
static/background.worker.js
static/grayIconWhileLoading.js
webpack.config.js

Extracted from:
- https://github.com/pixiebrix/pixiebrix-extension/pull/2107
To avoid keeping a MV3 fork, we can start merging these changes. Most of this code isn't read at all on MV2.
Together with other code, this will make it easier to gradually test MV3.
Before merging I just want to test it a little bit but otherwise changes are quite minimal.

Small MV3 changes that are fine for MV2

---

package-lock.json
package.json
src/Globals.d.ts
src/background/devtools/index.ts
src/background/iframes.ts
src/background/initContextMenus.ts
src/background/protocol.ts
src/components/formBuilder/formBuilderHelpers.ts
src/contentScript/externalProtocol.ts
src/devTools/editor/tabs/editTab/EditTab.tsx
src/icons/IconSelector.tsx
src/icons/list.ts
src/options/pages/installed/InstalledExtensionRow.tsx
src/options/pages/installed/InstalledPage.test.tsx
src/options/pages/installed/InstalledPage.tsx
src/options/pages/settings/PermissionsSettings.tsx
src/runtime/pipelineTests/autoescape.test.ts
src/runtime/pipelineTests/component.test.ts
src/runtime/pipelineTests/conditional.test.ts
src/runtime/pipelineTests/deploymentAlert.test.ts
src/runtime/pipelineTests/implicitDataFlow.test.ts
src/runtime/pipelineTests/options.test.ts
src/runtime/pipelineTests/outputKey.test.ts
src/runtime/pipelineTests/root.test.ts
src/runtime/pipelineTests/serviceContext.test.ts
src/runtime/pipelineTests/templateEngine.test.ts
src/runtime/pipelineTests/validateInput.test.ts

Companion to https://github.com/pixiebrix/eslint-config-pixiebrix/commit/2a5d6bcb5bff6daae54652d0ff7bf5646833ccb1

Enable some lint rules

---

src/components/fields/schemaFields/SchemaField.test.tsx
src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/devTools/editor/fields/devtoolFieldOverrides.tsx

#2084 Preserve field inputs when toggling

---

src/components/fields/schemaFields/SchemaField.test.tsx
src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/components/fields/schemaFields/widgets/WidgetLoadingIndicator.tsx
src/components/fields/schemaFields/widgets/v3/TextWidget.tsx

#2146 Fix bug - Only infer templated variable if field schema supports string input

---

src/blocks/registry.test.ts
src/blocks/registry.ts
src/components/brickModal/BrickModal.tsx
src/components/documentBuilder/edit/ElementBlockEdit.tsx
src/devTools/editor/hooks/usePipelineField.ts
src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/editTabTypes.ts
src/devTools/editor/validation/validateOutputKey.test.ts
src/devTools/editor/validation/validateOutputKey.ts
src/devTools/editor/validation/validateRenderers.test.ts
src/devTools/editor/validation/validateRenderers.ts
src/tests/factories.ts

Maintain a cache of all blocks with resolved types.

Cache resolved/inferred types for block in blockRegistry

---

src/components/documentBuilder/createNewElement.test.ts
src/components/documentBuilder/createNewElement.ts
src/components/documentBuilder/documentBuilderTypes.ts
src/components/documentBuilder/documentTree.tsx
src/components/documentBuilder/edit/ButtonOptions.tsx
src/components/documentBuilder/edit/ElementButtonEdit.tsx
src/components/documentBuilder/edit/getElementEditSchemas.ts
src/components/documentBuilder/edit/useElementOptions.tsx

Closes #2144 
Closes #1976 
Editor and Preview
Side panel (button rendered in a List element)

#2144 Document Builder. Button element.

---

src/actionPanel/PanelBody.tsx
src/components/documentBuilder/documentTree.test.tsx
src/components/documentBuilder/documentTree.tsx
src/components/documentBuilder/preview/DocumentPreview.test.tsx
src/components/documentBuilder/preview/ElementPreview.test.tsx
src/components/documentBuilder/preview/ElementPreview.tsx
src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap

Related to #1976 
- Fixes the Dropdown getting closed on hovering another element in Preview
- Removes onClick handler from the Button element in Preview
- Adds some unit tests

Document Builder. Enhancements and unit tests

---

src/extensionPoints/actionPanelExtension.ts

#2158: don't notify on side panel error

---

src/actionPanel/native.tsx
src/common.ts
src/components/quickBar/QuickBarApp.tsx
src/contentScript/notify.tsx

https://user-images.githubusercontent.com/1402241/146366249-b1744f62-39c0-4edd-a795-b815b58032e3.mov

Place notifications above sidebar + cleanup sidebar creation

---

src/devTools/Editor.tsx
src/devTools/editor/panes/save/useSavingWizard.ts
src/devTools/editor/slices/editorSlice.ts

Fixes #2162
Can't resave after updating team blueprint in Page Editor

#2162 Reload Formik state of active element when BP updated

---

src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/useBlockActions.ts

Tried to make as few changes as possible.

Fetching Brick actions from EditTab

---

src/devTools/editor/tabs/editTab/EditTab.tsx
src/devTools/editor/tabs/editTab/useBlockActions.ts

#2169 Fixing Block error shown on wrong block

---

src/manifest.json

#2182: re-add https: to connect-src

---

src/background/executor.ts

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2193
Compare this video with the one in https://github.com/pixiebrix/pixiebrix-extension/issues/2191#issuecomment-997892025
@twschiller does this also fix https://github.com/pixiebrix/pixiebrix-extension/issues/2191 for you?
https://user-images.githubusercontent.com/1402241/146773784-a1c5251c-1339-47db-86e8-fc02e184e224.mov

Use permissions instead of `tabReady` for broadcasting

---

src/components/documentBuilder/edit/getElementEditSchemas.ts
src/components/documentBuilder/preview/getPreviewComponentDefinition.tsx

#2223: ability to disable button in document builder

---

src/options/pages/brickEditor/referenceTab/BrickDetail.stories.tsx

Resolves #1917 
This fixes BrickDetail stories by wrapping the component in a `react-redux` provider.

fix brickdetail stories

---

src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/components/fields/schemaFields/widgets/BooleanWidget.tsx

#2239: Add BooleanWidget for schema fields

---

src/components/TooltipIconButton.tsx
src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx

#2244: Fix dev build console spam from TooltipIconButton

---

src/components/fields/schemaFields/AppServiceField.tsx
src/components/fields/schemaFields/SchemaFieldContext.tsx
src/components/fields/schemaFields/v3/SchemaField.tsx
src/devTools/editor/fields/DatabaseOptions.tsx

#2238 automatically set service for pixiebrix app service fields and don't render the field

---

src/components/fields/schemaFields/propTypes.ts
src/components/fields/schemaFields/widgets/NumberWidget.tsx
src/components/fields/schemaFields/widgets/OmitFieldWidget.tsx
src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/components/fields/schemaFields/widgets/v1/TextWidget.tsx
src/components/fields/schemaFields/widgets/v3/TextWidget.tsx

Closes #2194. Also focuses the input after toggling field input modes.

#2194 Toggle out of 'omit' mode on click

---

src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/devTools/editor/hooks/useToggleFormField.tsx

#2269 Fix bug with formik helper reference changing

---

src/components/quickBar/QuickBarApp.tsx

- Part of #2190
Tested on LinkedIn

#2190: Display quick bar above content

---

src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx

#2236: Fix external brick icon size

---

src/components/quickBar/QuickBarApp.tsx

Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2294

#2294: Improve quickbar style isolation

---

src/messaging/protocol.ts

No longer used, 🎉  it's been replaced by the Messenger everywhere

Drop HandlerMap

---

.idea/copyright/AGPLv3.xml
src/blocks/transformers/parseDataUrl.test.ts
src/blocks/transformers/parseDataUrl.ts
src/testEnv.js
src/utils/parseDataUrl.ts

#2302: support passing undecoded data through parsed data URL

---

src/blocks/transformers/parseDataUrl.test.ts
src/utils/parseDataUrl.ts

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/2304
Anything else I can do here?

Document parseDataUrl

---

src/actionPanel/native.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2308
- Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/2161

#2308: Don't create multiple sidebars

---

src/icons/Icon.module.scss
src/icons/Icon.tsx
src/icons/IconSelector.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2309
- Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/2027

#2309: Fix IconSelector’s spacing

---

src/background/logging.ts

#2265: include context with rollbar error

---

src/components/fields/schemaFields/v3/BasicSchemaField.tsx

#2345: fix schema mutation error

---

src/components/fields/schemaFields/SchemaField.test.tsx

Follows up from #2346, adds a test case

#2346 Followup - add test case

---

src/components/fields/schemaFields/fieldInputMode.ts
src/components/fields/schemaFields/v3/BasicSchemaField.test.tsx
src/components/fields/schemaFields/v3/BasicSchemaField.tsx
src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/devTools/editor/extensionPoints/upgrade.ts
src/devTools/editor/hooks/useToggleFormField.tsx

#2305 Handle enum fields for v2 --> v3 upgrade

---

src/devTools/editor/ElementWizard.tsx
src/devTools/editor/extensionPoints/actionPanel.tsx
src/devTools/editor/extensionPoints/base.ts
src/devTools/editor/extensionPoints/contextMenu.tsx
src/devTools/editor/extensionPoints/elementConfig.ts
src/devTools/editor/extensionPoints/menuItem.ts
src/devTools/editor/extensionPoints/panel.ts
src/devTools/editor/extensionPoints/quickBar.tsx
src/devTools/editor/extensionPoints/trigger.tsx
src/devTools/editor/sidebar/InstalledEntry.tsx
src/devTools/editor/slices/editorSlice.ts
src/devTools/editor/tabs/editTab/UpgradedToApiV3.tsx

#2315 Mark element dirty in redux state after auto-upgrading an extension to v3

---

src/options/pages/services/ServiceEditorModal.module.scss
src/options/pages/services/ServiceEditorModal.tsx

#2363: fix file picker z-index

---

src/devTools/editor/sidebar/Sidebar.tsx

Add reload button to editor during development

---

src/devTools/editor/slices/editorSelectors.ts
src/devTools/editor/slices/editorSlice.ts
src/devTools/editor/tabs/editTab/UpgradedToApiV3.tsx

#2362 Track the v3 upgrade message for each element separately

---

src/components/fields/schemaFields/v3/BasicSchemaField.tsx

#2369 Fix empty schema object widget

---

package-lock.json
package.json

#2371: bump typescript to 4.5.4

---

src/actionPanel/PanelBody.tsx
src/hooks/useBlockOptions.ts

#2413: fixing stale config props

---

src/runtime/mapArgs.test.ts
src/runtime/mapArgs.ts

#2413 Do not fail on empty template

---

src/devTools/editor/extensionPoints/base.test.ts
src/devTools/editor/extensionPoints/base.ts
src/utils.ts

#2427 Handle empty expression values properly

---

src/components/fields/fieldUtils.test.ts
src/components/fields/fieldUtils.ts
src/components/fields/schemaFields/widgets/ComplexObjectWidget.tsx
src/components/fields/schemaFields/widgets/TextWidget.tsx

#2460 Auto switch to nunjucks if possible

---

src/blocks/effects/highlight.ts

#2441: make highlight brick backward compatible

---

src/components/form/Form.tsx
src/core.ts
src/devTools/editor/extensionPoints/base.ts
src/devTools/editor/hooks/useCreate.ts
src/devTools/editor/panes/save/saveHelpers.ts
src/devTools/editor/tabs/editTab/EditTab.tsx
src/options/pages/blueprints/BlueprintsPage.tsx
src/options/pages/blueprints/installableUtils.ts
src/options/pages/blueprints/useInstallableActions.tsx
src/options/pages/blueprints/useInstallables.tsx
src/options/pages/installed/ExtensionRows.tsx
src/options/pages/installed/InstalledExtensionRow.tsx
src/options/pages/installed/InstalledPage.tsx
src/options/pages/installed/ShareExtensionModal.test.tsx
src/options/pages/installed/ShareExtensionModal.tsx
src/options/pages/installed/ShareLinkModal.tsx
src/options/pages/installed/__snapshots__/ShareExtensionModal.test.tsx.snap
src/options/pages/installed/installedPageSlice.ts
src/options/pages/installed/installedPageTypes.ts
src/runtime/runtimeUtils.ts
src/store/extensionsSelectors.ts
src/store/extensionsSlice.ts
src/store/extensionsTypes.ts

#2467: fix sharing modal

---

src/blocks/readers/SelectionReader.ts
src/blocks/readers/registerReaders.ts
src/components/quickBar/QuickBarApp.tsx
src/contentScript/devTools.ts
src/devTools/editor/extensionPoints/base.ts
src/extensionPoints/contextMenu.ts
src/extensionPoints/contextMenuReader.ts
src/extensionPoints/quickBarExtension.tsx
src/headers.ts
src/nativeEditor/dynamic.ts
src/utils.ts
src/utils/selectionController.ts

- Closes #2443
https://user-images.githubusercontent.com/1402241/150635232-4782c3fe-922b-405b-bd08-a5d5e91d2638.mov

#2443: Preserve selection on quickbar toggle

---

src/components/fields/schemaFields/BasicSchemaField.test.tsx
src/components/fields/schemaFields/widgets/TextWidget.tsx

#2505 Fix auto-wrap vars with braces in text fields

---

src/contrib/google/sheets/LookupSpreadsheetOptions.tsx

#2352 fix google sheet lookup brick Column Header field to default to select

---

src/components/fields/schemaFields/AppServiceField.tsx
src/components/fields/schemaFields/ServiceField.tsx

#2240 Clear the selected service if it doesn't exist in the extension configured services

---

src/devTools/editor/hooks/useRemove.ts

#2491: improve remove modal copy

---

src/options/App.tsx
src/options/pages/blueprints/BlueprintTableList.tsx
src/options/pages/blueprints/BlueprintTableRow.module.scss
src/options/pages/blueprints/BlueprintTableRow.tsx
src/options/pages/blueprints/BlueprintsCard.tsx
src/options/pages/blueprints/ListFilters.module.scss
src/options/pages/blueprints/ListFilters.tsx

Related to #2448 and #2447 
Before:
After:

#2448: refactor consolidate blueprints page filters and UI tweaks

---

src/devTools/editor/sidebar/DynamicEntry.tsx

Fix dynamic entry highlight on hover in editor

---

src/components/ErrorBoundary.tsx

- Closes https://github.com/pixiebrix/pixiebrix-app/issues/882
The solution was to clone the file and drop 2 lines, so I preferred just adding a condition. Stuff like this can help tree-shake this code completely:
- https://github.com/fregante/webext-detect-page/issues/12

Don't attempt to report errors in app

---

src/blocks/effects/disable.ts
src/blocks/effects/enable.ts
src/blocks/effects/registerEffects.ts
src/headers.ts

#2565: add enable/disable bricks

---

src/background.ts
src/background/navigation.ts

#2595: fix SPA navigation regression

---

src/blocks/readers/ArrayCompositeReader.ts
src/blocks/readers/CompositeReader.ts
src/blocks/transformers/blockFactory.ts
src/contrib/pipedrive/readers.ts
src/extensionPoints/panelExtension.ts
src/types.ts
tsconfig.json

Context: https://www.typescriptlang.org/tsconfig#useDefineForClassFields

Enable ts flag: useDefineForClassFields

---

src/devTools/Panel.tsx
src/errors.ts
src/telemetry/reportUncaughtErrors.ts
src/telemetry/rollbar.ts

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/2622
This completely swallows the errors: They're not logged and they're not sent to rollbar. Is this what you're looking for? I haven't been able to reproduce that Cancel error though.

Swallow some errors

---

src/contrib/slack/message.ts

Closes #2667 
Will require header update in app: https://github.com/pixiebrix/pixiebrix-app/issues/1152

#2667: indicate Slack bricks are deprecated

---

src/components/quickBar/QuickBarApp.tsx
src/vendors/kbar/KBarAnimator.tsx
src/vendors/kbar/useOuterClick.ts

- closes #2594
Todd’s intuition was right: it's due to useOuterClick
https://user-images.githubusercontent.com/1402241/153145258-59d25cd7-ff3b-433e-b8e0-38bb055d226e.mov

#2594: Fix Quick Bar behavior with clicks

---

src/background/deployment.test.ts
src/background/deployment.ts
src/contrib/uipath/LocalProcessOptions.test.tsx

Closes #2650 
Watches per-organization server flag from https://github.com/pixiebrix/pixiebrix-app/pull/1169
TODO:

#2650: don't open options page on update for normal users

---

src/components/fields/schemaFields/ServiceField.tsx
src/hooks/auth.ts

#2691 Don't default service for HTTP GET/POST bricks

---

src/layout/Sidebar.tsx
src/options/App.tsx
src/options/pages/activateExtension/ActivateForm.tsx
src/options/pages/deployments/DeploymentModal.stories.tsx
src/options/pages/marketplace/ActivateBody.tsx
src/options/pages/marketplace/ConfigureBody.tsx
src/options/pages/settings/ExperimentalSettings.tsx
src/pages/marketplace/useInstall.ts
src/store/settingsSelectors.ts
src/store/settingsSlice.ts
src/store/settingsTypes.ts

Closes #2678 
This adds a settings toggle option for the new Blueprints page.

#2678: blueprints page skunkworks flag

---

src/components/ConfirmationModal.tsx
src/devTools/editor/hooks/useReset.ts
src/hooks/useAuthorizationGrantFlow.ts
src/options/pages/marketplace/AuthWidget.tsx
src/options/pages/services/ServicesEditor.tsx

Not a perfect experience, but good enough for 1.5.4

#2681: redirect to app for authorization grant flow

---

src/background/logging.ts
src/components/logViewer/EntryRow.tsx
src/errors.ts
src/services/errors.ts
src/services/requestErrorUtils.ts
src/telemetry/rollbar.ts

#2668: include URL in network error

---

package.json
webpack.config.js

Upload JS as well as sourcemaps to AWS

---

src/blocks/transformers/parseDate.test.ts
src/blocks/transformers/parseDate.ts

#2746: provide a better error messages for invalid dates

---

src/devTools/editor/fields/DatabaseOptions.tsx

Closes #2765 
App PR: https://github.com/pixiebrix/pixiebrix-app/pull/1241

#2765: add fields for missing key and merge strategy options

---

src/contrib/google/sheets/FileWidget.module.scss
src/contrib/google/sheets/FileWidget.tsx
src/options/pages/installed/ShareExtensionModal.module.scss
src/options/pages/installed/ShareExtensionModal.tsx
src/options/pages/installed/__snapshots__/ShareExtensionModal.test.tsx.snap
src/options/pages/services/ServiceEditorModal.module.scss
src/options/pages/services/ServiceEditorModal.tsx

- Fixes #2763
Self-test report: I think the following screenshots cover all/most modals affected.
- https://github.com/pixiebrix/pixiebrix-extension/pull/2364
- https://github.com/pixiebrix/pixiebrix-extension/pull/2457

#2763: Fix z-index regression on modals

---

src/blocks/transformers/ephemeralForm/EphemeralForm.tsx

Notice the lack of padding and the extra scroll
https://user-images.githubusercontent.com/1402241/154797539-295605bf-faed-4471-a875-54216abbadd0.mov
- https://github.com/pixiebrix/pixiebrix-extension/pull/2179

Fix padding in sidebar ephemeral form

---

src/auth/authTypes.ts
src/auth/token.ts
src/background/deployment.ts
src/messaging/external.ts
src/services/api.ts

#2701: fix extension link update check

---

src/actionPanel/DefaultActionPanel.tsx
src/devTools/editor/ElementWizard.tsx
src/devTools/editor/askQuestion/AskQuestionModalButton.tsx
src/devTools/editor/panes/IntroButtons.tsx
src/devTools/editor/sidebar/Sidebar.tsx
src/options/pages/installed/InstalledPage.tsx
src/options/pages/installed/OnboardingPage.tsx

Splits blueprint options and blueprint sidebar off to separate feature flags
Along the way makes some button text/sizing more consistent

Split page editor feature flags

---

src/contentScript/uipath.ts
src/contrib/uipath/UiPathRobot.ts
src/contrib/uipath/localProcess.ts

Low-hanging fruit since all the UiPathRobot calls we have are already promised

Lazy-load UiPathRobot

---

src/components/formBuilder/DescriptionField.tsx
src/components/formBuilder/FormPreview.test.tsx
src/components/formBuilder/__snapshots__/FormPreview.test.tsx.snap
src/utils/safeMarkdown.ts

Using util for markdown

---

src/contrib/automationanywhere/aaApi.ts
src/contrib/automationanywhere/aaUtils.test.ts
src/contrib/automationanywhere/aaUtils.ts
src/contrib/automationanywhere/contract.ts

#2790: fix bot output retrieval

---

src/blocks/effects/pageState.test.ts
src/blocks/effects/pageState.ts

#2818: fix shared state NPE

---

src/components/form/FieldTemplate.tsx

Related to #2820 and #2828 
cc @twschiller @BLoe

2814 Don't show errors of nested fields

---

src/components/fields/schemaFields/BasicSchemaField.tsx
src/components/fields/schemaFields/widgets/TextWidget.tsx

#2814 Provide form error feedback in service configuration modal

---

src/devTools/editor/fields/SelectorSelectorWidget.module.scss
src/devTools/editor/fields/SelectorSelectorWidget.tsx

- Fixes #2832
I reverted this code to what I had in my first commit in https://github.com/pixiebrix/pixiebrix-extension/pull/2658
https://user-images.githubusercontent.com/1402241/155925808-309c7aa3-9edc-465a-a993-0eb119210eba.mov

Fix SelectorSelectorWidget z-index

---

.github/workflows/ci.yml
.github/workflows/release.yaml
scripts/upload-sourcemaps.sh

- Follows #2834
Current error:

Fix Rollbar notification API calls with correct ENV missing from #2834

---

src/background/contextMenus.ts
src/contrib/google/sheets/FileWidget.tsx
src/hooks/useDeployments.ts
src/hooks/useRefresh.ts
src/hooks/useUserAction.ts
src/options/pages/activateExtension/useEnsurePermissions.ts
src/options/pages/brickEditor/useSubmitBrick.ts
src/options/pages/installed/ShareExtensionModal.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/marketplace/useEnsurePermissions.ts
src/options/pages/settings/FactoryResetSettings.tsx
src/pageEditor/fields/SelectorSelectorWidget.tsx
src/pageEditor/hooks/useAddElement.ts
src/pageEditor/hooks/useCreate.ts
src/pageEditor/hooks/useRemove.ts
src/pageEditor/panes/save/useSavingWizard.ts
src/services/useDependency.ts
src/utils/notify.tsx

- As suggested in https://github.com/pixiebrix/pixiebrix-extension/pull/2836#issuecomment-1057555637
- Tracked in https://github.com/pixiebrix/pixiebrix-extension/issues/2865

Automatically append error details to notifications

---

src/options/pages/marketplace/ActivateBody.tsx

Closes #2868 
Had called "some" without awaiting promise, so it was always truthy

#2868: fix quickbar warning

---

src/pageEditor/validation/applyTraceInputError.test.ts
src/pageEditor/validation/applyTraceInputError.ts

Related to #2856 
Before:
After:

#2856 Parse input errors by instanceLocation

---

src/background/locator.ts

Part of #2925: adding more assertions to try to localize the problem

#2925: add more assertions to locator code flow

---

src/pageEditor/Editor.tsx
src/pageEditor/Panel.tsx

Fixes a crash in the page editor related to #2947

Move telemetry code down one level, into redux context

---

src/blocks/transformers/ParseJson.ts
src/blocks/transformers/parseJson.test.ts
src/blocks/transformers/registerTransformers.ts
src/development/headers.ts

Closes #2863 
Adds a brick to parse JSON

#2863: @pixiebrix/parse/json brick

---

src/extensionPoints/triggerExtension.ts
src/pageEditor/tabs/trigger/TriggerConfiguration.tsx

#2913: add keyboard trigger events

---

src/extensionPoints/triggerExtension.ts
src/pageEditor/extensionPoints/trigger.tsx
src/pageEditor/tabs/trigger/TriggerConfiguration.tsx

Closes #2913 
This PR contains content from #2950. Review #2950 first
How to test: 
1. Add a keyup trigger on a text area (https://github.com/pixiebrix/pixiebrix-extension/pull/2950)
2. Try with and without debounce

#2913: add support for debouncing triggers

---

src/services/api.ts

I screwed up the output type of the query, sorry 😬

#2557 - 3 - Followup: fix type

---

src/extensionPoints/triggerExtension.ts

#2954: don't fire leading event on interval trigger

---

src/pageEditor/panes/RecipePane.tsx
src/pageEditor/panes/save/useRecipeSaver.ts
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSlice.ts
src/pageEditor/tabs/editRecipeTab/EditRecipe.module.scss
src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx
src/types/definitions.ts

#2927 Edit recipe metadata

---

src/pageEditor/sidebar/Footer.tsx

Part of #2962
There may be more digging to do it this is a symptom of the query failing sometimes

#2962: fix query race condition in Page Editor sidebar footer

---

src/errors.ts
src/testEnv.js

Follow up of https://github.com/pixiebrix/pixiebrix-extension/pull/2952#discussion_r826922303

#2826: clarify promise rejection type check

---

src/services/locator.ts

Part of #2715 
Fixes an error where one failed request would block all subsequent service updates

#2715: fix locator debounce

---

src/components/jsonTree/treeHooks.tsx

#2898 Clicking property name in data tree to expand it also copies the path

---

jest.config.json
package-lock.json
package.json
src/core.ts
src/options/pages/blueprints/modals/ShareExtensionModal.tsx
src/options/pages/blueprints/useInstallableActions.ts
src/options/pages/blueprints/utils/exportBlueprint.ts
src/options/pages/blueprints/utils/installableUtils.ts
webpack.sharedConfig.js

#3032: fix extension export on blueprints export page

---

src/components/fields/schemaFields/widgets/BooleanWidget.tsx
src/options/pages/brickEditor/BrickHistory.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/brickEditor/useSubmitBrick.ts
src/services/api.ts
src/types/contract.ts

- Switches the brick query to use RTK
- Shows errors in the page body if the brick fails to load

Refactor Workshop brick edit page

---

src/blocks/effects/forms.ts
src/blocks/effects/highlight.ts
src/blocks/effects/vue.ts
src/blocks/readers/ElementReader.ts
src/blocks/readers/jquery.ts
src/blocks/transformers/FormData.ts
src/blocks/transformers/component/ComponentReader.ts
src/blocks/transformers/component/ComponentReaderOptions.tsx
src/blocks/transformers/component/TableReader.ts
src/blocks/transformers/detect.ts
src/blocks/transformers/jquery/JQueryReader.ts
src/blocks/types.ts
src/components/fields/schemaFields/getToggleOptions.tsx
src/contentScript/nativeEditor/infer.ts
src/contentScript/pageEditor.ts
src/extensionPoints/helpers.ts
src/helpers.ts
src/options/pages/blueprints/useInstallableViewItems.tsx
src/options/pages/brickEditor/useSubmitBrick.ts
src/options/pages/marketplace/useWizard.ts
src/runtime/runtimeUtils.ts
src/utils/requireSingleElement.ts

Quick autofix from https://github.com/antfu/case-police
We should use the correct case especially for user-facing text

Fix JQuery case to jQuery

---

.github/dependabot.yml
scripts/upload-sourcemaps.sh
src/background/locator.ts
src/blocks/readers/frameworkReader.ts
src/options/pages/blueprints/labels/LastUpdatedLabel.tsx
src/pageEditor/askQuestion/AskQuestionModalButton.tsx
webpack.config.js

See inline review comments for details

Small webpack build improvements

---

src/background/deployment.test.ts
src/background/deployment.ts

#3112 Open the options page if the extension became unlinked

---

src/utils.test.ts
src/utils.ts

#3137: Preserve existing parameters `makeUrl`

---

src/pageEditor/tabs/effect/BlockPreview.tsx

#3129 Page Editor Preview panel doesn't show preview for non root-aware bricks

---

package-lock.json
package.json
src/runtime/pipelineTests/trace.test.ts
src/runtime/reducePipeline.ts
src/telemetry/trace.ts
src/testUtils/factories.ts

#3171: fix error when referencing conditional outputs in brick inputs

---

src/pageEditor/hooks/useResetExtension.ts

Bug fix: Error when resetting an extension after adding it to a blueprint

---

src/pageEditor/tabs/RecipeOptions.tsx

#3204 Refactor UI of the blueprint options tab

---

src/pageEditor/pageEditorTypes.ts
src/pageEditor/sidebar/DynamicEntry.tsx
src/pageEditor/sidebar/Entry.module.scss
src/pageEditor/sidebar/InstalledEntry.tsx
src/pageEditor/sidebar/RecipeEntry.tsx
src/pageEditor/sidebar/Sidebar.module.scss
src/pageEditor/sidebar/Sidebar.tsx
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSlice.ts

#3140 Page editor sidebar UI tweaks

---

src/auth/authUtils.ts

Related to #2909 
This PR is complementary to the one for the app https://github.com/pixiebrix/pixiebrix-app/pull/1540

AuthState refactoring

---

src/pageEditor/slices/editorSlice.ts

#3221 Unselect recipe when a new element is added

---

src/pageEditor/panes/save/useRecipeSaver.ts
src/pageEditor/sidebar/RemoveFromRecipeModal.tsx
src/pageEditor/sidebar/Sidebar.tsx
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSlice.ts

#3220 Fix reset recipe (+ save recipe) with deleted extensions

---

src/pageEditor/panes/save/useRecipeSaver.ts

#3231 Don't save removed extensions in blueprints

---

src/auth/RequireScope.tsx
src/auth/ScopeSettings.tsx
src/options/pages/blueprints/modals/ShareExtensionModal.test.tsx
src/pageEditor/panes/save/SaveExtensionWizard.test.tsx
src/services/api.ts

#3226 Fix ScopeSettings to correctly use RTK query instead of using a raw api client

---

src/pageEditor/panes/save/saveHelpers.test.ts
src/pageEditor/panes/save/saveHelpers.ts

---
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/3254 with some additional unit tests for de-duplication and services

#3222: add tests for buildRecipe

---

src/pageEditor/Editor.tsx
src/pageEditor/extensionPoints/base.test.ts
src/pageEditor/extensionPoints/base.ts
src/pageEditor/pageEditorTypes.ts
src/pageEditor/panes/save/saveHelpers.ts
src/pageEditor/panes/save/useRecipeSaver.ts
src/pageEditor/sidebar/AddToRecipeModal.tsx
src/pageEditor/sidebar/CreateRecipeModal.tsx
src/pageEditor/sidebar/SaveAsNewRecipeModal.tsx
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSlice.ts
src/testUtils/factories.ts

#3233 Save-as-new for marketplace blueprints

---

src/options/pages/blueprints/Status.tsx
src/options/pages/blueprints/useInstallableViewItemActions.ts

#3269: fix reinstall button that wouldn't do anything when clicked

---

src/errors.ts
src/runtime/pipelineTests/templateEngine.test.ts
src/runtime/renderers.ts

#3113 Throw more informative error on malformed Nunjucks template

---

jest.config.json

#3319: Fix Jest conflict due to `use-debounce`

---

src/components/documentBuilder/DocumentBuilder.stories.tsx
src/components/documentBuilder/edit/DocumentEditor.test.tsx
src/components/documentBuilder/edit/DocumentEditor.tsx
src/components/documentBuilder/edit/ElementEditor.tsx
src/components/documentBuilder/edit/MoveElement.tsx
src/components/documentBuilder/edit/RemoveElement.tsx
src/components/documentBuilder/preview/AddElementAction.tsx
src/components/documentBuilder/preview/DocumentPreview.test.tsx
src/components/documentBuilder/preview/DocumentPreview.tsx
src/components/documentBuilder/preview/ElementPreview.test.tsx
src/components/documentBuilder/preview/ElementPreview.tsx
src/components/documentBuilder/utils.ts
src/pageEditor/fields/DocumentOptions.tsx

Related to #2970 
Making Document builder store a relative path to its active element.

#2970 Document builder active element

---

src/components/fields/schemaFields/ServiceField.tsx
src/components/fields/schemaFields/serviceFieldUtils.test.ts
src/components/fields/schemaFields/serviceFieldUtils.ts
src/testUtils/factories.ts

- Closes #3323
Possible performance impacts. Suggestions for additional tests.
It allows to select the integration, but still there's no way to set the `output` for the service.
_None required_

#3323 Can't select integration when configuring brick for button using service in document builder

---

src/background/deployment.test.ts
src/background/deployment.ts

#3357: fix NPE in deployment updater

---

src/background/deployment.test.ts
src/utils/deployment.ts

- Part of #3358 
- Adds a test and fixes another NPE in the deployment installer logic

#3358: fix deployment match NPE

---

src/components/documentBuilder/edit/DocumentEditor.test.tsx
src/components/documentBuilder/edit/ElementBlockEdit.tsx
src/components/documentBuilder/edit/RemoveElement.tsx
src/components/fields/schemaFields/AppServiceField.tsx
src/components/fields/schemaFields/ServiceField.tsx
src/components/fields/schemaFields/serviceFieldUtils.test.ts
src/components/fields/schemaFields/serviceFieldUtils.ts
src/pageEditor/tabs/editTab/useBlockPipelineActions.ts
src/testUtils/testHelpers.tsx

- Fixes #3340
- Adds a bottom margin to the "Select a brick" button in the Document builder
- _What order should the reviewer review the files in?_
- _Are there any implementation approaches you want feedback on?_
- Initialization of the test looks complex. However, this can be the first step toward PageEditor tests.
https://www.loom.com/share/7337e4dc8f024c989c33cdea796acc3f

#3340 Service dependency not removed when you remove a brick using service variable from the document builder

---

jest.config.json
src/pageEditor/askQuestion/AskQuestionModal.test.tsx
src/pageEditor/askQuestion/AskQuestionModal.tsx
src/testUtils/testHelpers.tsx

- Adds a basic render test for `AskQuestionModal`
- @fregante: do you know why we had to make this change to the jest config to get this test to work with `svg`s? Does this break other things?

#3353 AskQuestionModal test

---

src/pageEditor/fields/FieldSection.tsx
src/pageEditor/tabs/effect/BlockConfiguration.test.tsx
src/pageEditor/tabs/effect/BlockConfiguration.tsx
src/pageEditor/tabs/effect/ConfigurationTitle.test.tsx
src/pageEditor/tabs/effect/ConfigurationTitle.tsx
src/pageEditor/tabs/effect/__snapshots__/BlockConfiguration.test.tsx.snap
src/pageEditor/tabs/effect/__snapshots__/ConfigurationTitle.test.tsx.snap
src/types/contract.ts

#3354 Show brick name and marketplace documentation link in Page Editor

---

src/errors.ts

Fix error cause check in getRootCause

---

src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx
src/components/fields/schemaFields/widgets/ObjectWidget.tsx
src/components/fields/schemaFields/widgets/__snapshots__/ObjectWidget.test.tsx.snap

#3353 ObjectWidget tests

---

src/components/fields/schemaFields/widgets/ArrayWidget.test.tsx
src/components/fields/schemaFields/widgets/__snapshots__/ArrayWidget.test.tsx.snap

#3353 Add tests for ArrayWidget

---

src/testUtils/testHelpers.tsx

- Some minor refactoring in the custom `renderWithWrappers()` function
https://pixiebrix.slack.com/archives/C02DKNNB7T9/p1652899768883709

Refactor rest render function, pull store outside wrapper

---

src/components/fields/schemaFields/widgets/SchemaSelectWidget.test.tsx
src/components/fields/schemaFields/widgets/__snapshots__/SchemaSelectWidget.test.tsx.snap

- Add snapshot tests for `SchemaSelectWidget`

#3353 Schema select widget tests

---

src/options/pages/blueprints/ListFilters.module.scss
src/options/pages/blueprints/ListFilters.tsx

Fixes #3121 
https://www.loom.com/share/0a8eec8857474b43b3dc2b6731e48fbf

#3121: fix nav item alignment on small screen

---

src/pageEditor/tabs/editTab/dataPanel/DataPanel.test.tsx
src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.test.tsx
src/pageEditor/tabs/editTab/dataPanel/PageStateTab.test.tsx
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/FoundationDataPanel.test.tsx.snap
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/PageStateTab.test.tsx.snap
src/testUtils/factories.ts

- Add a basic render/snapshot test for `DataPanel`

#3353 DataPanel render test

---

src/components/ConfirmationModal.stories.tsx
src/components/ConfirmationModal.tsx

Fixes #2246 
https://www.loom.com/share/9e2137087dd3447893fd8ce290c60c35

#2246: fix confirmation modal fadeout animation

---

src/background/partnerTheme.ts
src/hooks/useTheme.ts
src/options/constants.ts
src/options/types.ts
src/store/settingsSlice.ts
src/store/settingsTypes.ts
src/utils/themeUtils.ts

- Fixes #3437 
- Double check that the icon appears as expected, and that theming still works.
Shoutout to @fregante for the suggested fix :)

#3437: use proper pixiebrix favicon for toolbar icon

---

src/pageEditor/sidebar/DynamicEntry.test.tsx
src/pageEditor/sidebar/InstalledEntry.test.tsx
src/pageEditor/sidebar/__snapshots__/DynamicEntry.test.tsx.snap
src/pageEditor/sidebar/__snapshots__/InstalledEntry.test.tsx.snap
src/testUtils/factories.ts

- Add snapshot tests for `DynamicEntry` and `InstalledEntry`

#3353 Sidebar entry render tests

---

src/components/fields/schemaFields/widgets/ArrayWidget.test.tsx
src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx
src/components/fields/schemaFields/widgets/SchemaSelectWidget.test.tsx
src/components/form/widgets/RegistryIdWidget.test.tsx
src/components/form/widgets/radioItemList/RadioItemListWidget.test.tsx
src/components/tabLayout/EditorTabLayout.test.tsx
src/options/pages/blueprints/modals/ConvertToRecipeModal.test.tsx
src/options/pages/blueprints/modals/ConvertToRecipeModal.tsx
src/options/pages/blueprints/modals/ShareRecipeModal/ShareRecipeModal.tsx
src/options/pages/blueprints/modals/__snapshots__/ConvertToRecipeModal.test.tsx.snap
src/options/pages/services/ServiceEditorModal.test.tsx
src/options/pages/services/__snapshots__/ServiceEditorModal.test.tsx.snap
src/options/testHelpers.tsx
src/pageEditor/sidebar/DynamicEntry.test.tsx
src/pageEditor/sidebar/InstalledEntry.test.tsx
src/pageEditor/tabs/editTab/dataPanel/DataPanel.test.tsx
src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.test.tsx
src/pageEditor/tabs/editTab/dataPanel/PageStateTab.test.tsx
src/pageEditor/testHelpers.tsx
src/testUtils/factories.ts
src/testUtils/testHelpers.tsx

- Part of #3409 
- Adds snapshot tests for the `ConvertToRecipeModal`
- Updates the copy of the "Public" switch
- Refactors the `render` test helper
- "Public" switch
- More tests for the ConvertToRecipeModal
- Tests for the ShareRecipeModal

#3409 Share modal improvements

---

src/hooks/useTheme.ts
src/options/options.html
src/utils/themeUtils.ts

Nit: @mnholtz your previous commit was almost there. This PR can be merged into yours before merging that one.

Small simplification for #3424

---

src/auth/authTypes.ts
src/auth/authUtils.ts
src/testUtils/factories.ts
src/types/contract.ts
src/types/swagger.ts

- Part of app PR: https://github.com/pixiebrix/pixiebrix-app/pull/1736
- Adds a flag to organization memberships returned from /api/me/
- The app depends on some type files from the extension project

Add deployment manager flag to organization memberships

---

src/utils/themeUtils.ts

Fix favicon-related error in sidebar

---

src/options/pages/SetupPage.tsx
src/pageEditor/components/LoginCard.tsx
src/services/baseService.ts

- Skips one unnecessary step in the login process from the editor
- Centers the LoginCard component to match the rest of them
(except the centering)
https://user-images.githubusercontent.com/1402241/170859578-ae92d37d-45cb-4e00-a8a5-925abeda51d9.mov
https://user-images.githubusercontent.com/1402241/170858091-5f396150-d180-4004-9cf6-f5b55a5d5163.mov

Skip one step in LoginCard

---

src/pageEditor/tabs/editTab/EditTab.tsx

#3535 Fix bug - show selector widget instead of text input for selector match pattern field

---

__mocks__/react-virtualized-auto-sizer.js
src/components/TooltipIconButton.tsx
src/components/brickModal/BrickModal.tsx
src/components/fields/schemaFields/serviceFieldUtils.test.ts
src/components/tabLayout/__snapshots__/EditorTabLayout.test.tsx.snap
src/contrib/uipath/LocalProcessOptions.test.tsx
src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/PageStateTab.test.tsx.snap
src/pageEditor/tabs/editTab/editorNode/EditorNode.tsx
src/pageEditor/tabs/effect/BlockConfiguration.test.tsx
src/pageEditor/testHelpers.tsx
src/testUtils/factories.ts
src/testUtils/testHelpers.tsx

- Part of #3491
- Adds test harness and first tests for the Editor Pane

#3491 EditorPane tests

---

src/sidebar/store.ts

- Fixes #3568
- Adds necessary Redux store setup to the sidebar

#3568: fix sidebar Redux store setup

---

src/sidebar/SidebarApp.test.tsx
src/sidebar/__snapshots__/SidebarApp.test.tsx.snap

- Follow-up from https://github.com/pixiebrix/pixiebrix-extension/pull/3569
- Adds a smoke test for the sidebar to check that it renders
Hopefully this will help catch sidebar issues before they occur.
This is just a quick smoke test for the sidebar. We can add more cases to test onboarding views in the sidebar in the future.

#3568: Add smoke test for sidebar

---

src/components/asyncCard/AsyncCard.tsx
src/components/paginatedTable/PaginatedTable.module.scss
src/components/paginatedTable/PaginatedTable.tsx
src/options/pages/workshop/CustomBricksCard.module.scss
src/options/pages/workshop/CustomBricksCard.tsx
src/options/pages/workshop/WorkshopPage.tsx
src/types/reactTableConfig.d.ts

Fixes #3593 
@twschiller I have modified PaginatedTable to support RowProps in case if we want to add any click event on entire row , or to override row styles or providing custom class to row
needed this as CustomBricksCard had custom styles for table row on hover and also click Event attached to entire row

Integrated Paginated Table in CustomBricksCard

---

src/components/errors/getErrorDetails.tsx
src/components/logViewer/LogTable.module.scss
src/components/logViewer/LogTable.tsx
src/components/logViewer/__snapshots__/LogCard.test.tsx.snap

#3638 Fix table headers on log viewer

---

src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/editTab/editTabTypes.ts
src/pageEditor/tabs/editTab/editTabVariables.scss
src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
src/pageEditor/tabs/editTab/editorNodes/OutputKeyView.module.scss
src/pageEditor/tabs/editTab/editorNodes/OutputKeyView.tsx
src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.module.scss
src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.tsx
src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.module.scss
src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx
src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.module.scss
src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.tsx
src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.module.scss
src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNodeContent.module.scss
src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNodeContent.tsx
src/pageEditor/tabs/editTab/useBlockPipelineActions.ts

- Part of #3491
- Following up on changes requested from #3632

#3491 Editor node layout - follow up bug fixes and tweaks

---

src/components/documentBuilder/edit/useElementOptions.tsx

- Fixes a bug I introduced where the editor options were remounting on each key stroke/interaction

Fix Document Builder options remount bug

---

src/components/errors/ErrorDetail.module.scss
src/components/errors/InputValidationErrorDetail.tsx
src/components/errors/NetworkErrorDetail.tsx
src/components/errors/OutputValidationErrorDetail.tsx
src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap
src/components/errors/getErrorDetails.tsx
src/components/logViewer/EntryRow.module.scss
src/components/logViewer/EntryRow.tsx
src/components/logViewer/LogTable.module.scss
src/pageEditor/tabs/editTab/dataPanel/ErrorDisplay.module.scss

- Fixes #3666
- I need to QA this with a network error, but there's a bug blocking network errors from being logged properly

#3666 Fix bug with error details layouts

---

src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.module.scss
src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx

#3693 Fix bug with closed pipeline UI with no output key

---

src/types/swagger.ts

- Part of https://github.com/pixiebrix/pixiebrix-app/pull/1856
- Updates the routes for getting and updating a control room per PR feedback

Update control room routes in api contract

---

src/components/brickModal/BrickModal.module.scss
src/components/brickModal/BrickModal.tsx
src/components/brickModal/BrickResult.module.scss
src/components/brickModal/TagList.module.scss
src/components/brickModal/brickModalVariables.scss

- Fixes #3601 
- The trade-off here is the tag list scrolls horizontally at narrower widths. I don't think it's that bad though, and I think it's better than figuring out how to make the icons/labels wrap in a non-ugly way.

#3601 - Fix bug with brick modal results disappearing

---

src/components/documentBuilder/utils.ts
src/pageEditor/slices/editorSlice.ts
src/pageEditor/utils.ts
src/utils/debugUtils.test.ts
src/utils/debugUtils.ts

#3703: add nodes to bricks/buttons inside lists

---

src/core.ts
src/options/pages/services/PrivateServicesCard.tsx
src/services/registry.ts

Integrated Paginated Table in PrivateServicesCard

---

src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.module.scss
src/pageEditor/tabs/editTab/editorNodes/brickNode/MoveBrickControl.module.scss

#3711 Fix pipeline offset alignment issues

---

src/background/messenger/api.ts
src/background/messenger/registration.ts
src/background/partnerIntegrations.ts
src/contentScript/contentScript.ts
src/contentScript/partnerIntegrations.ts
src/services/locator.ts

- Closes #3549 
- Marks partner page with username of the configured integration
- 😞  Add tests

#3549: mark partner page root with username

---

package-lock.json
package.json
src/errors/errorHelpers.test.ts
src/errors/errorHelpers.ts
src/telemetry/BackgroundLogger.ts
webpack.config.js

- Closes #3722 
- Turns off class name minimization for error classes
- Adds some more tests for sanity-checking our error code

#3722: keep unminified error class names

---

src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.test.tsx
src/pageEditor/tabs/editTab/editHelpers.ts
src/testUtils/testHelpers.tsx

- Part of #3491
- Adds tests to Editor Pane
- Refactors `TraversPipeline`

#3491: add tests for page editor tests

---

src/components/brickModal/BrickModal.tsx

#3742 Don't sort popular bricks first in brick modal if the user has typed a search query

---

src/pageEditor/slices/editorSlice.ts

#3737 Mark elements dirty when bricks are added/removed from sub pipelines

---

src/contrib/google/auth.ts

- Fixes #3746
- browser-polyfill not compatible with chrome.identity.getAuthToken?
- 😞  Add tests

#3746: fix google file picker

---

src/hooks/useFlags.ts
src/pageEditor/Editor.tsx
src/pageEditor/panes/RestrictedPage.stories.tsx
src/pageEditor/panes/RestrictedPane.tsx

- Closes #3748 
- Corresponding app PR: https://github.com/pixiebrix/pixiebrix-app/pull/1880
- 😞  Add tests

#3748: restrict access to page editor

---

src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx

#3750 Status indicator not showing up on extension point

---

src/pageEditor/panes/EditorPane.test.tsx

#3752 - Fix flaky test

---

src/pageEditor/hooks/useAllBlocks.ts
src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/editTab/EditTab.tsx
src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
src/pageEditor/tabs/effect/ConfigurationTitle.tsx

#3753 Data panel Output of renderer brick shows unknown error

---

src/options/Sidebar.tsx
src/types/swagger.ts

- Part of https://github.com/pixiebrix/pixiebrix-app/issues/1857
- Depends on https://github.com/pixiebrix/pixiebrix-app/pull/1887

Add partner documentation url to sidebar link

---

src/blocks/renderers/customForm.tsx
src/components/fields/schemaFields/AppServiceField.tsx
src/components/fields/schemaFields/serviceFieldUtils.test.ts
src/components/fields/schemaFields/serviceFieldUtils.ts
src/pageEditor/fields/DatabaseOptions.tsx
src/pageEditor/fields/FormRendererOptions.tsx
src/pageEditor/sidebar/Sidebar.tsx

- Fixes #3783 
- Fetches service vars from the nested pipelines
- Fixes the service field on Form database storage

#3783 Adding custom form with database storage to document doesn't add PixieBrix service

---

src/components/documentBuilder/render/BlockElement.tsx
src/components/documentBuilder/render/ButtonElement.tsx
src/contentScript/pipelineProtocol.ts

- Fixes #3809 
- Pass message context through with buttons/bricks in panels
- Use BackgroundLogger for buttons/bricks in panels so errors show in logs
- 😞  Add tests

#3809: fix page state brick calls and call logging from sidebar

---

src/components/documentBuilder/render/ListElement.tsx

#3793: handle null list in document ListElement

---

src/blocks/transformers/controlFlow/IfElse.test.ts
src/runtime/pipelineTests/pipelineTestHelpers.ts
src/runtime/reducePipeline.ts

- Closes #3818 
- Fixes bug where the root wasn't being passed to control flow bricks branches/body

#3818: fix control flow brick root element

---

src/background/deployment.ts
src/options/pages/deployments/DeploymentModal.test.tsx
src/options/pages/deployments/DeploymentModal.tsx
src/options/pages/deployments/__snapshots__/DeploymentModal.test.tsx.snap
src/store/settingsSelectors.test.ts
src/store/settingsSelectors.ts

- Follow up to first PR for #3791 
- Fixes bug where modal wouldn't snooze
- Hides inconsistent snooze options during countdown

#3791: fix snooze and time remaining check

---

src/components/fields/schemaFields/widgets/TextWidget.tsx
src/pageEditor/toolbar/PermissionsToolbar.tsx

- Clears up a couple warnings showing up in the logs for the `EditorPane` tests

Fix warnings in `EditorPane` tests

---

src/pageEditor/toolbar/PermissionsToolbar.tsx

#3859: Fix PermissionsToolbar NPE

---

src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
src/pageEditor/tabs/editTab/dataPanel/PageStateTab.tsx
src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.test.tsx
src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.tsx
src/pageEditor/tabs/editTab/dataPanel/tabs/__snapshots__/PageStateTab.test.tsx.snap

#3880 Fixing Document body path

---

src/options/pages/blueprints/ListFilters.tsx

- Closes/Fixes/Part of #3879 
https://www.loom.com/share/5d9b4a32b7e142e286fc31b1202c4fa6
None

Prevent form default behavior on blueprints screen search

---

src/hooks/useUndo.test.ts
src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.module.scss
src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx
src/pageEditor/utils.ts

- Closes #3765 
- cleans up a possible memory leak in tests (console warning)
- Check out the changes to the `util` function and how that flows through to the UI

#3765 show pipeline header keys

---

src/options/pages/marketplace/useWizard.ts

#3895 Preserve blueprint options on re-activate

---

src/contrib/automationanywhere/aaUtils.test.ts
src/contrib/automationanywhere/aaUtils.ts

- Closes #3912
- Fixes bug in our AA Community hostname regex

#3912: fix AA community URL detection in Page Editor

---

src/contrib/automationanywhere/aaApi.ts

Fix bot inputs for AA community edition bot deployments

---

src/components/documentBuilder/documentTree.tsx
src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
src/components/documentBuilder/preview/getPreviewComponentDefinition.tsx

#3792 Handle card body overflow in Document Builder

---

src/components/fields/schemaFields/BasicSchemaField.tsx
src/components/form/ConnectedFieldTemplate.tsx
src/components/form/useFieldError.ts
src/pageEditor/Panel.tsx
src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/panes/EditorPane.tsx
src/pageEditor/slices/editorSelectors.ts

#3947 Fields to pull errors from analysis slice

---

src/analysis/analysisVisitors/extensionUrlPatternAnalysis.ts
src/components/fields/schemaFields/serviceFieldUtils.test.ts
src/components/form/FieldTemplate.tsx
src/options/pages/services/__snapshots__/ServiceEditorModal.test.tsx.snap
src/pageEditor/extensionPoints/base.ts
src/pageEditor/extensionPoints/contextMenu.tsx
src/pageEditor/extensionPoints/menuItem.ts
src/pageEditor/extensionPoints/panel.ts
src/pageEditor/extensionPoints/quickBar.tsx
src/pageEditor/extensionPoints/sidebar.tsx
src/pageEditor/extensionPoints/trigger.tsx
src/pageEditor/toolbar/PermissionsToolbar.tsx
src/testUtils/factories.ts
src/utils/permissions.ts

- Fixes #3910 
- Shows validation message for pristine form fields

#3910 Error checking permissions when saving extension in Page Editor

---

src/components/addBlockModal/AddBlockModal.tsx
src/pageEditor/hooks/useAllBlocks.ts
src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
src/pageEditor/tabs/effect/ConfigurationTitle.tsx

- Fixes #3959 
- I think this should be fine to refresh on mount, I wasn't seeing much performance impact, but something to possibly be aware of?

#3959 Update allBlocks typed block map on mount

---

vercel.json

Storybook is being automatically deployed to https://pixiebrix-extension.vercel.app (`main` branch) and to a temporary URL for every PR.
This will let us quickly refer to it or to verify new components before merging PRs.
This specific PR only disables the comments that Vercel leaves on every commit and PR. The URL is available in the "Checks list" at the bottom of PR and commit: https://vercel.com/support/articles/how-to-prevent-vercel-github-comments

Enable Storybook previews

---

contrib/recipes/v3-example.txt
schemas/innerDefinition.json
src/options/pages/brickEditor/validate.test.ts
src/options/pages/brickEditor/validate.ts
src/validators/generic.ts

- Closes #3997
- Why weren't we getting an `Unknown file` error instead of having the browser try to hit the server to resolve it? The ref parser started falling back to the bult-in http resolver? When?

#3997: fix workshop validation error

---

src/options/pages/marketplace/useEnsurePermissions.ts

- #3761
- Refreshed remote and local services in blueprint activation flow
- 😢  Add tests

#3761: refresh remote services during blueprint activation

---

src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx

#4003 Fix invalid old blueprint warnings

---

src/blocks/renderers/__snapshots__/table.test.ts.snap
src/blocks/renderers/table.test.ts
src/blocks/renderers/table.tsx

- Closes #4014 
- Shows empty table instead of erroring on nullish value in runtime v2/v3

#4014: show empty table renderer on null data

---

src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx

#4011: fix race condition NPE in EditorNodeLayout

---

src/contrib/google/initGoogle.ts

- Part of #3914 
- This is an attempt to gather more info, this won't fix the issue (obviously)

#3914: gapi load error telemetry

---

contrib/services/automation-anywhere-oauth2.yaml
schemas/service.json
src/auth/useRequiredPartnerAuth.test.tsx
src/auth/useRequiredPartnerAuth.ts
src/background/partnerIntegrations.test.ts
src/baseRegistry.ts
src/contrib/automationanywhere/RunBot.ts
src/hooks/useTheme.ts
src/services/constants.ts
src/store/settingsTypes.ts

- Part of #3796 and partner work
- Adds tests and clarifies documentation

#3796: partner tests and documentation

---

src/pageEditor/context.ts

- Part of  https://github.com/pixiebrix/pixiebrix-extension/issue/3940
- Extends https://github.com/pixiebrix/pixiebrix-extension/pull/3941

#3940: Update "connection lost" banner message in editor

---

src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSlice.ts
src/pageEditor/tabs/editTab/dataPanel/tabs/StateTab.tsx
src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
src/pageEditor/tabs/editTab/editorNodeLayout/decideStatus.ts
src/pageEditor/uiState/uiState.ts
src/pageEditor/uiState/uiStateTypes.ts

Removes Error map and all the related code from the page editor

Removing Error map from page editor slice

---

src/components/documentBuilder/allowedElementTypes.ts
src/components/documentBuilder/createNewElement.test.ts
src/components/documentBuilder/createNewElement.ts
src/components/documentBuilder/documentBuilderTypes.ts
src/components/documentBuilder/documentTree.tsx
src/components/documentBuilder/edit/getElementEditSchemas.ts
src/components/documentBuilder/elementTypeLabels.ts
src/components/documentBuilder/preview/DocumentPreview.test.tsx
src/components/documentBuilder/preview/ElementPreview.test.tsx
src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
src/components/documentBuilder/preview/getPreviewComponentDefinition.tsx
src/components/fields/schemaFields/HeadingStyleField.tsx
src/components/fields/schemaFields/SchemaField.tsx
src/components/fields/schemaFields/widgets/HeadingStyleWidget.module.scss
src/components/fields/schemaFields/widgets/HeadingStyleWidget.tsx
src/pageEditor/exampleBlockConfigs.ts

#4008 Add support for switching between header element types in Document Builder

---

src/chrome.ts

- Closes #4069 
- Opera doesn't support managed storage. We're getting some error telemetry that Rollbar has a hard time categorizing, so handle the error in the code
- 😢  Add tests

#4069: avoid noise from Opera managed storage errors

---

src/components/Markdown.tsx
src/components/documentBuilder/__snapshots__/documentTree.test.tsx.snap
src/pageEditor/exampleBlockConfigs.ts

- Part of #4007 
- Fixes the styles applied to the markdown text

#4007 apply styles to markdown element

---

src/blocks/transformers/component/ComponentReader.ts

#4074: Mark component reader as experimental

---

src/blocks/effects/alert.ts
src/utils/notify.stories.tsx
src/utils/notify.tsx

#4020 Differentiate warning toast from error toast style

---

src/components/documentBuilder/createNewElement.test.ts
src/components/documentBuilder/createNewElement.ts
src/components/documentBuilder/documentBuilderTypes.ts
src/components/documentBuilder/documentTree.tsx
src/components/documentBuilder/edit/ButtonOptions.tsx
src/components/documentBuilder/edit/PipelineOptions.tsx
src/components/documentBuilder/edit/getElementEditSchemas.ts
src/components/documentBuilder/edit/useElementOptions.tsx
src/components/documentBuilder/preview/elementsPreview/Button.tsx
src/components/documentBuilder/preview/getPreviewComponentDefinition.tsx
src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx

#4009 Add ability to label brick/buttons pipelines in Document Builder

---

package-lock.json
package.json

- Includes https://github.com/pixiebrix/webext-messenger/pull/82
- Probably fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4078
I can no longer replicate with my usual repro for this issue described in https://github.com/pixiebrix/pixiebrix-extension/issues/4078#issuecomment-1226987503
This does fix the repro I've been using so it's an improvement. Let me know if you still see the issue.
- 🙉 Add tests

Ensure the options page doesn't derail the messenger

---

src/contentScript/contentScriptCore.ts
src/options/options.tsx
src/sidebar/sidebar.tsx

- Part of #4115 
- @twschiller I'd like to see this merged before the next release to ensure that any further reports of #4021 are not just due to context invalidation. It's not the cleanest implementation nor the best wording, but it's better than having it go through multiple rounds of review and miss releases.
https://user-images.githubusercontent.com/1402241/186669877-b5d9f219-b983-49f2-a493-2bf4e06db254.mov

Report context invalidation in sidebar and options page

---

src/errors/networkErrorHelpers.ts
src/options/pages/brickEditor/CodeEditor.tsx
src/options/pages/brickEditor/CreatePage.tsx
src/options/pages/brickEditor/EditPage.tsx
src/options/pages/brickEditor/useSubmitBrick.ts
src/services/api.ts

- Fixes #3115 
- Use RTKQ to create/update/delete packages

#3115 Workshop shows stale brick detail after save

---

src/analysis/analysisVisitors/templateAnalysis.test.ts
src/analysis/analysisVisitors/templateAnalysis.ts
src/blocks/PipelineExpressionVisitor.test.ts
src/blocks/PipelineExpressionVisitor.ts
src/blocks/PipelineVisitor.ts

- Fixes #4077 
- Pulls expression visiting to another class
Column and Line don't always come from nunjucks:

#4077 Invalid text template error analysis result not showing

---

src/contentScript/sidebarDomControllerLite.ts

- Fixes #4134 
https://user-images.githubusercontent.com/1402241/187021597-67257993-8215-4d5e-8801-3d615a7b825a.mov

#4134: Fix: Sidebar no longer pushes the content aside

---

src/background/messenger/api.ts
src/background/messenger/registration.ts
src/pageEditor/hooks/useRemoveExtension.ts
src/pageEditor/hooks/useRemoveRecipe.ts
src/pageEditor/toolbar/ActionToolbar.tsx

- Closes #3360 
- Expose clearLog function to background messeng api

#3360: Clear extension logs when removing extension

---

src/options/options.html
src/pageEditor/pageEditor.html
src/sidebar/sidebar.html
src/tinyPages/permissionsPopup.html

- Closes #4162 
- See PR for copy changes: Loading PixieBrix Options -> Loading Extension Console

#4162: remove brand name from html fallback loaders

---

package-lock.json
package.json
src/components/Stylesheets.tsx
src/components/quickBar/QuickBarApp.tsx

- Closes #3504 
- Upgraded kbar library version to "^0.1.0-beta.36"

#3504: Quickbar can't be closed by clicking outside

---

src/analysis/analysisVisitors/traceAnalysis.ts
src/pageEditor/analysisManager.ts
src/pageEditor/slices/runtimeSelectors.ts

- Fixes #4177
https://www.loom.com/share/5fc68a081c864eeb89b4d8083fb962cf

#4177 Analysis Engine shows error on wrong brick if you insert a brick before a brick

---

src/options/pages/blueprints/ListFilters.tsx
src/options/pages/marketplace/ActivateWizard.tsx
src/pageEditor/ElementWizard.tsx
src/utils/preventNativeFormSubmission.ts

- Fixes #4122 permanently
- Re-fixes https://github.com/pixiebrix/pixiebrix-extension/issues/3879
- Re-fixes https://github.com/pixiebrix/pixiebrix-extension/issues/1654
- Instead of catching each form at a time, this catches them all
The video shows focusing one of the affected fields and pressing enter (see the black keypress overlay in the middle)
https://user-images.githubusercontent.com/1402241/187023698-f0b0dc98-c70a-45d9-a016-ad49f93c9d72.mov

#4122: Globally prevent native form submissions

---

src/background/browserAction.ts

More details in:
- fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4180#issuecomment-1232477503
- Feel free to close if you prefer going to opposite direction and showing an error for both instead

#4180: Open option page when clicking the browser action on the Web Store

---

src/auth/ScopeSettings.tsx
src/contrib/google/initGoogle.ts
src/options/pages/services/ServiceEditorModal.tsx

Small `reportError`-related fixes

Fix a couple of `reportError` mis-uses

---

src/auth/RequireAuth.test.tsx
src/auth/RequireAuth.tsx
src/pageEditor/Panel.tsx

#4200 Removing Router from Page Editor

---

.gitattributes
.gitignore
.prettierignore
public/mockServiceWorker.js
src/auth/RequireAuth.tsx
src/background/browserAction.ts

Reverts pixiebrix/pixiebrix-extension#4211
Fixes https://github.com/pixiebrix/pixiebrix-extension/pull/4221
Gitignore it
https://github.com/mswjs/msw/discussions/1015#discussioncomment-1747585
Commit it 🤷‍♂️ or generate it every time via `npx msw init public`
https://mswjs.io/docs/faq#should-i-commit-the-worker-script-to-git

Restore `mockServiceWorker.js` + small fixes

---

src/utils/jqueryHack.ts

- Fixes #4326
- Introduced by #4281 
- `Element#querySelectorAll` is a different function from `document.querySelectorAll`, but the latter was being "reset" to both
- The code could be better, but I opted for some copy-paste to avoid overengineering it
https://user-images.githubusercontent.com/1402241/191488585-0c18f47a-fde7-4a12-bd67-7c86271141af.mov
- https://github.com/jquery/jquery/pull/5107

#4326: Restore native querySelectorAll after jQuery monkeypatch

---

src/sidebar/Tabs.module.scss
src/sidebar/Tabs.tsx

- Closes #4290 
1 tab
2 tabs
3 tabs

#4290 Improve stacked tabs UI

---

src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/tabs/editTab/editorNodeLayout/usePasteBlock.ts
src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx

- Fixes #4287 
- I thought about creating a better helper function to normalize one block, but I didn't think the implementation here was quite messy enough to warrant that

#4287 Fix the paste action for bricks with sub-pipelines

---

src/components/addBlockModal/AddBlockModal.module.scss
src/components/addBlockModal/AddBlockModal.tsx
src/components/addBlockModal/TagList.module.scss
src/components/addBlockModal/TagList.tsx

- Closes #4341 
- This is definitely a one-off solution for Automation Anywhere, but we already are doing that to hide the UiPath bricks
- We will eventually have to generalize some of this stuff for custom tags and custom filters for certain parter keys

Add block filter tag for Automation Anywhere users

---

src/blocks/transformers/component/TableReader.test.ts
src/blocks/transformers/component/TableReader.ts

#4364 Fix table reader - show better error message for bad selector

---

src/components/documentBuilder/preview/ElementPreview.test.tsx
src/components/documentBuilder/preview/ElementPreview.tsx
src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap

#4402 Disable markdown links in the document builder preview

---

src/components/selectionToolPopover/SelectionToolPopover.tsx
src/contentScript/contentScript.scss
src/contentScript/nativeEditor/elementPicker.ts
src/contentScript/nativeEditor/selectorInference.ts
src/vendors/Overlay.tsx

- Part of #4282 
- _Were there multiple approaches you were deciding between?_
Selection expand should overlay similar elements with light overlay.
In the screenshot, top 3 links are examples and others are selection expand overlays.

#4082: add support for inferring a selector for multiple elements

---

src/background/logging.ts

- Closes #4407
- I didn't set this up so I'm not totally sure this is the right fix. But it looks straightforward.

#4407: Stop reporting user/business errors to Rollbar

---

src/options/pages/blueprints/InstallableIcon.module.scss
src/options/pages/blueprints/InstallableIcon.tsx

4342 Inconsistent alignment in List View

---

src/blocks/effects/alert.ts

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4447

#4447: Stop reporting errors from the Alert brick

---

src/components/selectionToolPopover/SelectionToolPopover.module.scss
src/components/selectionToolPopover/SelectionToolPopover.tsx
src/contentScript/contentScript.scss
src/contentScript/nativeEditor/elementPicker.ts

- Closes #4450 
- How can i change the color of Icon component? 
-before
-after
8.png)
- Updated Icon and Cursor

#4450: Improve ux of selection tool card

---

.github/workflows/loom-get.sh
.github/workflows/loom-reminder.yml
.github/workflows/loom-slack.yml

To do:
https://www.loom.com/share/123456789a123456789a123456789a12

Automatically post PR Looms to Slack

---

src/components/selectionToolPopover/SelectionToolPopover.module.scss
src/contentScript/nativeEditor/selectorInference.ts

- Closes #4440 
-before
-after

#4440: Selection Tool is not isolated from page style 

---

.github/workflows/loom-slack.yml

Continues from:
- #4498 
To do:

Improve "PR to Slack" automation

---

src/validators/generic.test.ts
src/validators/generic.ts

- Fixes #4505 
https://www.loom.com/share/09b6d5a8bd664097a571d9e2a9a4b97c

#4505 Running brick with DB ref parameter errors at runtime with "Unresolved $ref"

---

src/options/App.tsx
src/options/store.ts
src/pageEditor/Panel.tsx
src/pageEditor/store.ts
src/sidebar/Header.tsx

- May be related to #4220 
Moves the logs polling from a store to an app level. Solves the issue with Sidebar polling logs unnecessary.

#4220 Sidebar bugfixes

---

src/contentScript/sidebarDomControllerLite.ts
src/utils/shadowWrap.ts

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4502
Requesting review from @BLoe because he recently reviewed similar PRs
https://user-images.githubusercontent.com/1402241/197162136-c2237a27-9aff-4a27-9f8b-0540dc338621.mov
- https://github.com/pixiebrix/pixiebrix-extension/pull/4517
- https://github.com/pixiebrix/pixiebrix-extension/issues/4518

Limit sidebar DOM conflicts

---

src/development/errorsBadge.ts
src/options/Navbar.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2710

#2710: Don't show email before user connects the account

---

src/blocks/transformers/FormData.test.ts
src/blocks/transformers/FormData.ts
src/pageEditor/sidebar/modals/AddToRecipeModal.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4500

#4500: Add support for checkboxes in `@pixiebrix/forms/data`

---

src/pageEditor/EditorContent.tsx
src/pageEditor/hooks/useCurrentUrl.ts

- Fixes #4552 
- Adds some logging to help diagnose #4551

#4552 Fix broken grant-permissions button

---

src/pageEditor/panes/PermissionsPane.tsx

- Part of #4552 
- Show error toast if permissions request fails

#4552: show error toast on permissions error

---

src/core.ts
src/errors/errorHelpers.ts
src/pageEditor/EditorContent.tsx
src/pageEditor/hooks/useAddElement.ts
src/pageEditor/pageEditorTypes.ts
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSlice.ts
src/pageEditor/tabState/tabStateSelectors.ts
src/pageEditor/tabState/tabStateSlice.ts
src/pageEditor/tabState/tabStateTypes.ts

- Closes #4459 
- Replaces and closes https://github.com/pixiebrix/pixiebrix-extension/pull/4526
@fregante Does this seem alright to you? Does this remove the need for #4526?
@twschiller @BALEHOK Anyone see anything wrong with this?

#4459 Serialize errors in redux

---

src/options/pages/onboarding/SetupPage.test.tsx
src/options/pages/onboarding/SetupPage.tsx
src/options/pages/onboarding/partner/PartnerSetupCard.tsx

#4629: prepend url scheme in AA configuration form and ensure service definitions have been fetched

---

src/blocks/transformers/FormData.test.ts
src/blocks/transformers/FormData.ts

- Fixes #4593
- The fromEntries was failing due to undefined elements in the array

#4593: handle unnamed fields in form reader

---

src/extensionPoints/menuItemExtension.ts

- Fixes #4654 
See also:
- https://github.com/pixiebrix/pixiebrix-extension/pull/4651/files#r1022140607
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1668463852889079

#4654 - Fix button placement on the page

---

src/components/fields/schemaFields/widgets/registerDefaultWidgets.ts
src/extensionPoints/panelExtension.ts

- See https://github.com/pixiebrix/pixiebrix-extension/pull/4655
- Reverts another line from https://github.com/pixiebrix/pixiebrix-extension/pull/4651

#4654 - Fixes panelExtension placement on the page

---

src/runtime/brickYaml.ts

- Fixes #4724 
https://www.loom.com/share/425e0446ad604e88bea64d5b7f785a24

#4724 Blueprints have invalid top-level id field in Workshop YAML

---

package-lock.json
src/components/addBlockModal/AddBlockModal.test.tsx
src/pageEditor/EditorContent.test.tsx
src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/testHelpers.ts
src/recipes/recipes.test.tsx
src/services/api.ts
src/testUtils/testAfterEnv.js
src/types/contract.ts
src/types/definitions.ts

#4724 blueprint id test

---

src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx

Fix broken import on `main`

---

src/__snapshots__/Storyshots.test.js.snap

- Fixes broken storyshot on `main`

Fix broken snapshot on `main`

---

src/components/form/widgets/createMenuListWithAddButton.tsx
src/options/pages/blueprints/BlueprintActions.tsx
src/options/pages/blueprints/modals/ShareRecipeModal/ActivationLink.tsx
src/options/pages/blueprints/modals/ShareRecipeModal/PublishRecipeModal.tsx
src/options/pages/blueprints/modals/ShareRecipeModal/ShareRecipeModal.tsx

- Closes #4791 
- This is a PR subsequent to #4786 
https://www.loom.com/share/f34fdf72b45746f38226e7fffdd9cc7e

#4791 Marketplace Publish A2: Modify Share Modal to Remove Public Link

---

src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
src/runtime/pipelineTests/pipelineTestHelpers.ts

4789 don't throw on invalid template

---

src/blocks/effects/replaceText.ts

- Follow up to #4864
- Use TreeWalker instead of recursion

#4864: use tree walker for replace text brick

---

src/hooks/common.test.ts
src/hooks/common.ts
src/options/pages/brickEditor/EditPage.tsx

-  Fixes #4935 
https://www.loom.com/share/92fecb9ac7d44a71b6298fb8f8557132

#4935: disable brick buttons while deleting in Workshop

---

src/background/contentScript.test.ts
src/background/contentScript.ts
src/utils.ts

- Part of #4863 
- Adds Jest tests for content script injection
- Doesn't change any behavior - behavior looks OK

#4863: add tests for content script injection

---

src/analysis/analysisVisitors/requestPermissionAnalysis.test.ts
src/analysis/analysisVisitors/requestPermissionAnalysis.ts

- Add an analysis rules to warn on `http:` URLs
- Add an analysis rule to error on invalid URLs

Add URL validation analysis rules

---

src/manifest.json

#4952: Update manifest externally connectable

---

src/pageEditor/EditorLayout.tsx
src/pageEditor/store.ts

- Related to #4830 
- We are removing this code for now until we have a better solution for some issues

#4830 Remove persistence and session sync code

---

src/utils/postMessage.ts
webpack.config.js

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4968

#4968: Fix ENV config for `WEBEXT_MESSENGER_LOGGING`

---

src/runtime/mapArgs.ts
src/runtime/pipelineTests/trace.test.ts
src/runtime/reducePipeline.ts

- Closes #4966 
- Closes #4965
- I found these when looking into #4964, but it's doubtful it solves the problem
- I couldn't figure out how to get the mocking right for one of the assertions

#4966: avoid unnecessary messenger calls when not tracing

---

src/blocks/effects/__snapshots__/highlight.test.ts.snap
src/blocks/effects/highlight.test.ts
src/blocks/effects/highlight.ts
src/blocks/effects/highlightText.test.ts
src/blocks/effects/highlightText.ts
src/blocks/effects/replaceText.test.ts
src/blocks/effects/replaceText.ts

#4996: Highlight Text Brick: don't highlight text in the head of the document

---

src/pageEditor/PanelContent.test.tsx
src/pageEditor/PanelContent.tsx
src/pageEditor/extensionPoints/adapter.ts
src/pageEditor/hooks/useExtensionTrace.ts

- Fixes #4779
- After
https://www.loom.com/share/26bf53becdf44c02b29dde7669557959
- Before
https://www.loom.com/share/b7512eeb35f74b27bf514b07cf4b0124

#4779 Bug: Trace data/statuses don't appear in Page Editor

---

src/pageEditor/exampleBlockConfigs.ts
src/pageEditor/fields/FormRendererOptions.tsx

- Closes #5033 
- Exposes submitCaption option in Page Editor
- https://www.loom.com/share/b3f5a6b6668b4f1d9821da8af760a50b

#5033: customize submit caption for Custom Form renderer

---

src/blocks/transformers/httpGet.ts

- Closes #5008 
Before:
After:

#5008 Deprecate the HTTP Get brick

---

src/telemetry/logging.ts

- Closes #4619
https://www.loom.com/share/97caf94506dd49288fd21e220f9bbb43

#4619: Throttle certain 5xx errors to Rollbar

---

src/blocks/effects/forms.ts
src/blocks/effects/registerEffects.ts
src/blocks/effects/scrollIntoView.ts
src/blocks/effects/scrollToElement.test.ts
src/blocks/transformers/component/TableReader.ts
src/contentScript/pageEditor/elementPicker.ts
src/development/headers.ts
src/pageScript/pageScript.ts
src/utils/requireSingleElement.ts

- Closes #5053 
- Matches the API of Element.scrollIntoView: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
- https://www.loom.com/share/a73715b055e94368bc1583cb5fc48a21

#5053: add scroll into view brick

---

src/blocks/transformers/randomNumber.ts

#5076: fix random number brick field description

---

src/options/pages/blueprints/useInstallables.ts

#5080: fix an NPE in useInstallables

---

src/components/addBlockModal/TagSearchInput.tsx
src/components/brickModalNoTags/BrickModal.tsx
src/components/fields/schemaFields/widgets/NumberWidget.tsx
src/components/fields/schemaFields/widgets/PasswordWidget.tsx
src/hooks/useAutoFocus.test.ts
src/hooks/useAutoFocus.ts
src/hooks/useAutoFocusConfiguration.ts
src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx

#5088 Change `useAutoFocus` to `useAutoFocusConfiguration` and default `focus` param to `false`

---

contrib/services/automation-anywhere-oauth2.yaml

- Closes #5090
- In `automation-anywhere/oauth2@3.0.1`, the `name` and `description` fields were changed but those changes weren't applied to the yaml file in this. This PR syncs those changes for consistency.

#5090: Sync automation-anywhere/oauth2 metadata

---

package-lock.json
package.json

- Closes #5123 
- Pins immer to 9.0.18

#5123: pin immer to 9.0.18

---

src/options/pages/brickEditor/useSubmitBrick.test.tsx
src/options/pages/brickEditor/useSubmitBrick.ts

- Closes: #4697 
- Closes: #4556
- https://www.loom.com/share/8718a982d429474195b96dfbb39b7c33

#4697: notify on non-config field errors in workshop

---

.github/workflows/rainforestqa.yml

- Fixes issue with #5129 
- Part of #5126

Fix option that was renamed in rainforest CLI

---

src/runtime/pipelineTests/trace.test.ts
src/runtime/reducePipeline.ts

- Fixes #3751 
- The extension id wasn't be passed through correctly when recording entries. So the Page Editor couldn't find the start entry
- https://www.loom.com/share/b9dd204d3e7947e2972e242e4d3c3adf

#3751: show in progress indicator on bricks

---

.storybook/main.js

- Fixes Stories that reference background messenger API directly/indirectly

Import jest mock for storybook

---

package-lock.json
package.json
webpack.sharedConfig.js

- Adds path polyfill required by https://github.com/pixiebrix/pixiebrix-extension/pull/5151

Add path polyfill

---

src/__snapshots__/Storyshots.test.js.snap
src/components/fields/schemaFields/widgets/TextWidget.stories.tsx
src/components/form/Form.tsx

- Creates a TextWidget.stories.tsx file

Add TextWidget to Storybook

---

.github/workflows/ci.yml
src/__snapshots__/Storyshots.test.js.snap
src/components/ServiceAuthSelector.tsx
src/options/components/ServiceFieldError.tsx
src/options/pages/activateExtension/ServicesRow.tsx
src/options/pages/marketplace/ActivateWizard.module.scss
src/options/pages/marketplace/ActivateWizard.tsx
src/options/pages/marketplace/ExtensionsBody.tsx
src/options/pages/marketplace/OptionsBody.tsx
src/options/pages/marketplace/PermissionsBody.tsx
src/options/pages/marketplace/ServicesBody.tsx
src/options/pages/marketplace/__snapshots__/ActivateWizard.test.tsx.snap
src/options/pages/marketplace/__snapshots__/OptionsBody.test.tsx.snap
src/options/pages/marketplace/useWizard.ts
src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.module.scss
src/sidebar/activateRecipe/ActivateRecipePanel.tsx
src/sidebar/activateRecipe/__snapshots__/ActivateRecipePanel.test.tsx.snap
src/testUtils/testEnv.js
src/utils/strings.ts
webpack.config.js

- Follow up from #5072 - UI polish

#5072 Marketplace sidebar activation UI fixes

---

src/background/activeTab.ts
src/background/messenger/api.ts
src/background/messenger/registration.ts
src/background/navigation.ts
src/contentScript/lifecycle.ts
src/contentScript/messenger/api.ts
src/contentScript/messenger/registration.ts
src/options/pages/blueprints/useInstallableViewItemActions.ts
src/options/pages/blueprints/utils/uninstallRecipe.ts
src/options/pages/blueprints/utils/useInstall.ts
src/options/pages/blueprints/utils/useReinstall.test.ts
src/options/pages/blueprints/utils/useReinstall.ts
src/options/testHelpers.tsx
src/pageEditor/PanelContent.test.tsx
src/pageEditor/PanelContent.tsx
src/store/dynamicElementStorage.ts
src/store/extensionsSlice.ts
src/testUtils/testHelpers.tsx

- Fixes #5134 
https://www.loom.com/share/af0754a180734748a4b01c60377857bc
A demo with context menu item
https://www.loom.com/share/cb09feeadbe74ad68c47e4d2cd2af883

#5134 Bug: Blueprint showing up multiple times in QuickBar

---

src/components/ServiceAuthSelector.tsx
src/options/pages/marketplace/ServicesBody.module.scss
src/options/pages/marketplace/useWizard.ts
src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.module.scss

- Fixes the release blocker bug described here: https://www.notion.so/pixiebrix/Release-1-7-19-ec688e1662344cb39a11bc60531787c7

Marketplace sidebar activation - bug fixes

---

src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
src/runtime/expressionCreators.ts

- Fixes the "" is not a variable annotation
https://www.loom.com/share/95f5d98d443f44e19c2735bf868ac1e3

Do not show "" is not a variable annotation

---

src/contentScript/marketplace.ts
webpack.config.js

- Changes some configs to get this all working properly in staging with the staging marketplace

Marketplace sidebar activation - url configs for staging

---

src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx

- Follow up to [the comment](https://github.com/pixiebrix/pixiebrix-extension/pull/5233#discussion_r1111265408) on PR #5233

Cleanup duplicate mock in ActivateRecipePanel test

---

src/blocks/transformers/jquery/JQueryReader.ts

#5241 - Rename jQuery brick to Extract from Page

---

src/extensionPoints/triggerExtension.test.ts
src/extensionPoints/triggerExtension.ts

- Fixes #5270 
- Fixes bug where trigger was calling stub reader and erroring out

#5270: fix trigger reader error

---

contrib/services/google-sheet.yaml

- Part of #5272, but not the real fix, this just updates the placeholder on the extension side. The real fix is in the app project.

#5275 Fix sheet picker in add-new-service modal during mod activation

---

public/mockServiceWorker.js
src/components/fields/schemaFields/BasicSchemaField.tsx
src/components/fields/schemaFields/getToggleOptions.tsx
src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx
src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
src/contrib/google/sheets/SheetsFileWidget.tsx
src/contrib/google/sheets/TabField.test.tsx
src/contrib/google/sheets/TabField.tsx
src/hooks/useToggleFormField.tsx

- Closes #5265 
https://www.loom.com/share/2ac608be68444b109af301637bb2f48f

#5265 Allow variables in the tab name fields

---

src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
src/contrib/google/sheets/useOnChangeEffect.test.ts
src/contrib/google/sheets/useOnChangeEffect.ts

- Part of #5303 
- Add test for useOnChangeEffect hook

#5303: fix change handler for GSheets fields

---

src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx
src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
src/contrib/google/sheets/LookupSpreadsheetOptions.test.tsx
src/contrib/google/sheets/TabField.test.tsx
src/contrib/google/sheets/TabField.tsx

- Fixes another TabField issue

GSheets - fix tab field again and add tests

---

src/pageEditor/tabs/contextMenu/ContextMenuConfiguration.tsx
src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx
src/pageEditor/tabs/trigger/DebounceFieldSet.tsx
src/pageEditor/tabs/trigger/TriggerConfiguration.tsx

- Closes #5329 
- ~Assigning @BrandonPxBx to review the copy updates here, Todd just for S.A.~
- Brandon and Corinne will review in the UI of the app, not the PR here

#5329 Update field labels and descriptions on starter brick config panels

---

src/options/options.html
src/tinyPages/permissionsPopup.html

- Closes #5373
I searched for all instances of the URL

#5373: allow region in marketplace URL

---

.github/workflows/rainforestqa.yml

- Part of [#3166](https://github.com/pixiebrix/pixiebrix-app/pull/3166) in app
- Updates reset endpoint for rainforest test data to new endpoint

update rainforest data seed endpoint in workflow

---

.github/workflows/release.yaml

- Part of #5408 
- https://github.com/pixiebrix/pixiebrix-extension/pull/5409

#5408: Fix CI variables for Datadog in release build

---

.github/workflows/release.yaml

- Part of #5408
- Follow up to the previous PR that added to CI for the CWS, but not alpha/beta builds

#5408: include Datadog on alpha/beta builds

---

src/telemetry/performance.ts

- Fixes #5430 
- See https://github.com/DataDog/browser-sdk/issues/446
- Will need to verify in next beta build

#5430: suport RUM in page editor

---

.storybook/main.js
package-lock.json
package.json
src/options/pages/blueprints/BlueprintsPageSidebar.tsx
src/utils/inference/markupInference.ts

- Closes #5356 
- Bumps the extension project to Typescript 5
- The one bootstrap type is wacky/hard to grok. Just ignoring the error given that the code hasn't been touched in months

#5356: bump to Typescript 5

---

src/components/fields/schemaFields/widgets/TextWidget.test.tsx
src/components/fields/schemaFields/widgets/TextWidget.tsx

- Fixes #5282
- Tests `isVarValue` separately
- https://www.loom.com/share/69de3aa4e00a474ba3c0b3cc7ae7ca97

Update isVarValue to recognize spaces in variables

---

src/contrib/google/sheets/getSheetServiceOutputKey.test.ts
src/contrib/google/sheets/getSheetServiceOutputKey.ts
src/contrib/google/sheets/useSpreadsheetId.test.ts
src/contrib/google/sheets/useSpreadsheetId.ts

#5442 Handle legacy sheets service configs

---

src/options/pages/blueprints/useInstallables.test.ts
src/options/pages/blueprints/useInstallables.ts

- Closes ##5460
- Shows single installable on mods screen for unknown mod

#5460: fix repeat deleted/revoked installables entries

---

src/__snapshots__/Storyshots.test.js.snap
src/blocks/effects/alert.ts
src/blocks/transformers/component/TableReader.ts
src/blocks/transformers/jquery/JQueryReader.ts
src/blocks/transformers/url.ts
src/components/fields/schemaFields/ServiceField.tsx
src/components/fields/schemaFields/genericOptionsFactory.tsx
src/components/fields/schemaFields/widgets/ObjectWidget.tsx
src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx
src/components/fields/schemaFields/widgets/__snapshots__/ObjectWidget.test.tsx.snap
src/contrib/automationanywhere/__snapshots__/BotOptions.test.tsx.snap
src/contrib/editors.ts
src/contrib/google/sheets/__snapshots__/AppendSpreadsheetOptions.test.tsx.snap
src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap
src/pageEditor/fields/AlertOptions.tsx
src/pageEditor/fields/SelectorSelectorWidget.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap

#5330 Update page editor terminology - slice 2

---

src/chrome.test.ts
src/chrome.ts
src/extensionConsole/pages/activateRecipe/PermissionsBody.tsx
src/pageEditor/extensionPoints/quickBar.tsx
src/sidebar/activateRecipe/ActivateRecipeInputs.tsx

- Automatically scrolls/highlights the Quick Bar shortcut entry  in Chrome settings

Automatically scroll to Quick Bar shortcut entry on shortcuts screen

---

src/pageEditor/tabs/contextMenu/ContextMenuConfiguration.tsx

#5330 Followup - fix context menu field label

---

src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.module.scss
src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.tsx
src/sidebar/activateRecipe/__snapshots__/ActivateRecipePanel.test.tsx.snap

- Closes #5497 
https://www.loom.com/share/7d8c3fc918ac4854adaf43916f58a02c

#5497 Quick Bar marketplace sidebar activation improvements

---

.github/workflows/rainforestqa.yml

- Fixes #5542 
- [Reference used for updating usage](https://github.com/orgs/community/discussions/27027#discussioncomment-3254357)

5527: Fix usage of github env var in shell

---

src/pageEditor/tabs/recipeOptionsDefinitions/RecipeOptionsDefinition.tsx
src/pageEditor/tabs/recipeOptionsDefinitions/RecipeOptionsDefinitions.test.tsx

- Closes #5535 
- Will be a merge conflict after the gsheets feature flag removal PR merges, will wait until after fixing that to merge this one
https://www.loom.com/share/9e7b49a47e084bb4b184697e278f741a

#5535: add Create Personal Database to mod input options

---

src/components/quickBar/QuickBarApp.tsx
src/components/quickBar/QuickBarResults.tsx
src/components/quickBar/quickBarTheme.tsx

#5537 Update quick bar color and spacing

---

src/contentScript/lifecycle.ts
src/extensionPoints/menuItemExtension.ts

- Closes #5603 
- Fixes lifecycle navigation bug where if an extension point wasn't available on initial page of SPA, then it couldn't be available after navigation

#5603: fix lifecycle navigation bug for SPAs

---

src/contentScript/sidebarDomControllerLite.ts
src/themes/colors.scss
src/vendors/theme/assets/styles/_themes.scss
src/vendors/theme/assets/styles/_variables.scss

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/5573
- Also adds some color variables to colors.scss to support team selector color changes in https://github.com/pixiebrix/pixiebrix-app/pull/3373
- See video demo below, but some of the colors in the spec don't correspond to design system color variables. I named them something arbitrary for now (e.g. `neutral-surface-color`) but we'll ideally use colors define somewhere in Figma
- https://www.loom.com/share/8a848b57ba9b4e73afe4a55c7faf1d76

#5573 Update Extension Console background color

---

src/hooks/auth.ts
src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.tsx
src/sidebar/activateRecipe/RequireRecipe.tsx
src/sidebar/activateRecipe/useMarketplaceActivateRecipe.ts

- Fixes #5572 
- Pays back some tech debt around mod activation permissions, it was very hacky
- Look at the changes to `RequireRecipe` and then follow how the state is passed down into the activate panel components

#5572 Fix infinite loading on marketplace activation

---

src/sidebar/activateRecipe/ActivateRecipePanel.tsx

- Follow up from #5607, code cleanup
- Didn't want to hold up the build to get this through CI again

Follow up to #5572 - fix unneeded async effect

---

src/extensionConsole/components/RequireBrickRegistry.tsx

- Fixes a semantic merge conflict in https://github.com/pixiebrix/pixiebrix-extension/pull/5649

#5648: fix type error in merged code

---

src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx
src/sidebar/activateRecipe/__snapshots__/ActivateRecipePanel.test.tsx.snap

#5710 Fix activation error with mods with empty options schema

---

src/hooks/useAsyncState.ts
src/sidebar/FormBody.test.tsx
src/sidebar/FormBody.tsx
src/sidebar/__snapshots__/FormBody.test.tsx.snap
src/testUtils/factories.ts

- Fixes #5713 
- Modifies the useAsyncState hook to start in an isLoading/isFetching state

#5713: change useAsyncState to start in isLoading state; fix NPE in FormBody

---

src/components/fields/schemaFields/serviceFieldUtils.test.ts
src/components/fields/schemaFields/serviceFieldUtils.ts

- Fixes #5699 
- We should rewrite this function as a pipeline visitor soon

#5699: handle document builder list element when collecting integration variables

---

src/components/documentBuilder/render/ListElement.tsx

- Closes #5872 
- Switches to use the new useAsyncState hook, and shows loader on isLoading vs. isFetching
- Wraps loader in DelayedRender to avoid flickering on load, because DeferredExpression calculations are fast
- https://www.loom.com/share/53cea03952964ed4ada14b3ade820c5a
- https://github.com/pixiebrix/pixiebrix-extension/issues/5825

#5872: fix DocumentBuilder list element flickering

---

src/activation/ActivationLink.tsx
src/activation/activateLinkClickHandler.test.tsx
src/activation/activateLinkClickHandler.ts
src/extensionConsole/pages/blueprints/modals/shareModals/EditPublishContent.tsx
src/extensionConsole/pages/blueprints/modals/shareModals/PublishRecipeContent.tsx
src/extensionConsole/pages/blueprints/modals/shareModals/PublishedContent.tsx
src/extensionConsole/pages/blueprints/modals/shareModals/ShareRecipeModalBody.tsx
src/sidebar/ConnectedSidebar.tsx

- Closes #5866 
https://www.loom.com/share/e314e46b02b1436786699dda9ab3a34a

#5866 - Activate links in sidebar mods

---

src/components/floatingActions/FloatingActions.scss
src/components/floatingActions/FloatingActions.tsx
src/components/floatingActions/QuickbarButton.tsx
src/components/floatingActions/store.ts
src/icons/drag-handle.svg

- Closes #5887
- Adds drag handle to floating action button
- Adds telemetry for the reposition
- [Loom](https://www.loom.com/share/eb0ef697a0a944438810d65ca22828ef?sid=a1e72bba-2023-4a24-a191-e1215668c546)

5887 Reposition Floating Action Button

---

src/blocks/transformers/ephemeralForm/formTransformer.ts
src/contentScript/ephemeralFormProtocol.ts
src/sidebar/sidebarSlice.test.ts
src/sidebar/sidebarSlice.ts
src/testUtils/factories/sidebarEntryFactories.ts
src/types/sidebarTypes.ts

- Closes #5998
- [Slack Discussion Thread](https://pixiebrix.slack.com/archives/C023KL47XV4/p1688405282167619)
https://www.loom.com/share/f9e3c9282fe34aba85056fd23ed77ef8

#5998: check for other panels for the mod on remove

---

src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx

- Fixes a semantic merge conflict in some recent branches

Fix broken VarMenu tests from merge conflict

---

src/__mocks__/@/background/messenger/api.ts
src/runtime/pipelineTests/trace.test.ts
src/runtime/reducePipeline.ts

- Part of #6058 
- 🐛 Fixes bug in my recent PR https://github.com/pixiebrix/pixiebrix-extension/pull/6059 where a condition would never be met
- Adds test coverage for the condition

#6058: fix tracing check for brick telemetry

---

src/__mocks__/@/background/messenger/api.ts
src/background/messenger/api.ts
src/background/messenger/registration.ts
src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
src/contrib/google/sheets/append.ts
src/contrib/google/sheets/handlers.ts
src/contrib/google/sheets/lookup.ts
src/contrib/google/sheets/types.ts

- Closes #5996 
- `getAllSpreadsheets` and `getSpreadsheet` aren't used yet, just added for later
- It might be easier to just open the `handlers.ts` file and read it there, since I essentially re-wrote most of it
- Some of the functions were using batch calls where they didn't need to, so I simplified them to the single-request versions

#5996 Switch google sheets handlers to use proxyService

---

src/contrib/google/sheets/handlers.ts

- Fixes a merge conflict with some type names + my recent google sheets PR

Fix type rename merge conflict

---

src/components/documentBuilder/edit/getElementEditSchemas.tsx

#6033 - page editor button field label updates

---

src/contentScript/sidebarActivation.ts

- Closes #6025
- https://www.loom.com/share/d82bff5609dc4840a89b1603a7ec4920

#6025 Redirect to nextUrl before starting sidebar activation when user is logged in

---

src/types/starterBrickTypes.ts

- Improves starter brick documentation
- See PR feedback from: https://github.com/pixiebrix/pixiebrix-extension/pull/6127/files

Improve starter brick interface method documentation

---

README.md

- Clarify dual AGPL and commercial license in the README.md

Clarify dual AGPL and commercial license in README

---

src/background/installer.ts
src/telemetry/events.ts

#6169 - fixes telemetry event - PixieBrixUninstall -> PixieBrixUpdate

---

src/contrib/google/sheets/core/sheetsApi.ts

- Part of #6176 
- Adds a timeout to non-interactive Google token retrieval
- Probably doesn't solve the underlying cause of the hanging

#6176: add timeout to non-interactive legacy google token retrieval

---

src/sidebar/Tabs.module.scss
src/sidebar/Tabs.test.tsx
src/sidebar/Tabs.tsx
src/sidebar/TemporaryPanelTabPane.tsx
src/sidebar/__snapshots__/Tabs.test.tsx.snap
src/sidebar/modLauncher/ActiveSidebarModsList.tsx
src/sidebar/modLauncher/ActiveSidebarModsListItem.module.scss
src/sidebar/sidebar.html
src/sidebar/sidebarSelectors.test.ts
src/sidebar/sidebarSelectors.ts
src/sidebar/sidebarSlice.ts
src/sidebar/testHelpers.ts
src/types/sidebarTypes.ts

- Closes #6159 
https://www.loom.com/share/cb271075ec624349992de9c44b30a6af

#6159: open and close mods tab

---

src/activation/WizardValuesModIntegrationsContextAdapter.tsx
src/contrib/google/sheets/core/sheetsApi.ts
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
src/extensionConsole/pages/activateRecipe/ActivateRecipeCard.test.tsx
src/extensionConsole/pages/activateRecipe/__snapshots__/ActivateRecipeCard.test.tsx.snap
src/extensionConsole/pages/mods/modals/shareModals/__snapshots__/PublishRecipeModals.test.tsx.snap

#6226 - Fix console activation for mods with no services property

---

src/auth/ScopeSettings.tsx
src/extensionConsole/pages/mods/modals/convertToRecipeModal/__snapshots__/ConvertToRecipeModal.test.tsx.snap
src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap

#6081 - slice 1 update account alias validation messaging in page editor

---

src/vendors/jsonSchema/deep-compare-strict.ts
src/vendors/jsonSchema/dereference.ts
src/vendors/jsonSchema/format.ts
src/vendors/jsonSchema/index.ts
src/vendors/jsonSchema/pointer.ts
src/vendors/jsonSchema/types.ts
src/vendors/jsonSchema/ucs2-length.ts
src/vendors/jsonSchema/validate.ts
src/vendors/jsonSchema/validator.ts
tsconfig.json

- Part of #6206 
- Vendors the json-schema dependency with the changes from https://github.com/cfworker/cfworker/compare/main...fregante:cfworker:srcdoc
- I tried using https://gitpkg.vercel.app/ to add the subfolder in the fork directly as a dependency, but was getting a `TAR_BAD_ARCHIVE: Unrecognized archive format` error
- Visit https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe and add a confetti brick with target set to "All Frames"

#6206: vendor json-schema with URI bugfix

---

src/background/activeTab.ts
src/background/messenger/api.ts
src/pageEditor/hooks/useRemoveExtension.ts
src/store/uninstallUtils.ts

- Fixes #5716
- https://www.loom.com/share/c0426b81b3544f1e913ea11eacd63a32
- I haven't confirmed if not awaiting removing extensions from every tab before reactivating for every tab will cause an issue yet

#5716 Exclude non-http urls from getTabsWithAccess, and convert removeExtensionFromEveryTab to notification

---

src/contrib/google/sheets/core/useGoogleAccount.ts
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx
src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
src/contrib/google/sheets/ui/__snapshots__/AppendSpreadsheetOptions.test.tsx.snap
src/contrib/google/sheets/ui/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap
src/contrib/google/sheets/ui/__snapshots__/SpreadsheetPickerWidget.test.tsx.snap

#6238 Google PKCE / GSheets feature flag

---

.eslintrc.js
jest.config.json
src/contentScript/sidebarDomControllerLite.ts
src/development/cryptoNodePolyfill.js
src/development/headers.ts

- Part of #6231 
- Fixes bug where crypto.randomUUID was being used in insecure context
- Adds eslint rule to ban randomUUID

#6231: ban uses of crypto random uuid

---

src/errors/errorHelpers.ts

- Part of #6246 
- Quick-fix to eliminate the Rollbar spam here

#6246 - Add new filter string to ignored error message patterns

---

src/contentScript/lifecycle.ts

- Closes #6253 
- Closes a bug where starter bricks not available on page load are not run on SPA navigation
- Do origin-matching to determine starter bricks that can't run in the same session/SPA

#6253: add new starter bricks on SPA navigation

---

src/bricks/transformers/jquery/JQueryReaderOptions.test.tsx
src/bricks/transformers/jquery/JQueryReaderOptions.tsx

- Closes #6275
https://www.loom.com/share/e2bf07f7fe014eaca895f5485c706b61

#6275: clearing a property in the extract from page brick then blurring throws an error

---

src/sidebar/ConnectedSidebar.test.tsx
src/sidebar/ConnectedSidebar.tsx
src/sidebar/Tabs.test.tsx
src/sidebar/Tabs.tsx
src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap
src/sidebar/__snapshots__/Tabs.test.tsx.snap

- removes the mod launcher flag

Remove mod launcher feature flag

---

src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx

- Closes #6230
- https://www.loom.com/share/a19d1615f0644095b0f86f70e30badd8

#6230 Scroll-to document renderer brick when clicking a document preview element without a pipeline

---

src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
src/extensionConsole/pages/mods/hooks/useViewPublishAction.ts

#6325 adds feature flag for publishing to marketplace

---

src/components/fields/schemaFields/widgets/cssClassWidgets/CssSpacingWidget.tsx

6318: fix margin/padding select menu placement

---

src/components/fields/schemaFields/widgets/cssClassWidgets/CssSpacingWidget.module.scss

6317: fixes papercut with carat placement

---

src/activation/useActivateRecipeWizard.ts

- Part of https://github.com/pixiebrix/pixiebrix-extension/pull/6323
- Slack context: https://pixiebrix.slack.com/archives/C0436P48QHY/p1692977278764239

Fix activation wizard allowing activation without required service configurations

---

src/activation/useActivateRecipeWizard.ts
src/background/modUpdater.ts
src/extensionConsole/pages/mods/utils/useReinstall.ts
src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
src/store/extensionsUtils.test.ts
src/store/extensionsUtils.ts

#6338 Handle unconfigured integrations in `inferModIntegrations()`

---

src/extensionConsole/pages/activateRecipe/ActivateRecipePage.tsx

- Closes #6326 
- https://www.loom.com/share/03d2f6a6c04f48f2bfe5d702e89cda8d

#6326 Add a notify error & redirect if 404 response on Activate Recipe page

---

src/utils/deploymentUtils.test.ts
src/utils/deploymentUtils.ts

- Fixes https://pixiebrix.slack.com/archives/C05DW7JE16Y/p1693489582892879

#6375: re-add pixiebrixIntegration in mergeDeploymentIntegrationDependencies

---

src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.ts

- Closes #6320 
- Allows using the enter key to select an item in the variable suggestion popover

Use Enter Key in Variable Suggestion Popover

---

src/store/extensionsUtils.test.ts
src/store/extensionsUtils.ts

- Fixes #6438 
- This affects the "copy mod" functionality as well as possibly the background mod updater

#6438 Fix PixieBrix integration being filtered out from mods in some situations

---

webpack.sharedConfig.js

- Part of https://github.com/pixiebrix/pixiebrix-app/pull/3965
It can be merged before or after that, it's not interdependent

Update support for webpack config reuse

---

.github/workflows/release.yaml

- Updates the channel name in the Release build

fix slack release notifications

---

package-lock.json
package.json

#6520: reverts @apidevtools/json-schema-ref-parser to 10.x to fix breaking change

---

src/__mocks__/@/background/messenger/api.ts
src/background/messenger/api.ts
src/background/messenger/registration.ts
src/components/fields/schemaFields/BasicSchemaField.tsx
src/components/fields/schemaFields/fieldInputMode.test.ts
src/components/fields/schemaFields/fieldInputMode.ts
src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx
src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx
src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/contrib/google/sheets/core/sheetsApi.ts
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
src/contrib/google/sheets/ui/RequireGoogleSheet.tsx
src/extensionConsole/pages/activateExtension/ActivateExtensionCard.tsx
src/hooks/useToggleFormField.tsx

- Fixes #6542 
- Adds a function to check login state for a given google pkce config
- Improves some UX around clearability with SchemaSelectWidget and IntegrationDependencyWidget

#6542 Fix unhandled error edge case with google drive integration login flow

---

.github/workflows/ci.yml
src/contentScript/contentScript.ts
src/contentScript/loadActivationEnhancements.ts

#6499: Extend Messenger exclusion check to contentScript.js

---

src/__snapshots__/Storyshots.test.js.snap
src/bricks/transformers/tourStep/__snapshots__/TourStepOptions.test.tsx.snap
src/components/fields/schemaFields/widgets/__snapshots__/ArrayWidget.test.tsx.snap
src/components/fields/schemaFields/widgets/__snapshots__/FixedInnerObjectWidget.test.tsx.snap
src/components/fields/schemaFields/widgets/__snapshots__/ObjectWidget.test.tsx.snap
src/components/form/FieldTemplate.tsx
src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
src/contrib/automationanywhere/__snapshots__/BotOptions.test.tsx.snap
src/contrib/google/sheets/ui/__snapshots__/AppendSpreadsheetOptions.test.tsx.snap
src/contrib/google/sheets/ui/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap
src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
src/extensionConsole/pages/activateRecipe/__snapshots__/ActivateRecipeCard.test.tsx.snap
src/extensionConsole/pages/activateRecipe/__snapshots__/OptionsBody.test.tsx.snap
src/extensionConsole/pages/integrations/__snapshots__/ServiceEditorModal.test.tsx.snap
src/extensionConsole/pages/mods/modals/convertToRecipeModal/__snapshots__/ConvertToRecipeModal.test.tsx.snap
src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap
src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap
src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
src/pageEditor/tabs/editTab/EditTab.module.scss
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/FoundationDataPanel.test.tsx.snap
src/pageEditor/tabs/effect/__snapshots__/BlockConfiguration.test.tsx.snap
src/pageEditor/tabs/recipeOptionsValues/__snapshots__/RecipeOptionsValues.test.tsx.snap
src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
src/sidebar/activateRecipe/__snapshots__/ActivateModPanel.test.tsx.snap

- Fixes #6588
- Initially tried to fix the existing css
- Switched to using the `Collapse` from react-bootstrap
- Live demo'd to @BrandonPxBx 
https://www.loom.com/share/d965ca5d7cca4554bbf1d3ce4c7bae66

#6588: fix ux bugs from variable popover work

---

src/sidebar/Tabs.module.scss
src/sidebar/Tabs.tsx
src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap
src/sidebar/__snapshots__/Tabs.test.tsx.snap

#6493: fixes sidebar body z-index

---

src/components/quickBar/QuickBarApp.tsx

#6605: sets quickbar container background to transparent

---

src/contrib/google/sheets/core/useGoogleAccount.ts
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx

#6625: replace gsheets integration flag

---

src/store/editorMigrations.ts
src/store/extensionsMigrations.ts
src/store/extensionsStorage.ts
src/store/extensionsTypes.ts
src/types/modComponentTypes.ts

- Fixes #6661 
* I manually tested upgrading from pre-service-rename-pr, to current `main` HEAD, then applied my changes, and saw all the expected behavior, the write-to-db mod works, then breaks, then works again after my fixes

#6661 - Bug - Fix extensions slice migrations

---

src/background/partnerIntegrations.ts
src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx

- Closes #6653
-  See demo for this fix below
- Closes https://github.com/pixiebrix/pixiebrix-app/issues/4118
- See demo for this fix in the the corresponding App PR: https://github.com/pixiebrix/pixiebrix-app/pull/4119
- I thought about deleting the integration config if the login fails but there are multiple places where the login can fail so decided updating the Control Room URL is the best way to go
https://www.loom.com/share/5cd45434fd9a4b4297010cb5456996a1

#6653: Update control room URL in integration config. Also, display server error on AA auth error.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
src/errors/genericErrors.ts

- Fix lint and prettier errors, which are blocking PR's from being merged

Fix lint and prettier errors

---

.eslintrc.js
package-lock.json
package.json
src/background/refreshToken.test.ts
src/bricks/effects/pageState.test.ts
src/bricks/registry.test.ts
src/bricks/renderers/customForm.test.tsx
src/components/fields/schemaFields/widgets/cssClassWidgets/CssClassWidget.stories.tsx
src/components/fields/schemaFields/widgets/cssClassWidgets/CssSpacingWidget.stories.tsx
src/contrib/google/sheets/core/sheetsApi.test.ts
src/errors/errorHelpers.test.tsx
src/extensionConsole/pages/brickEditor/useSubmitBrick.test.tsx
src/extensionConsole/pages/integrations/ServiceEditorModal.stories.tsx
src/extensionConsole/pages/integrations/ServiceEditorModal.test.tsx
src/services/api.test.tsx
src/services/locator.test.ts
src/testUtils/testItRenders.tsx
src/testUtils/testMiddleware.ts

I'm opening this PR to test and prepare for an update in the eslint config repo:
- https://github.com/pixiebrix/eslint-config-pixiebrix/pull/128
- https://github.com/pixiebrix/pixiebrix-app/pull/4173

Move some ESLint config back into the shared config

---

src/contrib/google/sheets/ui/SheetsFileWidget.module.scss

6736: fixes the zindex for the legacy sheet picker

---

contrib/integrations/google-oauth2-pkce.yaml

Add scope to google/oauth2-pkce

---

src/contrib/google/sheets/core/sheetsApi.ts

#6701 - Include shared google sheets in the get-all-spreadsheets calls

---

.eslintrc.js
eslint-local-rules/noBrowserRuntimeGetUrl.js
eslint-local-rules/noBrowserRuntimeGetUrl.test.js
src/background/browserAction.ts
src/background/installer.ts
src/background/messenger/external/_implementation.ts
src/components/fields/schemaFields/integrations/IntegrationDependencyField.tsx
src/extensionConsole/pages/brickEditor/Editor.tsx
src/sidebar/LoginPanel.tsx
src/telemetry/logging.test.ts
src/utils/extensionUtils.test.ts
src/utils/extensionUtils.ts

- Small change for https://github.com/pixiebrix/pixiebrix-extension/pull/6780
@twschiller  I was looking into the issue you were having, so I fixed this across the extension to avoid issues and improve consistency.

Add `getExtensionConsoleUrl` utility

---

src/components/annotationAlert/FieldAnnotationAlert.module.scss
src/components/annotationAlert/FieldAnnotationAlert.tsx
src/contrib/google/auth.ts
src/contrib/google/sheets/core/sheetsApi.test.ts
src/contrib/google/sheets/ui/RequireGoogleSheet.tsx
src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx

- Fixes #6779 
- The annotation in the SpreadsheetPickerWidget was duplicated in two places in a weird way

#6779 Fix Google Sheets page editor crash

---

src/contentScript/pageEditor/beautify.ts
src/contentScript/pageEditor/insertButton.tsx
src/contentScript/pageEditor/insertPanel.tsx

- #6784 
- Fixes regression introduced in #6785

#6798: fix dynamic js-beautify import

---

src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
src/components/form/useFieldAnnotations.test.tsx
src/components/form/useFieldAnnotations.ts

- Closes #6398 
https://www.loom.com/share/d4a39a1508f94c6f97ac82b306653fd6

6398: fixes unknown variable flashup with the Variable Popup 

---

src/sandbox/messenger/executor.test.ts
src/sandbox/messenger/executor.ts

- Adds the original error to the BusinessError when running user-provided JS

adds stack trace to business errors

---

schemas/service.json

- Closes #6782 
- See corresponding backend PR: https://github.com/pixiebrix/pixiebrix-app/pull/4268
https://www.loom.com/share/27f30414c525464186a342e4f46401a5

#6782: Update service json schema

---

src/starterBricks/helpers.test.ts
src/starterBricks/helpers.ts

#6887: error adding multiple buttons to the page

---

src/components/auth/AuthWidget.tsx

#6890 - Fix regression bug in the integration auth widget for sidebar activation

---

package-lock.json
package.json
src/bricks/readers/PageMetadataReader.ts
src/globals.d.ts
src/vendors/page-metadata-parser/parser.js
src/vendors/page-metadata-parser/url-utils.js

#6889: invalid url error on retool

---

src/__snapshots__/Storyshots.test.js.snap
src/components/fields/schemaFields/widgets/varPopup/SourceLabel.module.scss
src/components/fields/schemaFields/widgets/varPopup/VarMenu.module.scss
src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
src/components/fields/schemaFields/widgets/varPopup/__snapshots__/VarMenu.test.tsx.snap
src/components/fields/schemaFields/widgets/varPopup/__snapshots__/VariablesTree.test.tsx.snap
src/components/fields/schemaFields/widgets/varPopup/popoverTheme.ts

- Closes #6685 
https://www.loom.com/share/eda2bcbeb48c4ff79cfb536b35bd4b54

#6685: variable popover visual updates

---

src/extensionConsole/App.tsx

Remove stray semicolon

---

src/background/starterMods.test.ts
src/background/starterMods.ts

- Fixes #6955 
https://www.loom.com/share/1ea8b099d2bc4933936cb1480e12b1b6

#6955: google drive version of starter mods not installing

---

.github/workflows/dependabot-auto-merge.yml

- Closes #7000
- Since this workflow only runs on Dependabot PRs, I can't test it until I've merged it

#7000: auto-approve and auto-merge dependabot @types patch prs

---

src/bricks/transformers/javascript.ts

- Javascript -> JavaScript, see https://en.wikipedia.org/wiki/JavaScript

Fix JavaScript brick capitalization

---

src/background/executor.ts
src/telemetry/events.ts

- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/5041
See that issue for context.
- https://github.com/pixiebrix/pixiebrix-extension/issues/6964

Report `PerformanceMessengerManyTabsBroadcast` event

---

src/__mocks__/@/background/messenger/api.ts
src/__mocks__/@/sandbox/messenger/api.ts
src/__mocks__/readme.md

This file was a modified copy-paste of another file. I found a solution that just re-exports any un-mocked calls instead.

Improve messenger auto-mocking

---

src/bricks/renderers/CustomFormComponent.tsx
src/components/formBuilder/TextAreaWidget.tsx

- Closes #7008 
- Fixes value passing for submitOnEnter from TextAreaWidget in RJSF

#7008: fix submitOnEnter value

---

src/sidebar/sidebarSlice.test.ts
src/sidebar/sidebarSlice.ts

- Closes #7013 
https://www.loom.com/share/52c12df825664028943da3391eacb934

#7013: closes mod launcher when temporary panels are launched

---

src/components/AsyncStateGate.tsx
src/components/documentBuilder/edit/getElementCollectionName.ts
src/components/formBuilder/ImageCropWidget.tsx
src/services/requestErrorUtils.ts
src/tsconfig.strictNullChecks.json
src/utils/inference/selectorInference.ts
src/utils/inference/selectorTypes.ts
src/utils/postMessage.ts
src/utils/typeUtils.ts

This file has several null issues so I extracted it into its own PR.
Best seen without whitespace changes
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/6908

Incremental strict null checks adoption: `selectorInference.ts`

---

src/bricks/effects/postMessage.ts
src/utils/modUtils.ts

cc @grahamlangford @BLoe `main` is failing and this is the solution. 
I mistakenly merged a PR before making this change

Fix `assertNotNull` imports 

---

src/bricks/transformers/javascript.ts

- removes the [Experimental] flag from the JS brick

Remove [Experimental] from javascript brick name

---

src/bricks/renderers/__snapshots__/customForm.test.tsx.snap
src/bricks/transformers/ephemeralForm/EphemeralForm.test.tsx
src/components/formBuilder/FieldTemplate.tsx
src/components/formBuilder/preview/FormPreview.test.tsx

#7106: fixes empty label being replaced by field name

---

src/sidebar/sidebarSlice.test.ts
src/sidebar/sidebarSlice.ts

- Fixes #7119 
https://www.loom.com/share/24c57de627324f24bff28248c9836890

#7119: closes the mod launcher when opening the mod activation panel

---

.github/workflows/dependabot-auto-merge.yml

- Expand the automatic approval and merge of dependabot PRs to include all patch updates

auto approve and merge all patch dependabot prs

---

.github/workflows/stale-issue.yml

- adds the workflow dispatch option to the stale issues pipeline

adds the workflow dispatch option to the stale issues pipeline

---

src/utils/postMessage.ts
webpack.config.js

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/7159
- Partially reverts https://github.com/pixiebrix/pixiebrix-extension/pull/6546

 #7159: Restore SANDBOX_LOGGING ENV

---

src/extensionConsole/pages/settings/ExperimentalSettings.tsx
src/sandbox/messenger/api.ts
src/store/settings/settingsTypes.ts

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/7150
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7086
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/a9f17839-b805-4337-9c14-4605d121e29e
Same but on loom: https://www.loom.com/share/8f6dbba5a8d6490caab1e9e507ec7438

#7150: Add skunkworks flag to toggle sandboxed execution

---

.github/workflows/ci.yml
.github/workflows/rainforestqa.yml
.github/workflows/release.yaml
webpack.config.js

- Mentioned in #7171
- I created a standalone PR for discovery

#7171: Drop GOOGLE_ ENVs

---

.github/workflows/ci.yml
.github/workflows/release.yaml

- Closes #7171
See review comments

#7171: Build MV3 on CI

---

.eslintrc.js
package-lock.json
package.json
scripts/webpack.scripts.js
src/background/browserAction.ts
src/starterBricks/tourExtension.ts
src/starterBricks/triggerExtension.ts
src/vendors/hoverintent.js

#7208: Restore background worker in MV3

---

.github/workflows/ci.yml
.github/workflows/release.yaml

- Closes #7189
- Maybe part of https://github.com/pixiebrix/pixiebrix-extension/issues/7174

#7189: Upload MV3 sourcemaps

---

src/extensionConsole/pages/settings/ExperimentalSettings.tsx
src/mv3/api.ts
src/sandbox/messenger/api.ts

#7222: Enforce sandbox in MV3

---

src/background/messenger/api.ts
src/background/messenger/registration.ts
src/background/telemetry.test.ts
src/background/telemetry.ts
src/runtime/pipelineTests/trace.test.ts
src/runtime/reducePipeline.ts

- Drops code related to brick run count telemetry experiment (was never turned on for external users)

Drop brick run count telemetry experiment

---

src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.test.tsx
src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.tsx

- Fixes #7272 
https://www.loom.com/share/306e3f236f0646c69f5762a9c15e841e

#7272: opens datapanel when clicking the view brick comments button

---

src/components/MarketplaceListingModIcon.module.scss
src/components/MarketplaceListingModIcon.tsx
src/extensionConsole/pages/mods/gridView/GridCardErrorBoundary.tsx
src/extensionConsole/pages/mods/listView/ListItemErrorBoundary.tsx
src/icons/constants.ts
src/mods/ModIcon.tsx
src/sidebar/Tabs.tsx
src/sidebar/modLauncher/ActiveSidebarModsList.tsx
src/sidebar/modLauncher/ActiveSidebarModsListItem.tsx
src/sidebar/modLauncher/ModLauncher.tsx
src/sidebar/sidebarSelectors.ts
src/store/extensionsSelectors.ts

- Closes #7274 
https://www.loom.com/share/7fe55b8a5ff04996b8e47d27fca73be1
- More cleanup could be done with `ModIcon` but I didn't want to mess with the Extension Console right now

#7274 - Refactor sidebar mods list for loading performance

---

.github/workflows/ci.yml
scripts/__snapshots__/manifest.test.js.snap
scripts/manifest.mjs

- Probably fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7297
- Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/7211

#7297: Restore `externally_connectable` for the app

---

src/sidebar/Tabs.tsx
src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7294
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/1234
It turns out _it was_ one class

#7294: Fix sidebar scrolling behavior

---

.github/workflows/ci.yml
.github/workflows/release.yaml
scripts/__snapshots__/manifest.test.js.snap
scripts/manifest.mjs
src/contentScript/setExtensionIdInApp.ts
src/manifest.json
webpack.config.mjs

- Part of https://github.com/pixiebrix/pixiebrix-app/issues/4523
https://www.loom.com/share/33e4d121da644af29f9ea2107dcc6ec0

Support linking App to Extension beta

---

src/contrib/google/sheets/bricks/append.test.ts
src/contrib/google/sheets/bricks/append.ts
src/contrib/google/sheets/core/sheetsApi.ts

#7347 GSheets add row validation slice 3

---

src/contrib/google/sheets/bricks/append.test.ts
src/contrib/google/sheets/bricks/append.ts
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx

#7348 GSheets add row validation configs slice 4

---

src/contrib/google/sheets/bricks/append.test.ts
src/contrib/google/sheets/bricks/append.ts
src/contrib/google/sheets/core/sheetsApi.ts
src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx

#7350 GSheets add row validation config slice 6

---

src/contrib/google/sheets/bricks/append.test.ts
src/contrib/google/sheets/bricks/append.ts

#7375 Handle empty columns when requiring all headers

---

src/extensionConsole/pages/brickEditor/BrickHistory.test.tsx
src/extensionConsole/pages/brickEditor/BrickHistory.tsx

This change also fixes a performance issue with the dropdown as described in:
https://github.com/pixiebrix/pixiebrix-extension/issues/7409
- Fixes #6455 and #7409
- Please leave any feedback on PixieBrix best practices or test utilities I might have missed.
- Not needed

 #6455 Show correct date in Workshop History tab version dropdown

---

src/__snapshots__/Storyshots.test.js.snap
src/bricks/transformers/mapping.ts
src/components/fields/fieldUtils.ts
src/components/fields/schemaFields/widgets/TextWidget.tsx
src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.ts
src/contentScript/lifecycle.ts
src/extensionConsole/pages/mods/ModsPageSidebar.tsx
src/hooks/useInterval.ts
src/hooks/useTheme.ts
src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
src/permissions/permissionsTypes.ts
src/utils/typeUtils.ts

- Resolves [#104](https://github.com/pixiebrix/eslint-config-pixiebrix/issues/104)
- Switch to using loose equality everywhere for null checks. See corresponding lint change in https://github.com/pixiebrix/eslint-config-pixiebrix/issues/104

Update eqeqeq eslint rule

---

src/development/errorsBadge.ts
src/errors/errorHelpers.ts

- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/7430
See that issue for context

#7430: Avoid RECORD_ERROR loops

---

src/__snapshots__/Storyshots.test.js.snap
src/extensionConsole/pages/mods/onboardingView/OnboardingView.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/4663
- The text has since since been fixed
- I dropped the color as suggested
- I also dropped it from another paragraph on the same page, visible only to some users (not me)
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="530" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f65b074c-e75e-48ee-a24c-099d40893709">
<td><img width="530" alt="Screenshot 10" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/f081ef94-ac67-447a-9df2-b69d4fb565cb">
</table>

#4663: Extension console marketplace text minor fix

---

src/pageEditor/sidebar/ActionMenu.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7442
| A week ago | Regression | After |
|--------|--------|--------|
| <img width="192" alt="Screenshot 14" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/6ecc6fdf-9a1b-4bd1-94bc-3b52fd98213f"> | <img width="191" alt="Screenshot 16" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/6f524943-37f7-4c0f-9105-18d260f00743"> | <img width="191" alt="Screenshot 15" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/55fb41e5-a677-4bce-aca1-cf6be791dcb8"> |

#7442: Restore space in page editor ActionMenu

---

src/bricks/transformers/ephemeralForm/formTransformer.ts
src/sidebar/sidebar.tsx

- Fixes #7467
Not in the demo, but I also verified that the modal still works.
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/aa5b62a1-b4f7-4407-8763-e95a3b09bb89

#7467: Add support for sidebar forms brick in MV3

---

src/store/browserExtensionIdStorage.ts

- Part of #7468 
- See corresponding App PR: https://github.com/pixiebrix/pixiebrix-app/pull/4665
https://www.loom.com/share/8126cf9c03e048cd9d8a60310e6f7939

#7468: Use chrome extension id from App body's dataset

---

package-lock.json
package.json
scripts/__snapshots__/manifest.test.js.snap
scripts/manifest.mjs
static/background.worker.js
static/grayIconWhileLoading.js
webpack.config.mjs

- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7374
- Inspired by https://github.com/awesome-webextension/webpack-target-webextension/issues/24#issuecomment-1914057083
- https://more-ephiframe.vercel.app/Outer?sandbox=&iframe=./Full-sandbox&iframe=./No-sandbox
_`sidePanel` shown to ensure it's MV3_
- https://ephiframe.vercel.app/?sandbox=&srcdoc=%3Ch1%3ESandboxed%20srcdoc&srcdoc=%3Ch1%3EFree%20srcdoc

#7300: Add support for sandboxed iframes (MV3 too)

---

src/background/sidePanel.ts
src/bricks/effects/sidebar.ts
src/contentScript/sidebarController.tsx
src/sidebar/protocol.tsx
src/types/strictMessengerApi.ts
src/types/typeOnlyMessengerRegistration.ts
src/utils/sidePanelUtils.ts

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7476
1. show sidebar
2. wait 2 seconds
3. close sidebar
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/83acfd5b-2bd6-46ce-9a56-07d34750286c
1. show sidepanel
2. wait 2 seconds
3. close sidepanel
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/8645b9c4-8326-4951-bdc7-32ef077c4516

#7476: Open sidebar from iframe

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/specification.md

- Adds a template for specification spikes

Create spec slice template

---

src/bricks/renderers/CustomFormComponent.tsx
src/bricks/renderers/customForm.ts
src/bricks/renderers/document.ts

- Closes #7495 
- validate URLs in schema not code

#9495 Document Builder custom styles Slice 5: Attach stylesheets to the rendered custom form

---

src/bricks/renderers/customForm.ts
src/bricks/renderers/document.ts
src/bricks/transformers/ephemeralForm/formTransformer.ts
src/components/documentBuilder/edit/DocumentOptions.test.tsx
src/pageEditor/fields/FormModalOptions.tsx

#7496 Document Builder custom styles Slice 6: Update FormTransformer (modal form) brick input schema and config UI

---

src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx

#7518: page editor mod metadata layout regression

---

package-lock.json
package.json

- Includes https://github.com/pixiebrix/webext-messenger/pull/206
I think it would be a good idea to hotfix v1.8.8 with this update so that we get more information.
This might be a good one too, just in case there's an iframe in there:
- https://github.com/pixiebrix/pixiebrix-extension/pull/7557

Extend "This target is not in a frame" error

---

src/auth/token.ts
src/background/restrictUnauthenticatedUrlAccess.test.ts
src/background/restrictUnauthenticatedUrlAccess.ts
src/utils/extensionUtils.ts

- Closes #7552 
- https://www.loom.com/share/12cf6c29bc574388b6c6123040ea9c2f

#7552 Redirect existing restricted tabs on token clear

---

.eslintrc.js
src/bricks/renderers/documentView/DocumentView.tsx
src/components/annotationAlert/FieldAnnotationAlert.tsx
src/components/documentBuilder/documentTree.tsx
src/components/documentBuilder/preview/DocumentPreview.tsx
src/components/documentBuilder/render/ListElement.tsx
src/components/ellipsisMenu/EllipsisMenu.stories.tsx
src/components/ellipsisMenu/EllipsisMenu.tsx
src/components/fields/schemaFields/widgets/ArrayWidget.tsx
src/components/form/FieldAnnotation.ts
src/components/form/FieldTemplate.tsx
src/components/formBuilder/FieldTemplate.tsx
src/components/tabLayout/EditorTabLayout.tsx
src/components/walkthroughModal/WalkthroughModalApp.tsx
src/extensionConsole/pages/integrations/PrivateIntegrationsCard.tsx
src/extensionConsole/pages/mods/ModsPageActions.tsx
src/pageEditor/sidebar/ActionMenu.tsx
src/pageEditor/tabs/editTab/AnalysisResult.tsx
src/utils/notify.tsx

- Part of https://github.com/pixiebrix/eslint-config-pixiebrix/issues/194
- Mentioned in https://github.com/pixiebrix/pixiebrix-extension/issues/7019#issuecomment-1932279426

Enable `react/no-array-index-key` rule

---

src/sidebar/sidebarSlice.test.ts
src/sidebar/sidebarSlice.ts
src/sidebar/thunks/removeTemporaryPanel.ts

- Fixes #7542 
https://www.loom.com/share/9d0ce51417c54ba99aab68ecab0db649

#7542: Show mod launcher when mod activation panel closes and no other panels

---

.github/workflows/rainforestqa.yml

- Closes #5796
I thought this would be a quick fix. Feel free to close if unwanted or not enough.

#5796: Run Rainforest QA on `main` after each PR merge

---

.github/workflows/rainforestqa.yml

#7611: add slack notification when rainforest run fails

---

src/pageEditor/slices/editorSlice.ts

- Closes #5551 
- Drops unused code for calculating unavailable mod component count
- I just dropped the return values and any unused code. I didn't look at refactoring the methods more

#5551: Drop unused availability count code

---

src/background/activateBrowserActionIcon.test.ts
src/background/activateBrowserActionIcon.ts
src/background/background.ts
src/background/partnerTheme.ts
src/tsconfig.strictNullChecks.json

- #7612 
https://www.loom.com/share/806d7e935c17407a9023f18f553ee086?sid=d6f7327e-d613-47d7-9867-a53a4e96bd66

#7612: slice 3 image loading and transformation for browser seticon

---

src/__mocks__/@/background/messenger/api.ts
src/__mocks__/@/background/messenger/strict/api.ts
src/auth/token.ts
src/background/deploymentUpdater.test.ts
src/background/messenger/api.ts
src/background/messenger/registration.ts
src/background/messenger/strict/api.ts
src/background/messenger/strict/registration.ts
src/background/partnerIntegrations.test.ts
src/bricks/registry.test.ts
src/components/integrations/AuthWidget.test.tsx
src/extensionConsole/pages/activateMod/IntegrationsBody.test.tsx
src/modDefinitions/modDefinitionHooks.test.ts
src/modDefinitions/modDefinitions.test.tsx
src/pageEditor/starterBricks/adapter.ts
src/pageEditor/starterBricks/base.ts
src/registry/memoryRegistry.ts
src/registry/packageRegistry.ts
src/sidebar/activateMod/ActivateModPanel.test.tsx
src/tsconfig.strictNullChecks.json

- Part of #7613 
- See  `src/background/messenger/strict/*`
- Required for changes in https://github.com/pixiebrix/pixiebrix-extension/pull/7632

#7613: adds required methods to strict messenger methods for toolbar icon work

---

src/registry/memoryRegistry.ts
src/registry/packageRegistry.ts

- Follow-up to: https://github.com/pixiebrix/pixiebrix-extension/pull/7636
- Refine an exported type signature

#7613: refine registry null check

---

src/background/background.ts

- Fixes https://github.com/pixiebrix/pixiebrix-extension/pull/7632#discussion_r1492866424
After that PR it takes like 10 seconds unless the managed storage is set.
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/15888d8d-77f0-4302-99b5-c10a17531c50
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/59552db4-b62f-49f7-832a-526c7ea2ded6

#7632: Fix slow browser action icon

---

src/types/helpers.ts

- Gives more detail to debug [this error](https://app.datadoghq.com/logs/error-tracking/issue/0af3e65a-cff1-11ee-9bdc-da7ad0900002?query=service%3Apixiebrix-browser-extension%20version%3A1.8.9&from_ts=1708437927841&to_ts=1708524327842&live=true) showing up in DataDog

Improve error message for 'Invalid UUID' in DataDog

---

src/contentScript/commandPopover/commandController.test.tsx
src/contentScript/selectionTooltip/tooltipController.test.ts

- Part of #7682 
- Skip flaky tests for skunkworks features to make CI more reliable
- The tests are tagged in the code with TODOs for #7682

#7682: skip flaky tests for skunkworks features to improve CI health

---

src/components/fields/schemaFields/genericOptionsFactory.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.module.scss
src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx

- Fixes [#7662 (comment)](https://togithub.com/pixiebrix/pixiebrix-extension/pull/7662#issuecomment-1954255678) by @grahamlangford

Fix EditorNodeConfigPanel label alignment

---

src/background/contentScript.ts
src/contentScript/contentScript.ts

#7566: Don't load content script in tab-less frames

---

src/vendors/theme/assets/styles/_variables.scss

- Fixes https://pixiebrix.slack.com/archives/C03CA2M4RCM/p1708961525481959

Improve input field contrast in extension console and app

---

src/contentScript/selectionTooltip/SelectionToolbar.tsx
src/contentScript/selectionTooltip/tooltipController.tsx
src/utils/selectionController.ts

#7729: Handle Gmail's deselection on mousedown

---

src/components/fields/schemaFields/widgets/PasswordWidget.module.scss
src/themes/colors.scss
src/vendors/theme/assets/styles/_variables.scss

- Part of #7788 
- Accidentally left out of #7815

#7788: adds password styling change missed in previous pr

---

src/bricks/effects/InsertAtCursorEffect.ts
src/contentScript/sidebarController.tsx
src/contentScript/textEditorDom.ts
src/utils/focusController.ts

- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7827
The file is included in the background page and the immediate instantiation uses `window`.

#7827: Restore MV3 support

---

src/utils/focusController.ts

- Links to note https://github.com/pixiebrix/pixiebrix-extension/issues/7774#issuecomment-1980041738 in the code

Add focus controller developer note in comment

---

src/modDefinitions/modDefinitions.test.tsx
src/pageEditor/hooks/useBuildAndValidateMod.ts
src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts
src/pageEditor/hooks/useCompareModComponentCounts.test.ts
src/pageEditor/hooks/useCompareModComponentCounts.ts
src/pageEditor/hooks/useCreateModFromMod.test.ts
src/pageEditor/hooks/useCreateModFromModComponent.test.ts
src/pageEditor/hooks/useCreateModFromModComponent.ts
src/pageEditor/hooks/useSaveMod.test.ts
src/pageEditor/panes/save/saveHelpers.ts
src/pageEditor/sidebar/modals/CreateModModal.tsx
src/pageEditor/slices/editorSlice.ts

#7821 - Fix issue preventing save-as-new-mod with sidebar component

---

src/bricks/transformers/ephemeralForm/formTransformer.test.ts
src/utils/focusController.ts

- Fixes #7848
- Fixes lint merge conflict
- https://www.loom.com/share/452d75763c794dd2874243524672f907?sid=c42330f4-755d-4627-aef6-166527cf0f83
- 😞 : Add tests: will need E2E testing/manual regression testing due to focus

#7848: never focus body in focus controller

---

src/contentScript/textEditorDom.ts
src/utils/domFieldUtils.ts

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7814
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/67a2db37-1896-488a-a1a1-52d02427de38

#7814: Fix DraftJS support on empty fields (Insert Text brick)

---

src/development/visualInjection.ts

Small change. I think the "remove on hide" makes it difficult to inspect and understand. This instead makes it self-documenting.

Make `visualInjection` pixel clickable

---

src/__snapshots__/Storyshots.test.js.snap
src/background/installer.ts
src/contrib/automationanywhere/aaFrameProtocol.ts
src/extensionConsole/pages/onboarding/SetupPage.test.tsx
src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
src/extensionConsole/pages/onboarding/partner/ControlRoomTokenForm.tsx
src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx
src/sidebar/LoginPanel.tsx

- Closes #7888 
- pixiebrix-extension changes for Automation Co-Pilot branding
- See [Google Doc](https://docs.google.com/document/d/1UllMHDYBsIkUxvIYZOyubbu8bAWRhMHF_2g3MCDsdc4/edit#heading=h.qdnty582py2i) for requirements
- pixiebrix-app PR to update the branding in the Admin Console

#7888: AA Automation Co-Pilot branding

---

src/background/starterMods.ts
src/data/service/api.ts

- Part of https://github.com/pixiebrix/pixiebrix-app/issues/3629

Remove retired ignore_user_state request param

---

end-to-end-tests/utils.ts

Improves the utility for checking a11y violations. It won't fail now if there are any allowed violations that are no longer present and improves logging if it fails, and notes when an allowed violation can be removed.

improve a11y violations checker util

---

src/contrib/ckeditor/ckeditorProtocol.ts
src/sidebar/sidebar.tsx
src/telemetry/performance.ts

_Just extracting some minor fixes I wrote while working on the assigned bugs._

Fix forbidContext/expectContext usage

---

scripts/__snapshots__/manifest.test.js.snap
src/bricks/readers/ElementReader.test.ts
src/manifest.json
src/testUtils/testEnv.js
src/utils/domUtils.ts

_Just extracting some minor fixes I wrote while working on the assigned bugs._

Fix `isVisible` usage

---

src/bricks/effects/forms.test.ts
src/bricks/transformers/convertDocument.ts
src/data/model/ControlRoom.ts
src/data/model/Me.ts
src/data/model/MeOrganization.ts
src/data/model/MeOrganizationMembership.ts
src/data/model/MeUserGroupMembership.ts
src/data/model/OrganizationTheme.ts
src/data/model/PartnerPrincipal.ts
src/data/model/UserMilestone.ts
src/data/model/UserOrganizationMembershipRole.ts
src/data/model/UserPartner.ts
src/extensionConsole/components/IDBErrorDisplay.stories.tsx
src/starterBricks/triggerEventReaders.ts

_Just extracting some minor fixes I wrote while working on the assigned bugs._
Some 2023 notices are still being added to the codebase. You might want to check your editor config.
Also I dropped a couple of duplicate copyright notices.

Fix copyright notices

---

src/contentScript/commandPopover/CommandPopover.tsx
src/contentScript/commandPopover/commandPopoverSlice.test.ts
src/contentScript/commandPopover/commandPopoverSlice.ts
src/tsconfig.strictNullChecks.json

- Closes #7893 
- Make snippet search case insensitive

#7893: make snippet search case insensitive

---

src/components/formBuilder/edit/FieldEditor.tsx
src/components/formBuilder/edit/FormEditor.test.tsx
src/pageEditor/testHelpers.ts

- Closes #7850
https://www.loom.com/share/87f9effe526840fbb470f7610f6a1d3d

#7850: adds # rows field for textarea in form builder

---

src/contentScript/commandPopover/CommandPopover.scss

- Fixes bug seen in https://pixiebrix.slack.com/archives/C023KL47XV4/p1710592528435789?thread_ts=1710519930.124569&cid=C023KL47XV4
- Like https://github.com/pixiebrix/pixiebrix-extension/pull/7699
- Related https://github.com/pixiebrix/pixiebrix-extension/issues/7670

CommandPopover: Fix scrollbar style on some websites

---

src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
src/components/quickBar/QuickBarApp.tsx
src/hooks/useEventListener.test.ts
src/hooks/useEventListener.ts
src/hooks/useKeyboardShortcut.ts
src/pageEditor/hooks/useEscapeHandler.ts
src/sidebar/ConnectedSidebar.tsx
src/tsconfig.strictNullChecks.json

I didn't see this hook and wrote my own implementation for https://github.com/pixiebrix/pixiebrix-extension/pull/7974 (later unused)
Since I also added tests I thought I'd also just open a PR and use the hook in a few places

Refactor, test and use `useEventListener`

---

.github/workflows/ci.yml
knip.mjs
package.json
src/testUtils/renderWithCommonStore.ts
src/vendors/page-metadata-parser/parser.js

- Required for https://github.com/pixiebrix/pixiebrix-extension/pull/7941

Bump knip to v5

---

src/sidebar/Tabs.module.scss

- Fixes #7978 
- This will almost certainly require some Rainforest screenshots to be updated

#7978: fix vertical alignment of close buttons

---

src/contentScript/commandPopover/commandController.tsx

- This fixes a very small visual bug when animating the command popover (now called the snippet shortcut menu)
https://www.loom.com/share/4dca326c19a0431b9467c9afe7b00020

fix command popover animation flash

---

package-lock.json
package.json
src/pageEditor/toolbar/ReloadToolbar.tsx

- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7983
- Likely fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7847
- Maybe also https://github.com/pixiebrix/pixiebrix-extension/issues/7753
More context in:
- https://github.com/pixiebrix/webext-messenger/pull/224
- https://github.com/pixiebrix/webext-messenger/issues/219#issuecomment-2011000477
1. Sent from a tab
2. Forwarded in the background
3. Ignored by another runtime page
4. Received once by the other tab
You can compare it to the screenshot in https://github.com/pixiebrix/webext-messenger/issues/219#issuecomment-2011000477

#7983: Fix duplicate message forwarding

---

src/background/auth/launchOAuth2Flow.test.ts
src/background/auth/launchOAuth2Flow.ts

- Fixes #8004 
https://www.loom.com/share/630731f01fa5487dafecc1073b6ceef2

#8004: memoizes launchOAuth2Flow to prevent banners on login pages

---

src/contentScript/selectionTooltip/tooltipController.tsx

- Fixes #7994
I'm not sure of the exact context of why this approach wasn't taken in the context of #7729 so @fregante and @twschiller are free to chime in if I overlooked something.
https://www.loom.com/share/b9901e58bc7f4b15b507c79576b5eb3d

#7994: Hide selection menu when clicking outside

---

src/utils/textAreaUtils.ts

- Fixes #7993
We should probably prioritize adding some visual regression testing for this method, or extracting some of the methods out into helper functions that can be unit tested individually.
https://www.loom.com/share/5837c43adaad4bb08c10e5816e5edce7
I also quickly double checked that the variable popover in the page editor still worked as expected since
there are currently no unit tests around the `getCaretCoordinates` method.

#7993: fix text selection menu obscured within input

---

scripts/__snapshots__/manifest.test.js.snap
src/manifest.json

#8019: update `frame-src` to allow `http:`

---

src/activation/useActivateModWizard.ts
src/activation/useActivateRecipe.ts
src/background/deploymentUpdater.ts
src/background/modUpdater.ts
src/extensionConsole/pages/activateMod/ActivateModCard.tsx
src/extensionConsole/pages/activateMod/ActivateModPage.tsx
src/extensionConsole/pages/brickEditor/EditPage.tsx
src/extensionConsole/pages/deployments/DeploymentsContext.tsx
src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModalBody.tsx
src/extensionConsole/pages/mods/utils/useReinstall.ts
src/extensionConsole/pages/settings/useDiagnostics.ts
src/mods/useModViewItems.tsx
src/mods/useMods.ts
src/pageEditor/analysisManager.ts
src/pageEditor/hooks/useDeactivateMod.tsx
src/pageEditor/hooks/useResetExtension.ts
src/pageEditor/hooks/useUpsertModComponentFormState.test.ts
src/pageEditor/panes/save/SaveDataIntegrityErrorModal.tsx
src/pageEditor/panes/save/useSavingWizard.ts
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
src/sidebar/activateMod/ActivateModInputs.tsx
src/sidebar/activateMod/ActivateMultipleModsPanel.tsx
src/sidebar/activateMod/RequireMods.tsx
src/sidebar/sidebarSelectors.ts
src/store/extensionsSelectors.ts
src/utils/modUtils.ts

rename selectors in extensionsSelectors

---

src/activation/useActivateRecipe.test.ts
src/activation/useActivateRecipe.ts
src/background/deploymentUpdater.ts
src/background/messenger/registration.ts
src/background/modUpdater.test.ts
src/background/modUpdater.ts
src/background/starterMods.test.ts
src/background/starterMods.ts
src/extensionConsole/pages/activateExtension/ActivateExtensionCard.tsx
src/extensionConsole/pages/deployments/activateDeployments.ts
src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModal.test.tsx
src/extensionConsole/pages/mods/utils/useReinstall.test.ts
src/extensionConsole/pages/mods/utils/useReinstall.ts
src/modDefinitions/modDefinitions.test.tsx
src/pageEditor/hooks/useBuildAndValidateMod.test.ts
src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
src/pageEditor/hooks/useCompareModComponentCounts.test.ts
src/pageEditor/hooks/useCreateModFromMod.test.ts
src/pageEditor/hooks/useCreateModFromMod.ts
src/pageEditor/hooks/useSaveMod.test.ts
src/pageEditor/panes/save/saveHelpers.test.ts
src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.test.tsx
src/store/checkAvailableInstalledExtensions.test.ts
src/store/extensionsSlice.ts
src/store/sessionChanges/sessionChangesListenerMiddleware.ts

- Part of #8076 
- Changes are in `extensionsSlice` and `src/background/starterMods.ts`. Everything else is just updating imports.

Rename install starter mods to activate

---

.env.example

- We changed the static test user used in e2e tests. This updates the env.example with the correct email

Update env.example with new test user email

---

end-to-end-tests/README.md
end-to-end-tests/fixtures/extensionBase.ts
end-to-end-tests/pageObjects/modsPage.ts
end-to-end-tests/tests/modsPageSmoke.spec.ts
end-to-end-tests/tests/sidebarSmoke.spec.ts
end-to-end-tests/utils.ts

- Adds a troubleshooting section, with an initial entry on visibility errors

add troubleshooting section to e2e tests readme

---

src/extensionConsole/pages/activateExtension/ServicesRow.tsx

- Fixes a broken styles reference
- Fixes the field name string value `"config"` --> `"configId"` set on `AuthWidget`
- Closes #8057

Fix bugs in `ActivateExtensionCard`

---

end-to-end-tests/pageObjects/pageEditorPage.ts
end-to-end-tests/tests/pageEditorSmoke.spec.ts

- Closes #7961
See my demo of me writing this test!
https://www.loom.com/share/4a8ece97e28c43b9a65e95a6c3d1f694

#7961 pageEditor e2e smoke test

---

src/pageEditor/sidebar/ExtensionIcons.tsx
src/pageEditor/sidebar/__snapshots__/DynamicModComponentListItem.test.tsx.snap

- Closes #8086
Visual screenshot testing with playwright would be a nice follow up

#8086: fixed width icons in page editor mod sidebar

---

src/extensionConsole/pages/mods/ModsPageLayout.module.scss
src/extensionConsole/pages/mods/ModsPageLayout.tsx
src/extensionConsole/pages/mods/ModsPageSidebar.tsx
src/extensionConsole/pages/mods/__snapshots__/ModsPageLayout.test.tsx.snap

- Part of #4914
Fixes one small thing that has bugged me for the longest time.

#4914: Fix extension console sidebar wrapping

---

src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx

- Follow-up of #8164
- Adds a test for this bugfix

#8164 Follow-up: add deployment tests

---

.github/workflows/ci.yml

#8232 Fix CodeCov CI uploader

---

src/contrib/automationanywhere/BotOptions.tsx

- Fixes a bad character that snuck in here... 🤦

Fix a typo in the BotOptions page editor component

---

src/extensionConsole/pages/mods/ModsPageLayout.tsx

- Closes #8285 
- Sorts "Shared with Me" team filter names

#8285: sort team filter names

---

src/background/starterMods.test.ts
src/background/starterMods.ts

#8210: support PixieBrix API in starter mod

---

end-to-end-tests/pageObjects/extensionConsole/localIntegrationsPage.ts
src/components/brickModalNoTags/BrickDetail.tsx

- Fixes the flakiness as observed in https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8758098517/attempts/1?pr=8295
- There's a small layout shift in the modal sometimes, which causes the scrollbar to move, and the previous Configure button in the item row was disappearing.

improve flakiness in local integrations e2e test

---

src/auth/authTypes.ts
src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx
src/contentScript/pageEditor.ts
src/contrib/automationanywhere/ApiTaskOptions.tsx
src/contrib/automationanywhere/BotOptions.tsx
src/contrib/uipath/LocalProcessOptions.tsx
src/contrib/uipath/ProcessOptions.tsx
src/contrib/uipath/uipathHooks.ts
src/integrations/components/RequireIntegrationConfig.tsx
src/integrations/useSanitizedIntegrationConfigFormikAdapter.test.ts
src/integrations/useSanitizedIntegrationConfigFormikAdapter.ts
src/utils/variableUtils.ts

- Closes #8137 
- Enables full handling in the page editor for multiple integration dependencies with the same integrationId

#8137 aa bricks two integrations bug

---

src/components/IsolatedComponent.tsx

- Fixes auto-save not working in forms rendered by the IsolatedComponent
https://www.loom.com/share/7f9f301915084e1abdf373b07f46c23f
- Update the Playwright tests

fix over-memoization in the IsolatedComponent

---

src/__snapshots__/Storyshots.test.js.snap
src/analysis/analysisVisitors/extensionUrlPatternAnalysis.ts
src/integrations/UserDefinedIntegration.ts
src/pageEditor/fields/UrlMatchPatternField.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/tabs/contextMenu/ContextMenuConfiguration.tsx
src/pageEditor/tabs/quickBar/QuickBarConfiguration.tsx
src/pageEditor/tabs/quickBarProvider/QuickBarProviderConfiguration.tsx
src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
src/permissions/patterns.ts

#8313: update match patterns doc links to use the mv3 link

---

.github/workflows/ci.yml

Adds retries to the install step to try to avoid the e2e tests failing due to failed checksums.

msedge ci flakiness

---

end-to-end-tests/tests/regressions/formFlicker.spec.ts

Validate that form autosaving works as correctly

---

package-lock.json
package.json
src/components/errors/NetworkErrorDetail.tsx
src/contrib/google/sheets/core/handleGoogleRequestRejection.ts
src/data/service/errorService.ts
src/errors/errorHelpers.ts
src/utils/urlUtils.ts

- Fixes axios security alert
- Most of the pain upgrading from 0.27.2 was eliminated by a fix in 0.28.1

Axios upgrade

---

package-lock.json
package.json
src/background/browserAction.ts
src/bricks/transformers/tourStep/tourStep.ts
src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
src/components/quickBar/QuickBarResults.tsx
src/extensionConsole/pages/deployments/useDeactivateUnassignedDeploymentsEffect.ts
src/extensionConsole/pages/integrations/ConnectExtensionCard.tsx
src/hooks/useBrickOptions.ts
src/pageEditor/fields/TemplateWidget.tsx
src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
src/pageEditor/hooks/useCreateModFromMod.ts
src/pageEditor/hooks/useCreateModFromModComponent.ts
src/pageEditor/protocol.ts
src/utils/textAreaUtils.ts

- installs latest `eslint-config-pixiebrix`
- fixes lint errors

update eslint-config-pixiebrix and resolve lint errors

---

end-to-end-tests/tests/extensionConsoleActivation.spec.ts

adds test to activate mod with database and run it

---

src/tinyPages/offscreen.ts

- Closes #8397 
https://www.loom.com/share/6188dfe9c099410282536b56e9818dd1

#8397: Fix App crashing when chrome runtime is undefined

---

src/background/messenger/external/_implementation.ts

- Removes deprecated code used for legacy Extension support by App
- See https://github.com/pixiebrix/pixiebrix-app/pull/5229
- Found and removed while debugging https://github.com/pixiebrix/pixiebrix-app/pull/5248

Removes unused external code

---

src/integrations/util/getUnconfiguredComponentIntegrations.test.ts
src/integrations/util/getUnconfiguredComponentIntegrations.ts

#8459 Fix activation and deployments for mods that have more than one integration config for the same integration

---

src/sidebar/SidebarBody.tsx
src/tinyPages/RestrictedUrlPopupApp.tsx
src/tinyPages/restrictedUrlPopup.tsx

#8489: add url to BrowserActionRestrictedUrl event

---

src/sidebar/activateMod/ActivateModPanel.module.scss

- Fixes https://pixiebrix.slack.com/archives/C073CFWD98T/p1716319149676279

Reduce padding of footer buttons in Mod Activation Panel

---

scripts/manifest.mjs

- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/8491
- Missed a change in the shape for web_accessible_resources

fix web_accessible_resources path

---

end-to-end-tests/tests/runtime/allFrames.spec.ts
src/bricks/available.test.ts
src/bricks/available.ts
src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
src/pageEditor/starterBricks/base.test.ts
src/pageEditor/starterBricks/base.ts
src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
src/types/availabilityTypes.ts

- Stacked on https://github.com/pixiebrix/pixiebrix-extension/pull/8533
- Closes #8327 
- Stacked on https://github.com/pixiebrix/pixiebrix-extension/pull/8533
- `@pixies/test/8527-all-frames`

#8327: toggle for running mod only in the top-level frame

---

src/background/auth/authHelpers.test.ts
src/background/auth/authHelpers.ts
src/contentScript/integrations/LoginBanners.tsx

- Fixes #8247
https://www.loom.com/share/1ffe1b795faa48d5928d3b653f804b07

#8247: login banner button doesnt show error on failure to show web auth flow

---

package-lock.json
package.json

- Fixes #8645
- Figure out why this upgrade causes these issues. 
- Write an e2e playwright test to catch this issue. https://github.com/pixiebrix/pixiebrix-extension/issues/8647

#8645 downgrading webpack to 5.91.0

---

src/contentScript/executor.ts
src/contentScript/messenger/api.ts
src/contentScript/messenger/registration.ts
src/pageEditor/tabs/effect/BrickPreview.tsx

- Refactoring to clarify run brick action naming in content script API

Clarify run brick action name in content script API

---

src/contentScript/lifecycle.ts
src/pageEditor/EditorContent.tsx
src/pageEditor/sidebar/DraftModComponentListItem.tsx

#8615: change remaining instances of dynamic -> draft

---

end-to-end-tests/tests/runtime/sidebarNavigation.spec.ts

Fixes e2e tests which currently are failing after this app change was merged:
https://github.com/pixiebrix/pixiebrix-app/commit/b3ab1ce2b05ff8338e7ba9bc442298e69e65518d
Ideally we would run the extension e2e tests alongside any back-end changes as well.

fix e2e test

---

src/background/messenger/external/_implementation.ts
src/contentScript/sidebarActivation.ts

#8687: fixes potential NPE in sidebarActivation

---

src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
src/pageEditor/slices/editorSelectors.ts
src/pageEditor/slices/editorSliceHelpers.ts
src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap

- Closes #8686
- Spent some time tracing upstream from 3 different potential causes of the NPE
- Without more information, it's hard to determine which path to focus on
- Added additional type assertions to help determine the root cause if this NPE occurs again

#8686: add additional type assertions to improve messaging if NPE reoccurs

---

src/telemetry/logging.ts
src/telemetry/reportError.test.ts
src/telemetry/reportError.ts
src/tsconfig.strictNullChecks.json
src/types/loggerTypes.ts

Closes #8688 
This PR enhances the telemetry logging capabilities of the Pixiebrix extension by adding three new fields to the logging context: `url`, `connectionType`, and `referrer`. These fields are captured in the `reportError` function and added to the `MessageContext` type.
Manually verified the output in the offscreen payload:
```
{
"service": "pixiebrix-browser-extension",
"session_id": "9cbcdeaa-ecc4-4e6f-a76d-0add0a673b73",
"usr": {
"id": "1701b77a-5ccc-4255-b768-55ee07ceca5e",
"email": "eduardo+test@pixiebrix.com",
"organizationId": "7939ffb1-1ac6-49cd-954e-0e3b25d93a95"
},
"view": {
"referrer": "",
"url": "chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/offscreen.html"
},
"code_version": "014fa5d59",
"date": 1719254853748,
"message": "Sidebar should not be loaded in an …
```

#8688 additional props for error reporting

---

src/background/auth/codeGrantFlow.ts
src/background/performConfiguredRequest.test.ts

- Fixes #8713 
~- [ ] Added jest or playwright tests and/or storybook stories~ See: https://github.com/pixiebrix/pixiebrix-extension/issues/8715

#8713 Fix bug with OAuth2 login request params

---

src/bricks/renderers/documentView/DocumentView.tsx
src/pageEditor/documentBuilder/documentBuilderTypes.ts
src/pageEditor/documentBuilder/documentTree.test.tsx
src/pageEditor/documentBuilder/documentTree.tsx
src/pageEditor/documentBuilder/render/ListElement.tsx
src/pageEditor/exampleStarterBrickConfigs.ts

#8703: documentBuilderBranch -> documentBuilderSubtree

---

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts

Adds some additional timeouts in some places that seem to sometimes fail.

Improve e2e test flakiness

---

end-to-end-tests/pageObjects/pageEditor/createModModal.ts
src/pageEditor/modListingPanel/modals/CreateModModal.tsx

#8738 Package standalone mods on save - Slice 2

---

src/extensionConsole/pages/BrowserBanner.test.tsx
src/extensionConsole/pages/BrowserBanner.tsx
src/extensionConsole/pages/__snapshots__/BrowserBanner.test.tsx.snap
src/utils/browserUtils.ts

#8801: fix browser warning on MS Edge

---

end-to-end-tests/tests/runtime/textSnippets.spec.ts
end-to-end-tests/utils.ts
src/contentScript/snippetShortcutMenu/snippetShortcutMenuController.tsx
src/contentScript/textSelectionMenu/selectionMenuController.tsx
src/domConstants.ts

Closes #8059
Worked on this now due to a recent bug that caused snippet shortcuts to stop working entirely that was not caught.
A fairly simple interaction was tested - just verifying clicking on the snippet shortcut items work as expected. Using keyboard controls to navigate the options seems to be flaky.

#8059 snippet shortcut e2e test

---

src/contrib/google/sheets/core/useGoogleAccount.ts
src/contrib/google/sheets/ui/RequireGoogleSheet.tsx

- Fixes #8751 
https://www.loom.com/share/415b893d9ef44ce1b314e1e6675c7581

#8751: automatically refresh spreadsheet list when activating a mod and configuring a new google auth config

---

end-to-end-tests/tests/pageEditor/brickActions.spec.ts
end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copied-to-another-mod.diff

8596: add test for copying a brick from one mod to another

---

src/contrib/google/sheets/core/useGoogleAccount.ts

- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/8803/files/122e7a1cff02bd51151d47ba6572c1e2f895f7db..8962a07991b435349e97f80c254cefeeca104a5b#r1674693657

#8751: move loginController inside the useEffect

---

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts

handling flaky loading of the mods page

---

contrib/integrations/automation-anywhere.yaml
src/integrations/UserDefinedIntegration.test.ts

- Part of https://github.com/pixiebrix/pixiebrix-app/issues/5497

Update automation-anywhere/control-room integration definition

---

src/pageEditor/layout/ModComponentFormStateWizard.tsx
src/pageEditor/panes/EditorPane.tsx
src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap

Fixes a style regression in the page editor due to an extra div

fix style regression

---

contrib/integrations/automation-anywhere.yaml

- Part of https://github.com/pixiebrix/pixiebrix-app/issues/5500

Update AA control room integration definition

---

src/bricks/effects/comment.ts

- Remove `[Experimental]` from comment brick name
- Listing icon has also been updated: https://app.pixiebrix.com/admin/marketplace/listing/c4950a5c-6198-4078-9316-01fceb2db98e/change/

Remove `[Experimental]` from comment brick name

---

src/extensionConsole/pages/settings/ExperimentalSettings.tsx
src/store/settings/settingsTypes.ts

- Skunkworks -> Experimental Settings

Use consistent terminology for experimental settings

---

end-to-end-tests/tests/runtime/allFrames.spec.ts
end-to-end-tests/tests/runtime/insertAtCursor.spec.ts
end-to-end-tests/tests/runtime/srcdocFrames.spec.ts

Skip failing tests due to chromium bug. See discussions in the following channels for context:
https://pixiebrix.slack.com/archives/C07DQ2J7C78
https://pixiebrix.slack.com/archives/C07DGPVQJKH

Disable failing tests caused by Chromium 127 bug

---

end-to-end-tests/tests/runtime/allFrames.spec.ts
end-to-end-tests/tests/runtime/srcdocFrames.spec.ts
src/contentScript/contentScriptCore.ts

#8921 Fix content script injection on sandboxed srcdoc iframes

---

src/pageEditor/starterBricks/trigger.ts
src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
src/starterBricks/trigger/triggerStarterBrick.test.ts
src/starterBricks/trigger/triggerStarterBrick.ts
src/starterBricks/trigger/triggerStarterBrickTypes.ts

- Define report mode constants

Define report mode constants

---

src/data/service/errorService.ts

- Follow-up to #8934 
- Adds a feature flag check that will disable reporting to the PixieBrix error telemetry service

Add a feature flag check to disable reporting errors to the PixieBrix error service

---

src/bricks/effects/sidebarEffects.ts
src/contentScript/sidebarController.tsx
src/sidebar/protocol.tsx
src/store/sidebar/sidebarSlice.ts
src/store/sidebar/sidebarUtils.ts

- Closes #8976 
https://www.loom.com/share/4a4cf4cfbb7a440e981e443c313b051a

#8976: show sidebar brick not showing active tab

---

end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
end-to-end-tests/tests/runtime/sidebar/sidebarActivation.spec.ts

- This fixes some of the flakiness we have been observing in e2e tests which stem from the www.pixiebrix.com website experiencing significant performance issues.
- See follow-up on fixing this performance issue in slack: https://pixiebrix.slack.com/archives/C01HKC37E6L/p1723472807167539

improve end-to-end test flakiness

---

src/pageEditor/hooks/useBuildAndValidateMod.test.ts
src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
src/pageEditor/hooks/useSaveMod.test.ts
src/pageEditor/modListingPanel/ModListItem.test.tsx
src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
src/pageEditor/starterBricks/base.test.ts
src/pageEditor/starterBricks/pipelineMapping.test.ts
src/pageEditor/store/editor/editorSlice.test.ts
src/pageEditor/store/editor/editorSliceHelpers.test.ts
src/pageEditor/tabs/editTab/dataPanel/BrickDataPanel.test.tsx
src/pageEditor/tabs/editTab/dataPanel/StarterBrickDataPanel.test.tsx
src/pageEditor/tabs/editTab/dataPanel/tabs/CommentsTab.test.tsx
src/pageEditor/tabs/editTab/editHelpers.test.ts
src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.test.tsx
src/pageEditor/tabs/effect/BrickConfiguration.test.tsx
src/pageEditor/tabs/trigger/TriggerConfiguration.test.tsx
src/registry/packageRegistry.test.ts
src/runtime/pipelineTests/validateInput.test.ts
src/sidebar/Tabs.test.tsx
src/sidebar/activateMod/ActivateModPanel.test.tsx
src/starterBricks/starterBrickModUtils.test.ts
src/store/checkAvailableActivatedModComponents.test.ts
src/store/editorStorage.test.ts
src/store/sidebar/sidebarSlice.test.ts
src/tsconfig.strictNullChecks.json

- Raises coverage to 95.7%
- 85 files remaining 
- Accidentally pushed to main by mistake first
- Reverted the changes to main
- Created this branch, re-reverted to get the changes in

Strict null checks: 95.7%

---

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
end-to-end-tests/tests/extensionConsole/activation.spec.ts
end-to-end-tests/tests/smoke/sidebar.spec.ts
src/activation/useActivateModWizard.ts
src/integrations/components/IntegrationAuthSelector.tsx

- Fixes issue with the integration dependencies not being properly validated when activating a mod in the Extension Console

fix integration dependency validation in the extension console

---

src/store/migratePersistedState.test.ts
src/store/migratePersistedState.ts

- Fixes some issues with the redux-persist migrations

Bug - Fix redux persist migrations for sidebar state, related to welcome mod activation

---

src/utils/expressionUtils.ts

- Fixes issue repinning Extension
- Once strict null checks is implemented, this will no longer be necessary
- Necessary because we include the messenger typings in the App project

Fix typing issue in App

---

src/components/IsolatedComponent.tsx
webpack.config.mjs

- Fixes #8965 
- https://www.loom.com/share/068ba34341d9451ca2ff192892ab2ea1

#8965: Fix sidebar activation body is sometimes missing

---

.github/workflows/e2e-test-pre-release-browsers.yml
.secrets.baseline

#9009: add pre-release test failure slack notification

---

src/bricks/effects/TelemetryEffect.ts
src/bricks/effects/getAllEffects.ts
src/extensionConsole/store.ts

#9068: include deployment id with customuserevent

---

.github/workflows/ci.yml

#9065: allow dependabot to write the playwright report comment to the PR

---

src/auth/RequireAuth.tsx
src/auth/useRequiredPartnerAuth.test.tsx
src/auth/useRequiredPartnerAuth.ts
src/extensionConsole/pages/onboarding/SetupPage.test.tsx

- Fixes #9089
See slack: https://pixiebrix.slack.com/archives/C07JERJHK4M/p1725557072609449?thread_ts=1725549567.695749&cid=C07JERJHK4M

#9089: deployment key does't take effect if team has an associated aa control room

---

src/__snapshots__/Storyshots.test.js.snap
src/components/ellipsisMenu/EllipsisMenu.test.tsx
src/components/ellipsisMenu/EllipsisMenu.tsx
src/pageEditor/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap

- Fixes a bug where clicks on the menu items propagated up to the parent element

Bug - Fix click propagation on ellipsis menus

---

schemas/recipe.json

- #9133 
- Add variables section to mod definition json schema
- Corresponding app PR: https://github.com/pixiebrix/pixiebrix-app/pull/5746/

#9133: add variables section to mod definition JSON schema

---

src/extensionConsole/App.tsx
src/extensionConsole/pages/TeamTrialBanner.test.tsx
src/extensionConsole/pages/TeamTrialBanner.tsx
src/extensionConsole/pages/useTeamTrialStatus.ts
src/testUtils/factories/organizationFactories.ts

- Closes #9129 
https://www.loom.com/share/6e636376a48a41e08525c2e495230c2f

#9129: slice 1 display banner for in progress and expired team trials

---

.github/workflows/e2e-test-pre-release-browsers.yml

- Fixes failing workflow here: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/10824451789/workflow

fix slack notification

---

src/__snapshots__/Storyshots.test.js.snap
src/components/ellipsisMenu/EllipsisMenu.tsx
src/pageEditor/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap

- Closes #9171
https://www.loom.com/share/dfdfa0767afb4b91a5444b9ad08d2ec1

#9171: Fix EllipsisMenu wrapping to next line

---

src/extensionConsole/pages/mods/ModsPageSidebar.tsx

- Fixes #9173
- I would love to add tests for this, but I do not see an easy way to write tests for this, so I don't think it's worth the effort
https://pixiebrix.slack.com/archives/C0436P48QHY/p1726758182247319?thread_ts=1726676968.486329&cid=C0436P48QHY

#9173: fix shared mods filtering

---

end-to-end-tests/tests/regressions/sidebarLinks.spec.ts
end-to-end-tests/tests/telemetry/errors.spec.ts
src/__mocks__/@/telemetry/reportError.ts
src/telemetry/logging.test.ts
src/telemetry/logging.ts
src/telemetry/reportError.ts
src/telemetry/trace.ts

- Part of #9169
- We should use this error wrapping in the other idb calls for other databases as well.
- [ x] Added jest or playwright tests and/or storybook stories

9169 Add idb log error handling

---

package-lock.json

- Part of https://github.com/pixiebrix/pixiebrix-extension/security/dependabot/86

updates package-lock.json to protech against vuln dependency

---

src/registry/packageRegistry.ts
src/utils/idbUtils.test.ts
src/utils/idbUtils.ts

- Fixes https://pixiebrix.slack.com/archives/C07MJ3LJ66B/p1728053485577609
- Added unit tests for idb utils
- Verified functionality by manually triggering the idb error by deleting log blob entries to force the large value error
- 

fix idb error retry behavior

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/research_spike.md
.github/ISSUE_TEMPLATE/specification.md

- Adds a new "Research Spike" issue template

Add template for research spikes

---

src/contentScript/pageEditor/draft/runStarterBrickReaderPreview.ts
src/contentScript/pageEditor/draft/updateDraftModComponent.ts
src/contentScript/pageEditor/types.ts
src/contentScript/sidebarController.tsx
src/pageEditor/editorPermissionsHelpers.ts
src/pageEditor/layout/EditorContent.tsx
src/pageEditor/panes/EditorPane.test.tsx
src/pageEditor/panes/ModComponentEditorPane.tsx
src/pageEditor/starterBricks/button.ts
src/pageEditor/starterBricks/contextMenu.ts
src/pageEditor/starterBricks/dynamicQuickBar.ts
src/pageEditor/starterBricks/quickBar.ts
src/pageEditor/starterBricks/sidebar.ts
src/pageEditor/starterBricks/trigger.ts
src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx
src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
src/pageEditor/toolbar/ReloadToolbar.tsx

- Refactoring pre-work for injecting draft mod instances: https://github.com/pixiebrix/pixiebrix-extension/pull/9298

DraftModComponent type refactoring

---

.eslintrc.js
end-to-end-tests/tests/pageEditor/brickConfiguration.spec.ts
package-lock.json
package.json
src/background/requests.ts
src/bricks/effects/AddDynamicTextSnippet.test.ts
src/bricks/effects/AddTextSnippets.test.ts
src/bricks/effects/replaceText.test.ts
src/bricks/transformers/brickFactory.ts
src/bricks/transformers/regex.test.ts
src/components/errors/getErrorDetails.test.tsx
src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
src/components/logViewer/LogCard.test.tsx
src/contentScript/ready.ts
src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.test.tsx
src/contentScript/snippetShortcutMenu/snippetShortcutUtils.test.ts
src/contentScript/stateController/modVariablePolicyController.ts
src/contrib/automationanywhere/RunApiTask.ts
src/contrib/automationanywhere/RunBot.ts
src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
src/platform/state/stateTypes.ts
src/runtime/pipelineTests/pipelineTestHelpers.ts
src/store/sidebar/sidebarSlice.test.ts
src/store/sidebar/sidebarSlice.ts
src/testUtils/testEnv.js
src/utils/inference/selectorInference.test.ts
src/utils/stringUtils.ts

- Updates eslint-config-pixiebrix
- Part of preparation for upgrading to ESLint v9

Update eslint config pixiebrix

---

end-to-end-tests/tests/smoke/modsPage.spec.ts
package-lock.json

- Fixes an issue with @axe-core/playwright in the package-lock which for some reason got deleted in 
https://github.com/pixiebrix/pixiebrix-extension/pull/9301/files
How did this get merged in and pass e2e tests?

fix axe-core in package-lock

---

src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.test.ts
src/runtime/pathHelpers.ts

- Fix selection of variable with trailing number in the variable popover

Fix selection of variable with trailing number

---

src/pageEditor/store/editor/editorSelectors/editorModComponentSelectors.ts
src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
src/pageEditor/store/editor/editorSlice.test.ts
src/pageEditor/store/editor/editorSlice.ts
src/pageEditor/store/editor/editorSliceHelpers.ts

- Fixes https://pixiebrix.slack.com/archives/C0436P48QHY/p1730395007799569
https://www.loom.com/share/5cf1f2243e7a412ba8d584fa823594db

Fixes resetting dirty form states outside the mod that was saved

---

src/components/richTextEditor/RichTextEditor.module.scss
src/components/richTextEditor/RichTextEditor.test.tsx
src/components/richTextEditor/toolbar/HeadingLevelDropdown.tsx
src/components/richTextEditor/toolbar/Toolbar.tsx

#9338 Add Heading Level Dropdown to Rich Text Editor

---

package-lock.json
package.json

- React-redux added type definitions in v8

Remove @types/react-redux

---

applications/browser-extension/package.json
package-lock.json

- FLUP to closing https://github.com/pixiebrix/pixiebrix-extension/pull/9486

Drop unused `prop-types` package

---

.github/dependabot.yml

#9498: Retarget `npm` Dependabot

---

applications/browser-extension/end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
applications/browser-extension/src/pageEditor/hooks/useAddNewModComponent.ts
applications/browser-extension/src/pageEditor/modals/addBrickModal/useAddBrick.ts

#9511: fix error toast when starting new mod
