- src/blocks/effects/hide.ts
- src/blocks/effects/index.ts
Simple brick for hiding/removing elements
In future, could also support an array of selectors so people don't have to add multiple instances of the brick
Only hides the element once. So if it gets re-added, the effect will be undone
> #417: effect brick for hiding/removing elements

- .github/workflows/build.yaml
- .github/workflows/integration.yml
Fixes #410
Hopefully this will help with the frequent `npm install` failures I'm seeing on GHA here.
> #410: Set up dependency caching in GitHub Actions

- schemas/recipe.json
- src/blocks/combinators.ts
- src/blocks/renderers/customForm.tsx
- src/blocks/transformers/blockFactory.ts
- src/blocks/transformers/template.ts
- src/components/fields/blockOptions.tsx
- src/components/fields/propTypes.ts
- src/contentScript.ts
- src/contrib/pipedrive/calendar.ts
- src/core.ts
- src/extensionPoints/actionPanelExtension.ts
- src/extensionPoints/contextMenu.ts
- src/extensionPoints/menuItemExtension.ts
- src/extensionPoints/panelExtension.ts
- src/extensionPoints/triggerExtension.ts
- src/options/loader.ts
- src/options/pages/InstalledPage.tsx
- src/options/pages/extensionEditor/DataSourceCard.tsx
- src/options/pages/extensionEditor/ExtensionEditor.tsx
- src/options/pages/extensionEditor/ExtensionPointDetail.tsx
- src/options/pages/extensionEditor/OptionsArgsCard.tsx
- src/options/pages/marketplace/ActivatePage.tsx
- src/options/pages/marketplace/ActivateWizard.tsx
- src/options/pages/marketplace/OptionsBody.tsx
- src/options/pages/marketplace/ServicesBody.tsx
- src/options/pages/marketplace/wizard.ts
- src/options/slices.ts
- src/types/definitions.ts
Add support for an `options` section in blueprints where a blueprint author can expose options for a user to configure when activating
> #444: support for blueprint options

- package-lock.json
- package.json
- src/background/protocol.ts
- src/blocks/available.ts
- src/contentScript/lifecycle.ts
- src/devTools/editor/extensionPoints/base.ts
- src/services/factory.ts
Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/427
Changes:
- The generated pattern no longer includes the hash
- The patterns are validated and converted following WebExtensions’ logic rather than generic glob/pattern logic
- The code has been changed to convert and match all patterns at once since [webext-patterns](https://github.com/fregante/webext-patterns) can create a single regex from multiple patterns
What didn't change:
- The hash is still included in the pattern if the user manually specifies it.
If we preserve the current support for hash, we _might_ have issues, especially around `contentScript.register` (native vs polyfill). If we instead drop support, do we just silently ignore it?
For the record, I tried a pattern with a has in `content_scripts.matches` in …
> #427: Don't include hash when generating the pattern

- browsers/webpack.config.js
- package-lock.json
- package.json
- src/background/deployment.ts
- src/extensionPoints/panelExtension.ts
- src/options/pages/deployments/DeploymentBanner.tsx
- src/options/pages/deployments/hooks.ts
Replaces #462 
Part of #411 
`moment` is rather large when it bundles the many unnecessary locales. 
This PR excludes locales and drops `moment` entirely from most bundles. Now it only appears in `options` and `devtoolsPanel` because I don't think an exact [`moment#calendar`](https://momentjs.com/docs/#/displaying/calendar-time/) alternative exists.
Requires testing of the remaining `moment#calendar` call in `EntryRow.tsx`
> #411: Remove most `moment` usage

- browsers/webpack.config.js
- package-lock.json
- package.json
- scripts/webpack.scripts.js
- tsconfig.json
Related to #411 
TypeScript projects don't need babel for the most part. #420 reduced the transforms required, this PR drops it entirely — except for Jest, which supports TypeScript through babel.
2m 16s -> 2m 
A week ago, this build time was 2m 38s if I remember correctly.
Negligible (0.1MB)
> #411: Drop `babel-loader`

- src/actionPanel/ActionPanelApp.tsx
- src/actionPanel/PanelBody.tsx
- src/components/fields/BlockField.tsx
- src/contrib/automationanywhere/BotOptions.tsx
- src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
- src/devTools/Locator.tsx
- src/devTools/Panel.tsx
- src/devTools/editor/tabs/EffectTab.tsx
- src/devTools/editor/tabs/reader/ReaderBlockConfig.tsx
- src/devTools/editor/tabs/reader/ReaderConfig.tsx
- src/options/App.tsx
- src/options/pages/Settings.tsx
- src/options/pages/SetupPage.tsx
- src/options/pages/brickEditor/BrickLogs.tsx
- src/options/pages/brickEditor/BrickReference.tsx
- src/options/pages/brickEditor/EditPage.tsx
- src/options/pages/extensionEditor/DataSourceCard.tsx
- src/options/pages/extensionEditor/ExtensionEditor.tsx
- src/options/pages/extensionEditor/RunLogCard.tsx
- src/options/pages/marketplace/ActivateBody.tsx
- src/options/pages/marketplace/ActivatePage.tsx
- src/options/pages/services/ServicesEditor.tsx
- src/options/pages/services/SharedServicesCard.tsx
- src/options/pages/templates/TemplatesPage.tsx
- src/pages/marketplace/MarketplacePage.tsx
Replaces #462 
Part of #411 
This is manual tree shaking, but given it's a single, constant spinner, maybe it's worth it. If not, feel free to close it, I just cherry-picked a previous commit.
> #411: Use exact `react-spinners` import

- src/helpers.ts
Fix Chrome detection broken in #435
For reference, this is what the UAs look like in Chrome and Firefox respectively:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
```
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0
```
> Fix Chrome detection

- src/background/__mocks__/protocol.ts
- src/background/auth.ts
- src/background/contextMenus.ts
- src/blocks/effects/sound.ts
More context about these PRs in #484 
---
`await` was being called on non-promises. In one case the type was incorrect, so I fixed that instead.
Context: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md
> Don't await non-promises

- src/background/devtools/external.ts
- src/background/protocol.ts
- src/devTools/context.ts
- src/extensionPoints/helpers.ts
- src/extensionPoints/triggerExtension.ts
- src/messaging/chrome.ts
More context about these PRs in #484 
---
Context:
- https://github.com/typescript-eslint/typescript-eslint/issues/282
- https://eslint.org/docs/rules/prefer-promise-reject-errors
In short:
- `async` functions automatically wrap/unwrap their return values, so `Promise.resolve` is redundant.
- When an async function throws, one generally expects `err` in `catch(err)` to be an error, not a string
> No explicit `Promise.resolve`

- .github/workflows/build.yaml
- .github/workflows/integration.yml
- browsers/webpack.config.js
- src/telemetry/rollbar.ts
Fixes #463
Follows the instructions in https://github.com/pixiebrix/pixiebrix-extension/pull/435#discussion_r648706876
- uses single ROLLBAR_PUBLIC_PATH
- drops browser-specific builds everywhere
- simplifies transformer code
> #463: Simplify Rollbar source map upload configuration

- src/background/contextMenus.ts
- src/devTools/editor/SelectorSelectorField.tsx
- src/telemetry/logging.ts
Replacing #488, I might add similar code changes here
Related:
I saw a few simple `reportError(error)` calls across the code, I wonder if they could all be dropped in lieu of just letting the `unhandledrejection` handlers catch it. I don't think that there's any advantage in catching an error that doesn't otherwise affect nearby code (e.g. it's not awaited at all). Example:
```js
setUninstallURL().catch((err) => {
reportError(err);
});
```
> Clean `selectError` + drop unnecessary `ary`

- src/background/installer.ts
- src/background/telemetry.ts
Fixes #491 
Follows #483 
I also fixed a bug: The uninstall page only followed the DNT setting after a browser restart
> Do not track on DEBUG, but allow enabling

- package-lock.json
- package.json
- src/action.tsx
- src/background.ts
- src/background/logging.ts
- src/options.tsx
- src/telemetry/logging.ts
- src/telemetry/rollbar.ts
* Use rollbar instance instead of namespace so Typescript typing is correct (remove `any` casts)
* Deserialize the error before passing to Rollbar so it sees it as an error object and not context data
Not implemented:
* `actions.tsx` and `options.tsx` don't ever have the user identifier set on them. When rollbar catches a top-level error via `captureUncaught: true` (and same for unhandledrejections) in these apps, the telemetry won't have the user assigned
> #509: fix rollbar stack trace telemetry

- .eslintrc
Disable react-redux eslint plugin until it's available on Codacy: https://github.com/codacy/codacy-eslint/issues/1544
> #505: temporarily disable react-redux plugin

- .idea/inspectionProfiles/Project_Default.xml
- src/contentScript.ts
- src/contentScript/backgroundProtocol.ts
- src/contentScript/devTools.ts
- src/contentScript/errors.ts
- src/contentScript/executor.ts
- src/contentScript/externalProtocol.ts
- src/contentScript/lifecycle.ts
- src/extensionPoints/contextMenu.ts
- src/hooks/fetch.ts
Closes #540  
- Refactors contentScript imports to have default export to install the window listeners
- contentScript now performs NOP if a copy is already installed instead of throwing an error
- Improve logging of which handlers were installed (previously, we being logged when the lift methods were processed on module load, not when the handlers were actually installed)
> #428: only install window handlers once for content script

- browsers/webpack.config.js
- src/layout/Banner.tsx
_"Am I looking at the latest version?"_ 
Tiny improvement: This should help us see if the build is working and we're looking at what we expect to be looking at.
You can see below that we're looking at a build that started after 15:23
> Include build timestamp in version during development

- src/components/ConfirmationModal.tsx
- src/devTools/Panel.tsx
- src/devTools/editor/ElementWizard.tsx
- src/devTools/editor/editorHooks.ts
Closes #557 
Provides a generic React component/hook we can use for confirmation dialogs
> #557: confirm remove in page editor

- src/devTools/editor/ElementWizard.tsx
- src/devTools/editor/hooks/useCreate.ts
- src/devTools/editor/toolbar/PermissionsToolbar.tsx
- src/permissions/index.ts
- Show grant permissions button in page editor if the bricks/services require additional permissions
- Prompt user to accept permissions on save in the page editor if the user only had granted temporary access to the page
Closes #589
> #589: show grant permissions button in page editor

- browsers/src/action.html
- browsers/src/devtools.html
- browsers/src/frame.html
- browsers/src/options.html
- browsers/src/support.html
- Uses HTML5 doctype
- Specifies utf-8 everywhere the same way
https://www.w3.org/International/questions/qa-html-encoding-declarations
> Use consistent HTML doctype and encoding

- .eslintrc
- src/action.tsx
- src/actionPanel/native.tsx
- src/background/contextMenus.ts
- src/background/deployment.ts
- src/background/devtools/internal.ts
- src/background/executor.ts
- src/background/installer.ts
- src/background/navigation.ts
- src/background/preload.ts
- src/blocks/combinators.ts
- src/devTools/editor/fields/SelectorSelectorField.tsx
- src/devTools/editor/hooks/useCreate.ts
- src/extensionPoints/contextMenu.ts
- src/extensionPoints/triggerExtension.ts
- src/options/pages/deployments/DeploymentBanner.tsx
- src/options/pages/extensionEditor/ExtensionEditor.tsx
- src/options/pages/marketplace/ActivateWizard.tsx
- src/options/slices.ts
- src/vendors/libraryDetector/libraries.js
- src/vendors/notify.js
Part of https://github.com/pixiebrix/pixiebrix-extension/issues/580
> ### Automatic error handling
> Where possible, use top-level handlers to simplify error handling code (including unhandled promise rejections).
Assumptions:
- promise-returning functions should never throw synchronously (this will be enforced by the `promise-function-async` rule)
- some functions aren't expected to throw (reportError) so they should handle their own errors internally. 
Therefore, these 2 are exactly equivalent:
```diff
- preloadMenus({ extensions: [extensionConfig] }).catch(reportError);
+ void preloadMenus({ extensions: [extensionConfig] });
```
> #580: Don't handle non-awaited rejections

- browsers/manifest.json
- src/devTools/editor/extensionPoints/actionPanel.ts
- src/devTools/editor/extensionPoints/base.ts
- src/devTools/editor/extensionPoints/menuItem.ts
- src/devTools/editor/extensionPoints/panel.ts
- src/devTools/editor/extensionPoints/trigger.ts
- src/devTools/editor/hooks/useCreate.ts
- src/devTools/editor/tabs/AvailabilityTab.tsx
- src/devTools/editor/tabs/contextMenu/AvailabilityTab.tsx
- src/extensionPoints/factory.ts
- src/permissions/index.ts
- src/permissions/patterns.ts
- Fixes bug where permissions check on save would fail if the extension foundation did not already exist
- Switches to `<all_urls>` in optional permissions instead of `*://*/`
- Fixes match pattern shortcuts in devtools panel to remove trailing `*`
> #662: fix permissions check for context menus

- package-lock.json
- package.json
This is a rework of https://github.com/pixiebrix/pixiebrix-extension/pull/675 due to a misunderstanding of the contentScripts.register API. That PR was undone/closed:
- https://github.com/fregante/content-scripts-register-polyfill/pull/27#issuecomment-873398462
And that logic was moved to:
- https://github.com/fregante/webext-dynamic-content-scripts/pull/24
This change regards Firefox because the polyfill’s behavior did not match Firefox’ and therefore the issue described in #671 still existed there. This is untested in Firefox due to large incompatibilities (#490), but it works in Chrome.
The red text here is to show that the style is also injected. The console shows that the JS is injected once.
> Fix Firefox "injection on grant" compatibility

- src/background/auth.ts
- src/background/devtools/external.ts
- src/background/devtools/internal.ts
- src/background/executor.ts
- src/background/logging.ts
- src/background/requests.test.ts
- src/background/requests.ts
- src/background/util.ts
- src/chrome.ts
- src/contentScript/backgroundProtocol.ts
- src/contentScript/executor.ts
- src/utils.ts
- src/utils/expect-context.ts
Such utility functions make context-limiting it short and consistent. The functions are still flexible enough to let you customize the error type and/or the error message.
There are some other context exclusions in the code (e.g. multiple contexts allowed) but I left those out for now since they're one or two.
> Add expect/forbid context helpers

- src/background/devtools/external.ts
Fixes #679 
It seems to work for me and it enables the PixieBrix tab in the devtools: (screenshot taken on pixiebrix.com)
> #679: Disable unsupported API call in Firefox in dev tools

- .github/workflows/build.yaml
- .github/workflows/integration.yml
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
Also might I suggest moving the project to Node 15 or 16? They use `npm 7` and the lockfile v2 which probably has worthwhile improvements. Maybe it avoids "broken npm installs" (https://github.com/pixiebrix/pixiebrix-extension/issues/595#issuecomment-867650460) (one can dream)
> #410: Use native npm caching on CI

- src/blocks/transformers/remoteMethod.ts
- src/components/fields/FieldTable.tsx
- src/components/fields/TextField.tsx
- src/components/fields/blockOptions.tsx
- src/extensionPoints/panelExtension.ts
Closes #708
- Allow any data in `@pixiebrix/http` brick
- Show object configuration for empty field schemas
- Avoid unnecessary re-renders in ObjectField
> # 708: http input schema

- src/devtools.ts
I was always annoyed by how long it takes for the _tab_ to show up and that it never did if there was an error with the content script.
Both issues could be alleviated this way. You can follow the commits one by one to make more sense of the changes.
However it's still not instant during development, likely because it still needs to execute 13MB of devtools.js
> Create dev tab and panels immediately

- package-lock.json
- package.json
- src/contentScript/context.ts
- src/contentScript/externalProtocol.ts
- src/messaging/external.ts
Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/682
Quick and dirty solution to see what you think about the idea.
Problem:
- The app needs to know whether the extension is ready to receive messages
Solution:
- The extension adds an attribute to the `body` after loading
Explanation:
- The app doesn't have access to `PIXIEBRIX_READY_SYMBOL` and other local variables. Either we have a "very public" marker that the extension has loaded (an attribute) or we have to resort to polling via messages + timeouts, probably. Alternative solutions welcome.
If this is accepted, I'll probably turn the poller into a MutationObserver on `body`
> #682: Wait for content script before sending external messages

- src/actionPanel/native.tsx
- src/actionPanel/protocol.tsx
- src/background/browserAction.ts
- src/background/executor.ts
- src/background/protocol.ts
- src/background/util.ts
- src/blocks/effects/index.ts
- src/blocks/effects/sidebar.ts
- src/contentScript/backgroundProtocol.ts
- src/contentScript/browserAction.ts
- src/contentScript/connection.ts
- src/contentScript/errors.ts
- src/contentScript/executor.ts
- src/errors.ts
- src/helpers.ts
- src/utils/expectContext.ts
- Add warning suppressions for `promise-function-async` on message listeners because the async keyword breaks the behavior (and the warning is auto-fixable, so eslint was breaking them)
- Simplifies the sidebar state logic. Instead of tracking the nonce/state separately separately in the content script, it just uses the HTML element for it
- Adds `@pixiebrix/sidebar/hide` and `@pixiebrix/sidebar/show` bricks. The show brick is more important, as there's situations where we want to show a panel if certain conditions are met on the page
@fregante adding you as a reviewer since this touches the messaging code
Closes #634
> #634: bricks to open/close the sidebar

- src/actionPanel/protocol.tsx
- src/background/browserAction.ts
- src/background/devtools/contract.ts
- src/background/devtools/internal.ts
- src/background/executor.ts
- src/background/iframes.ts
- src/background/protocol.ts
- src/contentScript/backgroundProtocol.ts
- src/contentScript/executor.ts
- src/core.ts
- src/messaging/protocol.ts
An extension to this other PR that I never did because it required moving around a bit more code
- https://github.com/pixiebrix/pixiebrix-extension/pull/487
Improvements:
- instead of an ever-growing number of unrelated message handlers in a single function under a `switch`, now we have independent one-message-type handlers
- separate handlers means we can finally use async/await 
- Many of these onMessage listeners are now actually identical (makes you wonder if these intermediary handlers could be deduplicated even further!)
I tried not to change the behavior at all, even when sometimes I'm not sure whether returning a Promised value was intentional or just a way to `await` a value before responding (e.g. `return browser.runtime.sendMessage()` doesn't immediately make sense to me) …
> Allow use of `await` in message handlers

- src/background/locator.ts
- src/components/logViewer/details/NetworkErrorDetail.tsx
- src/devTools/editor/tabs/ServicesTab.scss
- src/devTools/editor/tabs/ServicesTab.tsx
- src/hooks/common.ts
- src/hooks/events.ts
- src/hooks/fetch.ts
- src/hooks/useFetch.ts
- src/options/pages/extensionEditor/ExtensionPointDetail.tsx
- src/options/pages/extensionEditor/ServiceAuthSelector.tsx
- src/options/pages/extensionEditor/ServicesFormCard.tsx
- src/options/pages/services/PrivateServicesCard.tsx
- src/options/pages/services/ServicesEditor.tsx
- src/services/baseService.ts
- src/services/locator.ts
- src/validators/generic.ts
Closes #753
- Adds link to service configuration page in page editor
- Adds button to refresh available service auths in page editor
- Cleans up integration table formatting
- Adds better useFetch hook
> #753: button to refresh service auths in page editor

- package-lock.json
- package.json
- src/background/util.ts
- Fixes #727 
1. Add some visible styles to `styles.css` like `*{background: red}`
2. Open permissionless website, like https://www.gov.uk
3. Open sidebar
4. Notice styles being applied
> #727: Inject content script CSS in `ensureContentScript`

- .eslintrc
- browsers/resolve.config.js
- browsers/webpack.config.js
- scripts/webpack.scripts.js
- src/blocks/readers/index.ts
- Fixes #570
This was low priority but the solution was pretty simple:
- extract resolutions into shared file
- point eslint to this file
- import file from both webpack.browsers.js and webpack.scripts.js
In the future:
Side note: The plugin is quite buggy in general (350 open issues for a single eslint plugin) so we might not always be able to follow its suggestions.
> #570: Extract and deduplicate webpack resolution config

- src/background/deployment.ts
- src/options/pages/marketplace/ActivateWizard.tsx
- src/options/pages/marketplace/ServicesBody.tsx
- src/permissions/index.ts
- src/utils/permissions.ts
Closes #837
- Simplifies updateDeployments
- Exclude pixiebrix API from calculation of service permissions since it's a required permission
> #837: don't show pixiebrix api for marketplace wizard integrations

- src/background.ts
- src/background/firefox-compat.ts
- src/background/firefoxCompat.ts
- src/helpers.ts
There are a few behaviors in Firefox that don't match Chrome’s. I wanted to add more here but I think I'll just open multiple PRs.
To open the extension’s options page you have to:
1. Right click on the icon
2. Click **Manage Extension**
2. Open the tiny hamburger menu
3. Click Preferences 🤦‍♂️ 
Whereas in Chrome:
And now also in Firefox:
https://user-images.githubusercontent.com/1402241/126060811-53bf3a62-a414-45e9-8724-a49c286dff75.mov
It's been implemented as its own file for now as it can be extracted into its own module later, like `webext-consistent-behavior` or something like that.
> Add Options menu item in the extension dropdown in Firefox

- src/background/contextMenus.ts
- src/background/deployment.ts
- src/extensionPoints/contextMenu.ts
- src/options/pages/InstalledPage.tsx
- src/options/pages/deployments/DeploymentBanner.tsx
- src/telemetry/events.ts
Closes #867
Removes context menus in the deployment flow
- When installed from banner
- When installed automatically via the background page
Fixes some lint:
- Missing react dependencies
- Promise calls without void or await
Other:
- There's a bunch of duplicate code related to deployment reinstall (3 different places) that needs to be combined in the future. The `deployments.ts` code is hard to refactor because it uses a hacky approach to reusing the reducers
> #867: uninstall context menus in deployment flow

- src/actionPanel/PanelBody.tsx
- src/blocks/renderers/common.ts
- src/devTools/editor/extensionPoints/actionPanel.tsx
- src/devTools/editor/extensionPoints/base.ts
- src/devTools/editor/extensionPoints/panel.ts
- src/devTools/editor/tabs/effect/QuickAdd.tsx
- src/extensionPoints/actionPanelExtension.ts
Closes #865
- Don't show property tree by default when using page editor to add a panel
- Add iframe to the list of recommended bricks
> #865: remove property panel as default

- src/options/pages/deployments/DeploymentBanner.tsx
- src/utils/permissions.ts
I can't reproduce #866, so add logging to try to replicate it on client machines after next release
> #866: add additional logging to deployment permission check

- src/actionPanel/ActionPanelApp.tsx
- src/actionPanel/native.tsx
- src/actionPanel/protocol.tsx
- src/background/browserAction.ts
- src/background/devtools/protocol.ts
- src/background/navigation.ts
- src/background/util.ts
- src/contentScript/backgroundProtocol.ts
- src/contentScript/browserAction.ts
- src/contentScript/lifecycle.ts
- src/devTools/editor/hooks/useCreate.ts
- src/devTools/editor/hooks/useRemove.ts
- src/extensionPoints/actionPanelExtension.ts
- src/options/pages/InstalledPage.tsx
- src/telemetry/events.ts
* Closes #877 
* Closes #878 
TODO:
> #878, #877: side panel reliability and removal

- src/blocks/combinators.ts
- src/extensionPoints/menuItemExtension.ts
- src/helpers.ts
- src/utils/renderers.ts
Closes #811
Future work: 
- Refactor helpers.ts to separate mapArgs from the more generic content (e.g., `isChrome`) which is used by more of the bundles
> #811: lazy-load handlebars/nunjucks

- src/__mocks__/iconsMock.ts
- webpack.config.js
@fregante any idea of what might be causing webpack to still bundle the icon assets? 
I'm trying to alias to our existing mock for Jest
```
resolve.alias["@/icons/svgIcons"] = path.resolve("src/__mocks__/iconsMock");
```
But Webpack is still creating the icon directories:
```
Mocking icons for development build
{
'@': '/Users/tschiller/projects/pixiebrix-extension/src',
'@img': '/Users/tschiller/projects/pixiebrix-extension/img',
'@contrib': '/Users/tschiller/projects/pixiebrix-extension/contrib',
'@schemas': '/Users/tschiller/projects/pixiebrix-extension/schemas',
vendors: '/Users/tschiller/projects/pixiebrix-extension/src/vendors',
'@microsoft/applicationinsights-web': '/Users/tschiller/projects/pixiebrix-extension/src/contrib/uipath/quietLogger',
handlebars: …
```
> #881: add `DEV_SLIM` environment option

- .eslintrc
- package-lock.json
- package.json
- src/background/telemetry.ts
- src/blocks/effects/alert.ts
- src/blocks/readers/ImageEXIFReader.ts
- src/blocks/readers/ImageReader.ts
- src/blocks/renderers/dataTable.ts
- src/blocks/transformers/prompt.ts
- src/components/fields/BlockModal.tsx
- src/components/fields/ServiceModal.tsx
- src/components/fields/blockOptions.tsx
- src/contrib/google/sheets/handlers.ts
- src/devTools/editor/sidebar/DynamicEntry.tsx
- src/devTools/editor/sidebar/InstalledEntry.tsx
- src/extensionPoints/helpers.ts
- src/extensionPoints/menuItemExtension.ts
- src/extensionPoints/panelExtension.ts
- src/frameworks/component.ts
- src/nativeEditor/infer.ts
- src/options/pages/brickEditor/useSubmitBrick.tsx
- src/options/pages/deployments/hooks.ts
- src/options/pages/marketplace/ActivateBody.tsx
- src/registry/localRegistry.ts
- src/test-env.js
- src/utils.ts
- src/validators/validation.ts
In this PR:
- drop most custom configuration since it's covered by xo presets
- soft-enable more rules
This PR lets us:
- more easily enable rules over time because the eslint config just requires deleting a line rather than adding config
- progressively enable rules or disable some rules permanently with a reason
- enable the strict rules that are completely disabled
- also use a shared tsconfig https://github.com/sindresorhus/tsconfig
- First and last commits are for configuration
- other commits enable
Some of these are soft-enabled by the preset itself, like max-params, but most aren't
139 [eqeqeq](https://eslint.org/docs/rules/eqeqeq)
127 [no-eq-null](https://eslint.org/docs/rules/no-eq-null)
111 [@typescript-eslint/no-confusing-void-expression](https://github.com/typescript-eslint/ty …
> Soft-enable most lint rules from strict configuration

- src/blocks/effects/index.ts
- src/blocks/effects/telemetry.ts
Adds a new effect brick that enterprise/team customers can use to send custom telemetry. For example, expected time/money saved for a particular action
> #890: add brick for reporting events

- src/action.scss
- src/actionPanel/ActionPanelApp.tsx
This adds a close sidebar button to the PixieBrix sidebar, which resolves #849, like so:
> #849: add close sidebar button

- package-lock.json
- package.json
- src/auth/AuthContext.ts
- src/background/protocol.ts
- src/chrome.ts
- src/contentScript/externalProtocol.ts
- src/hooks/fetch.ts
- src/layout/Banner.tsx
- src/services/baseService.ts
- src/telemetry/logging.ts
- src/telemetry/rollbar.ts
Currently the detection is:
https://github.com/pixiebrix/pixiebrix-extension/blob/ede30e8e08065622ce659d1119fc296b8ac771b3/src/chrome.ts#L80-L87
But that does not include the sidebar. This line has been at the [base of `webext-detect-page`](https://github.com/fregante/webext-detect-page/blob/1eb24e148d0d773225ba5d2b6f7cb984c3989054/index.ts#L1) for a while:
```js
typeof globalThis.chrome?.extension === 'object'
```
> Fix extension context detection

- src/devTools/getSelectedElement.ts
- src/devtools.ts
Until now, every time you open the console _a lot_ of code is run or attempts to run even if your intention is not to use PixieBrix.
This file has been refactored to:
- avoid running the element detection code unless the PB devtools sidebar is visible
- avoid content script injection attempts until the PB panel is selected
- if we have permissions, the CS is already injected 
- if we don't have permissions, the attempt will fail
- if we have activeTab, the user is likely already on PB panel anyway, which is handled directly by `connectFrame` in the background (which could also benefit from similar changes)
- this avoids console noise when I open the regular console
- actually show errors in the sidebar pane thanks to `serializeError`
- reduce but not completely avoid confusing console …
> Clean up devtools init

- src/blocks/effects/alert.ts
- src/blocks/effects/clipboard.ts
Resolves #794 and also resolves #900
This adds additional boolean and number types to the JSON schema for Alert and CopyToClipboard blocks, to prevent unintentional type errors when building up actions.
> #794: copy to clipboard accepts numbers and bools

- schemas/component.json
- src/blocks/combinators.ts
- src/blocks/errors.ts
- src/blocks/transformers/blockFactory.ts
- src/blocks/transformers/prompt.ts
- src/components/logViewer/EntryRow.tsx
- src/components/logViewer/details/OutputValidationErrorDetail.tsx
- src/options/pages/brickEditor/validate.ts
- src/telemetry/rollbar.ts
- src/validators/generic.ts
Half of #914 
- Checks output against `outputSchema` if available, and logs validation errors
- Adding support for outputSchema in `kind: component` defined via YAML
Not included:
- Checking output of readers against their output schema
> #914: validate brick output and log validation errors

- src/options/pages/SetupPage.scss
1. Install extension
2. Resize window to about 1000px
> Avoid overflow on setup page

- src/components/ConfirmationModal.tsx
This adds cancelCaption to the cancel button if it exists, and "Cancel" by default. Prior to this feature, the cancelCaption prop existed in the ModelProps type, but was never used in the template.
> add cancelCaption to confirmation modal cancel button

- src/actionPanel/native.tsx
Minor change, the sidebar had borders all around and they are not needed
> Avoid duplicate borders on sidebar

- package.json
- resolve.config.js
- src/frameworks/contrib/ember.ts
Resolves #943
**Attempt using normal lodash**
The import works if I import it directly. I then get the same error for "compact" when using the selector selection widget: https://www.loom.com/share/e4be13054532425db9064082fac1c708
**Switching to lodash-es**
`lodash-es` is a build of lodash using es6 modules. It works in the page script even using destructured import. It should also let us benefit from tree-shaking in lodash
> #943: switch to lodash-es to avoid module import error

- src/background/logging.ts
- src/blocks/effects/event.ts
- src/blocks/effects/forms.ts
- src/blocks/errors.ts
- src/blocks/readers/jquery.ts
- src/components/fields/FieldTable.tsx
- src/errors.ts
- src/extensionPoints/menuItemExtension.ts
- src/nativeEditor/infer.ts
- src/nativeEditor/utils.ts
- src/script.ts
- src/telemetry/logging.ts
- src/telemetry/rollbar.ts
- src/tests/errors.test.ts
Closes #918
- Fixes bug where nested ContextErrors weren't getting unrolled all the way to get the root cause
- Fixes handling of BusinessError subclasses
- Introduces `NoElementsFoundError` and `MultipleElementsFoundError` classes that take a selector (to keep the message in the error telemetry cleaner)
> #918: fix error root cause filtering

- src/background/browserAction.ts
- src/background/util.ts
- Fixes: https://github.com/pixiebrix/pixiebrix-extension/issues/694
I had some issues while debugging https://github.com/pixiebrix/pixiebrix-extension/issues/958 that were caused by this. The _fun part_ is that the extension was attempting to inject the content script **into the sidebar’s iframe** due to this, resulting in content script code running in an unexpected context.
Related:
- https://github.com/pixiebrix/pixiebrix-extension/issues/801
- https://github.com/pixiebrix/pixiebrix-extension/issues/575
- https://github.com/fregante/webext-detect-page/issues/9
> Avoid injection on extension pages; Avoid duplicates on app pages

- webpack.config.js
Because of https://github.com/pixiebrix/pixiebrix-app/issues/380 we're going to have to publish versions to npm to have them picked up by the app
As part of that, we need to support alpha versioning in the extension. However, the extension manifest only supports numbers in the version
> #700: only include semver in manifest version

- src/action.tsx
- src/devTools/Panel.scss
- src/devtoolsPanel.tsx
PR #976 imported the theme in overrides, which then cause the theme to flow into the devtools.
This PR removes the overrides import from the devtools and puts the one rule that was in there in the devtools SCSS file
> #904: isolate CSS in devtools

- webpack.config.js
Closes #981 
@fregante The port appears to be required in the externally_connectable. I was able to reproduce the connection problem reliably
> #981: add port to origins used by externally_connectable in local development

- src/devTools/Panel.scss
- src/devtoolsPanel.tsx
- src/options.scss
- src/vendors/overrides.scss
This moves css added in PR #976 to the css file specific to only the options page (`options.scss`). This separates it from affecting the dev tools panel and the action panel. Also keeps the `vendors/overrides.scss` file clean from the options page navbar customizations so it can still be referenced everywhere.
> #904: move options navbar css to options css file

- src/action.scss
- src/actionPanel/ActionPanelApp.tsx
Closes #912 
This makes a few tweaks to the top layout of the action panel sidebar:
- Replace the two chevrons+css hack with just the angle-double-right fontawesome icon
before: ![image](https://user-images.githubusercontent.com/2801308/128241537-87235392-f4c1-43dc-b36d-610ab511a6e1.png) after: ![image](https://user-images.githubusercontent.com/2801308/128241591-029cd827-87bc-4bec-b93c-858b097cc031.png)
- Update the look & feel of the options button
before: ![image](https://user-images.githubusercontent.com/2801308/128241993-af1798b4-1c18-40f8-9f27-356276398a1a.png)
after: ![image](https://user-images.githubusercontent.com/2801308/128242037-df0c32e2-8c57-4250-96c1-43b7c46f383f.png)
- Switch the whole top div to use flexbox space-between as opposed to an empty "spacer" piece to separate …
> #912 Improve layout/styling of close/options buttons at the top of the action panel

- src/telemetry/rollbar.ts
`can't access dead object`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object
I've been seeing this error for a while now but I never addressed it because I thought it was due to some internal browser communication. Firefox has many of these. It turns out Rollbar is causing `can't access dead object` and breaking injection.
Diff best reviewed without whitespace. I just wrapped an assignment with an IIFE that includes a try/catch. Alternative solutions welcome.
1. In Firefox
2. Open tab with permitted website
3. Reload extension
4. The `executeScript` that takes care of injecting into existing tabs will throw with that error, and the new content script will not be injected
This actually fixes []() #963, but the suggested code in there would still be good.
> Avoid breakage due to init errors

- .github/workflows/integration.yml
- src/background/devtools/internal.ts
- src/background/devtools/protocol.ts
- src/background/util.ts
- src/chrome.ts
- src/devTools/context.ts
- src/devTools/editor/hooks/useAddElement.ts
- src/devTools/editor/panes/PermissionsPane.tsx
- src/devTools/editor/panes/insert/GenericInsertPane.tsx
- src/devTools/editor/panes/insert/useAddExisting.ts
- src/devTools/editor/tabs/AvailabilityTab.tsx
- src/devTools/editor/tabs/contextMenu/AvailabilityTab.tsx
- src/devTools/utils.ts
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/801
I was investigating a heisenbug when I noticed `getTabInfo` was used mainly to get the URL of the current tab but doing so with multiple steps (devtools, background, content script and back)
It "kind of" fixes the mentioned issue in that the user is no longer presented with a broken UI, but instead it shows the permission denied error (this also makes it consistent with Firefox)
Future improvements for UX described in https://github.com/pixiebrix/pixiebrix-extension/issues/801#issuecomment-890942445
> The solution here is to introduce a third permission state:
> 
> - has permission
> - no permission
> - cannot have permission or "it makes no sense" (i.e. show the editor on the extension pages)
> Don't show unresponsive editor UI on special browser pages

- src/options/pages/templates/TemplatesPage.scss
As reported by @mnholtz. I thought I'd take a stab at it since I saw a common problematic pattern.
This PR is not meant to be a final solution but rather to ensure it never happens:
- fixed widths and heights are problematic
- if the intent is to normalize the sizes of multiple items, let's use `stretch`
I don't know which commit caused this issue, but this gives us a hint:
My guess is that that `vendor/**/_cards.scss` file is being imported _after_ the TemplatesPage (apparently duplicate, too) and therefore it's overriding it.
> Avoid category card clipping in options page

- src/background/browserAction.ts
- src/devTools/editor/panes/PermissionsPane.tsx
- src/popups/PermissionsPopup.tsx
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/813
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/812
In short, the `activeTab` permission is lost on refresh in Firefox, so the previous behavior was not possible. This is now documented in: https://github.com/pixiebrix/pixiebrix-extension/wiki/Web-Extensions-behaviors#activetab
https://user-images.githubusercontent.com/1402241/128483105-b78e539f-243d-43bf-af07-98b7e10bebb9.mov
https://user-images.githubusercontent.com/1402241/128483033-be2f0541-ebf3-4878-bb12-99c82a3fbf2d.mov
> Immediately catch `activeTab` and update editor state

- src/components/AsyncButton.tsx
- src/layout/ErrorModal.tsx
- src/popups/PermissionsPopup.tsx
0. In Firefox, in the editor
1. Click "Grant Permanent Permission"
2. The button is not focused, so <kbd>Enter</kbd> won't work
---
0. Visit `about:blank`
1. Click the browser action
2. The modal can't be closed with <kbd>Enter</kbd> because it's not focused
> Improve modals’ accessibility

- src/devTools/editor/sidebar/Sidebar.tsx
It's a checkbox that does nothing and it should thus be hidden.
> Hide "Show 0 unavailable"

- src/blocks/effects/vue.ts
- src/blocks/transformers/jsonPath.ts
- src/frameworks/contrib/vue.ts
- src/pageScript/protocol.ts
- src/utils.ts
- Closes #1008: use lodash `set` to support setting nested properties in vue components
- Clean some lint
> #1008: support property paths in set-values brick

- src/__mocks__/webextDetectPage.ts
- webpack.config.js
Context:
- https://github.com/pixiebrix/pixiebrix-extension/issues/669#issuecomment-894785221
In a perfect/pure world this solution would be enough to solve/avoid that issue since Webpack would be able to just drop unrelated code.
---
This is a basic setup of that suggestion. This partial implementation doesn't affect us much, but it's also super simple so I thought I'd add it here. 
In the future it could be replaced by using `process.env` directly in my module, but I have to see how that affects non-webpack users first: https://github.com/fregante/webext-detect-page/issues/12
> Make `webext-detect-page` static in some cases

- src/auth/token.ts
One thing I noticed in Firefox is that it repeatedly notified the user that the authentication data was updated, even by refreshing the cache. 
This was the culprit: https://github.com/epoberezkin/fast-deep-equal/blob/a8e7172b6c411ec320d6045fd4afbd2abc1b4bde/src/index.jst#L13
The `postMessage` object appears to be created with `Object.create(null)` so it never matches an equivalent but "normal" object.
I replaced it with… 🥁 lodash! 
I also took the chance to drop the deprecated read/store functions and started storing a regular object instead of JSON
> Correctly track auth data changes in Firefox + Update storage

- src/background/firefoxCompat.ts
- src/background/permissionPrompt.ts
- src/chrome.ts
- src/contrib/google/initGoogle.ts
- src/development/autoreload.ts
- src/helpers.ts
- src/messaging/external.ts
Minor cleanup
- Use existing detections in `webext-detect-page`
- Ensure that browser exclusions are exact (`!isChrome` might not necessarily mean `=== firefox` in the future)
> Cleanup browser detection

- src/contentScript.ts
- src/contentScript/externalProtocol.ts
- src/messaging/external.ts
Core changes:
- it ensures that the messages aren't just lost into the void: Every message has to ping back or else it will fail just like `chrome.runtime.sendMessage` does.
- avoids passing of serialized errors as described in https://github.com/pixiebrix/pixiebrix-extension/issues/580
- refactors the file to linearize the sequence of events: send, await response, return response/error
Interim solution to some issues described in:
- https://github.com/pixiebrix/pixiebrix-extension/issues/1015
Fixes:
- Fixes https://github.com/pixiebrix/pixiebrix-app/issues/334
<table>
<tr>
<th>No extension
<th>With extension
<tr>
<td><img src="https://user-images.githubusercontent.com/1402241/128657290-56183934-843d-4c4a-8c9d-d403800fe271.gif">
<td><img …
> Tighten `externalProtocol` messaging

- src/manifest.json
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/845
Let's merge this **after August 10th** (Firefox 91 release) or else Firefox will not let me open it unless I install a beta.
In the meanwhile one can follow the instructions in:
- https://github.com/pixiebrix/pixiebrix-extension/issues/992
> Increase minimum Firefox version to 91

- .github/workflows/integration.yml
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/1063
I left the other upload as it's not on a slow path
> Don't upload extension artifacts for non-main CI builds

- webpack.config.js
Related:
- https://github.com/pixiebrix/pixiebrix-extension/pull/1059#issuecomment-898562916
- https://github.com/pixiebrix/pixiebrix-extension/issues/975
In short: 
- `typescript-plugin-css-modules` installed `sass`
- `sass-loader` picks it up automatically over the existing `node-sass`
- Bootstrap isn't liked by dart sass
<details>
<summary>580 omitted</summary>
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($spacer, 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
│                               ^^^^^^^^^^^
╵
node_modules/bootstrap/scss/_variables.scss 302:31  @import
src/vendors/theme/app/app.scss 17:9                 root …
```
> Hide dart-sass warnings by enforcing node-sass

- .github/workflows/integration.yml
The `build` script includes type-checking too, but on CI that's already part of its own job (#1061)
> Avoid duplicate type annotations on CI

- src/layout/Sidebar.tsx
- src/options.scss
This fixes #996 
Adds some css to override what bootstrap is doing to move the sidebar to the other side.
> #996 - Keep sidebar on the left side at smaller widths

- package-lock.json
- package.json
Let's not include rarely-used "tooling" dependencies in the package as they will slow down every update unnecessarily. This adds 155 dependencies: https://npmgraph.js.org/?q=madge
It can still be part of the `scripts` but it's best to install it once, globally.
This PR 😅
> Suggestion: Remove `madge` dependency

- src/options/pages/extensionEditor/ServiceAuthSelector.tsx
`react-select` throws an error when the dropdown is created if undefined is passed for the MenuList
> #1099: fix NPE in ServiceAuthSelector in Page Editor

- package-lock.json
- package.json
> #1098: revert mini-css-extract-plugin version

- src/icons/getSvgIcon.ts
Full fix for https://github.com/pixiebrix/pixiebrix-extension/issues/1103
The defaults had gotten lost due to a confusion around the typing, now resolved with `Partial<>`
> #1103: Handle null icons in getSvgIcon

- src/blocks/readers/frameworkReader.ts
- src/contentScript/devTools.ts
- src/devTools/editor/tabs/reader/ReaderConfig.tsx
- src/pageScript/protocol.ts
Fixes #1046 
Fixes bug where reader previews in the page editor weren't using the pathSpec because it wasn't being passed through (I didn't include the pathSpec field originally b/c the devtools configuration interface doesn't support configuring the pathSpec)
> #1046: include pathSpec when previewing reader data

- .storybook/main.js
- src/__mocks__/browserMocks.ts
- src/components/logViewer/EntryRow.tsx
- src/components/logViewer/LogContext.tsx
- src/components/logViewer/LogTable.stories.tsx
- src/components/logViewer/LogTable.tsx
- src/components/logViewer/LogToolbar.tsx
Closes #1124 
- Mocks http://github.com/pixiebrix/pixiebrix-extension/blob/5137e9e0922ebbf65490af8efbc1c9da962946cd/src/__mocks__/browserMocks.ts#L21-L21 so the LogTable story can run
- Applies the fix from out main webpack config to prevent Storybook's webpack from spitting out warnings about bad css: http://github.com/pixiebrix/pixiebrix-extension/blob/5137e9e0922ebbf65490af8efbc1c9da962946cd/.storybook/main.js#L53-L53
> #1124: fix log table story; fix SCSS warnings

- src/components/fields/FieldTable.tsx
Fixes #1111 
`useRef()` creates something akin to a local variable that persists its own value across renders in a functional component, but the input parameter is just a default value, there is no tracking/updating of the current value happening under the covers. The ref must have its current value updated manually in order to store a new value across renders.
This change updates the current ref value for `ObjectField` on each render.
> #1111 - Fix "Add Property" button for object brick options

- package.json
Tells Jest to only collect coverage from TypeScript files since the Codacy coverage reported breaks if you send multiple languages at once
The alternative would be to figure out how to report them separately, but that's not worth it given our own code is 99% TypeScript
> When working with multiple languages on your repository, it would be ideal to send separate coverage reports, one for JavaScript and one for TypeScript but another possible workaround for this would be uploading the same file twice specifying -l JavaScript once and -l TypeScript on the second upload.
> 
> Could you try uploading the coverage reports separately or uploading the same file twice specifying the languages with the flag -l, together with --force-language. For example:
> 
> bash <(curl -Ls …
> #1122: only report typescript coverage to appease codacy

- .github/workflows/ci.yml
- .github/workflows/storybook.yml
- webpack.config.js
To make for speedier reviews, I left out these small changes I had made in
- https://github.com/pixiebrix/pixiebrix-extension/pull/1071
Also in the future (or now) we can pre-zip the extension to speed up uploading because it takes as long as the build itself. Apparently this is due to the large number of files (the icons) that GHA uploads 2 at a time…
> Further webpack config fixes

- src/devtoolsPanel.html
- webpack.config.js
These changes enable `react-devtools` to run against our Page Editor app in the Chrome dev tools panel.
In order to run this, you'll need to install react-devtools first:
```
npm i -g react-devtools
```
Then, uncomment the script injection in `devtoolsPanel.html` to let the app connect.
Example:
> Set up react-devtools for use as a global npm dependency

- .eslintrc
- src/options/slices.ts
Should fix half of #1169 
Additional:
- Turns on the no-mixed-operators rule and forces explicit parens around `??` expressions
- For arithmetic, I could enable the rule b/c it conflicts with prettier's behavior. (Prettier has its own point of view of what's confusing). It's possible we might hit incompatibility with the other rules. IMO it's safer to enable for now and tweak as we go. The alternative is to leave it enabled and force the developer to assign subexpressions to variables to avoid the confusing code
> #1169: fix use of null coalescing operator in saveExtension

- src/core.ts
- src/options/pages/marketplace/ActivateWizard.tsx
- src/options/pages/marketplace/AuthWidget.tsx
- src/options/pages/marketplace/ConfigureBody.tsx
- src/options/pages/marketplace/PermissionsBody.tsx
- src/options/pages/marketplace/ServicesBody.tsx
- src/options/pages/marketplace/wizardTypes.ts
- src/pages/marketplace/useInstall.ts
- src/permissions/index.ts
Closes #1181 
Also fixes bug/warning where extension permissions could not be calculated if a services section was not defined for all extensions in the blueprint
> #1181: handle services with period in the name

- src/options/pages/marketplace/AuthWidget.tsx
- src/options/pages/marketplace/ServicesBody.tsx
Closes #1047
Also re-fetches the remote configurations. Probably unnecessary, but the quickest way to fix for now
> #1047: make new personal configuration immediately available in wizard

- webpack.config.js
Related to
- https://github.com/pixiebrix/pixiebrix-extension/pull/617#issuecomment-869160489
- https://github.com/pixiebrix/pixiebrix-extension/issues/480#issuecomment-869167118
> Exclude `redux-logger` from production build

- .eslintrc
As reported by @BALEHOK on Slack.
```
Filename 'LogTable.stories' must match the exported name 'LogTable'. eslint(filenames/match-exported)
```
`.stories` files must have that special filename and there's no practical way to name variables with a period.
> Disable `filenames/match-exported` on stories

- package-lock.json
A sub-dependency is causing noise when linting, the fix is easy (lockfile only)
- https://github.com/ljharb/es-abstract/issues/133
```
❯ nr lint -- --quiet
(node:20287) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./2020/" in the "exports" field module resolution of the package at ./node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./2020/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:20287) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at ./node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./helpers/*".
```
> Fix eslint deprecation warning

- src/blocks/renderers/DataTableComponent.tsx
- src/blocks/renderers/PropertyTree.tsx
- src/blocks/renderers/customForm.tsx
- src/blocks/transformers/modal.tsx
- src/importAssets.d.ts
- webpack.config.js
- webpack.sharedConfig.js
- Related to https://github.com/pixiebrix/pixiebrix-extension/issues/480
- Related to #978 
- Likely fixes icon fonts in injectable stylesheets
0.6 MB saved on disk.
> Import injectable stylesheets as URLs

- src/devTools/editor/extensionPoints/menuItem.ts
Fixes #1045 
Update the effect tab name to "Action" for buttons, matching other extension types.
> Change "Effect" to "Action" in Page Editor for buttons

- .github/workflows/ci.yml
- tsconfig.json
… since Codacy is hit or miss: https://github.com/pixiebrix/pixiebrix-extension/pull/1241#pullrequestreview-746068548
And also because annotations always appear immediately.
Annotation example:
> Restore GitHub Actions annotations

- src/background/dataStore.ts
- src/background/logging.ts
- src/background/telemetry.ts
- src/chrome.ts
- src/services/registry.ts
Fixes #1267 
- Fixes type signatures of readStorage and readStorageWithMigration (the default, if provided, must be a valid value to store)
- Fixes form of the browser.storage.local.get to work on chrome
> #1267: fix read storage calls

- src/auth/token.ts
- src/background/auth.ts
- src/background/dataStore.ts
- src/background/logging.ts
- src/background/telemetry.ts
- src/chrome.ts
- src/options/loader.ts
- src/services/baseService.ts
- src/services/registry.ts
> #1271: fix manual access to persisted redux state

- src/background/executor.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/blocks/effects/redirectPage.ts
- src/devTools/editor/panes/NoExtensionsPane.tsx
- src/devTools/editor/panes/SupportWidget.tsx
- src/devTools/editor/panes/WelcomePane.tsx
- src/devTools/editor/tabs/AvailabilityTab.tsx
- src/devTools/editor/tabs/contextMenu/AvailabilityTab.tsx
As I migrate the lifted functions to the messenger, I might refactor some code to skip the messenger altogether where possible. 
Related:
- https://github.com/pixiebrix/pixiebrix-extension/pull/907
> Use real links wherever possible + use Messenger for `sendTab`

- src/blocks/readers/jquery.ts
- src/blocks/transformers/jquery/JQueryReader.ts
- src/blocks/transformers/registerTransformers.ts
- src/devTools/editor/fields/Fields.tsx
- src/headers.ts
Part of #1321
- Exposes a `@pixiebrix/jquery-reader` block which can be used as a normal block
- Pull request in the app: https://github.com/pixiebrix/pixiebrix-app/compare/feature/1321-jquery-header?expand=1
> #1321: jquery block

- package-lock.json
- package.json
- src/blocks/transformers/modalForm/ModalForm.tsx
- src/blocks/transformers/modalForm/formTypes.ts
- src/blocks/transformers/modalForm/modal.tsx
- src/contentScript.ts
- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/contentScript/modalForms.ts
- Use new messenger to replace some raw sendMessage calls
- The code was summarily tested, the modal opened and the next step was executed
- the frame SRC includes the whole opener information: frame **and** tab, so no extra `whoAmI` call
- https://github.com/pixiebrix/webext-messenger/pull/15
> Use Messenger for ModalForm

- src/blocks/readers/ElementReader.ts
- src/blocks/readers/ImageExifReader.ts
- src/blocks/readers/ImageReader.ts
- src/blocks/readers/PageMetadataReader.ts
- src/blocks/readers/PageSemanticReader.ts
- src/blocks/readers/meta.ts
- src/blocks/transformers/FormData.ts
- src/blocks/transformers/detect.ts
- src/blocks/transformers/encode.ts
- src/blocks/transformers/httpGet.ts
- src/blocks/transformers/jquery/JQueryReader.ts
- src/blocks/transformers/mapping.ts
- src/blocks/transformers/modalForm/modal.tsx
- src/blocks/transformers/parseUrl.ts
- src/blocks/transformers/prompt.ts
- src/blocks/transformers/regex.ts
- src/blocks/transformers/remoteMethod.ts
- src/blocks/transformers/template.ts
- src/blocks/transformers/url.ts
- src/components/formBuilder/formBuilderHelpers.ts
- src/core.ts
- src/devTools/editor/sidebar/Footer.tsx
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/editHelpers.ts
- src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
- src/devTools/editor/tabs/effect/PreviewView.tsx
- src/utils.test.ts
- src/utils.ts
- Adds the brick name as a placeholder for step name
- Generates a fresh default output key when adding a note
- Switches to the new block when adding a block
- Refactors out the helper method for generating fresh identifiers
- Support a feature flag for automatically toggling the beta checkbox
> #1325: default output keys

- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
- src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.module.scss
- src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
Quick fix to move the delete-node button back to a full button in the config panel rather that an X on each node.
> Page Editor - Move delete button back to step config panel

- src/components/fields/fieldUtils.ts
- src/components/fields/schemaFields/SchemaFieldContext.tsx
- src/components/fields/schemaFields/ServiceField.tsx
- src/devTools/editor/fields/devtoolFieldOverrides.tsx
- src/hooks/auth.ts
Part of #1320
- Adds support for bricks that accept alternative services ids
Out of Scope / TODO: 
- Clean up output keys generate when switching between auths
> #1320: add support bricks with integration alternatives

- src/actionPanel/ActionPanelApp.tsx
"Buttons" should not also have an underline
> Remove underline from Options button

- src/devTools/Panel.scss
- src/devTools/editor/sidebar/Sidebar.tsx
- Discussed in https://github.com/pixiebrix/pixiebrix-extension/pull/1330
Changes:
- drops extra border on the right of each extension
- restore hover state on logo
- drop rounded borders on logo to make its look more consistent
- drop some CSS left behind by an old PR
Hover:
> Improve styles of editor sidebar logo

- src/components/form/FieldTemplate.module.scss
- src/components/form/FieldTemplate.tsx
`BootstrapForm.Control.Feedback` shows an error message only if there's an element with class `is-invalid` next to it. This creates a not-so-obvious requirement for authoring widgets and makes the `FieldTemplate` depend on a widget implementation.
Making the login simpler giving the full responsibility of the errors to `FieldTemplate`.
> Show error message for custom widgets

- src/blocks/readers/frameworkReader.ts
- src/blocks/renderers/propertyTable.tsx
- src/blocks/transformers/component/ComponentReader.ts
- src/blocks/transformers/component/ComponentReaderOptions.tsx
- src/blocks/transformers/registerTransformers.ts
- src/contrib/editors.ts
- src/headers.ts
- #1321: Exposes a separate framework ComponentReader brick
- Adds support for passing a variable to the PropertyTable renderer
TODO:
> #1321: expose framework reader as a brick

- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
Part of #1421. In the switch to the DataTab, we lost the ability to view output data on the foundation (first node)
> #1421: fix off by one error in data panel

- src/components/brickModal/QuickAdd.tsx
- src/components/fields/schemaFields/ChildObjectField.tsx
- src/components/fields/schemaFields/ServiceField.tsx
- src/components/form/widgets/RemoteSelectWidget.tsx
- src/components/form/widgets/SelectWidget.tsx
- src/contrib/automationanywhere/BotOptions.tsx
- src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
- src/devTools/editor/tabs/editTab/useBrickRecommendations.ts
- src/utils.ts
Closes #1427: fixes inconsistent use of onChange in ServiceField
Fixes infinite re-render in  generating brick recommendations
TODO:
- RemoteSelectWidget is flaky. Sometimes it doesn't get values back, but is not showing an error message.  (Seen when testing the AA configuration options)
> #1427: fix ServiceField onChange; fix infinite re-render in generating recommendations

- src/devTools/editor/extensionPoints/actionPanel.tsx
- src/devTools/editor/extensionPoints/base.test.ts
- src/devTools/editor/extensionPoints/base.ts
- src/devTools/editor/extensionPoints/contextMenu.tsx
- src/devTools/editor/extensionPoints/menuItem.ts
- src/devTools/editor/extensionPoints/panel.ts
- src/devTools/editor/extensionPoints/trigger.tsx
- src/devTools/editor/tabs/effect/BlockPreview.tsx
- src/utils.test.ts
- src/utils.ts
Closes #1433
- Removes object entries that are `undefined` or `""` before passing them to PixieBrix
> #1433: don't pass empty values from Formik state to PixieBrix

- src/blocks/types.ts
- src/blocks/util.ts
- src/components/fields/schemaFields/propTypes.ts
- src/components/fields/schemaFields/widgets/ArrayWidget.tsx
- src/components/formBuilder/FormEditor.tsx
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/exampleBlockConfigs.ts
- src/devTools/editor/tabs/editTab/useBrickRecommendations.ts
- src/devTools/editor/tabs/effect/BlockConfiguration.tsx
> #1341: instantiate block configs with defaults

- src/components/form/FieldTemplate.module.scss
- src/components/form/FieldTemplate.tsx
Stretches the label to full height and keeps the text aligned to the top.
> #1408: Vertical align labels to top row of inputs

- src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.module.scss
Restore the full button text when below the bootstrap xl breakpoint for the columns (1200px)
> #1408: Show remove text on button below the column breakpoint

- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
This re-sets the default active tab when the active node changes, so that form nodes will show the preview data tab.
> Change active tab to preview for form builder nodes

- src/components/BrickIcon.tsx
- src/devTools/editor/tabs/editTab/EditTab.module.scss
- src/devTools/editor/tabs/editTab/EditTab.tsx
This makes brick icons that use basic font awesome icons inherit the node color scheme in the editor node layout. Customized SVG icons are unaffected and keep their branded color schemes.
> Add css class for fa icons in BrickIcon component

- src/blocks/transformers/modalForm/modal.tsx
1. Looking for z-index is slow
2. If our intent is to appear on top of everything, let's just go to the moon
2. z-index is not global, they have a [stacking context](https://bitsofco.de/how-z-index-works/#2establishanewstackingcontextwiththezindexproperty):
> #1368: Use the highest possible z-index without looking for it

- schemas/component.json
- schemas/effect.json
- schemas/extensionPoint.json
- schemas/reader.json
- schemas/recipe.json
- schemas/renderer.json
- schemas/service.json
- src/blocks/combinators.ts
- src/blocks/readers/factory.ts
- src/blocks/transformers/blockFactory.ts
- src/core.ts
- src/devTools/editor/extensionPoints/actionPanel.tsx
- src/devTools/editor/extensionPoints/base.ts
- src/devTools/editor/extensionPoints/contextMenu.tsx
- src/devTools/editor/extensionPoints/elementConfig.ts
- src/devTools/editor/extensionPoints/menuItem.ts
- src/devTools/editor/extensionPoints/panel.ts
- src/devTools/editor/extensionPoints/trigger.tsx
- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
- src/extensionPoints/actionPanelExtension.ts
- src/extensionPoints/contextMenu.ts
- src/extensionPoints/menuItemExtension.ts
- src/extensionPoints/panelExtension.ts
- src/extensionPoints/triggerExtension.ts
- src/extensionPoints/types.ts
- src/options/slices.ts
- src/tests/factories.ts
- src/types/definitions.ts
> #1506: apiVersion 2 with explicit data flow

- src/background/browserAction.ts
- src/layout/ErrorModal.tsx
- src/utils.ts
- Replaces https://github.com/pixiebrix/pixiebrix-extension/pull/1395
- Fixes #1334 
https://user-images.githubusercontent.com/1402241/134939098-668a8509-ba15-40d2-a101-9ce7975e5e35.mov
> #1334: Don't show error when the user clicks on browserAction

- src/devTools/editor/hooks/useExtensionTrace.ts
- src/devTools/editor/slices/runtimeSelectors.ts
- src/devTools/editor/slices/runtimeSlice.ts
- src/telemetry/trace.ts
Solves trace data update for #1472 
Formik errors not working because the the error  gets set, but then theres a follow on render event where the error is no longer in there. Will have to look into it
> #1472: fix race condition in trace update check

- src/components/AsyncIcon.tsx
- src/components/BrickIcon.tsx
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
- src/types/contract.ts
This fixes https://github.com/pixiebrix/pixiebrix-extension/issues/1414 specifically.
Future work:
- have a `<AsyncIcon>` component that can be used exactly like `FontAwesomeIcon`, except it's async. It could also support other libraries
- replace every icon import with `<AsyncIcon>` so that no icons are ever bundled (+ lint rule to never import `@fortawesome/*` directly)
I'm not sure I will be able to make those changes by the release since I'm preparing to move tomorrow.
https://user-images.githubusercontent.com/1402241/135047425-01288030-4ffd-4526-bbdb-2ce7e3f6b370.mov
> #1414: Add `AsyncIcon` component to load single FontAwesome icon

- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
This adds the output key to the Output tab data on the data panel. This makes the copy functionality on the json tree include the output key when copying a value.
> #1408: Add output key to output in data panel so that the copy label includes the output key

- src/blocks/combinators.ts
- src/blocks/readers/ArrayCompositeReader.ts
- src/blocks/readers/BlankReader.ts
- src/blocks/readers/CompositeReader.ts
- src/blocks/readers/PageMetadataReader.ts
- src/blocks/readers/PageSemanticReader.ts
- src/blocks/readers/meta.ts
- src/blocks/transformers/blockFactory.ts
- src/blocks/transformers/component/ComponentReader.ts
- src/blocks/transformers/jquery/JQueryReader.ts
- src/blocks/types.ts
- src/core.ts
- src/devTools/editor/tabs/effect/BlockConfiguration.tsx
- src/types.ts
Closes #1466
- Adds a `rootMode` property on the BlockConfiguration. Can be used to force the root element passed in for BlockOptions to be `document` instead of inherited from the pipeline/foundation
- Adds a `isRootAware` method to IBlock for native blocks to declare whether or not they use the root from BlockOptions
- Shows a rootMode configuration option in the PageEditor where applicable
> #1466: rootMode on BlockConfiguration

- src/components/fields/schemaFields/ServiceField.tsx
- src/contrib/RequireServiceConfig.tsx
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/services/serviceUtils.ts
Closes #1451 
Future work / Out of Scope: 
- Share dependencies when possible for the `get` and `http` bricks which don't declare which services they use
- Handle rapidapi cases where multiple different services are using the same integration
> #1451: cleanup unused service dependency entries

- src/devTools/editor/tabs/effect/BlockPreview.tsx
Similar to #1526 , this adds the output key to the data tree in the preview tab of the data panel, and makes the labels "copyable".
> UI Quick Hit: Add output key to preview data tree and make it copyable

- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
- src/devTools/editor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
- src/devTools/editor/tabs/effect/BlockPreview.tsx
Related to #1540 
This makes certain nodes expand by default in the data panel so they don't need to be clicked every time the panel refreshes/changes.
> UI Quick Hit: Expand certain nodes in the data panel by default

- src/components/brickModal/BrickModal.tsx
- src/devTools/editor/components/Centered.tsx
- src/devTools/editor/extensionPoints/actionPanel.tsx
- src/devTools/editor/extensionPoints/contextMenu.tsx
- src/devTools/editor/extensionPoints/trigger.tsx
- src/devTools/editor/panes/insert/GenericInsertPane.module.scss
- src/devTools/editor/panes/insert/GenericInsertPane.tsx
- src/devTools/editor/panes/insert/InsertMenuItemPane.tsx
- src/devTools/editor/panes/insert/InsertPanelPane.tsx
This updates some button text and tweaks styling in the add/insert extension panels in page editor.
**Generic Add New Panel:**
**Insert Button:**
**Insert Panel:**
> #989: Page editor add/insert panel updates

- src/blocks/combinators.ts
- src/components/formBuilder/FormBuilder.tsx
- src/components/formBuilder/FormPreview.test.tsx
- src/components/formBuilder/FormPreview.tsx
- src/components/formBuilder/__snapshots__/FormPreview.test.tsx.snap
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
- src/telemetry/trace.ts
Implement warnings when stale data is detected in block pipeline configs.
This warning is shown on the `Context` and `Rendered` tabs:
This warning is shown on the `Output` tab:
> #1323: Stale data warnings on data tab

- src/options/pages/installed/InstalledPage.test.tsx
- src/options/pages/installed/InstalledPage.tsx
> #1547 Do not show active brick cards when there's no Resolved extensions

- package-lock.json
- package.json
- src/runtime/pipelineTests/pipelineTestHelpers.ts
- src/runtime/pipelineTests/trace.test.ts
- src/runtime/reducePipeline.ts
- src/telemetry/trace.ts
- src/tests/ConsoleLogger.ts
Closes #1767 
- Adds test cases for tracing calls in the runtime
- Fixes bug introduced in runtime where trace records weren't being created because run/block instance data wasn't being passed in correctly
TODO (out of scope)
- Figure out how to type the mocks to avoid casting to any
> #1767: fix tracing; add tests

- src/devTools/editor/tabs/trigger/TriggerConfiguration.tsx
Closes #1720 
Our field types don't protect against unexpected property names
> #1720: use element selectMode for trigger

- src/blocks/transformers/blockFactory.ts
- src/runtime/mapArgs.test.ts
- src/runtime/pipelineTests/component.test.ts
- src/runtime/pipelineTests/serviceContext.test.ts
- src/runtime/pipelineTests/templateEngine.test.ts
- Adds test for component runtime isolation
- Adds tests to demonstrate handlebars behavior (handlebars doesn't work with v2/v3 of the runtime because variables can't be prefixed with @, because handlebars tries to treat those as "data" variables
> Additional engine/template tests

- src/runtime/pipelineTests/implicitDataFlow.test.ts
- src/runtime/pipelineTests/pipelineTestHelpers.ts
- src/runtime/reducePipeline.ts
Closes #1801
Fixes runtime "v1" bug where the output of the previous block was not being included in the context of the next block
> #1801: include previous output in context of next step

- src/styles.css
Tiny change, but I thought highlighting the margin is confusing because it's not part of the target. Feel free to close if you disagree
> Don't highlight margin in overlay

- src/blocks/effects/forms.ts
- Closes #1751
- moves `querySelector` and warnings to the setValue function to avoid duplication
- handles a selection of multiple elements as a single entity — if `name` was used.
Using the name `size` and value `M` the right radio will be `checked`:
```html
<input type="radio" name="size" value="S">
<input type="radio" name="size" value="M">
<input type="radio" name="size" value="L">
```
When the exact value isn't found, the previous behavior will be used (`value` is set as a boolean on all the matching elements)
- adds support for `select` elements by value
Tested on https://pixiebrix.github.io/playground/example/
> #1751: Allow setting a specific value of boxes

- src/core.ts
- src/options/pages/brickEditor/referenceTab/BlockResult.tsx
- src/options/pages/installed/ActiveBricksCard.tsx
- src/options/pages/marketplace/ActivateBlueprintPage.tsx
- src/options/pages/marketplace/ActivateWizard.tsx
- src/options/slices.ts
- src/pages/marketplace/MarketplacePage.tsx
Closes #1687, and depends on https://github.com/pixiebrix/pixiebrix-app/pull/781
This adds Team sections to the Active Bricks page that further group Active Bricks by their respective teams, or by Public Marketplace if not associated with a team.
> #1687 group active marketplace bricks by team

- src/actionPanel/DefaultActionPanel.test.tsx
- src/actionPanel/DefaultActionPanel.tsx
- src/messaging/external.ts
- src/options/pages/deployments/DeploymentBanner.tsx
- src/options/pages/marketplace/ActivateBlueprintPage.tsx
- src/pages/marketplace/useInstall.ts
- Removes remaining references to the Templates screen that doesn't exist anymore. (There's only the My Blueprints page now)
TODO:
> #1849: remove straggling references to templates page

- src/devTools/editor/ElementWizard.tsx
- src/devTools/editor/panes/EditorPane.tsx
- src/devTools/editor/panes/save/SaveExtensionWizard.test.tsx
- src/devTools/editor/panes/save/SaveExtensionWizard.tsx
- src/devTools/editor/panes/save/savingExtensionSelectors.ts
- src/devTools/editor/panes/save/savingExtensionSlice.ts
- src/devTools/editor/panes/save/useSavingWizard.test.tsx
- src/devTools/editor/panes/save/useSavingWizard.ts
- src/devTools/editor/toolbar/ActionToolbar.tsx
Closes #1653 
Formik prevents submitting the form with validation errors. We want to allow this. Saving the extension without involving Formik at all.
> #1653 Allow saving an extension with errors

- .github/workflows/rainforestqa.yml
Closes #1773 
- Cancel any existing runs in Rainforest QA
- Reset test accounts before run
> #1773: reset QA data before running rainforest

- src/blocks/effects/event.ts
> #1869: Dispatch non-jQuery events in `@pixiebrix/dom/trigger-event`

- .storybook/main.js
- package.json
- src/components/AsyncButton.tsx
- src/components/fields/schemaFields/FieldRuntimeContext.ts
- src/components/fields/schemaFields/SchemaField.tsx
- src/devTools/editor/hooks/useApiVersionAtLeast.tsx
- src/layout/Page.stories.tsx
- src/options/pages/marketplace/ActivateWizard.tsx
- src/options/pages/marketplace/OptionsBody.stories.tsx
- src/options/pages/marketplace/OptionsBody.test.tsx
- src/options/pages/marketplace/OptionsBody.tsx
- src/options/pages/marketplace/__snapshots__/OptionsBody.test.tsx.snap
- src/options/pages/services/ServiceEditorModal.stories.tsx
- src/options/pages/services/ServiceEditorModal.test.tsx
- src/options/pages/services/ServiceEditorModal.tsx
- src/options/pages/services/__snapshots__/ServiceEditorModal.test.tsx.snap
- src/types.ts
- src/utils.test.ts
- src/utils.ts
- The error is caused by SchemaField being used in a couple places where there's no `apiVersion` on the form: the ServiceEditorModal and the OptionsBody (for configuring blueprint options during install)
- Adds a FieldRuntimeContext for passing apiVersion down to uses of `useApiVersionAtLeast`
- Modifies useApiVersionAtLeast to check the version from FieldRuntimeContext. But it prefers the version from `apiVersion` on the form root
- Removes some inaccurate documentation from the OptionsBody card
- Closes #1878 
TODO: 
Things I couldn't quite get working but aren't important right now:
- `?loadAsText` query string with Jest. (Fine for now since the tests aren't over the authentication section which is where expressions are allowed
- In Storybook the …
> #1878: schema field fixes for integrations page and activation wizard

- package-lock.json
- package.json
- src/blocks/effects/attachAutocomplete.ts
- src/blocks/effects/registerEffects.ts
- src/headers.ts
- Defines a brick for attaching an autocomplete input (useful for providing suggestions based on an API call, or acting as documentation for users)
Out of scope:
- Get font style working on dark themed sites
> 527: effect to attach an autocomplete to an input

- src/devTools/editor/panes/save/saveHelpers.test.ts
- src/devTools/editor/panes/save/saveHelpers.ts
- src/runtime/brickYaml.test.ts
- src/runtime/brickYaml.ts
Fixes #1871 
`sharing` is a valid part of a recipe object, hence removing it only on the serialization phase.
> #1871 metadata.sharing section is being saved on server when performing "Update Blueprint"

- src/components/fields/schemaFields/fieldInputMode.ts
- src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
- src/core.ts
- src/runtime/brickYaml.test.ts
- src/runtime/brickYaml.ts
- src/runtime/mapArgs.test.ts
- src/runtime/mapArgs.ts
- src/runtime/pipelineTests/pipelineExpression.test.ts
- src/runtime/pipelineTests/pipelineTestHelpers.ts
Closes: #1924
Adds support for `!pipeline` expressions in YAML files and argument rendering
The !pipeline tag acts as a barrier to rendering so that the brick can make subsequent calls to reducePipeline
> #1922: support for pipeline expressions

- src/components/fields/schemaFields/widgets/ArrayWidget.tsx
- src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
- src/components/form/FieldTemplate.tsx
- src/devTools/editor/fields/ApiVersionField.tsx
- src/devTools/editor/panes/EditorPane.tsx
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
- src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
- src/devTools/editor/tabs/effect/BlockConfiguration.tsx
Fixes #1860 
The biggest change here is to changer our Formik setup so that we're validating inputs on blur events instead of on change events. This was, by a long shot, the most effective change I made that helped typing speed in inputs in dev builds of the page editor. I also memo-ized a few components and tried to make sure that their props were being memo-ized properly.
> #1860: Validate on blur and memoize some things

- src/background/devtools/protocol.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/background/util.ts
- src/contentScript/messenger/api.ts
- src/devTools/context.ts
- src/devTools/editor/hooks/useRemove.ts
- src/devTools/editor/panes/insert/GenericInsertPane.tsx
After a messenger refactor+cooldown, I'm back to porting the last bits of communication to it.
- CHECK_TARGET_PERMISSIONS: works
- INJECT_SCRIPT: works
- SHOW_BROWSER_ACTION_PANEL: replaced by existing method, works
- UNINSTALL_ACTION_PANEL_PANEL: replaced by existing method, works
> Use Messenger from devTools -> background communication

- src/layout/Footer.tsx
Adds version number to the footer so you don't have to check app.pixiebrix.com to see what version someone is running during remote debugging sessions
> Add version number to footer

- src/blocks/readers/frameworkReader.ts
- src/blocks/transformers/component/ComponentReader.ts
- src/devTools/editor/extensionPoints/contextMenu.tsx
- src/devTools/editor/tabs/contextMenu/ContextMenuConfiguration.tsx
- src/extensionPoints/contextMenu.ts
- src/pageScript/protocol.ts
Closes #1947 
- Adds a rootMode field to contextMenu definitions
- Support passing a blank selector for component reader (to use the root)
> #1947: support passing event target for context menu

- src/components/fields/schemaFields/SchemaField.test.tsx
- src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
- src/components/formBuilder/FormEditor.test.tsx
- src/devTools/editor/tabs/effect/v3/__snapshots__/BlockConfiguration.test.tsx.snap
- src/tests/formHelpers.tsx
Closes #1861 
This sets up simple toggle cases for field toggles. These will be fleshed out and more cases will be added once we have more smart behavior around inferring template type, preserving current input value when toggling, etc.
> #1861: SchemaField data type toggle tests

- src/components/form/FieldTemplate.tsx
The check is bad because it also triggers for memoized React components
I've updated the testing wiki with how to avoid the problem this was originally checking: https://github.com/pixiebrix/pixiebrix-extension/wiki/Unit-tests#mocking-a-single-method-in-a-module
> #1986: remove incorrect check for plain objects being passed to field

- package.json
I think it makes sense to set a starting page when running the extension via `web-ext run`. 
I set https://pixiebrix.github.io/playground/ because it's lightweight and hopefully pushes us to extend the project with more pages, like the ones listed in https://github.com/pixiebrix/playground/issues
> Open an example page on `web-ext run`

- jest.config.json
- package-lock.json
- package.json
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/contentScript.ts
- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/devTools/getSelectedElement.ts
- src/devTools/utils.ts
- src/layout/Footer.tsx
- tsconfig.json
This is part of the effort to make `browser` types consistent and reliable. The `window.browser` type is defined due to a sub-dependency (so the build passed) but the global does **not** exist in Chrome, it only worked due to some patching.
This PR drops that patch and enforces usage via `import`
- https://github.com/pixiebrix/webext-messenger/releases/tag/v0.14.1
- https://github.com/pixiebrix/webext-messenger/pull/44
- https://github.com/pixiebrix/pixiebrix-extension/pull/1763
- https://github.com/fregante/webext-polyfill-kinda/issues/2
> Remove temporary `browser` global and forbid it

- webpack.config.js
This setting makes webpack not watch the node_modules folder, so if you change files in it or install updates, you'll have to restart the `watch` script.
I'm not sure why this was enabled, but it doesn't match the comment that precedes it:  https://webpack.js.org/configuration/watch/#saving-in-webstorm
> Drop webpack node_modules exclusion

- src/core.ts
- src/runtime/brickYaml.test.ts
- src/runtime/brickYaml.ts
- src/runtime/mapArgs.test.ts
- src/runtime/mapArgs.ts
- src/runtime/pipelineTests/deferExpression.test.ts
- src/runtime/pipelineTests/pipelineTestHelpers.ts
Closes #2010
- This adds support for a `!defer` expression to the runtime. Config/mappings underneath the expression is left as-is
- @BALEHOK See the [deferBlock](http://github.com/pixiebrix/pixiebrix-extension/blob/7d1c1df7de6602c578c31298d0d240482b7aa695/src/runtime/pipelineTests/pipelineTestHelpers.ts#L132-L132) tests to see how this might be used in our document renderer for repeated elements
> #2010: add `!defer` expression

- src/components/fields/schemaFields/SchemaField.test.tsx
- src/components/fields/schemaFields/SchemaFieldContext.tsx
Fixes #2008 
In page editor v2, When a config schema field allows multiple types, we need to give priority to text input if `text` is included in the types
> #2008: Show text input for v2 bricks if the oneOf schema includes text

- __mocks__/fit-textarea.js
- jest.config.json
- package-lock.json
- package.json
- src/components/fields/schemaFields/SchemaField.test.tsx
- src/components/fields/schemaFields/widgets/TextWidget.tsx
- src/components/formBuilder/__snapshots__/FormEditor.test.tsx.snap
- src/components/jsonTree/JsonTree.tsx
- src/devTools/editor/tabs/effect/v1/__snapshots__/BlockConfiguration.test.tsx.snap
- src/devTools/editor/tabs/effect/v3/__snapshots__/BlockConfiguration.test.tsx.snap
- src/options/pages/marketplace/__snapshots__/OptionsBody.test.tsx.snap
Closes #1714.
This uses @fregante 's `fit-textarea` library to make our `TextWidget` component expand and allow multiple lines.
> #1714: Support multi-line text inputs

- jest.config.json
- package-lock.json
- package.json
- schemas/reader.json
- src/Globals.d.ts
- src/blocks/available.test.ts
- src/blocks/available.ts
- src/blocks/effects/reactivate.ts
- src/blocks/effects/registerEffects.ts
- src/blocks/types.ts
- src/devTools/editor/extensionPoints/base.ts
- src/extensionPoints/menuItemExtension.ts
- src/headers.ts
- src/helpers.ts
- src/tests/factories.ts
- Adds support for urlPatterns in isAvailable of extension points
- Closes #2048 
- Adds a ReactivateEffect which causes extensions to be reinstalled on the page. (Useful in conjunction with triggers for handling sites SPAs that don't issue navigation events)
> #2048: add support for url patterns in `isAvailable`

- .swcrc
While debugging another PR, I noticed that `swc` defaults to targeting `es5` and apparently no sourcemaps. This fixes both.
After this I'll also open a PR on the app
> Improve Jest compilation quality

- src/development/darkMode.js
- src/devtoolsPanel.tsx
- src/options.tsx
Here's a quick and dirty QoL improvement for devs living in the dark. It will not be included in the production builds.
Call `pbToggleDark()` in the console of the options or editor to toggle the mode in both pages. ~~A reload will happen automatically.~~ I'll document this in the wiki after merge.
I think that we can use this pattern for more developer tools in the future as well. At some point I'll add a dev-only "reload" button to the editor that will reload both the tab _and_ the editor in one go.
> Add opt-in dark mode for devs

- src/components/form/widgets/SelectWidget.tsx
Dropdowns always open downwards, even if there's no space below, so it causes the container to expand and it requires the user to scroll:
https://user-images.githubusercontent.com/1402241/145455350-0a0d3a9d-cd76-481e-ab53-72ae4b0bcfad.mov
Thankfully `react-select` also has an option to behave correctly (your OS also does the same): Dropdowns open downwards only if there's enough space.
This PR only covers this specific select widget I found, but it could probably be applied to most `react-select` instances
https://user-images.githubusercontent.com/1402241/145455544-e64d41f5-cf25-43ee-a4d9-7806ad910f4d.mov
> Keep select widget in viewport

- package-lock.json
- package.json
- schemas/extensionPoint.json
- src/components/quickBar/QuickBarApp.module.scss
- src/components/quickBar/QuickBarApp.tsx
- src/components/quickBar/quickBarRegistry.ts
- src/components/quickBar/quickBarRegistry.tsx
- src/devTools/editor/extensionPoints/adapter.ts
- src/devTools/editor/extensionPoints/base.ts
- src/devTools/editor/extensionPoints/elementConfig.ts
- src/devTools/editor/extensionPoints/quickBar.tsx
- src/devTools/editor/panes/insert/GenericInsertPane.tsx
- src/devTools/editor/sidebar/Sidebar.tsx
- src/devTools/editor/tabs/quickBar/QuickBarConfiguration.tsx
- src/extensionPoints/contextMenu.ts
- src/extensionPoints/factory.ts
- src/extensionPoints/quickBarExtension.ts
- src/extensionPoints/quickBarExtension.tsx
- src/extensionPoints/types.ts
- src/icons/Icon.tsx
_Experimental quick bar POC_
See the issue for more context, but the basics are: 1) placing buttons is sometimes hard, 2) the ergonomics of context menus are bad
Is currently behind the "page-editor-beta" feature flag
Not implemented yet / decisions:
> #1866: quick bar POC

- src/components/documentBuilder/DocumentBuilder.stories.tsx
- src/components/documentBuilder/documentTree.test.tsx
- src/components/documentBuilder/documentTree.tsx
- src/components/documentBuilder/render/BlockElement.tsx
- src/components/documentBuilder/render/ButtonElement.tsx
- src/components/documentBuilder/render/ListElement.tsx
- src/contentScript/pipelineProtocol.ts
- src/runtime/mapArgs.test.ts
- src/runtime/mapArgs.ts
- src/runtime/pipelineTests/deferExpression.test.ts
- src/runtime/pipelineTests/pipelineExpression.test.ts
- src/runtime/pipelineTests/pipelineTestHelpers.ts
NOTE: this is a PR against feature/1976-doc-builder-pipeline
- Changes the behavior of mapArgs to keep the defer and pipeline expressions. (Previously is returned the value). We have to keep the expressions around so that a block that receives the value knows what kind of value it is. (In the pipeline case, it would just receive an array)
- Removes the mapArgs step from BlockElement. This was breaking the use of outputKeys in the embedded pipeline. (The reducePipeline call in runRendererPipeline already handles calling mapArgs.)
> #1976: adjust behavior of pipeline and defer in mapargs

- src/components/formBuilder/FormEditor.tsx
- src/devTools/editor/fields/DocumentOptions.tsx
- src/devTools/editor/fields/FormModalOptions.tsx
- src/devTools/editor/fields/FormRendererOptions.tsx
Related to #1976 
Steps to reproduce an issue on Edit Page:
1. Select a Document Builder node
2. Select an element in Document Builder preview
3. Switch to a different node with Document Builder
Expected result: Document Builder for another node is shown.
Actual result: an error is thrown and displayed on the Edit Page.
> Document builder. Reset active element on changing a node

- package-lock.json
- package.json
- src/background.ts
- src/background/axiosFetch.ts
Extracted from:
- https://github.com/pixiebrix/pixiebrix-extension/pull/2107
Context:
- Axios is based on `XMLHttpRequest` but that's not available in Service Workers
- This PR adds an adapter that uses `fetch` instead of `XMLHttpRequest`, only in the background page
Warnings:
- The adapter I found isn't well-tested nor used much, it's likely that it's not feature-complete
- This isn't actually required until we switch to MV3, but we could still merge it just to test it
- Not really tested, I'm just floating the idea first
The alternative to merging this is to:
- hope that Axios adds `fetch` support: https://github.com/axios/axios/issues/1219
- "…This is work up to a year…"
- swap Axios with a raw `fetch` (which would be my preferred solution, but maybe Axios does something `fetch` …
> Use `fetch` inside Axios in the background

- src/components/BrickIcon.tsx
> #2165: Fix "SVG Marketplace Icons broken in brick selection modal"

- src/auth/token.ts
- src/background/auth.ts
- src/background/dataStore.ts
- src/background/logging.ts
- src/chrome.ts
We added this migration 3+ months ago:
- https://github.com/pixiebrix/pixiebrix-extension/pull/1192
Is it time to drop it or is it too soon?
> Drop `readStorageWithMigration`

- src/extensionPoints/panelExtension.ts
- src/runtime/pipelineTests/component.test.ts
Closes #2175 
Fixed bug where options were being passed as input to the extension and reader output wasn't being passed at all
TODO:
> #2175: fix panel input

- src/background/devtools/contract.ts
- src/background/devtools/external.ts
- src/background/devtools/internal.ts
- src/background/executor.ts
- src/devTools/protocol.ts
- src/devtoolsPanel.tsx
- src/hooks/events.ts
- I'm porting the last pieces of the dev tools to the messenger
- These listeners don't need to be in the background page at all
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/1277
The video shows:
1. Start with host with permissions
2. Change to host without permissions
3. Detect `activeTab` permission (unchanged)
https://user-images.githubusercontent.com/1402241/146656035-fbe6b926-4513-4c36-9dde-438b2aae8844.mov
> Listen to navigation events from dev tools (instead of the background)

- src/devtools.html
- src/devtools.ts
- webpack.config.js
Related:
- #2184 
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/910
This context is only needed to create the dev tools tab, it doesn't need/use the port and it doesn't need to weigh 1.22MB. This change brings it down to 0.34MB and drops the unused port overhead.
If [the "sidebar panel" is not working](https://github.com/pixiebrix/pixiebrix-extension/issues/910) for you either and is completely unused, we can drop/archive it and just leave one line of code in this file.
> Drop port connection and data viewer panel from `devtools.html`

- src/runtime/mapArgs.test.ts
- src/runtime/pathHelpers.ts
- src/script.ts
- src/utils.ts
> #2195: don't truncate deeply nested values when using `var` expression engine

- src/action.html
- src/action.scss
- src/actionPanel/ActionPanelApp.tsx
- src/actionPanel/ActionPanelTabs.tsx
- src/actionPanel/PanelBody.tsx
- src/blocks/renderers/customForm.tsx
- src/components/documentBuilder/documentTree.test.tsx
Should fix:
- https://www.loom.com/share/fccdd5c9e6d448bbaa1606bfc6929da7
I can't replicate that issue because it probably depends on the content, but this PR revisits the usage of `height: 100%` (i.e. drops most of it) and just lets flexbox takes care of "filling the container".
I think the pattern I found is simple and flexible:
1. Sets 100vh only on the page container
2. Set `full-height` on every child just like you would with `h-100`
3. If `full-height` has multiple children, only the last one fills the frame
- This automatically supports fixed-height headers
3. If you want an area to scroll, use `scrollable-area`
Also this PR resolves several other visual issues I found in the sidebar, mainly around spacing (or lack thereof) and extra borders.
Related:
- …
> Adjust sidebar sizing and spacing

- .eslintrc.js
[Our shared config](https://github.com/pixiebrix/eslint-config-pixiebrix/blob/main/index.js) is in JavaScript because it allows generating custom rules based on the folder and importing other configurations. It makes sense to allow the same here, also to simplify moving the config between these two locations.
> Use JavaScript for ESLint config

- src/actionPanel/native.tsx
- src/blocks/transformers/ephemeralForm/formTransformer.ts
Closes #2154 
Introduces an awaitable ensureActionPanel method which doesn't re-attach the sidebar/reload the existing panels
> #2154: fix sidebar show behavior for ephemeral forms

- src/blocks/effects/alert.ts
Add notifications support to the alert brick
I figured it made sense to make the existing brick more flexible vs. introducing a different brick that does conceptually the same thing. (Although the difference is whether or not the alert/notification pauses the execution)
> Add notifications support to alert brick

- src/options/pages/services/PrivateServicesCard.tsx
Minor tweaks to https://github.com/pixiebrix/pixiebrix-extension/pull/2167
- Use fixed width icon
- Hide non-applicable action instead of disabling. (Normally I believe in showing the item, but disabling it and explaining why to the user. But in this case I think it's better to just hide it?)
- Use solid edit icon to match other icons
> #1474: Use fixed width icon; hide non-applicable action

- src/background/capture.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/blocks/transformers/captureTab.ts
- src/blocks/transformers/registerTransformers.ts
- src/blocks/transformers/screenshotTab.ts
- src/headers.ts
Gotchas:
- The extension needs `activeTab` for it to work. It errors out if the extension has access but not activeTab. 
That means that even if PixieBrix has access to the page, the user still has to:
- Executing a action
- Executing a context menu item
- Executing a keyboard shortcut from the commands API
> #2231: tab screenshot brick

- src/background/executor.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/contentScript.ts
- src/contentScript/context.ts
- src/contentScript/messenger/api.ts
- src/contrib/uipath/embedApp.ts
- src/frame.html
- src/frame.ts
- webpack.config.js
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/2215#issuecomment-997925457
- Related to https://github.com/pixiebrix/pixiebrix-extension/pull/2106
Read these from top to bottom, as a sequence of events
<table>
<tr>
<th>CS
<th>Frame
<th>Background
<tr>
<td>Asks BG to message iframe with `nonce`
<td>
<td>
<tr>
<td>
<td>
<td>Waits for `nonce` iframe to register itself, via local polling
<tr>
<td>
<td>Registers itself with BG
<td>
<tr>
<td>
<td>
<td>Forwards brick to frame
<tr>
<td>
<td>Iframe handles brick and responds to BG
<td>
<tr>
<td>
<td>
<td>Forwards response to CS
</table>
<table>
<tr>
<th>CS
<th>Frame
<th>Background
<tr>
<td>Asks BG to wait for specific URL to appear
<td>
<td>
<tr>
<td>
<td>
<td>Waits for new URL to starts loading
<tr>
<td>
<td>
<td>Responds with …
> Drop `tabReady` from in-frame brick execution

- src/components/documentBuilder/createNewElement.test.ts
- src/components/documentBuilder/createNewElement.ts
- src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
- src/components/fields/schemaFields/v3/BasicSchemaField.test.tsx
- src/components/fields/schemaFields/v3/BasicSchemaField.tsx
- src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
- src/devTools/editor/tabs/effect/v3/__snapshots__/BlockConfiguration.test.tsx.snap
Related to #2180 
- Changing default button caption to "Action"
- Fixing automatic switching of the Schema Field mode to text in case of Select when text (or template) is not accepted.
> #2180 Document builder UI improvement

- jest.config.json
- scripts/webpack.scripts.js
- src/components/quickBar/QuickBarApp.tsx
- Closes #2190 
The shadow DOM correctly isolates the styles (you can see that the input field does not have LinkedIn’s border here) but somewhere the margins are being miscalculated.
I tried looking into it but was unable to determine if this is kbar’s fault or ours. I also used a simple `attachShadow` on the React DOM root (instead of react-shadow-root), but the result is the same.
https://user-images.githubusercontent.com/1402241/147736308-c9d0155a-03c0-4ef6-98fa-583821de1950.mov
> #2190: Isolate kbar style via Shadow DOM

- src/background/devtools/internal.ts
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/2186
It seems that this piece of code is duplicate. Without it, these sequences still work:
1. Open editor 
2. Click browser action
3. The CS is injected via click listener: 
https://github.com/pixiebrix/pixiebrix-extension/blob/325e7bd309060ed677f582244b2029396d9dfa5d/src/background/browserAction.ts#L33-L47
4. Refresh page
3. The CS is injected via webNavigation listener in the open devTools, via connectToFrame
https://github.com/pixiebrix/pixiebrix-extension/blob/325e7bd309060ed677f582244b2029396d9dfa5d/src/devTools/context.ts#L114-L128
5. Refresh page
6. Close and reopen editor
7. The CS is injected via useDevConnection — this will change once we fully drop the `port` in a future (WIP) PR …
> Drop unused attemptTemporaryAccess

- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/editorNodeConfigPanel/UnsupportedApiVersionV1.tsx
- src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
If an extension is loaded in the page editor, instead of showing config options, show this message now:
The only option left in is changing the extension name (and selecting api version for those on the internal feature flag). Reasoning here is that people may still want to rename an extension, like add `(v1)` on the name or something like that so it's easy to identify when they go to pull it up in the workshop, or so they know the difference in the page editor. Can easily remove the option to edit the name if we don't think it's needed.
> #2284 Show message and block editing in page editor for v1 bricks/extensions

- .eslintrc.js
- src/Globals.d.ts
- src/blocks/effects/attachAutocomplete.ts
- src/blocks/effects/confetti.ts
- src/blocks/effects/exportCsv.ts
- src/blocks/effects/tour.ts
- src/blocks/readers/ImageExifReader.ts
- src/blocks/readers/PageMetadataReader.ts
- src/blocks/readers/PageSemanticReader.ts
- src/blocks/readers/frameworkReader.ts
- src/blocks/registry.ts
- src/blocks/renderers/markdown.ts
- src/blocks/transformers/jq.ts
- src/blocks/transformers/jsonPath.ts
- src/blocks/transformers/parseCsv.ts
- src/blocks/transformers/parseDate.ts
- src/blocks/transformers/parseUrl.ts
- src/permissions/patterns.ts
- src/runtime/renderers.ts
Minor QoL improvement, also useful for dependency/bundle tracking in https://github.com/pixiebrix/pixiebrix-extension/issues/1623
You'd think that webpack would be able to name a named dependency, but it can't. I even tried messing with [chunkFileName](https://github.com/pixiebrix/pixiebrix-extension/blob/50d0d3a11877cd0702b15ed10a819d33b1532c8a/webpack.config.js#L240) but it did not recognize anything more than `[id]` and `[name]` (which defaults to `[id]`)
There are still a few unnamed chunks, but it's possible that they're created/`import()`ed inside a dependency.
> Always name dynamic imports

- .eslintrc.js
- package-lock.json
- package.json
- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
- webpack.config.js
I was looking for a way to fix https://github.com/pixiebrix/pixiebrix-extension/issues/1881 but noticed this section in the Rollbar plugin’s docs: https://github.com/thredup/rollbar-sourcemap-webpack-plugin#webpack-sourcemap-configuration
It appears that Rollbar already does try to access the linked sourcemaps, we only needed this plugin because our source code is offline… but https://github.com/pixiebrix/pixiebrix-extension/pull/1071 made them available publicly, so we shouldn't need it anymore.
Since the build occasionally fails due to it, there's more more reason to exclude it.
> #1881: Upload sourcemaps once (no Rollbar-specific upload needed)

- src/devTools/editor/ElementWizard.tsx
- src/devTools/editor/sidebar/DynamicEntry.tsx
- src/devTools/editor/sidebar/InstalledEntry.tsx
- src/devTools/editor/sidebar/Sidebar.tsx
- src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
- src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
- src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.module.scss
- src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
- src/devtoolsPanel.tsx
Visually this changes little, it only adds the `:hover` and `:active` states, but it reduces code and delegates more to Bootstrap for style and behavior consistency.
The ListGroup component could actually be used even further to manage the whole interface and skip onClick handlers too since they're all essentially nested [tabbed interfaces](https://react-bootstrap-v4.netlify.app/components/list-group/#tabbed-interfaces)
- extensions
- edit
- bricks
- logs
https://user-images.githubusercontent.com/1402241/148351991-8b097772-340b-4cbf-a7ed-fe1f3074d596.mov
https://user-images.githubusercontent.com/1402241/148351998-bfe735dd-0f6b-4911-ae89-55ac12e00325.mov
> Use existing components for brick and node lists in editor

- src/devTools/editor/sidebar/DynamicEntry.tsx
- src/devTools/editor/sidebar/Entry.module.scss
- src/devTools/editor/sidebar/Footer.module.scss
- src/devTools/editor/sidebar/InstalledEntry.tsx
- src/devTools/editor/sidebar/Sidebar.tsx
- the sidebar’s labels were not aligned as the icons have varying widths
- the extension names would wrap under the extension icon, together with the unsaved/hidden icons
- the "Show unavailable" label was not clickable, only the checkbox was
- the scope footer was so close to the corner that it was nearly clipped by the rounder corner
- align, color or drop the "Show unavailable" checkbox
- avoid red icon on blue background <img width="24" valign=top alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/148677913-e5709f9c-a28d-4314-a88c-d59a1a88dc7e.png">
- I was actually hoping to color the whole sidebar purple to improve its visual hierarchy, but purple unfortunately doesn't really fit with the rest of the color scheme in the editor. 
- @twschiller how come the …
> Align editor sidebar

- src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
- src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
- closes #2343
Technically this does not solve the error but just silences it by reverting to a plain `<div tabindex>`, which react-dom does not detect (this could change in the future I suppose)
The actual solution would be to move the up/down buttons outside the `<ListGroup.Item>`, but styling it correctly requires more (fragile) code than you'd probably like.
I think it's just better to implement draggability instead and revert this PR later.
> #2343: Avoid nesting `button` in editor

- src/devTools/editor/tabs/effect/v3/BlockConfiguration.tsx
- src/devTools/editor/tabs/effect/v3/__snapshots__/BlockConfiguration.test.tsx.snap
Closes #2307 
Adds this message:
> #2307 Add a 'no options' message when there are no Advanced Options to present for a brick

- src/background/browserAction.ts
- src/background/contextMenus.ts
- src/background/initBrowserCommands.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/background/util.ts
- src/components/ErrorBoundary.tsx
- src/devTools/Panel.tsx
- src/devTools/context.ts
- src/devTools/editor/panes/PermissionsPane.tsx
- src/utils/permissions.ts
- Followup to https://github.com/pixiebrix/pixiebrix-extension/pull/2317
Purpose of this PR is described in the review
Tested and working, on domains with and without permissions:
- browser action (even double click, no duplicates)
- context menu
- command (browser shortcut)
- attemptTemporaryAccess in the dev tools via activeTab
- a combination of the above
> #2366: Cleanup ensureContentScript and neighboring code

- .eslintrc.js
- package-lock.json
- package.json
- src/__mocks__/svgAsComponentMock.js
- src/background/__mocks__/protocol.ts
- src/background/axiosFetch.ts
- src/blocks/readers/jquery.ts
- src/blocks/types.ts
- src/components/documentBuilder/documentTree.test.tsx
- src/components/fields/schemaFields/SchemaField.test.tsx
- src/components/logViewer/LogToolbar.stories.tsx
- src/contrib/uipath/UiPathRobot.ts
- src/devTools/editor/hooks/useEditable.ts
- src/devTools/editor/tabs/effect/v1/BlockConfiguration.tsx
- src/devTools/editor/tabs/effect/v3/BlockConfiguration.tsx
- src/hooks/useBlockOptions.ts
- src/importAssets.d.ts
- src/nativeEditor/infer.ts
- src/registry/internal.ts
Related:
- https://github.com/pixiebrix/pixiebrix-app/pull/1009
- https://github.com/pixiebrix/eslint-config-pixiebrix/releases/tag/v0.14.0
> Move lint config to shared package

- package-lock.json
- package.json
- src/blocks/transformers/component/TableReader.ts
- src/blocks/transformers/registerTransformers.ts
- src/headers.ts
- src/helpers.ts
- src/utils/parseDomTable.test.ts
- src/utils/parseDomTable.ts
- For https://github.com/pixiebrix/pixiebrix-extension/issues/2314
Let me know what inputs/options you'd like. There's a lot of guessing at the moment but I suppose it could be replaced by plain options in the editor, for example:
- headers: 
- direction:
Possible improvements:
- is "direction" ok? There must be a better word for "in which axis are the records added?"
Next:
- in the brick itself you can add a simple "html parser" anywhere if necessary and then pass the `<table>` element to this function.
> #2314: Add table parser and brick

- src/background/logging.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/components/logViewer/useLogEntries.ts
- src/contentScript/lifecycle.ts
- src/devTools/editor/hooks/useExtensionTrace.ts
- src/devTools/editor/tabs/LogsTab.tsx
- src/devTools/editor/tabs/RunLogCard.tsx
- src/types.ts
Related to #2216 
1. Fetching logs. Making requests to IDB by index, applying the rest of the context filters in code. `extensionId` and `blueprintId` are the most commonly used filters, hence building indexes for these properties.
2. Waiting for the previous request for Logs or Traces to finish before making a new one.
3. Clearing all traces when DevTools gets closed (trace is bound to a block by `blockId` which exists only within app lifetime, i.e. on the next start of the Edit Page old traces will not get fetched).
> Logs and Traces performance

- src/blocks/effects/hide.ts
Adds a default for the mode prop of the Hide brick so the Page Editor shows as a select widget instead of omit by default
> Add default for mode prop of hide brick

- src/nativeEditor/infer.test.tsx
Attempting to reproduce behavior where inference doesn't find good selectors. 
Seems to be working on the small scale, I'll have to reproduce on a live site and try to figure out what's difference
> Add additional selector inference tests

- src/blocks/effects/highlight.ts
- src/types.ts
Closes #2441 
NOTE: this is a backward incompatible change, but it's very unlikely it will impact anyone. If it does, the migration is to just set the brick context as "document" and not "inherit"
> #2441: make highlight brick root aware

- src/devTools/editor/tabs/editTab/EditTab.tsx
What does this PR do:
- Switches which feature flag the api version selector is behind to `"page-editor-developer"`. Now that v3 is out, no one should needs to use it but we might as well leave it in. 
Additional context:
- The extension points are being the "page-editor-beta" feature flag. So we can't use that one. Per the last release I actually enabled that flag for everyone... We should probably put each extension point behind a different flag
> Change runtime version field feature flag

- src/__mocks__/logging.ts
- src/auth/token.ts
- src/background/deployment.test.ts
- src/background/deployment.ts
- src/devTools/editor/panes/save/SavingExtensionModal.test.tsx
- src/devTools/editor/panes/save/saveHelpers.test.ts
- src/store/extensionsStorage.ts
- src/tests/factories.ts
- Closes #2492
- Closes #2493 
- Closes #2494 
TODO
Out of Scope
- Allow user to snooze deployment update for deployments requiring manual intervention
Follow-up Work
- Add more tests covering update logic (version numbers and update timestamps
> #2492: automatic deployment update enhancements/fixes

- src/extensionPoints/helpers.ts
- src/extensionPoints/triggerExtension.ts
- src/vendors/initialize.js
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/2471
Demo with the selector: `h2:lt(1000)`
https://user-images.githubusercontent.com/1402241/150931973-3ce562ca-43d2-4866-b506-3f719bcff0db.mov
> #2471: Enable jQuery selectors everywhere

- src/contentScript/lifecycle.ts
- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/core.ts
- src/devTools/editor/sidebar/InstalledEntry.tsx
- src/extensionPoints/triggerExtension.ts
- src/types.ts
Part of #2471 
- Remove extension from page prior to loading in page editor (to avoid repeat triggers)
- Document trigger watch mode code
Tested on menu items, side bar, and blur interval
> #2471: remove extension when loaded in page editor; document trigger watch

- src/components/fields/schemaFields/BasicSchemaField.tsx
- src/components/fields/schemaFields/WorkshopMessage.tsx
- src/components/fields/schemaFields/widgets/TextWidget.tsx
- src/components/fields/schemaFields/widgets/WorkshopMessageWidget.tsx
- src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
- src/contrib/google/sheets/FileWidget.tsx
- src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
- src/contrib/google/sheets/SheetServiceOptions.tsx
- src/contrib/google/sheets/TabField.tsx
- src/contrib/uipath/LocalProcessOptions.tsx
- src/contrib/uipath/ProcessOptions.tsx
- src/contrib/zapier/pushOptions.tsx
- src/devTools/editor/fields/DatabaseOptions.tsx
- src/devTools/editor/fields/SelectorSelectorField.tsx
Related to #2459 
This is a temporary fix so that the page editor no longer crashes when expression values are used in custom block options configs. Instead, we detect expression values and show an "edit in the workshop" message.
> #2459 Temporary workshop messages for custom block options fields

- src/contrib/google/sheets/TabField.tsx
- src/contrib/zapier/pushOptions.tsx
This fixes a bug with the implementation in #2517 where the widget only, without a fieldtemplate, was being shown in the zapier and sheets bricks
> #2459 Wrap WorkshopMessageWidget in FieldTemplate for Zapier and Sheets

- src/blocks/transformers/component/TableReader.ts
- src/blocks/transformers/registerTransformers.ts
- src/headers.ts
- src/utils/parseDomTable.test.ts
- src/utils/parseDomTable.ts
- closes https://github.com/pixiebrix/pixiebrix-extension/issues/2434
Tested on https://pbx.vercel.app/create-react-app/table/
Notes:
- I guess that the vast majority of tables on the internet are not labelled/captioned, so we should probably default to using the headers as key
To do:
> #2434: Add multiple-table reader

- src/core.ts
- src/hooks/auth.ts
- src/options/pages/services/ServicesEditor.tsx
- src/services/factory.ts
- src/types.ts
- src/types/contract.ts
- src/types/definitions.ts
- When user selects a service that uses OAuth2 authorization grant (currently Slack), opens an app authorization flow
- Shows the remote user-managed credential in the service selection dropdown
Corresponding app PR:
- https://github.com/pixiebrix/pixiebrix-app/pull/1112
Out of Scope (future PRs)
- Put the authorization grant services behind feature flag so general can't find them in the dropdown
- Trigger from activation wizard
> #2547: basic OAuth2 authorization grant flow

- src/extensionPoints/triggerExtension.ts
- src/nativeEditor/utils.ts
- src/script.ts
- src/vendors/initialize.js
- webpack.config.js
- Closes #725
I looked into using Sizzle but I figured it's probably not worth for you since stuff like `.css()` is more convenient than its native counterpart. So I went for the low-hanging fruit: jQuery Slim, which excludes animations/effects and Ajax.
> #725: Use jQuery Slim

- src/utils/selectionController.ts
- Fixes #2568
I could replicate the issue:
1. Open https://pbx.vercel.app/
2. Press cmd+k without selecting anything
Demo of this PR:
https://user-images.githubusercontent.com/1402241/152360030-c2b7d60a-1ae7-4746-95c4-bb358e6aaa7e.mov
> #2568: Make selectionController reliable when nothing is selected

- src/components/quickBar/QuickBarApp.tsx
- src/components/quickBar/quickBarRegistry.tsx
- Closes #2567
The documentation seems to suggest that the initial actions cannot be changed and indeed even if I set `this._actions` to an empty array they are not removed.
What do you think about this solution?
> #2567: Show custom QuickBar extensions on top

- src/devTools/editor/extensionPoints/trigger.tsx
- src/devTools/editor/tabs/trigger/TriggerConfiguration.tsx
- src/extensionPoints/triggerExtension.ts
Closes #2580 
This doesn't actually check if the tab is active not. For now we're using animation frame as a proxy for that
The caveat is that Chrome is allowed to pause/unload inactive tabs if it wants to. But this should be sufficient for the customer need
> #2580: option to run interval trigger on inactive tabs

- src/devTools/editor/tabs/trigger/TriggerConfiguration.tsx
- src/devTools/editor/toolbar/ReloadToolbar.tsx
- src/extensionPoints/triggerExtension.ts
Closes #2581 
Adds an "initialize" trigger, which fires on DOM attachment vs. appear
> #2581: add `initialize` trigger

- src/background/navigation.ts
- src/devTools/context.ts
- src/devTools/events.ts
- src/devTools/messenger/registration.ts
- src/devTools/protocol.ts
This should more or less restore the code to what it was before both PRs
- https://github.com/pixiebrix/pixiebrix-extension/pull/2596
- https://github.com/pixiebrix/pixiebrix-extension/pull/2426
- On every page **with access**:
- on load: webext-dynamic-content-scripts injects the CS
- on hash change: `background/navigation.ts` will notify the CS
- On every page, in the editor:
- on load: `devTools/protocol.ts` will emit a navigationEvent
- on hash change: `devTools/protocol.ts` will emit a navigationEvent
> Avoid duplicate HANDLE_NAVIGATE call

- package-lock.json
- package.json
- webpack.config.js
_Enjoy the silence._
The Messenger will no longer automatically log all of its operations to the console. If you want to see them, append `WEBEXT_MESSENGER_LOGGING=true` to your .env files **or** run build/watch as:
```js
WEBEXT_MESSENGER_LOGGING=true npm run build
WEBEXT_MESSENGER_LOGGING=true npm run watch
```
> Hide Messenger logging by default

- src/devTools/editor/sidebar/DynamicEntry.tsx
- src/devTools/editor/sidebar/InstalledEntry.tsx
- src/nativeEditor/dynamic.ts
- src/nativeEditor/selector.ts
- Follows #2507
This brings 2 changes:
- avoid showing a broken overlay (the black bar) on non-button extensions
- copy overlay feature to InstalledEntry as well
Notice the black bar appearing under "Action" on hover
> Avoid broken overlay on non-buttons

- src/devTools/editor/sidebar/DynamicEntry.tsx
- src/devTools/editor/sidebar/InstalledEntry.tsx
Improper assignment of Mouse events causes React to throw (`undefined` is allowed for optional event handlers, `false` is not).
> Fixing assignment of MouseEvent handlers

- .eslintrc.js
- __mocks__/connected-react-router.js
- __mocks__/fit-textarea.js
- __mocks__/react-redux.js
- __mocks__/react-toast-notifications.js
- src/__mocks__/browserMocks.ts
- src/__mocks__/svgAsComponentMock.js
Mocks and stories follow their own formats, so we can't enforce the regular rules on them (in fact they've always been disabled locally)
Side note: I think `filenames/match-exported` isn't worth it: https://github.com/pixiebrix/pixiebrix-extension/search?q=%22filenames%2Fmatch-exported%22
Maybe we should just enable it in the components folder
> Disable some lint rules on mocks and stories

- src/devTools/ErrorBanner.tsx
- src/devTools/context.ts
- Closes #627
- As mentioned in https://github.com/pixiebrix/pixiebrix-extension/pull/2617#issue-1125248180
This is mostly a DX issue but users could see this when the extension updates.
https://user-images.githubusercontent.com/1402241/152945787-f9abc259-6ae0-4e6d-bcac-cd588232f5dc.mov
> #627: Immediately detect when the context is invalidated

- src/action.html
- src/devtoolsPanel.html
- src/options.html
- src/options.scss
- src/permissionsPopup.html
- static/loadingScreen.css
- static/loadingScreen.js
- Closes #622
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/1004
https://user-images.githubusercontent.com/1402241/152931649-46ac310c-d698-447f-9bf5-82160cccf1da.mov
If the loading is quick enough, we don't need to show the message. This leads to a cleaner loading experience since there will be one fewer flash of intermediary content (which we already have too many)
https://user-images.githubusercontent.com/1402241/152931839-7455cd16-715c-4dd3-bb6d-1ba1256c15c3.mov
If loading takes long enough (FYI: dev builds always take longer) the message will still be shown, but faded in and centered
https://user-images.githubusercontent.com/1402241/152931709-aa701ec6-80b2-4574-9232-7683ed2cae2b.mov
> #622: Show first loading screen errors + center message

- src/devTools/editor/ElementWizard.tsx
- src/devTools/editor/hooks/useAddElement.ts
- src/devTools/editor/sidebar/Sidebar.tsx
- src/devTools/editor/tabs/editTab/EditTab.tsx
- src/devTools/editor/tabs/editTab/dataPanel/DataPanel.tsx
- src/devTools/editor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
- src/hooks/useFlags.ts
- src/layout/Sidebar.tsx
- src/options/App.tsx
- src/options/pages/installed/ExtensionGroup.tsx
- src/options/pages/installed/InstalledPage.test.tsx
- src/options/pages/installed/InstalledPage.tsx
- src/options/pages/installed/OnboardingPage.tsx
- src/options/pages/settings/AdvancedSettings.tsx
- src/options/pages/settings/SettingsPage.tsx
- src/options/pages/workshop/WorkshopPage.tsx
- src/pages/marketplace/MarketplacePage.tsx
- src/pages/marketplace/useInstall.ts
- src/services/requestErrorUtils.ts
Part of #2684 
We have some "anti"-flags for users on restricted enterprise accounts. This PR introduces a useFlags hook that consolidates the logic and properly handles loading/error state.
> #2684: introduce useFlags hook to consolidate flag/restriction logic

- src/auth/authTypes.ts
- src/auth/token.ts
- src/hooks/useFlags.ts
- src/services/api.ts
Part of #2684 
Uses the flags from local browser storage before the remote flags are loaded for the screen
> #2684: use flags from local browser storage before remote flags loaded

- src/hooks/useAuthorizationGrantFlow.ts
- src/options/pages/marketplace/AuthWidget.tsx
- src/options/pages/marketplace/ServicesBody.tsx
Part of #2575 
From the Activation Wizard, redirect to the Admin Console. This will force the set of services to load when the user goes back. Not a perfect UX, but good enough for initial OAuth2 release
> #2575: redirect to admin console from configure button

- src/extensionPoints/contextMenu.ts
- Fixes half of #2659
It appears that `run` is always preceded by `install` and both of them are calling the same `registerExtension`. Is it ok to drop `run` in this extension point?
https://github.com/pixiebrix/pixiebrix-extension/blob/5deb9710968fc19266c6016c5dbec3fd3c37f8ec/src/contentScript/lifecycle.ts#L73-L102
> #2659: Avoid duplicate registration in context menus

- package-lock.json
- package.json
- src/options/pages/settings/PermissionsSettings.tsx
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/1931
- Based on: 
- https://github.com/fregante/webext-additional-permissions/pull/12
- https://github.com/fregante/webext-additional-permissions/releases/tag/v2.3.0
- Possible future improvement, if the bug is verified:
While at first sight this may seem that _the user can no longer remove the permission from specific hosts_, this was never possible. Dropping an overlapping permission has always been a meaningless operation: `*://*/*` will still cover every website, whether explicitly in the list or not.
> #1931: Don't display overlapping permissions in the options page

- webpack.sharedConfig.js
Let's be honest, nobody is reading this while in `watch` mode. It's just noise. 
If we care about file size we should prioritize https://github.com/pixiebrix/pixiebrix-extension/issues/1623
This PR:
> Reduce watch script noise

- src/background/logging.ts
- src/core.ts
- src/telemetry/reportError.ts
Part of #2715 
Log page name (e.g., contentScript vs. options) with errors to collect more information about potentially invalid network calls
> #2715: log page name with errors

- static/loadingScreen.js
Related:
- https://github.com/pixiebrix/pixiebrix-extension/pull/2656
This PR:
- wraps the error message instead of overflowing the window (e.g.  in the sidebar)
- adds a reload button (useful in the editor, since the React button isn't available https://github.com/pixiebrix/pixiebrix-extension/issues/2377)
> Improve loading error experience

- src/devTools/editor/extensionPoints/elementConfig.ts
- src/devTools/editor/extensionPoints/quickBar.tsx
- src/devTools/editor/sidebar/Sidebar.tsx
- src/options/pages/marketplace/ActivateBody.tsx
- Clarifies user messaging around quick bar activation
- There's no "default" shortcut. While KBar's hotkey works on pages PixieBrix has access to, it doesn't work on pages on which PixieBrix is not already active
- Removes the beta flag from the Quick Bar
> Improve quick bar configuration information

- src/devTools/editor/sidebar/Sidebar.module.scss
Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/2704 probably
https://user-images.githubusercontent.com/1402241/154784765-6fd2cb33-4421-4c02-aab3-b704452e7cd6.mov
https://user-images.githubusercontent.com/1402241/154784770-a1c4a8a3-52ee-4fff-b8df-9f0b6e6a99bc.mov
> Fix height of editor sidebar collapsing animation

- src/telemetry/rollbar.ts
- Fixes #2789
Warning: untested
The idea is that `location.origin` does not have a trailing slash while the ENV does. Since the ENV is also used elsewhere, I'd rather not change it.
> #2789: Fix rollbar path transform

- src/devTools/editor/hooks/useCreate.ts
Notice how the saving progress is (unnecessarily) waiting for the permissions to be granted
https://user-images.githubusercontent.com/1402241/154786164-0b2dc3d3-a319-4aac-8bee-d19a1943a051.mov
The saving continues while the user confirms the permissions. This parallelizes the two actions (app saving, user confirmation).
This is fine because the result of the permission request isn't immediately used nor it is necessary.
https://user-images.githubusercontent.com/1402241/154786185-5d4feb9c-0993-4830-b0fe-d6f119113cf2.mov
> Continue saving while asking for permissions

- src/components/formBuilder/DescriptionField.tsx
- src/components/formBuilder/FormPreview.test.tsx
- src/components/formBuilder/__snapshots__/FormPreview.test.tsx.snap
- src/utils/safeMarkdown.ts
This static import caused `marked` to appear in every bundle even though we already used `import()` elsewhere, essentially loading it twice in some cases.
Please ensure:
- I'm using useAsyncState correctly
- that the extra element is fine
PR test status: It appears to work in the Editor form preview’s description
> Avoid duplicate `marked` import

- src/components/fields/schemaFields/widgets/ObjectWidget.tsx
- src/contrib/zapier/PushOptions.tsx
- src/options/pages/activateExtension/ServicesCard.tsx
- src/options/pages/marketplace/ServicesBody.tsx
- src/runtime/pathHelpers.test.ts
- src/runtime/pathHelpers.ts
- src/utils.test.ts
- src/utils.ts
Closes #2718 
Property keys support periods.
It is possible to set a variable with a property with a period (`@elements["a.b"]`), but this means we will not be able to use square brackets.
> #2718 Can't enter keys with periods into Object Entry in Page Editor

- src/options/pages/services/ServiceEditorModal.tsx
- src/validators/generic.ts
`ServiceEditorModal`, `buildYup` fails with an error.
1. The error started to appear after update of `schema-to-yup` #2732 
2. Before the update `buildYup` failed silently and validation schema was only partially built. For Automation Anywhere Control Room it had `required = true` for label but not for the config properties (like `username`).
3. Problem is that `buildYup` tries to "normalize" the required properties, i.e. sets the required attribute on a property itself rather than have it in the required array ([here](https://github.com/kristianmandrup/schema-to-yup/blob/master/src/yup-builder.js#L94)). I'm not sure why, but the schema produced by `$RefParser.dereference` is "frozen" and `buildYup` can't set the property required on `username`
> Unfreezing the service schema

- src/options/pages/settings/AdvancedSettings.module.scss
- src/options/pages/settings/AdvancedSettings.tsx
- src/options/pages/settings/SettingsPage.module.scss
- src/options/pages/settings/SettingsPage.tsx
Bootstrap’s column sizing isn't beneficial here and it causes the content to vary between too wide and too tight, even when there's plenty of space:
This applies to other option pages as well, like Workshop and its overflow, but I wanted the go-ahead before touching more pages.
Let's find a width that works best for the content and stick to it. It does not have to be the same across every page.
https://user-images.githubusercontent.com/1402241/154802310-3caacdfa-0e4f-4c62-ac86-052de8e0136d.mov
https://user-images.githubusercontent.com/1402241/154796174-12a1f31e-cdb6-44eb-b631-830e7b49ec01.mov
> Avoid wonky sizing of Settings page in Options

- .github/workflows/ci.yml
- .github/workflows/rainforestqa.yml
- .github/workflows/release.yaml
- package.json
- scripts/upload-extension.sh
- scripts/upload-sourcemaps.sh
- webpack.config.js
- Closes #2817 
Notable changes:
- I extracted the 2 the upload scripts to separate files to ensure readability (and IDE ShellCheck analysis)
- I extracted the SOURCE_MAP_URL_BASE creation to the CI workflow because it's used by both Webpack and the uploader
- I appended the Rollbar notification right after the sourcemap upload, which [should work](https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-now-delivers-strong-read-after-write-consistency-automatically-for-all-applications/)
> #2817: Unify source upload + notify Rollbar

- src/devTools/editor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
- Closes #2822
Updated behavior:
- Shows suggestions on `focus`, regardless of field content _(new)_
- Hides suggestions when one selection is picked (unchanged)
- Shows suggestions again when the content is modified (unchanged)
> #2822: Show `SelectorSelector` suggestions even if the field is empty

- src/options/pages/blueprints/installableUtils.ts
- src/options/pages/blueprints/useInstallableViewItems.tsx
Originally, type narrowing for an `Installable` involved checking for `_recipe` on a ResolvedExtension. While being a required field on `IExtension`, recipe can be `undefined`. This was causing undefined field errors on the Blueprints page.
This PR resolves this issue by changing the field used for type narrowing on an `Installable` from `_recipe` to `extensionPointId`.
> change Installable extension type narrowing to `extensionPointId`

- package-lock.json
- package.json
- src/background/logging.ts
- src/core.ts
- src/telemetry/reportError.ts
- src/telemetry/reportUncaughtErrors.ts
Changes:
- drop unnecessary `_reportError` wrapper (we no longer have any async calls in there) — this also re-unifies the logic that was currently half in the wrapper and half in the regular `reportError`
- replace inline `ErrorEvent` exclusion logic with explicit setting (this makes `reportUncaughtErrors`’s self-contained)
> Minor `reportError` cleanup

- src/options/pages/blueprints/listView/ListItem.module.scss
- src/options/pages/blueprints/listView/ListItem.tsx
> Fix Blueprints page shrinking with long items

- src/components/Loader.tsx
- src/options/pages/blueprints/BlueprintsPage.tsx
I noticed a very subtle bug due to [margin collapsing](https://stackoverflow.com/q/7742720/288906).
1. Notice the unnecessary scrollbar that briefly appears during the first loader. This appears regardless of the window height and probably causes similar issues elsewhere.
2. Notice the second loader on the left instead of being centered
https://user-images.githubusercontent.com/1402241/156134853-fa8e958f-c48d-46e8-8a40-f4c936848d55.mov
https://user-images.githubusercontent.com/1402241/156134843-aa29c283-7340-4e6f-81e4-385470d8c1e9.mov
> Fix Loader usage and subtle margin-collapsing bug

- src/options/pages/blueprints/BlueprintActions.tsx
- src/options/pages/blueprints/BlueprintsCard.tsx
- src/options/pages/blueprints/BlueprintsToolbar.tsx
- src/options/pages/blueprints/InstallableIcon.tsx
- src/options/pages/blueprints/Status.tsx
- src/options/pages/blueprints/blueprintsTypes.ts
- src/options/pages/blueprints/gridView/GridCard.module.scss
- src/options/pages/blueprints/gridView/GridCard.tsx
- src/options/pages/blueprints/gridView/GridView.module.scss
- src/options/pages/blueprints/gridView/GridView.tsx
- src/options/pages/blueprints/installableUtils.ts
- src/options/pages/blueprints/listView/ListItem.module.scss
- src/options/pages/blueprints/listView/ListItem.tsx
- src/options/pages/blueprints/useInstallableViewItems.tsx
- src/options/pages/blueprints/useInstallables.ts
Closes #2552 
These improvements aren't perfect, but they will have to do for now until we collect & distill additional feedback. Makes additional information hierarchy improvements to the Blueprints page:
- Boldens some of the font and icon colors to make blueprints appear more vivid
- Changes the "active" status from color info to color success -> and adds a checkmark icon
- Transforms the list view/grid view buttons into a button group to better communicate toggle-ability
- Shrinks and mutes the Sharing label and the Updated at labels, and moves them to the bottom of a Grid View card
- Addresses some inconsistent terminology: "Unisntalled" -> "Inactive", "Uninstall" -> "Deactivate", "Last modified" -> "Last Updated"
- Adds an in-progress default description for extensions that were …
> Blueprints page information hierarchy improvements

- src/options/pages/blueprints/useInstallableActions.ts
Some blueprint actions weren't working after consolidating extensions into a single blueprint. This fixes blueprint reactivate, deactivate, and view logs actions.
> Fix blueprint actions from consolidated blueprints change

- src/pageEditor/ElementWizard.module.scss
- src/utils/notify.tsx
I made a mistake in a commit before merging https://github.com/pixiebrix/pixiebrix-extension/pull/2836, the colon and space was not added + the error was appended even if it was not an error at all.
> Fix notification display

- src/blocks/transformers/component/TableReader.ts
- src/utils/parseDefinitionList.test.ts
- src/utils/parseDefinitionList.ts
- src/utils/parseDomTable.test.ts
- src/utils/parseDomTable.ts
- src/utils/requireSingleElement.ts
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2831
<table id="support-table">
<tr>
<th>
<th>Chrome
<th>Firefox
<tr>
<th>Coolness
<td>No
<td>Yes
</table>
<dl id="definitions">
<dt>Chrome</dt>
<dd>Google’s browser</dd>
<dt>Firefox</dt>
<dd>Mozilla’s browser</dd>
</dl>
Side note: refer to https://github.com/pixiebrix/pixiebrix-extension/issues/2882 for table output expectations
> Support DL tag in TableReader brick

- src/contentScript/nativeEditor/infer.test.tsx
- src/contentScript/nativeEditor/infer.ts
- Closes  #2899
This restores the previous null-check. The other PR as better logic to deal with length:
- https://github.com/pixiebrix/pixiebrix-extension/pull/2776#issuecomment-1056399114
> #2899: Avoid length-based filter in `inferSelectors`

- src/options/store.ts
- src/pageEditor/store.ts
- webpack.config.js
I believe this was asked on Slack a few months ago. With RKT being used more and more I think I've been seeing more messages in the console. This silences them by setting `DEV_REDUX_LOGGER=false` (prod builds are silent regardless)
> Allow disabling redux-logger via ENV

- src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
- src/contrib/google/sheets/append.ts
#2897 - This small changes might users who do not know that the Spreadsheet they're editing needs to have named headers
> Add documentation to Append to Google Sheets brick metadata

- src/background/executor.ts
- src/chrome.ts
- src/errors.ts
- Closes #2902
After the tab is closed, the timeout continues and then it throws a BusinessError.
https://user-images.githubusercontent.com/1402241/157635945-245d43c4-d567-450a-9d26-11507d7a9d78.mov
> #2902: Throw BusinessError on `runBrick` if tab is closed or has no access

- src/background/deployment.test.ts
- src/background/deployment.ts
- src/services/useDependency.ts
- Should close https://github.com/pixiebrix/pixiebrix-extension/issues/2925
I don't see any other references to `locator` and its services outside this function, that already don't go through the messenger.
This was probably code I left behind during my last Messenger migration PR
> Use Messenger for locator in useDependency

- src/components/documentBuilder/edit/ElementBlockEdit.tsx
- src/pageEditor/Panel.tsx
- src/pageEditor/hooks/useCreate.ts
- src/pageEditor/hooks/useRemove.ts
- src/pageEditor/hooks/useReset.ts
- src/pageEditor/panes/insert/useAddExisting.ts
- src/pageEditor/sidebar/DynamicEntry.tsx
- src/pageEditor/sidebar/InstalledEntry.tsx
- src/pageEditor/slices/sessionSelectors.ts
- src/pageEditor/slices/sessionSlice.ts
- src/pageEditor/store.ts
- src/pageEditor/tabs/editTab/useBlockPipelineActions.ts
MVP of #2924 
I want to get this PR out for 1.5.7 and then layer in more events in the 1.5.8 release
- Adds SessionStart/SessionEnd events
- Adds Open/Reset/Remove events
- Adds sessionId and extensionId to existing page editor telemetry 
Questions
- How do we feel about using useSelector? Should we introduce a helper hook (where the hook is connected to the Redux store)? That helper hook can have an option for whether or not extension should be reported with the event. (However, in some cases we have to manually provide the extension id if it hasn't been selected yet)
Out of Scope
- Need to report manually triggered runs
- Need to report run success/failure
> #2924: page editor session tracking MVP

- src/components/formBuilder/FormBuilder.test.tsx
- src/components/formBuilder/formBuilderHelpers.test.ts
- src/components/formBuilder/formBuilderHelpers.ts
- src/components/formBuilder/preview/FormPreviewSchemaField.tsx
Closes #2870 
With this PR the Dropdown will try to preserve created options when switching between regular and dropdown with labels.
More tests added.
> #2870 Map dropdown options. Tests

- src/layout/EnvironmentBanner.tsx
- src/options/App.tsx
I found it failing in the Admin app. Hope I get the meaning of the `extension` attribute right.
> removing auth dependency from env-banner

- src/contrib/google/sheets/append.ts
Arrays return true for `typeof foo === "object"` , so we need to use the more specific `Array.isArray()` check instead.
> Fix type check for append google sheet row

- src/options/pages/blueprints/BlueprintActions.tsx
- src/options/pages/blueprints/ListFilters.tsx
- src/options/pages/blueprints/installableUtils.ts
- src/options/pages/blueprints/useInstallableViewItems.tsx
This fixes #2992, which is actually not a problem of missing reactivate, but missing update:
1. fixes the "update" action not showing on blueprints in the blueprints page
2. hides "reactivate" ellipsis menu action for inactive blueprints
> #2992: fix blueprint update and reactivate

- src/options/pages/blueprints/useInstallableActions.ts
Closes #3007 
- Calls unwrap on the mutation result to throw the error
- The CSRF error from the issue is not a real error, was caused in part by my testing of https://github.com/pixiebrix/pixiebrix-extension/issues/3004
> #3007: throw on error deleting extension

- src/options/pages/blueprints/labels/LastUpdatedLabel.tsx
- src/options/pages/blueprints/labels/SharingLabel.tsx
Fixes:
```
Warning: [react-bootstrap] Specifying only the `"hover"` trigger limits the visibility of the overlay to just mouse users. Consider also including the `"focus"` trigger so that touch and keyboard only users can see the overlay as well.
```
"hover focus" is the default, it doesn't need to be set
> Avoid `trigger="hover"` on `OverlayTrigger`

- src/contrib/google/sheets/append.test.ts
- src/contrib/google/sheets/append.ts
---
- Closes #2560 
- Adds a rowValues alternative for passing multiple rows in one call
- Adds a `shape` property that defaults to "infer" to handle the corner case where the sheet has "header"/"value" as the only two column names. This property is not exposed in the page editor
- Does not change the Page Editor interface. If you are trying to pass multiple rows, you'd need to pass them as a variable
**Discussion**
- The JSON Schema could be re-written to be a combination of 4 oneOfs (one for each shape). That would let use avoid validateShape, but would complicate the schema
> #2560: support appending multiple rows to a Google Spreadsheet

- src/background/background.ts
- Close #3020 
As you found out, [the error is not used by the adapter](https://github.com/vespaiach/axios-fetch-adapter/blob/5fbe21087fbf10f266cff205e2647cd99e0d5260/index.js?rgh-link-date=2022-03-24T19%3A40%3A39Z#L50-L52). In theory [`fetch` only throws on Network errors](https://stackoverflow.com/a/61113372/288906), which I don’t think we can enrich, but in practice I see it throws on invalid URLs too, like `fetch("///")` (which throws a `TypeError`, but the adapter will only throw a network error.
I think we can drop the adapter for now, especially because there's no urgency to use it and hopefully Axios will eventually support it natively: This limitation is not exclusive to web extensions so I'm certain a better solution will surface sooner or later.
For reference, here's what that …
> Temporarily disable axios fetch adapter

- src/blocks/effects/getPageState.ts
- src/blocks/effects/pageState.ts
- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
- src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
- src/pageEditor/tabs/editTab/dataPanel/PageStateTab.tsx
Closes #2502 
A blueprint extension:
A non-blueprint extension:
An error:
> #2502 Data panel tab for page state observability

- src/contentScript/nativeEditor/infer.test.tsx
- src/contentScript/nativeEditor/infer.ts
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/2812
I changed the sorter to only prefer ID- and class-based selectors if they don't contain :nth-child
> #2812: Deprioritize :nth-child in selector dropdown

- src/services/api.ts
> #3063 Fixes updating a public blueprint in the Page Editor removes public sharing

- src/background/deployment.ts
- src/chrome.ts
- src/manifest.json
- src/services/apiClient.ts
- src/services/baseService.ts
- static/managedStorageSchema.json
- Closes #3064
I wasn't able to test this directly but I can confirm:
- Chrome loads the schema
- Chrome validates the schema
> #3064: Add managed storage to bootstrap PixieBrix link

- __mocks__/webext-messenger.js
- src/background/logging.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/contentScript/lifecycle.ts
- src/runtime/reducePipeline.ts
- src/store/extensionsSlice.ts
- src/telemetry/trace.ts
Closes #3101 
The implementation is not ideal. The traces and logs clean-up blocks the `reducePipeline`.
Alternatives:
1. Run the cleanup at the end of `reducePipeline`, select IDB entries by `runId` (although log entries do not have `runId`).
2. Clean the traces and debug logs when the DevTools start.
3. Do not write traces and debug logs if DevTools is not open.
> #3101 Page Editor crashes when traces/logs fill up

- src/errors.ts
- src/helpers.ts
- src/vendors/initialize.js
- Close #3021
I looked into wrapping the errors in jQuery itself, but:
- I couldn't find a public hook into its [error generator](https://cs.github.com/jquery/jquery/blob/2525cffc42934c0d5c7aa085bc45dd6a8282e840/src/selector.js#L148)
- if the selector is not user-provided, then we should not report BusinessErrors
For these reasons, I added this wrapper in `$safeFind`, which is presumably the only method we should use to handle user-provided selectors (+ `initialize.js`)
> #3021: Wrap invalid selector errors into BusinessErrors

- src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
* Re-order page state tab to immediately follow the context tab
* Only show the page state tab for get/set page state bricks
> Move page state tab and restrict to page state bricks

- src/components/jsonTree/JsonTree.tsx
> Fix the search input label width in the data panel

- src/blocks/effects/redirectPage.ts
- src/blocks/transformers/url.ts
- src/utils.test.ts
- src/utils.ts
- Closes #3031 
But I wonder why/when supporting both encodings would be beneficial. Even the native and modern `URL` constructor uses plus by default
> makeURL: Cleanup, test, and always default to `percent` space encoding

- src/auth/RequireAuth.tsx
- src/auth/token.ts
- src/background/deployment.ts
- src/errors.ts
- src/layout/Centered.tsx
- src/options/App.tsx
- src/options/pages/settings/AdvancedSettings.tsx
- src/services/api.ts
- src/utils/enrichAxiosErrors.ts
Closes #3056 
Closes #3036 
- Defaults requireLinked for RTK to `true`
- In RTK, clears auth state if the server responds with a 401.
- In RequireAuth, watches for the Token being lost (e.g., because the RTK error handler cleared the token) 
- In RequireAuth, doesn't clear existing auth on /api/me/
- In RequireAuth, waits to run /api/me/ query until the server because session-based state is inconsistent
- In RequireAuth and enrichBusinessRequestError check for the client being offline
Not in the PR:
- Does not handle ExtensionNotLinked in RequireAuth. That should only happen during a race condition with isLinked, because /api/me/ is only being called if the token is linked
Potential Improvements:
- If the user is offline, let the RequireAuth pass with the cached …
> #3056: force use of token auth for RTK queries,  fix RequireAuth checks, handle offline state

- src/background/requests.ts
- src/components/ErrorBoundary.tsx
- src/utils.test.ts
- src/utils.ts
- src/utils/enrichAxiosErrors.ts
Closes #3122 
- The bug was causing all request errors involving relative URLs to be reported as invalid scheme chrome-extension:
> #3122: fix use of baseUrl in assertHttpsUrl to fix request error enrichment

- src/background/deployment.test.ts
- src/background/deployment.ts
- static/managedStorageSchema.json
Closes #3111
- Changed primaryOrganizationId in managed storage to managedOrganizationId
- If the extension is not linked and managedOrganizationId is set in managed storage, opens the options page on heart beat (currently every 5 min)
> #3111: open managed extension automatically if unlinked

- src/extensionPoints/contextMenu.ts
- src/extensionPoints/menuItemExtension.ts
- src/extensionPoints/panelExtension.ts
- src/extensionPoints/quickBarExtension.tsx
- src/extensionPoints/sidebarExtension.ts
- src/extensionPoints/triggerExtension.ts
- src/extensionPoints/types.ts
- src/types.ts
- Follows #1080
Cycle:
- `@/types` <-> `@/extensionPoint/types`
Fix:
- move `ExtensionPoint` from `@/types` to `@/extensionPoint/types`
Warnings:
- 3 warnings fixed
- 54 warnings to go
> #1080: Fix `ExtensionPoint` circular dependency

- src/background/executor.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/blocks/types.ts
- src/pageEditor/tabs/effect/BlockConfiguration.tsx
- src/runtime/reducePipeline.ts
---
- Quick implementation of #3200 
- Provides a "top" target to run a brick in the top-most frame of a window/tab
- Sub-frame can get context of the root page directly by running bricks in the top-level frame
- Top-level frame can get context from a sub-frame by having the sub-frame call "Set page state" on the top level from on page load, triggers, etc.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
> #3200: run brick in top frame of window

- src/auth/ScopeSettings.module.scss
- src/auth/ScopeSettings.tsx
- src/components/form/Form.tsx
- src/options/pages/blueprints/modals/__snapshots__/ShareExtensionModal.test.tsx.snap
- src/options/pages/services/ServiceEditorModal.tsx
- src/pageEditor/sidebar/AddToRecipeModal.tsx
- src/pageEditor/sidebar/CreateRecipeModal.tsx
- src/pageEditor/sidebar/RemoveFromRecipeModal.tsx
- src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx
- src/types/helpers.ts
- src/utils/strings.ts
This cleans up some messy, direct usages of `<Formik/>` that can be cleaned up using our `<Form/>` component. This improves the field validation and standardizes/simplifies the code.
Also added validation for semver `Version` strings in the recipe metadata.
> Cutover direct Formik usage to our Form component, and add semver validation

- src/pageEditor/ErrorBanner.tsx
Closes #3131 
https://github.com/pixiebrix/pixiebrix-extension/pull/3167 fixed the original root cause by having RTK throw normal errors. 
Removes the old auth check. Given that the Page Editor panel is wrapped in a RequireAuth, authentication is already checked and an ErrorBoundary is shown at the top-level if the connection to the server is broken
> #3131: remove unnecessary error handler on error banner

- src/pageEditor/toolbar/ActionToolbar.tsx
Closes #3211 
When a new extension is moved into a blueprint, we should show the reset button even if it's unsaved, because it's going to reset the blueprint, not the extension.
> Show reset button for new extensions in blueprints

- .github/workflows/storybook.yml
---
- Turns back on Storybook artifact upload
- Uses our custom `.github/actions/upload-zipped-artifact` action for performance since there's a lot of small files
> Re-enable Storybook upload

- src/pageEditor/extensionPoints/base.ts
- src/pageEditor/panes/save/saveHelpers.test.ts
- src/pageEditor/panes/save/saveHelpers.ts
- src/store/extensionsSlice.ts
- src/testUtils/factories.ts
Fixes #3222 
This adds test coverage for the `buildRecipe()` function in the recipe save logic. Also includes lots of small tweaks to get tests working, and removes some unnecessary normalization of optional fields that makes testing harder.
We also needed to add logic to de-dupe the extension point `definitions` being added to the blueprints, to account for extension points that have their id changed to an `@internal/` reference in the page editor. This is because, when a blueprint is "installed" in the extensions slice, the entire `definitions` object is pushed down to each extension in the recipe, so each extension has dupes of the extension point definitions of every other extension in the blueprint.
> #3222 Add tests for buildRecipe() and fix some uncovered edge cases

- src/manifest.json
- src/options/options.html
- src/pageEditor/pageEditor.html
- src/sidebar/sidebar.html
- src/tinyPages/permissionsPopup.html
---
- Closes #3135 
- Relaxes the CSP on the extension, and re-enforces it on the extension pages: options page, devtools
- Don't enforce on the sidebar.html and ephemeralForm.html since the former supports rendered, and the later support markdown in the form description
Bananas for scale
> #3135: relax image CSP on frame page

- src/options/pages/blueprints/utils/useReinstall.ts
- src/pageEditor/panes/save/saveHelpers.ts
- src/services/serviceUtils.ts
- src/validators/generic.ts
---
- Fixes #3262 
- Handles cases where `IExtension.services` is not defined. (It's optional in the type, but in practice was always defined since we were normalizing values)
- PR implemented by searching for ".services" across the project and handling the cases of `IExtension.services`. For PageEditor FormState's services that will alsways be defined
> #3262: fix NPEs on `services`

- src/background/deployment.test.ts
- src/options/pages/blueprints/utils/useReinstall.ts
- src/options/pages/marketplace/useWizard.ts
- src/pageEditor/pageEditorTypes.ts
- src/pageEditor/sidebar/CreateRecipeModal.tsx
- src/pageEditor/slices/editorSlice.ts
- src/store/extensionsSlice.ts
- src/store/extensionsUtils.test.ts
- src/store/extensionsUtils.ts
---
- Closes #3265
- Refactors CreateRecipeModal into save hooks, schema, initialFormState, etc.
- Refactors logic for inferring options/auths from useReinstall into store/extensionUtils to re-use in CreateRecipeModal
> #3265: fix dropped services when using "Save as New"

- src/pageEditor/sidebar/CreateRecipeModal.tsx
> #3277 Save-as-new with the entire blueprint when one of its extensions is selected

- .gitignore
- src/blocks/transformers/parseUrl.test.ts
- src/blocks/transformers/parseUrl.ts
- src/blocks/transformers/regex.test.ts
- src/blocks/transformers/regex.ts
- src/errors.test.ts
- src/errors.ts
- src/telemetry/reportError.ts
---
- Part of #3279 (I'm not sure it solves the whole problem)
- Handles EventErrors where the message is defined, but error is null
- Removes "Synchronous Error:"/"Asynchronous Error:" message prefixes that were breaking message-based error filtering. E.g., for ResizeObserver loop limit exceeded
> #3279: fix error event handling

- src/runtime/mapArgs.test.ts
---
- Part of #3282
- Adds tests to demonstrate the v1-v3 runtime behavior of omitting object entries with a null value
> #3282: add tests for runtime null expressions

- jest.config.json
- package-lock.json
- package.json
- src/globals.d.ts
- src/options/pages/blueprints/BlueprintActions.tsx
- src/options/pages/blueprints/useInstallableViewItemActions.test.tsx
- src/options/pages/blueprints/useInstallableViewItemActions.ts
---
- Closes #3308
- Makes the uninstall/reinstall actions available to unrestricted users on deployments
- Hides the "Share" button for all deployments because they're managed via Admin Console
- Hides the "Export" button for all deployments 
- Adds the jest-extended library for additional test matchers for comparing actual/expected objects
> #3308: allow unrestricted users to reinstall/uninstall deployments

- src/background/deployment.ts
- src/hooks/useDeployments.test.ts
- src/hooks/useDeployments.ts
- src/testUtils/factories.ts
- src/types/contract.ts
- src/utils/deployment.test.ts
- src/utils/deployment.ts
---
- Closes #3311 
- A source of confusion is that PixieBrix will prompt a developer to install a version of a blueprint even if they have a newer version of it installed (e.g., during development). As a result, they install the deployment and then have the old version of the blueprint installed and accidentally modify that blueprint
> #3311: don't prompt developers to install deployments of blueprints they have installed

- src/pageEditor/panes/save/saveHelpers.test.ts
- src/pageEditor/panes/save/saveHelpers.ts
- src/pageEditor/sidebar/CreateRecipeModal.tsx
---
- Closes #3307 
- Removes special characters during registry id generation
- Falls back to null if a valid id is not generated
> #3307: ignore special chars in recipe id generation

- src/errors.ts
- src/utils/notify.tsx
- Closes #3260
This is what 400 characters look like. The limit is long enough to rarely be reached (truncating messages is never ideal) but short enough to avoid excessively-long notification messages.
> Municipiile erau orașe cu mai puține 
> drepturi decât coloniile, locuite de acei 
> cetățeni cu drepturi limitate. Satele 
> erau locuite de obicei de populația 
> autohtonă. Se așezau însă în ele și 
> coloniști romani. Romanizarea a mers 
> greu la sate, unde imensa majoritate 
> o formau geții, mai ales în primele 
> impuri după cucerire. Un rol important 
> în romanizare, la sate, l-au avut 
> veteranii, atât de origine 
I also placed a length limit on the error message to ensure we don't send out megabytes of errors to Rollbar.
Note: `JSON.stringify` is a last resort and we should …
> #3260: Limit the length of notifications and error messages

- src/options/pages/blueprints/Status.tsx
---
- Closes #3269 by removing TODO comment
- The underlying issue (where some actions weren't being set to null when unavailable) was fixed in https://github.com/pixiebrix/pixiebrix-extension/pull/3309
> #3269: remove outdated TODO comment about inconsistent status on blueprints screen

- .github/pull_request_template.md
- Adds a GitHub PR template
- It should show up automatically for new PRs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template
- I don't think the PR template shows up until we merge into main?
- Tweak the template based on our initial usage
> Initial commit of PR template

- src/components/fields/schemaFields/BasicSchemaField.tsx
> #3322 Fix SchemaField onBlur handling

- src/components/form/Form.module.scss
- src/components/form/Form.tsx
- src/pageEditor/sidebar/CreateRecipeModal.tsx
This updates the default layout for "status" in our `Form` component to a banner-style, error-alert layout across the top of the form.
Right now we only use the "status" of the form for errors. It's possible to use it for any other sorts of "status" as well, and we might want to expand that at some point. The status handler accepts `any` as the type, so we could have our own status types that we pass in that are handled differently by default in the `Form` component, like a separate status for error or success, that show as red or green banners, for example.
> #3268 Improve error msg layout in Form component

- src/pageEditor/hooks/useRemoveExtension.ts
- src/pageEditor/hooks/useRemoveRecipe.ts
- src/pageEditor/panes/RecipePane.tsx
- src/pageEditor/sidebar/CreateRecipeModal.tsx
- src/pageEditor/toolbar/ActionToolbar.tsx
- src/store/extensionsSlice.ts
- src/store/extensionsUtils.ts
- Fixes #3326 
- `removeRecipe()` now takes a config input similar to `removeExtension()` with a flag to bypass the confirmation modal
[Panel is no longer duplicated after adding the extension to a blueprint](https://www.loom.com/share/79cb06cfff084d85ad7130fcd8c04ed6)
- other bug discovered: https://github.com/pixiebrix/pixiebrix-extension/issues/3337
> #3326 Fix dupe sidebar panels with blueprint actions

- src/background/logging.ts
- src/blocks/transformers/jq.test.ts
- src/blocks/transformers/jq.ts
- src/errors.test.ts
- src/errors.ts
> #3216 JQ fromdate error gets cut off in page editor

- src/options/pages/marketplace/ActivateWizard.tsx
- Closes: #3275
- Ignores "enter" key press in activation wizard
Future Work
- This PR prevents you from using the "Enter" key to select an item from a dropdown
> #3275: don't submit activation wizard form on enter key

- src/options/pages/marketplace/useWizard.test.tsx
- src/options/pages/marketplace/useWizard.ts
- Closes #3344 
- Adds `@testing-library/react-hooks` for helping to test hooks
> #3344: skip personalize on empty options schema

- src/extensionPoints/triggerExtension.ts
- src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
- Closes #3347 
- Passes keyboard event data in an "event" property in the input
- Adds support for "keypress" event
- Include an official reader with an output schema for event like we do for context menus. There's not much advantage since the shape changes per event
- Show in the the preview of the data panel. (Also would require creating a fake reader)
> #3347: include trigger event data

- src/background/auth.ts
- src/background/proxyService.test.ts
- src/background/requests.ts
- src/services/locator.ts
- src/testUtils/factories.ts
- Part of #2966
- Adds checks to help isolate cause of service lookup errors
- Adds a sanitized service auth factory
> #2966: diagnose service lookup errors

- src/auth/authTypes.ts
- src/background/logging.ts
- src/background/requests.ts
- src/core.ts
- src/extensionPoints/helpers.ts
- src/options/pages/blueprints/modals/ShareExtensionModal.tsx
- src/options/pages/blueprints/utils/exportBlueprint.ts
- src/pageEditor/extensionPoints/base.ts
- src/pageEditor/panes/save/RecipeConfigurationModal.tsx
- src/pageEditor/panes/save/SavingExtensionModal.test.tsx
- src/pageEditor/panes/save/saveHelpers.test.ts
- src/pageEditor/panes/save/useSavingWizard.ts
- src/pageEditor/sidebar/CreateRecipeModal.tsx
- src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx
- src/runtime/pipelineTests/component.test.ts
- src/runtime/reducePipeline.ts
- src/services/errorService.ts
- src/testUtils/factories.ts
- src/types/contract.ts
- src/types/helpers.ts
- src/types/swagger.ts
- src/utils/deployment.test.ts
- src/utils/objToYaml.test.ts
- Closes #3332 
- Reports user-defined extension errors to PixieBrix error telemetry endpoint introduced here: https://github.com/pixiebrix/pixiebrix-app/pull/1615/
> #3332: report user-defined extension errors to errors endpoint

- src/background/locator.ts
- src/background/requests.ts
- src/components/fields/schemaFields/ServiceField.tsx
- src/components/fields/schemaFields/widgets/ServiceSelectWidget.stories.tsx
- src/components/fields/schemaFields/widgets/ServiceSelectWidget.tsx
- src/components/form/widgets/SelectWidget.tsx
- src/options/pages/activateExtension/ActivateForm.tsx
- src/options/pages/activateExtension/ActivatePage.tsx
- src/options/pages/activateExtension/ServicesCard.tsx
- src/options/pages/marketplace/AuthWidget.module.scss
- src/options/pages/marketplace/AuthWidget.tsx
- src/services/serviceUtils.ts
- Closes #2574 
- Adds a "refresh" button next to service selection widgets
- If service lookup fails in the background page, refreshes the service locator and tries the lookup again
- There are two parallel auth selection widgets. One set used by the options page and one used by schema fields. We should consolidate the service selection code
> #2574: refresh button and auto-refresh integrations

- src/auth/authTypes.ts
- src/auth/authUtils.ts
- src/components/form/widgets/RegistryIdWidget.module.scss
- src/components/form/widgets/RegistryIdWidget.test.tsx
- src/components/form/widgets/RegistryIdWidget.tsx
- src/components/form/widgets/SelectWidget.tsx
- src/options/pages/blueprints/modals/ShareExtensionModal.module.scss
- src/options/pages/blueprints/modals/ShareExtensionModal.tsx
- src/options/pages/blueprints/modals/__snapshots__/ShareExtensionModal.test.tsx.snap
- src/pageEditor/sidebar/CreateRecipeModal.tsx
- src/types/contract.ts
- src/types/swagger.ts
- Close #3029 
- Adds a new `RegistryIdWidget` component that loads user-accessible scopes and presents the id with a split input including a dropdown for scope and text input for the rest of the id
Page Editor:
Share Extension Modal:
* We should probably take a look at using the `react-select` styles api to make sure it matches the app styling in a more general way at some point
> #3029 RegistryId widget

- .storybook/main.js
- src/__mocks__/browserMock.mjs
- Part of #2152
- We are temporarily fixing broken storybook stories that use the extension api by writing a quick global import mock for browser in the storybook config.
- Perhaps run storybook and verify that all stories are working as expected.
- Eventually, we might want to move towards using a browser mock [like `jest-webextension-mock`](https://github.com/clarkbw/jest-webextension-mock) for storybook stories.
- n/a
- Finish adding onboarding stories to finish #2152 
- Implement a better browser mock (mentioned above)
> Fix storybook stories by mocking browser

- src/components/fields/schemaFields/fieldInputMode.test.ts
- src/components/fields/schemaFields/fieldInputMode.ts
- src/components/form/Form.tsx
- src/options/pages/services/ServiceEditorModal.stories.tsx
- src/options/pages/services/ServiceEditorModal.tsx
- Fixes the ServiceEditorModal stories
- Adds some basic test coverage for inferInputMode
- The fix: 
- Call registerDefaultWidgets to match the test code
- In Form.tsx, default the initialValues to `{}` if the called passes null/undefined
> Fix NPE in storybook stories

- src/components/documentBuilder/edit/DocumentEditor.test.tsx
- src/components/formBuilder/FormBuilder.test.tsx
- src/components/formBuilder/FormBuilder.tsx
- src/components/formBuilder/edit/FormEditor.tsx
- src/components/formBuilder/formBuilderHelpers.test.ts
- src/components/formBuilder/formBuilderHelpers.ts
- src/components/formBuilder/formEditor.testCases.ts
- src/pageEditor/extensionPoints/base.ts
- src/pageEditor/panes/save/saveHelpers.test.ts
- src/pageEditor/panes/save/useSavingWizard.test.tsx
- src/pageEditor/tabs/RecipeOptions.tsx
- Fixes #3368
- Initialized with the default (example) config, FormBuilder was not able to rename the field because `ui:order` property was `undefined`
- Move the from builder helpers defined in the scope of test file to `testUtils/formBuilderHelpers.ts`?
> #3368 Can't rename date field in form builder

- src/pageEditor/tabs/effect/BlockConfiguration.tsx
- src/pageEditor/tabs/effect/ConfigurationTitle.module.scss
- src/pageEditor/tabs/effect/ConfigurationTitle.test.tsx
- src/pageEditor/tabs/effect/ConfigurationTitle.tsx
- src/pageEditor/tabs/effect/__snapshots__/BlockConfiguration.test.tsx.snap
- src/pageEditor/tabs/effect/__snapshots__/ConfigurationTitle.test.tsx.snap
- Closes #3354
- Addresses the issues from https://github.com/pixiebrix/pixiebrix-extension/pull/3375#pullrequestreview-973196483
- Shows the brick name only when a custom label is set for the brick
- Adds UTM tags to the documentation link
- What would be the best way to define link color?
https://www.loom.com/share/a2344b1f5ab24455bb0698f1daed02ca
> 3354 Don't always show Block name in Title

- src/background/partnerTheme.ts
- src/hooks/useTheme.ts
- src/utils/themeUtils.ts
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/1470
- In order to prevent running into redux import conflicts while re-using the `getThemeLogo`, which formerly lived in the `useTheme` hook.
- Are there any other refactoring opportunities here? Ideally, I'd love to reuse the `useTheme` hook in the app, but this implementation currently touches both the options slice and the background script, which conflicts with the app.
- I was considering splitting off a `useGetTheme` from the `useTheme` hook, and `useTheme` could take a Theme as a parameter.
n/a
n/a
> Refactor theme utilities

- src/blocks/readers/factory.ts
- src/blocks/transformers/blockFactory.test.js
- src/blocks/transformers/blockFactory.ts
- src/core.ts
- src/services/factory.test.ts
- src/services/factory.ts
- Closes #3417
- Brick/Service ID weren't being reported for YAML based bricks because the version was never passed along through the corresponding brick factories
- Currently for JS bricks, we're default the version when adding the logging context: https://github.com/pixiebrix/pixiebrix-extension/blob/472e43f01561a1b8047a6b33c3dae45aefa67daa/src/runtime/reducePipeline.ts#L637-L637. In the future, we might consider having the JS bricks default in their constructor base classes instead
- If you're testing this locally, you have to run generate headers and then upload the updated headers for the JS bricks to the app project
> #3417: include brick version for YAML bricks

- src/components/fields/schemaFields/SchemaField.test.tsx
- src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx
- src/components/jsonTree/JsonTree.test.tsx
- src/components/jsonTree/JsonTree.tsx
- Add tests for the `searchData()` function in `JsonTree.tsx`
- I changed the behavior slightly because it was returning empty objects nested in arrays under certain conditions, after I fixed the bug with object/array checking order
- See the added TODO comment and some test cases for possible future improvements to the search function
> #3353 - Add tests for the search function in JsonTree and fix bugs

- package-lock.json
- src/contentScript/nativeEditor/selectorInference.ts
- src/contentScript/selectorInference.test.ts
- src/pageEditor/fields/SelectorSelectorWidget.test.ts
- src/pageEditor/fields/SelectorSelectorWidget.tsx
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/3321
- Fixes rare situation where a tag selector gets a higher preference than classes 
I was able to replicate the errors on https://developer.automationanywhere.com/challenges/automationanywherelabs-employeedatamigration.html
The selectors were sorted (by length) in multiple places. This PR ensures we use the new `getSelectorPreference` function for that.
- Do you remember any other places where we sort the selectors by length?
- The sorting currently happens repeatedly because more selectors are added in multiple parts or from multiple sources. This isn't ideal but doing otherwise would likely mean rewriting much of selectorInference.ts
> Drop length-only sorting in `SelectorSelectorWidget`

- src/blocks/effects/insertHtml.ts
- src/blocks/effects/registerEffects.ts
- src/development/headers.ts
- Prototype of #3485
- Adds a Insert HTML brick for inserting an arbitrary non-interactive element into the page
- For timer use case if it will be triggered every 1 second, we need a way to not send events for every trigger run. This is out of scope of this PR. (It also applies to other triggers, e.g., key up)
- I matched the DOM native API of insertAdjacentHTML. However, the position names aren't very intuitive :(
- I had waiting adding this kind of brick because it’s pretty ad-hoc and can be unreliable. E.g., the host page might remove the element during a render loop so your element would disappear. Our button and inline panel extension points take steps to prevent that. They watch to see if they’ve been removed and will re-add themselves. We could implement that kind of behavior for …
> #3485: insert custom HTML element brick

- src/blocks/readers/TimestampReader.test.ts
- src/blocks/readers/TimestampReader.ts
- src/blocks/transformers/parseDate.test.ts
- src/blocks/transformers/parseDate.ts
- Adds epochMillis output fields to the generate timestamp and parse date bricks to make it easier to work with date math (e.g., for timers)
> Add unix timestamps to timestamp and parse date bricks

- src/pageEditor/panes/insert/GenericInsertPane.tsx
I am creating a new event called ExtensionAddNew that gets triggered when a user adds actively a new extension and to track its type
Hoping config.elementType is the right one to hold the name of the extension trigger-brick, otherwise I would be considering using config.label - thoughts?
As a Mixpanel user, I want to see an event when a user creates a brand new extension, I want to know which is the trigger-brick - so that I can quickly identify which bricks are being added freshly to the page editor when a user is active.
> Add tracking when creating a new extension point

- src/contentScript/nativeEditor/selectorInference.ts
- src/contentScript/selectorInference.test.ts
- src/utils/escape.ts
By adding more tests for both `css-selector-generator` and our other partial generators, I realized that the former escapes spaces, not just quotes, so we should probably match that to avoid duplicated selectors.
I didn't use `CSS.escape` to `findContainerForElement` because there's most likely zero overlap with `css-selector-generator`, so we don't need to match its (excessive) escaping.
- https://github.com/pixiebrix/pixiebrix-extension/pull/3497## Checklist
> Match `css-selector-generator` escaping

- src/background/deployment.test.ts
- src/background/deployment.ts
- src/background/installer.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/background/telemetry.ts
- src/hooks/useDeployments.ts
- src/telemetry/initRollbar.ts
Last piece from the non-external Messenger migration. Not sure how we missed it!
> Drop last `liftBackground` usage

- src/components/fields/schemaFields/widgets/registerDefaultWidgets.ts
- src/components/fields/schemaFields/widgets/widgetsRegistry.ts
- src/pageEditor/components/UrlPatternWidget.test.tsx
- src/pageEditor/components/UrlPatternWidget.tsx
- src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap
- src/pageEditor/fields/UrlMatchPatternField.tsx
- src/pageEditor/fields/UrlPatternField.stories.tsx
- src/pageEditor/fields/UrlPatternField.tsx
- src/pageEditor/tabs/contextMenu/ContextMenuConfiguration.tsx
- src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
- src/pageEditor/tabs/panel/PanelConfiguration.tsx
- src/pageEditor/tabs/quickBar/QuickBarConfiguration.tsx
- src/pageEditor/tabs/sidebar/Configuration.tsx
- src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
- Closes #3501 
- Adds control for URL patterns rules in the Page Editor
- We will also be adding a control to require certain selectors to be on the on the page to run the extension. With these 2 additional "Advanced Fields" we may want to put them in an advanced section
- Because I wanted to use SchemaField/ObjectField, I left off some properties that are more obscure from the pre-coded rules. Otherwise there would be more hard-coded properties
- I did not add the control to Context Menu because Chrome's browser API can only use documentUrlPatterns to determine where to show menu item
- I left it off of QuickBar b/c our QuickBar config matches the Context Menu API. (Although in reality, we could have more control because we control what gets rendering in the bar after the user triggers …
> #3501: add URL pattern control to page editor

- src/pageEditor/extensionPoints/base.ts
- src/pageEditor/extensionPoints/contextMenu.tsx
- src/pageEditor/extensionPoints/menuItem.ts
- src/pageEditor/extensionPoints/normalizePipeline.test.ts
- src/pageEditor/extensionPoints/normalizePipeline.ts
- src/pageEditor/extensionPoints/panel.ts
- src/pageEditor/extensionPoints/pipelineMapping.test.ts
- src/pageEditor/extensionPoints/pipelineMapping.ts
- src/pageEditor/extensionPoints/quickBar.tsx
- src/pageEditor/extensionPoints/sidebar.tsx
- src/pageEditor/extensionPoints/trigger.tsx
- Part of #3491
- Removes `instanceId` from the sub pipeline blocks.
- Naming suggestions are very welcome.
> #3491 Update omitMetadata to remove instanceIds from bricks

- package-lock.json
- Bumps can-i-use
- I ran: `npx browserslist@latest --update-db`
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
Removes:
- chrome 96
- chrome 95
- chrome 94
- chrome 93
- chrome 92
Adds:
+ chrome 101
+ chrome 100
+ chrome 99
> Bump Browserslist/caniuse-lite

- src/pageEditor/extensionPoints/panel.ts
- Closes #3478
- Puts inline panel behind a feature flag `page-editor-extension-panel`
> #3478: put inline panel behind feature flag

- src/contentScript/nativeEditor/selectorInference.test.ts
- src/contentScript/nativeEditor/selectorInference.ts
- Closes #3545
- Moves selectorInference.test.ts to peer directory
- Adds inferSelectorsIncludingStableAncestors test
> #3545: fix anchoring to stable selectors

- src/auth/RequireAuth.test.tsx
- src/background/partnerTheme.ts
- src/hooks/useTheme.test.tsx
- src/hooks/useTheme.ts
- src/options/App.tsx
- src/options/pages/onboarding/SetupPage.test.tsx
- src/options/pages/onboarding/SetupPage.tsx
- src/sidebar/SidebarApp.tsx
- Adds tests for `SetupPage` and `useTheme` as a follow-up for https://github.com/pixiebrix/pixiebrix-extension/issues/3134
- Take a look at test files for `SetupPage` and `useTheme` first - make sure these tests cover a sufficient number of cases
- Not relevant to the tests was a small refactor for optional query parameter on `useTheme`
Not a huge issue, but I realized while I was refactoring `useTheme` that when using `useTheme` with a theme that's different than the one in redux (e.g. when manually setting the partner theme before the user is authenticated), the toolbar logo won't use the proper theme. This is because the background function `initPartnerTheme` background function doesn't take any parameters.
> #3134: add onboarding tests

- src/extensionPoints/triggerExtension.ts
- src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
- Closes #3553 
- Adds a selectionchange trigger, and makes it available in the Page Editor
- 😢  Add tests: we don't have testing harnesses for triggers
> #3553: add selectionchange trigger

- package-lock.json
- package.json
- src/background/executor.ts
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/3560
- Temporarily fixes https://github.com/pixiebrix/webext-messenger/issues/67
This new behavior was fixed in the messenger itself:
- Tab never existed: https://github.com/pixiebrix/webext-messenger/commit/75812465172e33835c37109c219eb9c62217d238
- Tab was closed: https://github.com/pixiebrix/webext-messenger/commit/0d20b5a073b95e2ff21d1add641c7c9c166e77ce
Nit: unless we install a global tab tracker, it's hard to tell whether a tab ever existed.
1. Open tab
2. Execute long-running brick in `target`
3. Close tab manually
Depending on how quickly the target is closed, the error will either be "tab doesn't exist" or "tab closed"
https://user-images.githubusercontent.com/1402241/172112864-bc55e2ba-791b-4a50-83b1-ad0e3f31e619.m …
> Handle closed tabs better while attempting to message them

- src/blocks/effects/sidebar.ts
- src/blocks/transformers/ephemeralForm/formTransformer.ts
- src/contentScript/lifecycle.ts
- src/contentScript/messenger/registration.ts
- src/contentScript/nativeEditor/dynamic.ts
- src/contentScript/sidebarController.tsx
- src/core.ts
- src/extensionPoints/sidebarExtension.ts
- src/pageEditor/sidebar/DynamicEntry.tsx
- src/pageEditor/sidebar/InstalledEntry.tsx
- src/sidebar/SidebarApp.tsx
- src/sidebar/messenger/registration.ts
- src/sidebar/protocol.tsx
- src/sidebar/sidebarSlice.ts
- src/sidebar/types.ts
- src/utils/domUtils.ts
- src/utils/notify.tsx
- Closes #3566 
- Add `forcePanel` and `panelHeading` options to the Show Sidebar brick
- By default, the Show Sidebar brick will activate a panel from the current blueprint
- User can also specify a panelHeading to match to activate
- When rendering a panel via the Page Editor, switch over to that panel 
- When selecting an extension in the Page Editor, switch over to that panel
- Keep a stable panel order in the sidebar (just based on sorting extensions UUIDs; non-intuitive, but it's stable)
- In the future we might want to make panelHeading support a regex. Technically, panel headers can vary dynamically (templating over the reader for the panel). However, that's not currently possible with sidebar panels made with the Page Editor
- Take a look at sidebarController first. It's the …
> #3566: add support for switching active sidebar panel via brick; automatically switch when using Page Editor

- .github/workflows/ci.yml
- .github/workflows/rainforestqa.yml
- .github/workflows/release.yaml
- .github/workflows/storybook.yml
- Pins node to 16.15.0 because 16.15.1 was erroring due to dependency conflicts during npm install
- Node 16.15.1 uses npm 8.11.0 vs. 8.5.5
- https://github.com/pixiebrix/pixiebrix-extension/pull/3598#issuecomment-1148930727
> Pin node on CI to 16.15.0

- src/vendors/overrides.scss
- Fixes #3597
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="485" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/172530179-3ddf6d58-71f3-4859-af6a-442532095eab.png">
<td><img width="486" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/172530185-1eaa619c-10f1-49e1-bdf1-7005b6225774.png">
</table>
> #3597: Ensure that long words don't break the UI

- src/pageEditor/Editor.tsx
- src/pageEditor/sidebar/Sidebar.tsx
- Fixes #2783
This solves several issues that appear when showing the sidebar while "inserting":
- the extensions in the sidebar are still selectable, but nothing happens
- new extensions can be "added" before the current one is done
**This sidebar-less view may look strange at first but the exact look can be improved later**
The user can roam the extension while the "inserting" state is active
https://user-images.githubusercontent.com/1402241/172535060-d0304ef1-150c-49c6-9b5e-bad934904c9d.mov
Inserting is now "modal" (i.e. no other operations are available) so you must act on it (add or cancel) before moving onto other operations
https://user-images.githubusercontent.com/1402241/172535252-802f344e-c574-4b0f-aacd-3fa158ba033e.mov
> #2783: Hide page editor sidebar while adding a new extension

- src/components/brickModal/BrickModal.module.scss
- Point 1 of #3574 
The difference is subtle: the explicit `margin` on the left pushes the modal lower, so it lengthens the document
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="272" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/172526941-21ff5cd4-0550-446d-82a8-28412109f0d2.png">
<td><img width="292" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/172526948-cf61086d-0fb5-4be6-b053-8236b62caa2c.png">
</table>
> #3574: Fix extra scrollbar outside the brick modal

- src/options/pages/marketplace/ConfigureBody.tsx
- Closes #3551 
- During re-activation flow, all extensions in the blueprint are toggled on by default
> #3551: activate all extensions by default during reactivation wizard

- src/components/jsonTree/JsonTree.tsx
- src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
- src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
- src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
- src/pageEditor/tabs/editTab/dataPanel/__snapshots__/FoundationDataPanel.test.tsx.snap
- src/pageEditor/tabs/effect/BlockPreview.tsx
- src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
- Adds a button next to JSON tree for output and preview to copy data as JSON to the clipboard
- Helpful for getting the data for playing around in jqplay, etc
- This adds it to all of our JSON trees
> Data panel button to copy JSON

- src/errors/errorHelpers.ts
- Closes #3641
- Fixes a dependency on webext-messenger in errorHelpers that was causes the pageScript module to error on initialization
- Fix button insertion
- Add linter rule to prevent webext-messenger imports in non-extension directories
> #3641: fix page script loading; fix button insertion

- src/components/documentBuilder/edit/getElementEditSchemas.ts
- src/components/documentBuilder/edit/useElementOptions.tsx
- src/components/fields/schemaFields/CssClassField.tsx
- src/components/fields/schemaFields/propTypes.ts
- src/components/fields/schemaFields/widgets/ClassClassWidget.test.tsx
- src/components/fields/schemaFields/widgets/CssClassWidget.stories.tsx
- src/components/fields/schemaFields/widgets/CssClassWidget.tsx
- src/components/fields/schemaFields/widgets/__snapshots__/ClassClassWidget.test.tsx.snap
- src/components/fields/schemaFields/widgets/registerDefaultWidgets.ts
- src/components/fields/schemaFields/widgets/widgetsRegistry.ts
- src/pageEditor/fields/ConfigErrorBoundary.tsx
- src/pageEditor/fields/SelectorSelectorField.tsx
- src/pageEditor/fields/devtoolFieldOverrides.tsx
- Initial part of #3557 
- Creates a CssClassWidget and CssClassField for adding bootstrap utility classes
- The `text-justify` class doesn't seem do anything. Might only be valid for `p` tags?
- If the value is a variable or includes template syntax, the controls are disabled. Will work to clean up the messaging on that
- Had do a bit of hack to get it to show up in the Document Builder. The Document Builder uses Schema Fields directly instead of using the options factory
- Support the layout utility classes (`p`, `m`, etc.). These require different handling because there are multiple in the family, e.g., `m`, `mx`, and `my`
> #3557: document builder formatting widget

- src/components/documentBuilder/edit/getElementEditSchemas.ts
- src/components/fields/schemaFields/widgets/ClassClassWidget.test.tsx
- src/components/fields/schemaFields/widgets/CssClassWidget.tsx
- src/components/fields/schemaFields/widgets/__snapshots__/ClassClassWidget.test.tsx.snap
- Part of #3557 
- Controls for updating the margin/padding of document elements
- The number spinners and collapse don't work well because on every change the component remounts: 1) the collapse state gets lost, 2) the spinner loses focus
- Clean up the formatting and spacing using CSS grid. The inputs should be aligned
- Fix the re-mounting/focus issues
- Use placeholders to indicate to user what the implied size is for elements
> #3557: margin/padding utility class formatting

- src/components/documentBuilder/render/BlockElement.tsx
- src/extensionPoints/sidebarExtension.ts
- src/pageEditor/tabs/editTab/EditTab.tsx
- src/sidebar/PanelBody.tsx
- src/sidebar/sidebarSlice.ts
- src/sidebar/types.ts
- Part of #3659 
- Makes the cancel and business error bricks available in sidebar panel root pipeline
- Passes the full serialized error to the panel
- Make the cancel/error states of the panel look better
- Improve the naming/description of the cancel brick to make more sense in panel extensions
> #3659: allow users to skip panel rendering

- src/blocks/renderers/customForm.tsx
- src/components/documentBuilder/render/BlockElement.tsx
- src/contentScript/pageState.ts
- src/extensionPoints/helpers.ts
- src/extensionPoints/sidebarExtension.ts
- src/extensionPoints/triggerExtension.ts
- src/pageEditor/fields/FormRendererOptions.tsx
- src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx
- src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
- src/sidebar/PanelBody.tsx
- src/sidebar/Tabs.tsx
- Closes #3554 
- Adds a "stagechange" trigger for triggers and sidebar panel render
- Fixes a bug in the custom renderer where state was being set on shared state instead of the blueprint state because no context want being passed through
- It's using CustomEvent currently. In the future we might use browser messaging instead to have a private channel
- It's not configurable yet, it just triggers for all extension/blueprint state changes
- 😞 Add tests: manually QA'd
> #3554: add statechange trigger

- src/components/fields/schemaFields/widgets/CssClassWidget.tsx
- src/components/fields/schemaFields/widgets/__snapshots__/ClassClassWidget.test.tsx.snap
- Part of #3557 
- Adds background fill and hide options
- When we go to improve the layout/UI of the margin/padding controls, we'll also want to clean up the fill control style
> #3557: additional formatting controls

- src/contentScript/sidebarController.tsx
- src/pageEditor/sidebar/DynamicEntry.tsx
- src/pageEditor/sidebar/InstalledEntry.tsx
- src/sidebar/types.ts
- Don't re-run panels when switching between them in Page Editor
- Running panels unnecessarily is a problem when using throttled APIs
- 😞 Add tests
> Don't rerun sidebar panels on selection in Page Editor

- src/components/fields/schemaFields/widgets/CssClassWidget.tsx
- src/components/fields/schemaFields/widgets/__snapshots__/ClassClassWidget.test.tsx.snap
- src/sidebar/Tabs.module.scss
- src/sidebar/Tabs.tsx
- Part of #3557
- Disables text-justify that's applied to bootstrap tab panes by default
- Adds justify style option in CSS widget
- 😞  Add tests
> #3557: Fix default text alignment in sidebar panel

- src/background/requests.ts
- Part of #3613
- Fixes response/request serialization
- `serializeError` doesn't seem to handle Axios errors in the cause well at all on Chrome. (Was having problems replicating on node/in tests)
> #3613: fix response serialization for HTTP bricks

- src/components/form/widgets/RemoteSelectWidget.tsx
- Closes #3536 
- Adds a refresh button to RemoteSelectWidget if the optionsFactory is a function
- 😞 Add tests: manual QA
> #3536: add refresh for cached remote options

- src/blocks/types.ts
- src/components/errors/NetworkErrorDetail.tsx
- src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap
- src/pageEditor/components/UrlMatchPatternWidget.tsx
- src/pageEditor/components/urlMatchPatternWidgetTypes.tsx
- src/pageEditor/extensionPoints/base.ts
- src/pageEditor/extensionPoints/contextMenu.tsx
- src/pageEditor/extensionPoints/elementConfig.ts
- src/pageEditor/extensionPoints/menuItem.ts
- src/pageEditor/extensionPoints/panel.ts
- src/pageEditor/extensionPoints/quickBar.tsx
- src/pageEditor/extensionPoints/sidebar.tsx
- src/pageEditor/extensionPoints/trigger.tsx
- src/pageEditor/fields/UrlMatchPatternField.tsx
- src/pageEditor/tabs/ExtraPermissionsSection.test.tsx
- src/pageEditor/tabs/ExtraPermissionsSection.tsx
- src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap
- src/pageEditor/tabs/contextMenu/ContextMenuConfiguration.tsx
- src/pageEditor/tabs/effect/BlockConfiguration.tsx
- src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
- src/pageEditor/tabs/panel/PanelConfiguration.tsx
- src/pageEditor/tabs/quickBar/QuickBarConfiguration.tsx
- src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx
- src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
- src/permissions/index.ts
- src/testUtils/factories.ts
- Closes #3054 
- Exposes the extension's `permissions.origins` field in the Page Editor
- Fixes a bug in extensionPermissions where `IExtension.permissions` wasn't being considered
- Start with the base adapter code for the Page Editor
- Review the UI changes
- Verify test snapshots are up to date
- Reminder: If you want to test permissions, you can revoke permissions on the Extension Console > Settings page
- Detect situations where the extension is calling tabs/origins the extension creator has given access to, but is not in the declared origin list
> #3054: extra extension permissions in page editor

- src/blocks/transformers/controlFlow/Retry.test.ts
- src/blocks/transformers/controlFlow/Retry.ts
- src/blocks/transformers/randomNumber.test.ts
- src/blocks/transformers/randomNumber.ts
- src/blocks/transformers/registerTransformers.ts
- src/development/headers.ts
- src/pageEditor/utils.ts
- Closes #3673 
- Adds a Retry brick
- Add a random number brick
- I chose to implement "Retry" instead of "wait until" b/c it's a bit more natural way of framing the more control flow (e.g., retrying network requests). A user can implement "wait until" by raising a business/cancel error if their condition is not met
- The retry brick shows as successful even if all the tries fail. Might be fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/3670
> #3673: add retry and random bricks

- src/components/brickModal/BrickModal.test.ts
- src/components/brickModal/BrickModal.tsx
- src/testUtils/factories.ts
- Makes types more specific on tag grouping
- Eliminated unnecessary iteration in tag grouping
- Extracts grouping method outside of component
> Speed up tag grouping in brick modal

- src/contentScript/contentScript.ts
- Closes #3510 
- Marks a nonce on the document to prevent multiple content script loads
- 😞 Add tests
> #3510: mark content script nonce on DOM

- src/components/brickModal/BrickModal.tsx
- Fixes #3715 
- This popular brick code was removing the prototype on the `IBrick` items, and this change uses `immer` instead to avoid that.
> #3715: fix default output key for added bricks

- src/pageEditor/tabs/editTab/EditTab.tsx
- src/pageEditor/tabs/editTab/editTabVariables.scss
- src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
- src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.module.scss
- src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.tsx
- src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.module.scss
- src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx
- src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.module.scss
- src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.tsx
- src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.module.scss
- Fixes #3725 
- Removes an unnecessary loading indicator on top of the entire node layout when adding/removing bricks
> #3725 Fix nested header colors in node layout

- webpack.config.js
- #3722 
- Fixes keep_classnames regex for errors during minimization
Can verify count of CancelError in a production build: 
```
sed 's/CancelError/CancelError\n/g' dist/contentScript.js | grep -c "CancelError"
```
> #3722: fix keep_classnames regex

- src/blocks/transformers/controlFlow/IfElse.test.ts
- src/runtime/reducePipeline.ts
- Fixes #3738 
- Returns the last output of a sub-pipeline, even if it has an output key
> #3738: return last value from sub-pipeline

- src/components/documentBuilder/edit/ButtonOptions.tsx
- src/components/documentBuilder/edit/getElementEditSchemas.ts
- src/components/documentBuilder/edit/useElementOptions.tsx
- src/components/fields/schemaFields/CssClassField.tsx
- src/components/fields/schemaFields/SchemaField.tsx
- src/components/fields/schemaFields/widgets/CssClassWidget.module.scss
- src/components/fields/schemaFields/widgets/CssClassWidget.tsx
- src/components/fields/schemaFields/widgets/__snapshots__/ClassClassWidget.test.tsx.snap
- Fixes #3721
- Disables the margin/padding controls for vars and expressions
- Enables CssClassWidget for buttons
- Fixes the styles buttons appearing above selector popup
> #3721 Minor document builder UI fixes

- src/blocks/readers/PageMetadataReader.ts
- src/blocks/renderers/__snapshots__/customForm.test.tsx.snap
- src/blocks/renderers/customForm.test.tsx
- src/blocks/renderers/customForm.tsx
- src/components/documentBuilder/render/BlockElement.tsx
- Fixes #3785
- Ensures the URL in the context changes with navigation
- Sets empty strings to the form fields that have no data (null or undefined)
This PR does not address the issue when the cleared value is not removed from the database.
https://www.loom.com/share/b30ebe22cec94f34b9c330661b94d8c0
> #3785 Custom Form in document shows previous/stale data if record doesn't exist

- src/auth/authConstants.ts
- src/auth/authTypes.ts
- src/auth/authUtils.ts
- src/auth/token.ts
- src/background/deployment.test.ts
- src/background/deployment.ts
- src/background/installer.ts
- src/hooks/useDeployments.ts
- src/options/pages/deployments/CountdownTimer.stories.tsx
- src/options/pages/deployments/DeploymentModal.stories.tsx
- src/options/pages/deployments/DeploymentModal.test.tsx
- src/options/pages/deployments/DeploymentModal.tsx
- src/options/pages/deployments/__snapshots__/DeploymentModal.test.tsx.snap
- src/store/settingsSelectors.test.ts
- src/store/settingsSelectors.ts
- src/store/settingsSlice.ts
- src/store/settingsStorage.ts
- src/store/settingsTypes.ts
- src/testUtils/factories.ts
- src/types/swagger.ts
- Closes #3791
- Corresponding api PR: https://github.com/pixiebrix/pixiebrix-app/pull/1950
- Tracks when the user was last shown an modal
- Enforces organization policy to update
- Need to get Storybook working with mocks for the browser runtime... I just story booked the countdown timer separately to get more storybook coverage
> #3791: browser extension/deployment update countdown timer

- .github/workflows/ci.yml
- scripts/upload-sourcemaps.sh
- Part of #3828 
- Turns off sourcemap upload on staging
- Ignores sourcemap upload errors to Rollbar
> #3828: mute rollbar sourcemap upload

- src/pageEditor/hooks/usePipelineErrors.ts
- src/pageEditor/slices/editorSelectors.ts
- src/pageEditor/tabs/editTab/EditTab.tsx
- src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
- src/pageEditor/uiState/uiStateTypes.ts
- Fixes #3812 
- the `usePipelineField` is changed to only apply the errors
- Loop over the nested pipelines to apply trace errors to the error state
> #3812 Display node error message

- src/options/App.tsx
- src/pageEditor/Panel.tsx
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/2657
From what I see, all data is persisted locally so there's no reason to show a loader since it's just **shown for a fraction of a second**, or maybe no time at all (I don't see a difference)
`RequireAuth`’s loader also seems to be instantaneous for me and I also suggest dropping it, but I didn't here. You can see how quickly it disappears in https://github.com/pixiebrix/pixiebrix-extension/pull/3611
> _For anything that takes less than 1 second to load, it is distracting to use a looped animation, because users cannot keep up with what happened and might feel anxious about whatever flashed on the screen._
> 
> From https://www.nngroup.com/articles/progress-indicators/
Delete this line on your computer,  I bet the …
> #2657: Avoid loader in PersistGate

- src/blocks/renderers/documentView/DocumentView.tsx
- src/blocks/renderers/markdown.ts
- src/components/documentBuilder/documentTree.tsx
- src/components/documentBuilder/hooks/useMoveWithinParent.ts
- src/components/documentBuilder/outline/outlineHelpers.ts
- src/components/documentBuilder/render/ListElement.tsx
- src/components/documentBuilder/utils.ts
- src/pageEditor/extensionPoints/pipelineMapping.ts
- src/pageEditor/hooks/usePipelineErrors.ts
- src/pageEditor/panes/EditorPane.test.tsx
- src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
- src/pageEditor/tabs/editTab/editHelpers.ts
- src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
- src/pageEditor/tabs/effect/ConfigurationTitle.tsx
- src/pageEditor/utils.test.ts
- src/pageEditor/utils.ts
- src/pageEditor/validation/applyTraceBlockError.test.ts
- src/pageEditor/validation/applyTraceBlockError.ts
- src/pageEditor/validation/applyTraceError.ts
- src/pageEditor/validation/applyTraceInputError.test.ts
- src/pageEditor/validation/applyTraceInputError.ts
- src/pageEditor/validation/setPipelineBlockError.ts
- src/pageEditor/validation/validateOutputKey.ts
- src/pageEditor/validation/validateRenderers.test.ts
- src/pageEditor/validation/validateRenderers.ts
- src/pageEditor/validation/validateStringTemplates.ts
- src/testUtils/factories.ts
- src/utils.ts
- Closes #3831 
Nunjucks validation:
Renderers validation:
Inputs validation:
Trace errors:
- Store error tree in Redux, gradually reducing the scope of Formik
> #3831 Add validation support for sub pipelines

- src/baseRegistry.ts
- Closes #3858 
- Adds the missing registry id to the error message to assist with debugging
- N/A: Add tests:
> #3858: add brick id to registry error message

- src/manifest.json
- src/options/options.html
- src/pageEditor/pageEditor.html
- src/sidebar/sidebar.html
- src/tinyPages/ephemeralForm.html
- src/tinyPages/permissionsPopup.html
- static/background.worker.js
- webpack.config.js
I think at this point the vendors bundle isn't saving much space anymore. I think we'd get better returns by looking into better tree-shaking somehow. I found that the vendor bundle somewhat conflicts with the logic expected in my other PR since the vendor is re-injected unconditionally, unlike the rest of the regular CS:
- #3915
> Drop vendors bundle

- src/blocks/transformers/screenshotTab.ts
- src/components/quickBar/QuickBarApp.tsx
This PR disables the exit animation of the QuickBar to ensure it does not appear when taking a screenshot.
- Fixes #3724
- Add a `await sleep(200)` before every screenshot, which makes it feel less instantaneous
-  100ms is the default https://github.com/timc1/kbar/blob/a232f3d8976a61eeeb844152dea25a23a76ad368/src/useStore.tsx#L20
- Only disable the exit animation if the action contains a screenshot, which seems difficult (but I don't know)
The last one would be ideal, but probably out of my reach for a couple of reasons 😬 
You can see the screenshot being added to the top of the page. None of them include the quickbar:
https://user-images.githubusercontent.com/1402241/182339583-b1edcdf7-fecb-4623-8f60-37b947c66cf2.mov
> #3724: Avoid screenshotting the quickbar

- src/components/addBlockModal/BlockGridItem.module.scss
- src/components/addBlockModal/BlockGridItem.tsx
- src/pageEditor/panes/EditorPane.test.tsx
I'm happy that most of the issues described in https://github.com/pixiebrix/pixiebrix-extension/issues/3574 were fixed 🎉 
Closes https://github.com/pixiebrix/pixiebrix-extension/issues/3574
- addresses the last point about the hover state  text (removing it)
- avoids using BS components unnecessarily
- `ListGroup.Item` did nothing and was not wrapped by `ListGroup`
- `Card` was being used only for its border
- both component’s styles were being specifically overridden by local styles
- adds focusability to the element (a11y), actually allowing the `:focus` style that was defined but unused
- I wanted to make the Add button smaller and always visible, but I'm sure you wouldn't have liked it, so I left it unchanged
- I equalized the x/y spacing of the cards
- Best reviewed [without …
> AddBlockModal: Drop redundant "Show details" text + use simple components

- src/pageEditor/Panel.tsx
- src/pageEditor/hooks/useCreate.ts
- src/permissions/index.ts
- src/services/locator.ts
- src/services/serviceUtils.ts
- Fixes #3951 
- Adds a guard rail to the `locator.locate()` function to make sure it's only called from the background context
- Refreshes all bricks (blocks, extensionPoints, readers, services) on `Panel` mount in the page editor, instead of just bricks
- Does it make sense to refresh all the brick types like this in either/both places? Or should I make the minimum change possible and just have the create function refresh services before the permissions check?
- Should we look at any other places where only one brick type is fetched and convert everything to refresh the whole registry in each place? This seems more robust, especially to changes in the future, but not sure of, e.g. performance, ramifications of a change like this.
> #3951 Fix crash on save when using the Translate brick

- src/auth/RequireAuth.tsx
- src/sidebar/ConnectedSidebar.tsx
- Closes #3985 3985
- I went with ignoreApiError rather than throwApiError to keep the default false
> #3985: ignore network errors in sidebar's authentication gate

- src/pageEditor/context.ts
- Fixes #3989 
- Does this make sense to return the initial `tabState`? The alternative would be to fix all the call-sites to null-coalesce the `tabState` property of `PageEditorTabContext` before destructuring the fields.
- Should I rename the const to `defaultFrameState` instead of `initial...`?
> #3989 Fix useInstallState NPE

- src/utils/notify.module.scss
- src/utils/notify.tsx
Error messages in notifications can be pretty long. Seeing a message like this can be overwhelming.
Adding a line break and automatically using a lighter color for the error message makes it easier to follow.
> <img width="406" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/183398672-7af678b7-fa69-4f2b-8aeb-0ea7d89db0fe.png">
This is particularly important because the concatenated error is generally a lower-level error.
This last one has an additional visual bug. Fixed:
- https://github.com/pixiebrix/pixiebrix-extension/issues/3961
> Improve notification readability

- src/options/pages/onboarding/PartnerSetupCard.tsx
- src/services/baseService.ts
- Fixes a leg of the Partner End User onboarding flow where they would see the enterprise success modal instead of screens for Partner Onboarding by linking back to a non-start url.
- Also removes the `install` search param from the Install url which is unused.
- The start url is reconstructed from the control room on the user's primary organization.
> link back to start url on PartnerSetupCard

- src/baseRegistry.ts
- src/pageEditor/hooks/useAllBlocks.ts
- Fixes #3994 
- This causes `brickRegistry.all()` to get called twice on page editor startup, but it's just pulling from the background registry / IDB, so it's not fetching twice
> #3994 Fix issue with bricks not appearing

- src/background/partnerIntegrations.ts
- Closes #4028 
- Handles missing `automation-anywhere/oauth2` definition which is not publicly available on prod yet
- I didn't need to change useRequiredPartnerAuth because it loops over all services, https://github.com/pixiebrix/pixiebrix-extension/blob/2a808ea401e2a0f8a38f6702489f57488e4a0e31/src/auth/useRequiredPartnerAuth.ts#L100-L100
- 😢  Add tests
> #4028: handle missing service definition

- src/sidebar/SidebarApp.tsx
- Closes #4031 
- Adds MemoryRouter to SidebarApp. Our RequireAuth does a location check to support ignoring the gate on settings page, so it needs a router in the tree: https://github.com/pixiebrix/pixiebrix-extension/blob/851aa40bd03e448af32199c5818ee81b881fc7b7/src/auth/RequireAuth.tsx#L163-L163
- 😢  Add tests
> #4031: add sidebar router to support auth hooks

- src/components/ErrorBoundary.tsx
- src/sidebar/ErrorBoundary.tsx
- Fixe #4027 
You can see that there's only one error report now:
> #4027: Avoid duplicate error reporting in `ErrorBoundary`

- src/components/formBuilder/ImageCropWidget.tsx
- Fixes the issue discovered in https://github.com/pixiebrix/pixiebrix-extension/pull/4024#pullrequestreview-1072315858
- Avoids the silent error caused by painting a cross-origin image onto the canvas
- This change is non-breaking because it the ability to load non-`data:` images, which was previously impossible
Uses the URL:
```
https://cdn.pixabay.com/photo/2015/10/01/17/17/car-967387__480.png
```
```
https://images.freeimages.com/images/large-previews/566/green-frog-1361810.jpg
```
> Allow cross-origin image URLs in form field

- src/contentScript/contentScript.ts
- src/errors/contextInvalidated.ts
- Fixes a `console.time('contentScript: ready')` message mismatch that prevented the timing
- Track the core file loading
- Documents the context-tracking code
- No change for users
> #4058: Fix contentScript loading logging

- src/contentScript/contentScript.ts
- src/contentScript/contentScriptCore.ts
- Part of #4058 
- Moves the onContextInvalidated listener to the contentScriptCore to avoid the messenger registration race condition
Discussion
---
- @fregante there's still a race in the `init()` method. If you put a `await sleep(1000)` as the first line init method, you'll see that you still get the error. That's because the __getTabData method is loading synchronously with the module load, while the registerMessenger is running async. 
- I think we need to be able explicitly set the messenger as "ready". Otherwise you'll always run into race conditions with: 1) message registration, 2) brick registration, 3) other content script initialization, etc.
Coordination
---
> #4058: fix race condition on tab load

- src/analysis/analysisVisitors/formBrickAnalysis.ts
- src/pageEditor/analysisManager.ts
- Closes #4025 
- Adds an analysis rule to error if the form modal is used in a renderer location
> #4025: show error if the form modal is used in a renderer branch

- src/extensionPoints/menuItemExtension.ts
- src/pageEditor/extensionPoints/menuItem.ts
- src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
- Closes #4010 
- Provides toggle to turn off default success message for menu item
- 😢  Add tests - we don't have extension point test framework yet
> #4010: provide toggle for default success message on menu item extensions

- src/components/fields/schemaFields/SchemaFieldContext.tsx
- src/components/fields/schemaFields/schemaFieldTypes.ts
- src/pageEditor/fields/devtoolFieldOverrides.tsx
- Drops the unused customFields and customWidgets properties from SchemaFieldContext
> Removing unused customFields and customWidgets properties from SchemaFieldContext

- package-lock.json
- package.json
- Permanently fixes #4058 
- Includes https://github.com/pixiebrix/webext-messenger/pull/77
Keep in mind that this issue was already fixed by https://github.com/pixiebrix/pixiebrix-extension/pull/4061 so in order to test it I had to locally revert that commit.
https://user-images.githubusercontent.com/1402241/185690927-2ec80718-7fdb-4fc6-8c25-5464bccc2160.mov
https://user-images.githubusercontent.com/1402241/185691267-fe7adb15-ee95-4816-90de-48b812f4526f.mov
> #4058: Fix content script race condition with messenger

- src/blocks/readers/window.ts
- src/common.ts
- src/contentScript/messenger/registration.ts
- src/contrib/pipedrive/readers.ts
- src/messaging/protocol.ts
`@/common` is imported by every context via `notify.ts` and unsafe-messaging stuff shouldn't be part of it.
No changes made, just moving code
- https://github.com/pixiebrix/pixiebrix-extension/issues/669
> Move messaging code out of `@/common`

- src/background/browserAction.ts
- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/contentScript/sidebarController.tsx
- src/contentScript/sidebarDomControllerLite.ts
- src/extensionPoints/sidebarExtension.ts
- src/helpers.ts
- src/tinyPages/browserActionInstantHandler.ts
- src/utils/notify.tsx
- webpack.config.js
- Part of #4078
- Before trying this PR, open your PB sidebar to see a slow-responding browser action for the last time [^1]
[^1]: For best effects, use on hosts without permissions. It does not affect the actual sidebar.html loading time. Contact your doctor if page loads take longer than 4 hours.
- Further readability improvements were possible but I tried to keep this PR slim
https://user-images.githubusercontent.com/1402241/185910211-271490e8-8b59-473b-8302-aa30eaa12d34.mov
https://user-images.githubusercontent.com/1402241/185910234-83ac4931-8cb8-4380-808b-d2531c95f793.mov
> #4078: Instant sidebar loading via browserAction

- .npmrc
- package-lock.json
It turns out it's easy to avoid errors when using npm 8. This fixes the issue permanently (or at least until npm 9)
> Add support for npm 8

- src/options/pages/blueprints/BlueprintsCard.tsx
- src/options/pages/blueprints/BlueprintsPage.tsx
Since [the API may be slow to respond](https://github.com/pixiebrix/pixiebrix-app/issues/2184), we can try to display most of the UI available so far to avoid having the user wait on an empty page without a title with only a loader for several seconds.
This concept is the same one behind the ["loading skeletons"](https://betterprogramming.pub/the-what-why-and-how-of-using-a-skeleton-loading-screen-e68809d7f702)  mentioned on Slack before.
https://user-images.githubusercontent.com/1402241/186395997-e696ef0c-41e7-4458-ba15-a66bfcda5d9e.mov
https://user-images.githubusercontent.com/1402241/186395953-11006026-0289-4cc6-88da-bd463fa30549.mov
- 🥲 Add tests
> Optimistically display Blueprints UI

- src/contentScript/lifecycle.ts
- src/extensionPoints/triggerExtension.ts
removeExtensions method is called when user select the extension in the sidebar.
- Closes #2273 
@twschiller left comment on `removeExtensions` method of TriggerExtensionPoint. However after some debugging, I found that when extension is removed, the triggered observers are not cleared in extensionPoint.
- Do we have any side-effects if we cancel observers in removeExtensions method? 
- Another thing to discuss is I found a case that when we remove trigger extension (which is already running) in the page editor, it clears extension and cancel Observers in the current tab. However it doesn't cancel observers in the different tabs. Thus trigger is still running on different tabs until refresh. Is this case that we need to fix?
> #2273: Existing interval trigger not deactivated when editing in Page Editor

- package-lock.json
- package.json
@types/yup is deprecated: https://www.npmjs.com/package/@types/simple-icons
According to the npm page:
> This is a stub types definition. simple-icons provides its own type definitions, so you do not need this installed.
Looks like we can delete this package.
> Remove deprecated npm package

- src/options/options.html
- src/sidebar/sidebar.html
- src/vendors/theme/app/app.scss
- src/vendors/theme/assets/styles/_fonts.scss
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/4100
Most [solutions](https://web.dev/defer-non-critical-css/) suggest `rel=preload` and an `onload` listener, but since our HTML is local and tiny this doesn't give any speed advantage over this:
- move the import to the bottom of the page
The stylesheets only delay the first paint of the page **if they come before the content**. By placing them after the JS, we ensure they don't delay anything (except the `document.onload` event, which we don't care about.)
In this demo, I placed 
- options.html: `<style>* {font-family: Roboto;}</style>` in the `head`
- options.html: `<link href="https://deelay.me/10000/https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet"/>` after `options.js`
- …
> #4100: Defer loading of Google Fonts

- src/contrib/automationanywhere/BotOptions.tsx
- src/contrib/automationanywhere/RunBot.ts
- src/contrib/automationanywhere/aaApi.ts
- src/contrib/automationanywhere/aaTypes.ts
- Closes #4127 (is the AA side of the ticket)
- Exposes a maxWaitMillis argument on the AA Remote Bot brick
- Currently if the field is left off, the default (currently 1 minute will be used). We could consider having the default be no timeout if the value is not provided
- 🕐  Add tests: will be added in follow up PR addressing AA option combinations
> #4127: add maximum wait option for AA bot

- src/auth/authSlice.ts
- src/auth/authTypes.ts
- src/auth/authUtils.ts
- src/hooks/useTheme.ts
- src/options/App.tsx
- src/options/Navbar.tsx
- src/options/Sidebar.tsx
- Closes #4165 
- Fixes `selectExtensionAuthState` to include the partner so it's cached in the persisted state
- Functional change: https://github.com/pixiebrix/pixiebrix-extension/pull/4166/files#diff-98ae72f5a9a3488b154dfa0eafc7aaa621ab92c69239263eef42f82ebd84cca5R82
> #4165: fix partner caching in Redux

- .github/dependabot.yml
Dependabot will update the lockfile but not package.json in most cases. This means that even if we update a dependency here, the app still sees the old version in package.json and isn't forced to update it.
- https://github.com/dependabot/dependabot-core/issues/310#issuecomment-373328152
I wonder if this is what caused this `IgnorePlugin` issue:
- https://github.com/pixiebrix/pixiebrix-app/pull/2148#discussion_r952628451
- Forces Dependabot to update package.json
- Enables dependabot to update GitHub Actions too
> Dependabot: update package.json + also keep GHA up to date

- src/components/documentBuilder/documentTree.tsx
- src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
- src/components/documentBuilder/preview/elementsPreview/Card.module.scss
- src/components/documentBuilder/preview/elementsPreview/Card.tsx
- src/components/documentBuilder/render/CardElement.tsx
> #4102 Add element dropdown gets cuts off inside list element preview in Document Builder

- src/background/proxyService.test.ts
- src/background/requests.ts
- Closes #4181 
- Specially handles AA token invalidation because the CR API doesn't use 401 to indicate invalid authentication
> #4181: detect AA token invalidation

- src/background/browserAction.ts
- Avoids attempting multiple simultaneous injections in the same tab
- Shows an error when the sidebar was supposed to open, but failed
- **Note:** this PR covers an actual failure to open the sidebar rather than "unable to edit special browser pages" like https://github.com/pixiebrix/pixiebrix-extension/pull/4188
Specifically:
- Closes #4124 
-  https://github.com/pixiebrix/pixiebrix-extension/issues/4125
- The "blank slate" design of the sidebar is being handled in other tickets. I think we can use the sidebar to display any _connection_ issues, rather than _injection_ (which at this point is unlikely)
> #4124: BrowserAction: notify failed clicks; debounce clicks

- package-lock.json
- package.json
- Includes https://github.com/pixiebrix/webext-messenger/pull/84
- It shouldn't have any real user-facing changes except better errors. I just need to try to cause these errors and see if we were catching the old errors somewhere.
> Bump webext-messenger from 0.20.1 to 0.21.0-0

- src/contentScript/sidebarController.tsx
- src/sidebar/messenger/api.ts
Something I forgot to do when I implemented this:
- Pre-binds sidebar messenger methods to the sidebar instead of having to specify `{ tabId: "this", page: "/sidebar.html" }` every time
And a proposal around the usage of Messenger methods:
- Always use `sidebar.method()` instead of `method()` to clarify that the method is related to the sidebar
I applied the proposal only to the sidebar, but once accepted we can change the background one too since it's also pre-bound:
```diff
- proxyService()
+ background.proxyService()
```
This does make it a little more verbose and explicit to call these methods, but maybe it helps readability.
The content script’s messenger isn't affected by this much considering that every call is followed by the target already:
```js
cancelForm(thisTab)
```
> Update Messenger pattern to clarify the messenger usage

- package-lock.json
- package.json
- Includes https://github.com/fregante/webext-dynamic-content-scripts/pull/38
The update preserves MV2 compatibility but should add support for MV3. 
Since I'll be testing the extension on MV3, we need to start making sure that every component works as we switch between MV2 and MV3 during testing phase.
From preliminary testing, everything seems to work:
- adding a new permission via page editor
- opening the sidebar on a new website
- opening the quickbar on a new website
- detecting activeTab in the page editor
- running bricks in a newly-created "target" tab from another tab
We should make sure that the logic was not broken so it's best to merge this at a convenient time, right **after** a release, so we can test it further during development (but I don't expect issues)
> Update `webext-dynamic-content-scripts` to enable MV3 support

- src/auth/token.ts
- src/background/partnerIntegrations.ts
- src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx
- src/permissions/index.ts
- src/services/factory.test.ts
- src/services/factory.ts
- Closes #4210 
- Closes #4209
- The getOrigins method for services does include the `/token` and `/authorize` URLs for OAuth2 integrations (along with the base URL): https://github.com/pixiebrix/pixiebrix-extension/blob/8802f394eb6e7f71c519078c4e20e5139070ae17/src/services/factory.ts#L134-L134
- https://github.com/pixiebrix/pixiebrix-app/issues/2228
> #4210: fix AA partner control room setup flow

- src/contentScript/nativeEditor/elementPicker.ts
- src/contentScript/nativeEditor/selectorInference.ts
- src/pageEditor/fields/SelectorSelectorWidget.tsx
- Closes #3946 
We implemented Site Selector Hint logic in selectorInference file so that you can easily define and attach bad/good patterns for specific site easily.
For example, `Salesforce` is using light web component and `data-component-id` attribute can be good selector. 
There are also several other good anchors : `.consoleRelatedRecord`, `.oneConsoleTab` and etc...
`data-aura-rendered-by` is typical attribute that salesforce lighting web component is using but it's bad pattern since it's value is changing. 
In this PR, we're able to define several good anchors and patterns, make selector working.
Before: 
After: 
@fregante Is there any specific reason that you added `data-aura-rendered-by` to `UNSTABLE_SELECTORS` list [here](https://github.com/pixiebrix/pixiebrix-extension/blob/mai …
> #3946: Add Salesforce selector hints

- src/options/pages/blueprints/BlueprintsPage.tsx
- Closes #4246
- This adds a `BlueprintsPageView` event to the Blueprints Page.
- We are potentially interested in interactions the user has with views on the Blueprints page. We may add more specific events to this page in the future.
> Add Mixpanel BlueprintsPageView event to the Blueprints page

- src/blocks/transformers/ephemeralForm/EphemeralForm.tsx
- src/contentScript/ephemeralFormProtocol.ts
- src/contentScript/messenger/api.ts
- src/sidebar/sidebarSlice.ts
Presumably fixes this frequent error found on Rollbar.
```
Cannot perform 'get' on a proxy that has been revoked
```
- Opened on notification by @johnnymetz regarding the high amount of bug reports on Rollbar
- See review notes
- 📉 Add tests
> Avoid proxy revocation by optimizing cancelForm call

- src/errors/errorHelpers.ts
- Stops reports of `Network Error` to Rollbar
- Part of #4256
- The browser does not add further information to these errors, they most likely are a consequence of user error (e.g. due to a flaky connection, wifi captive portal, wrong address, …)
- The aggregation of these errors however could lead to the discovery of new bugs when spikes occur — I'm not sure they'd be useful in that case either though
- Opened on notification by @johnnymetz regarding the high amount of bug reports on Rollbar
Medium-high
- 😣 Add tests
> #4256: Avoid reporting bare Network Errors to Rollbar

- src/errors/errorHelpers.ts
- Part of #4256
- Stops reports of cancelled actions to [Rollbar](https://rollbar.com/pixiebrix/all/items/?sort=%5Bobject%20Object%5D&status=all&date_from=08-11-2022%2019%3A00%3A00&date_to=&environments=production&activated_to=&framework=&levels=40&levels=50&activated_from=&offset=0&timezone=Europe%2FLisbon&assigned_user=&date_filtering=seen&projects=395009&query=cancelled&enc_query=jZ2v2aRYpQxVXZqWlvLbNp11FlZxk9oGPFoq94gzQUU%3D)
- We're already ignoring the more generic "Promise cancelled" error, so the specific "User cancelled action" feels like it should be ignored too
High
- 🤫 Add tests
- #4253
> #4256: Avoid reporting user cancellation errors to Rollbar

- src/background/background.ts
- src/contentScript/lifecycle.ts
- src/contrib/google/bigquery/handlers.ts
- src/contrib/google/initGoogle.ts
- src/options/options.tsx
- src/utils/injectScriptTag.tsx
- Makes the GAPI script failure loud: script load errors don't bubble to our global handlers as [one’d expect](https://github.com/pixiebrix/pixiebrix-extension/pull/4018/files#r945211199); this PR throws a proper error when that happens
- Instead of reporting "undefined", it reports `Script failed loading: {url}`, with a cause with more information, if ever present
- Prepares initGoogle for retries, should we want to do that in the future
Also:
- cleans up/standardizes the loading code
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/3914
- Partially reverts https://github.com/pixiebrix/pixiebrix-extension/pull/4018/files
- Replaces/extends/closes https://github.com/pixiebrix/pixiebrix-extension/pull/4252
> #3914: Clean GAPI script loading

- src/background/starterBlueprints.ts
- Part of https://github.com/pixiebrix/pixiebrix-app/pull/2250
- This adds a flag to the starter blueprints request in order to accommodate older versions of the extension. This prevents older versions of the extension from installing starter blueprints for all users (even enterprise) on extension launch.
- An alternative approach is keeping everything as-is and simply waiting for a certain percentage of the new extension release to be adopted.
> Add flag to starter blueprints request to accommodate older extension versions

- src/contentScript/contentScript.ts
- src/pageScript/pageScript.ts
- src/utils/jqueryHack.ts
- Closes #4280 
- Monkey patches QSA calls from JQuery to avoid regression in Chrome 105
- The content script runs in it's own VM
- The page script has it's own copy of jquery
> #4280: monkeypatch JQuery calls to QSA use non-native :has

- src/options/pages/blueprints/BlueprintsView.tsx
- src/options/pages/blueprints/onboardingView/OnboardingView.tsx
- Fixes #4322
- This removes the Loader on the `BlueprintsView` component, because the `isLoading` state for the `useOnboarding` hook is only relevant in the situation where there is an OnboardingView.
I had originally moved the `useOnboarding` hook into the `OnboardingView` entirely, but this would cause me to mock things in the OnboardingView story, which is out of scope for now.
https://user-images.githubusercontent.com/36575242/191343104-5f2d5a85-15a2-425a-9dbc-fa8a95c3a628.mov
- There is a PR open for adding tests to the BlueprintsPage: https://github.com/pixiebrix/pixiebrix-extension/issues/4316
- Please see this PR for why adding tests is momentarily blocked (I'm prioritizing fixing this immediate bug at the moment)
> #4322: Remove useOnboarding hook loader

- src/pageEditor/sidebar/AddExtensionPointButton.tsx
- Fixes #4320 
- Second time this week I've run into an issue related to improper `async` usage that wasn't caught at all by eslint/TS
- Is there any way to catch these edge cases with another lint rule or something?
- Should we try to check every usage of `async` closely in PRs from now on?
- Any other ideas here? Maybe it's not that big a deal...
> #4320 Fix bug with Panel type incorrectly appearing in the add-extension dropdown menu

- src/pageEditor/sidebar/Sidebar.module.scss
- Fixes #4331 
Menu places properly when scrollbars are enabled:
> #4331 Fix bug with add-extension dropdown menu overflowing

- src/sidebar/Tabs.module.scss
- src/sidebar/Tabs.tsx
- Closes #4286 
Before:
After:
- Will be followed by #4290
> #4286 Limit sidebar tab header names to one line and ellipsize the text overflow

- src/components/addBlockModal/AddBlockModal.test.tsx
- src/components/addBlockModal/AddBlockModal.tsx
- src/components/addBlockModal/addBlockModalConstants.ts
- src/components/addBlockModal/groupListingsByTag.test.ts
- src/components/addBlockModal/groupListingsByTag.ts
- src/pageEditor/panes/EditorPane.test.tsx
- Closes #4289
- Using the tag names as Record keys is sketchy, but alright for now. Keys with spaces and stuff can still be accessed using bracket notation, and we're not hard-coding any tag names with spaces. We should probably refactor the `taggedBrickIds` Record to a different data structure at some point.
> #4289 Hide UiPath bricks for AA users

- src/background/starterBlueprints.test.ts
- src/background/starterBlueprints.ts
- Fixes a bug @orliesaurus was seeing when visiting the Playground page and expecting starter blueprints to install. They were not installing.
- The added test should clarify the cause of the problem, which was accessing the `id` property on an `undefined` `_recipe`.
> Fix starter blueprint installation bug when user has an installed extension with no _recipe property

- src/background/background.ts
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/4357
- This is the easiest step to take a this point. Switching to `fetch` would have its benefits, but it takes more effort. We can explore that if staying with `axios` requires more effort than just leaving it.
- Axios is only planning to add official `fetch` support in the next major version/rewrite, which has been in the works for longer than a year already. I wouldn't wait for it.
- Keep an eye on Rollbar to ensure this PR doesn't cause a regression
> #4357: Use `fetch` in background worker

- package-lock.json
- package.json
- src/background/activeTab.ts
- src/background/background.ts
- src/background/browserAction.ts
- src/background/initBrowserCommands.ts
- src/background/partnerTheme.ts
- src/contrib/google/initGoogle.ts
- src/development/errorsBadge.ts
- src/globals.d.ts
- src/mv3/api.ts
- src/telemetry/reportUncaughtErrors.ts
- src/utils/preventNativeFormSubmission.ts
- webpack.config.js
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/4356
- Part of #287
- Continues https://github.com/pixiebrix/pixiebrix-extension/pull/2107
- Includes updates to https://github.com/fregante/webext-dynamic-content-scripts/pull/38
PixieBrix seems to work for the most part. I'm only seeing an issue related to https://github.com/pixiebrix/pixiebrix-extension/issues/4387 and one likely due to the worker recycling. Reloading the extension fixes the latter
Initial failures can only be debugged by checking the first checkbox on this page: 
```
chrome://serviceworker-internals/?devtools
```
The build alters the manifest on request:
```sh
MV=3 nr build
MV=3 nr watch
```
`web-ext` commands are unchanged, the folder is the same.
- Add MV3 artifact in CI?
- …
> #4356: Add MV3 build

- .github/pull_request_template.md
- Closes #2152
- This adds a PR checklist item to manually verify that no Storybook stories were broken from the feature. Unfortunately, we don't have a quick way to add automation to this task at this time because broken Storybook stories compile without errors.
- It sucks to have to verify Storybook stories manually. However, it also sucks that Storybook stories are always breaking and not available when we need them.
- There are broken stories on `main` at the moment. I'm leaving this for another PR so as to get this checklist item in.
- Potentially automating this process? https://github.com/pixiebrix/pixiebrix-extension/issues/2152#issuecomment-1261540166
> Add Storybook stories to PR checklist

- src/background/installer.ts
- Opens the correct install page even if no pixiebrix.com tabs are open
- Avoids opening a new tab when the extension is loaded via `web-ext`
> Fix `openInstallPage` inconsistency

- src/components/addBlockModal/useBlockSearch.ts
- This is a quick fix, part of https://github.com/pixiebrix/pixiebrix-extension/issues/4404
- I noticed while researching search behavior in the Page Editor that the keys used to initialize our fuzzy search algorithm don't match the shape of the actual data `BlockOption`. This was causing search results to only be conducted over the `label`, not the `packageId` or the `description`, as we had intended. Fixing this actually makes some improvements to problems we were seeing with search experiences in the past, like:
- the search term _**automation anywhere**_ not producing Automation Anywhere brick results
- the search term _**jq**_ producing the actual jq brick matching as the second search result, rather than first
- Search results that match the query string over all three keys, …
> Improve Page Editor brick searching by fixing search over `packageId` and `description`

- src/options/pages/blueprints/ListFilters.module.scss
- src/options/pages/blueprints/ListFilters.tsx
- src/options/pages/blueprints/__snapshots__/BlueprintsCard.test.tsx.snap
- Reduces wrapping by using space better
- Avoids wrapping of text _below_ the icon
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/3513
> #3513: Align icons in Blueprints sidebar

- src/options/pages/blueprints/BlueprintsCard.tsx
- src/options/pages/blueprints/BlueprintsToolbar.tsx
- src/options/pages/blueprints/Status.tsx
- src/options/pages/blueprints/__snapshots__/BlueprintsCard.test.tsx.snap
- src/options/pages/blueprints/listView/ListItem.module.scss
- Avoids repetition
- Avoids unnecessary wrapping in tighter windows
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/3513
> #3513: Avoid repeating dropdown labels in Blueprints

- src/contentScript/sidebarDomControllerLite.ts
- Fixes #4130
The upcoming Popups API will likely solve all of our z-index related issues:
https://developer.chrome.com/blog/pop-ups-theyre-making-a-resurgence/
> #4130: Keep sidebar below QuickBar

- src/background/logging.ts
- src/contentScript/nativeEditor/elementPicker.ts
- src/errors/errorHelpers.ts
- src/errors/networkErrorHelpers.ts
- src/pageEditor/fields/SelectorSelectorWidget.tsx
- src/pageEditor/hooks/useAddElement.ts
- src/pageEditor/tabState/tabStateSlice.ts
- src/services/serviceUtils.ts
- Stops showing an error when the user cancels an element selection
This matches existing behavior in `useAddElement`:
https://github.com/pixiebrix/pixiebrix-extension/blob/e60ad1ad95f8ac7bda6f0bf4377dbf5bd0ffb2f5/src/pageEditor/hooks/useAddElement.ts#L85-L93
- https://github.com/pixiebrix/pixiebrix-extension/pull/4451
> Don't show error when user stops the element picker

- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/contentScript/nativeEditor/elementPicker.ts
- src/pageEditor/protocol.ts
- Closes #4441 
- we're using `beforeunload` event listener to catch dev tool closing event.
> #4441: Stop inspecting after dev tool is closed

- src/background/activeTab.ts
- src/background/browserAction.ts
- src/background/contentScript.ts
- src/background/contextMenus.ts
- src/background/deployment.test.ts
- src/background/deployment.ts
- src/background/initBrowserCommands.ts
- src/background/messenger/registration.ts
- src/background/navigation.ts
- src/background/permissionPrompt.ts
- src/background/starterBlueprints.test.ts
- src/background/starterBlueprints.ts
- src/chrome.ts
- src/pageEditor/ErrorBanner.tsx
- src/pageEditor/tabState/tabStateSlice.ts
- Fixes the error message for the user
- Avoids unnecessary Error wrapping 
- Drops dead code (the 15s timeout was never reached)
- Wraps entire `ensureContentScript` into a single timeout
- Rename `@/background/utils` to `@/background/contentScript` to be more specific
- https://github.com/pixiebrix/pixiebrix-extension/issues/4189
- https://github.com/sindresorhus/p-timeout/issues/31
> Adjust injection expectations in `connectToContentScript`

- .github/workflows/loom-slack.yml
- src/__mocks__/@/hooks/useContextInvalidated.ts
- src/hooks/useContextInvalidated.ts
- src/sidebar/ErrorBanner.tsx
- src/sidebar/Header.tsx
- src/sidebar/SidebarApp.test.tsx
- src/sidebar/SidebarApp.tsx
- src/sidebar/__snapshots__/SidebarApp.test.tsx.snap
- Continues from https://github.com/pixiebrix/pixiebrix-extension/pull/4117
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/2359
[](https://github.com/pixiebrix/pixiebrix-extension/issues/4193)
I started this PR to add a "Reload Sidebar" to the "context invalidated" message but that's currently not possible:
- messaging is blocked after invalidation
- sidebar manager lives in the content script:  https://github.com/pixiebrix/pixiebrix-extension/blob/main/src/contentScript/sidebarController.tsx#L70-L95
The style matches the bootstrap-native alert bar that we use in the editor as well:
> #2359: Cleanup sidebar "context invalidated" state

- src/components/addBlockModal/AddBlockModal.module.scss
> #4360: Round corner in AddBlockModal

- .github/workflows/loom-slack.yml
- src/pageEditor/sidebar/SidebarExpanded.tsx
- src/pageEditor/sidebar/arrangeElements.ts
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/2614
- Related to https://github.com/pixiebrix/pixiebrix-extension/issues/2657
- The UI is waiting to show "everything" when the necessary parts are already available and sub-components that require additional loading time already handle it
This specific piece of code was added in https://github.com/pixiebrix/pixiebrix-extension/pull/2495/files#diff-a49d57aac9f4c53630d736168e2ffb549d29ab3aa545f3e6f32faeba02601a45
https://www.loom.com/share/fdec5eded32345a68b20573845c35959
> #2614: Show extension list much earlier in page editor

- src/options/pages/settings/AdvancedSettings.tsx
- Closes #4539
- Removes feature flag from Partner ID Advanced Setting so unauthenticated users can set the flag
- 😢  Add tests: N/A
- 😢  Run Storybook and manually confirm that all stories are working
> #4539: remove feature flag from partner id field

- public/mockServiceWorker.js
- src/auth/RequireAuth.tsx
- src/auth/token.ts
- src/auth/useRequiredPartnerAuth.test.tsx
- src/auth/useRequiredPartnerAuth.ts
- src/options/App.tsx
- src/options/pages/onboarding/SetupPage.tsx
- src/options/pages/onboarding/partner/PartnerSetupCard.tsx
- src/options/pages/settings/AdvancedSettings.tsx
- src/services/baseService.ts
- src/store/settingsSlice.ts
- src/store/settingsTypes.ts
- Workaround of #4542
- Trying to unblock partner, so exposing Settings > Advance Settings Options to force which authentication method is used by the extension
- Mode Options
- pixiebrix-token
- partner-oauth2
- partner-token: user still authenticates using PixieBrix token, but they also have to have a integration configuration installed for the Control Room
- 😢  Add tests - on time deadline, will circle back
- 😢  Add tests Run Storybook and manually confirm that all stories are working - on time deadline, will circle back
> #4542: make auth mode option explicit in advance settings

- src/contentScript/nativeEditor/selectorInference.test.ts
- src/contentScript/nativeEditor/selectorInference.ts
- Closes #4506 
- Fix some logic of commonCssSelector found while doing tests.
- fixed getting common classname of elements
> #4506:  Add Jest test cases for commonCssSelector

- src/services/api.ts
- Fixes #4499 
- Adds the `PackageVersion` RTK query tag to to the `updatePackage` mutation so that the diff viewer refreshes properly when updating a brick in the editor.
https://user-images.githubusercontent.com/36575242/199361652-753bf7fc-b868-4c9a-be83-7f220e6394df.mov
> #4499 add PackageVersion to invalidated tags on updatePackage mutation

- src/sidebar/ConnectedSidebar.test.tsx
- src/sidebar/LoginPanel.stories.tsx
- src/sidebar/LoginPanel.tsx
- src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap
- Closes #4548
- This modifies the "disconnected" Sidebar view for the case where a partner user is disconnected either from an expired partner token or from never having authenticated before. In this case, the user will be directed back to the extension where they'll be prompted to reconnect via OAuth2.
- Due to some additional complexity copying the `ControlRoomOAuthForm` & testing, I am leaving authenticating within the Sidebar itself for future work.
- Improve the UX for users that have expired tokens by allowing them to authenticate directly within the Sidebar, instead of being redirect back to the Extension Console https://github.com/pixiebrix/pixiebrix-extension/issues/4589
> #4548 add disconnected Sidebar view for Partner users

- src/background/logging.ts
- src/pageEditor/pageEditor.tsx
- src/pageEditor/sidebar/SidebarExpanded.tsx
- src/utils/performance.ts
- Part of #4485 
- Sending performance metrics from Page Editor to Rollbar
Rollbar event
> #4485 Send slow Page Editor times to rollbar

- src/pageEditor/tabState/tabStateSlice.ts
- Follow up from #4489 
- "context invalidated" errors should not be reported to rollbar
> #4489 Don't report context-invalidated errors to rollbar

- src/auth/RequireAuth.tsx
- src/auth/token.ts
- src/auth/useLinkState.ts
- src/auth/useRequiredPartnerAuth.ts
- src/background/partnerIntegrations.ts
- src/options/Navbar.tsx
- src/options/__snapshots__/Navbar.test.tsx.snap
- src/options/pages/onboarding/SetupPage.test.tsx
- src/options/pages/onboarding/SetupPage.tsx
- src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx
- src/options/pages/onboarding/partner/PartnerSetupCard.tsx
- src/options/pages/settings/AdvancedSettings.tsx
- src/services/api.ts
- src/store/settingsSlice.ts
- static/managedStorageSchema.json
- Part of #2453
- Fixes: https://github.com/pixiebrix/pixiebrix-extension/issues/4594
- Fixes: https://github.com/pixiebrix/pixiebrix-extension/issues/4628
- Add `controlRoomUrl` field to `managedStorageSchema.json` for enterprise IT departments to set as part of enterprise rollout
- PartnerSetupCard: Check and use configured `controlRoomUrl` in managed storage
- ControlRoomOAuthForm: fix `null` value handling for `settingsSlice.authServiceId`
- useRequiredPartnerAuth: check for  configured `controlRoomUrl` in managed storage, fix partner JWT check
- Check actual Control Room URL in cached partner auth data matches expected Control Room URL. (Unlikely for now that enterprise rollout users would need to switch)
> #2453: partner oauth2 login fixes

- src/options/pages/onboarding/partner/PartnerSetupCard.stories.tsx
- Closes #4657 
- Wraps partner onboarding stories in HashRouter to support inner useLocation call
- Applies partner theme colors to the stories
> #4657: fix partner login storybook stories

- README.md
- Drops Firefox from readme support grid because we don't currently official support it
> Drop Firefox from README

- src/background/auth.test.ts
- src/background/auth.ts
- src/background/browserAction.ts
- src/background/contextMenus.ts
- src/background/starterBlueprints.ts
- src/utils.test.ts
- src/utils.ts
- part of https://github.com/pixiebrix/pixiebrix-extension/issues/4358
I'm looking for and replacing all instances of data that should be stored in `chrome.storage.session`. This brought me to replace a couple of patterns around `getToken` and `ensureContextMenus`
> #4358: Use standard memoize instead of custom storage logic

- __mocks__/webext-messenger.js
- package-lock.json
- package.json
- src/background/executor.ts
- src/background/messenger/api.ts
- src/background/messenger/registration.ts
- src/blocks/renderers/customForm.tsx
- src/blocks/transformers/ephemeralForm/formTransformer.ts
- src/components/documentBuilder/documentTree.test.tsx
- src/components/documentBuilder/render/BlockElement.tsx
- src/components/documentBuilder/render/ButtonElement.tsx
- src/components/documentBuilder/render/ListElement.tsx
- src/contentScript/contentScriptCore.ts
- src/contentScript/context.ts
- src/contentScript/lifecycle.ts
- src/sidebar/ErrorBoundary.tsx
- src/sidebar/Header.tsx
- src/sidebar/sidebarSlice.ts
- Includes https://github.com/pixiebrix/webext-messenger/pull/89
- The messenger already knows its own tab as soon as the content script is executed
- Most of the time, we're fetching the current target only to know the top-level frame, so I exposed an API just for that
- There's a native API under discussion for this, however it might not be accepted anytime soon https://github.com/w3c/webextensions/issues/12
- In the future, I might just expose a `{tabId: "this", frameId: "top"}` object, but that requires extra logic in the sender
> Avoid Messenger roundtrip when fetching current tab data

- src/components/documentBuilder/documentTree.test.tsx
https://github.com/pixiebrix/pixiebrix-extension/pull/4696 and https://github.com/pixiebrix/pixiebrix-extension/pull/4699 each dropped a mock for the background API, so now it's not used by either
> Fix merge conflict

- src/pageEditor/tabs/effect/BlockConfiguration.test.tsx
- src/pageEditor/tabs/effect/BlockConfiguration.tsx
- src/testUtils/factories.ts
- Closes #4705 
- Modified BlockConfiguration to show Root Mode field for menuItem and quickBar
> #4705: show root mode for menuItem and quickBar

- src/vendors/theme/assets/styles/_colors.scss
- As part of kicking off incremental design system improvement work, we decided to start by creating a color variables file to define variables for colors that we are already hard-coding in our css modules
1. Whenever implementing or touching an existing css file, take stock of existing hard-coded color hex codes
2. For each hard-coded hex code, find the matching variable for it in `_colors.scss`
4. Otherwise, define a new color variable in `_colors.scss`
a. If the color is defined as a token in our Figma design system document here: https://www.figma.com/file/LiShRwQlnRG5zNl38oGCKl/%F0%9F%94%91-Foundation?node-id=359%3A11872&t=clXjxbSfhvEFAlPW-0, use the token name
b. Otherwise, come up with a good, descriptive name for the color
3. Import variables at the top of your css module `@import …
> Add Design System color variables file

- src/options/pages/onboarding/SetupPage.test.tsx
- src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx
- src/options/pages/onboarding/partner/ControlRoomTokenForm.tsx
- Closes #4731 
- Required due to /start URL logic in SetupPage
> #4731: redirect to blueprints screen after /start URL

- contrib/services/automation-anywhere-oauth2.yaml
- src/auth/authTypes.ts
- src/auth/token.ts
- src/background/background.ts
- src/background/partnerIntegrations.test.ts
- src/background/partnerIntegrations.ts
- src/services/factory.test.ts
- src/services/locator.ts
- Closes #4732 
- If using an AA JWT with a refresh_token, automatically refresh the token every 10 min
- On refresh failure (e.g., due to expiration), the code doesn't clear out the token state
- If the JWT is expired, the next time the JWT is used to authenticate against our API or the control room, it will be cleared out, prompting re-authentication
- TBD
> #4732: refresh partner auth token in the background

- src/errors/errorHelpers.test.ts
- src/errors/errorHelpers.ts
- src/errors/networkErrorHelpers.ts
- Closes #4763 
- Accounts for moduleName_className error class names in optimized code
> #4763: account for error class name namespacing/hoisting in production bundles

- src/errors/errorHelpers.test.ts
- src/errors/errorHelpers.ts
- src/errors/networkErrorHelpers.ts
- webpack.config.js
- Reverts #4767
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/4763
- Related to https://github.com/pixiebrix/pixiebrix-extension/pull/3731
Webpack is mangling the names due to `concatenateModules`, but we can't expect them to be stable. `concatenateModules` currently only saves a few KBs (1.09MB -> 1.05MB), so it's not worth keeping it.
Alternative solutions:
- use both a static and instance name: `Err {name = 'Err'; static name = 'Err'}`
- TS complains
- no way to enforce it
- extract the name from the constructor by instantiating it
- some errors **require** additional arguments, so we can't safely call `new` on them 
Future solution:
- https://github.com/sindresorhus/serialize-error/issues/72
- https://github.com/pixiebrix/pixiebrix-extension/blob/65427ee747ec2df78716 …
> Avoid error class name mangling in webpack

- src/background/contentScript.ts
- src/contentScript/messenger/api.ts
- src/contentScript/messenger/registration.ts
- src/contentScript/ready.ts
- Reverts one file from https://github.com/pixiebrix/pixiebrix-extension/pull/4728
- Brings `executeFunction` back because we have different expectations around retries (and probably other issues that are causing the page editor to break)
My editor still worked before this PR, so I don't know if this fixes it.
- It seems to work for me. This reverts the relevant change from the PR
> Restore `getTargetState`

- src/background/auth.ts
- src/background/partnerIntegrations.test.ts
- src/background/partnerIntegrations.ts
- Part of #4732
- Fixes bug where the refreshed token wasn't being saved in the oauth2 token cache
> #4732: save refreshed token in token cache

- jest.config.json
- src/testUtils/testEnv.js
- Allows to mute `console.debug` output in tests while you can still use `console.log` while debugging unit tests.
- To mite debug messages, add `NO_DEBUG_OUTPUT_IN_TESTS=true` to your `.env` file
- We use `console.debug` extensively. This creates a lot of noise when working on unit tests.
Before:
Same test after:
> Optionally disable debug output in tests

- package-lock.json
- package.json
- src/errors/networkErrorHelpers.test.ts
- src/errors/networkErrorHelpers.ts
- src/hooks/useRefresh.ts
- src/options/pages/brickEditor/useSubmitBrick.test.tsx
- src/options/pages/brickEditor/useSubmitBrick.ts
- src/services/api.test.tsx
- src/services/api.ts
- src/testUtils/testMiddleware.ts
- Closes #4792 
- Adds tests for Axis error handling: error shape from Axios and RTK base query
- Adds 400 error test for useSubmitBrick
- Disables cache invalidate on 400 error for updatePackage and updateRecipe endpoint
> #4792: fix workshop reset to original data on 400 error

- src/__mocks__/@/sandbox/messenger/api.ts
- src/extensionPoints/menuItemExtension.ts
- src/runtime/mapArgs.test.ts
- src/runtime/mapArgs.ts
- src/runtime/reducePipeline.ts
- src/runtime/renderers.ts
- src/runtime/runtimeUtils.ts
- src/sandbox/messenger/api.ts
- src/sandbox/messenger/executor.ts
- src/sandbox/messenger/registration.ts
- src/utils/postMessage.ts
- webpack.config.js
- Part of #4730
- Uses Chrome sandbox for calls to nunjucks and handlebars from runtime
- No user-facing changes
- Update Nunjucks constructor call in variable analysis framework. Might need to shift work to sandbox?
> #4730: sandbox nunjucks and handlebars calls from runtime

- src/sandbox/messenger/executor.test.ts
- src/sandbox/messenger/executor.ts
- Follow up for #4730
- Add missing re-throw
> #4730: rethrow non-nunjucks error in sandbox

- src/__mocks__/@/icons/list.ts
Restores the mock deleted in https://github.com/pixiebrix/pixiebrix-extension/pull/3934 and that was causing issues in https://github.com/pixiebrix/pixiebrix-app/pull/2779
It was introduced to speed up the build(s), sometimes on demand: 
https://github.com/pixiebrix/pixiebrix-extension/blob/6279fbd3322406d94621dbe559090dc231dd5ea9/webpack.config.js#L240-L246
> Restore `@/icons/list` mock

- src/pageEditor/components/Effect.tsx
- src/pageEditor/hooks/useCreate.ts
- src/pageEditor/hooks/useSaveRecipe.ts
- src/pageEditor/panes/EditorPane.test.tsx
- Fixes of #4857 
- Saving the blueprint is not a blocking task anymore (not related to this PR)
- After saving the blueprint page shows loader. This is because of re-fetching all the recipes from the server
- Despite calling the user permission earlier, the orange warning still appears after creating a new recipe
https://www.loom.com/share/eca5cd23314d4d2ca7a4e78438ca0e98
> #4857 Bug: Performance issue with the recipe update operation

- src/components/ellipsisMenu/EllipsisMenu.tsx
- src/options/pages/blueprints/BlueprintActions.tsx
- Part of #4820
- Uses type fest `RequireExactlyOne` for the `EllipsisMenuItem` type
> Marketplace Publish A4: Link to Published Marketplace Listing #4820

- src/blocks/effects/registerEffects.ts
- src/blocks/effects/replaceText.test.ts
- src/blocks/effects/replaceText.ts
- src/development/headers.ts
- Closes #4864 
- Adds a new brick that replaces text within elements
- The brick default isRegex to `false` if not provided
- To expose case insensitive mode in the future, can use https://www.npmjs.com/package/regex-escape to convert a string to a regex and then pass the `i` flag to the regex 
- https://www.loom.com/share/f1e8535eaf344304b1977d329d03253f
> #4864: add replace text brick

- .github/actions/upload-zipped-artifact/action.yml
- .github/workflows/ci.yml
- src/chrome.ts
- src/utils/expectContext.ts
- Avoids importing the polyfill in pageScript.js
- Adds a simple detection on CI to avoid the same issue in the future
- Permanently fixes #4869 
- Related to https://github.com/pixiebrix/pixiebrix-extension/pull/2671
Notice how the first commit fails because it correctly detects the existing issue and how the second one passes because the issue has been fixed.
If we ever get around to full automatic code splitting, a grep-based approach will no longer be enough:
- https://github.com/pixiebrix/pixiebrix-extension/pull/2676
> #4869: Detect mistaken polyfill import in pageScript.js

- src/background/contentScript.ts
This PR just clarifies why a certain action was taken while waiting for the content script. It helps with debugging.
See 
- https://github.com/pixiebrix/pixiebrix-extension/issues/4863#issuecomment-1364939061
> #4863: Clarify `ensureContentScript` logging

- .github/pull_request_template.md
Should we drop this from the PR checklist thanks to:
- #4812
> #4812: Drop "check storybook" checkbox from PR template

- schemas/element.json
- src/blocks/readers/ElementReader.test.ts
- src/blocks/readers/ElementReader.ts
- src/blocks/transformers/controlFlow/ForEachElement.test.ts
- src/blocks/transformers/controlFlow/ForEachElement.ts
- src/blocks/transformers/registerTransformers.ts
- src/blocks/transformers/traverseElements.test.ts
- src/blocks/transformers/traverseElements.ts
- src/blocks/types.ts
- src/contentScript/elementReference.test.ts
- src/contentScript/elementReference.ts
- src/core.ts
- src/development/headers.ts
- src/pageEditor/exampleBlockConfigs.ts
- src/pageEditor/extensionPoints/base.test.ts
- src/pageEditor/extensionPoints/base.ts
- src/pageEditor/tabs/effect/BlockConfiguration.test.tsx
- src/pageEditor/tabs/effect/BlockConfiguration.tsx
- src/pageEditor/tabs/effect/BlockPreview.tsx
- src/runtime/pipelineTests/root.test.ts
- src/runtime/reducePipeline.ts
- src/runtime/runtimeUtils.ts
- src/types/helpers.ts
- src/validators/generic.ts
- Implementation of https://www.notion.so/pixiebrix/Explicitly-Referring-to-HTML-Elements-to-make-scraping-automation-use-cases-easier-df1415ba0cd149acb158bb0b9a0e395c
Phase 1
Phase 2:
- I turned off preview for "element" and "inherit" mode entirely. The "inherit" logic was not correct anymore because it didn't account for For-Each Element loops
- Re-enable preview pane for certain cases of "inherit" and "element"
- I was mistaken when writing the spec. The menu item extension point currently always passes the document as the reader root. So we're going to need to provide a way in the future to get which menu item was clicked: https://github.com/pixiebrix/pixiebrix-extension/blob/feature%2Fexplicit-element/src/extensionPoints/menuItemExtension.ts#L342-L342
- Update non-root aware bricks …
> Add support for passing an explicit element to root-aware bricks

- src/analysis/analysisVisitors/regexAnalysis.ts
- src/analysis/analysisVisitors/regexAnalysisTest.test.ts
- src/pageEditor/analysisManager.ts
- Adds analysis engine rule to check regex validity
- Checks that literal is a valid regex (regex can compile)
- Checks that the regex contains at least one named group
- https://www.loom.com/share/f8694f5260334a8cb84fc1cdd022d83e
> Add analysis rule to check regex pattern validity

- src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
- src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx
- Closes #4899 
- Disables variable autosuggest in locations where analysis is available (because VarPopup errors out when the user types a `@`)
- This could have alternatively checked to see if the component was running in the dev tools context. The check for an analysis slice is conceptually cleaner
- Add tests: @BALEHOK will need to add tests in the future for triggering the var popup
> #4899: disable autosuggest in service configuration

- schemas/component.json
- schemas/service.json
- src/blocks/transformers/blockFactory.test.js
- src/blocks/transformers/blockFactory.ts
- src/components/fields/schemaFields/genericOptionsFactory.test.ts
- src/components/fields/schemaFields/genericOptionsFactory.tsx
- src/core.ts
- src/hooks/useBlockOptions.ts
- src/options/pages/services/ServiceEditorModal.tsx
- Implementation of https://www.notion.so/pixiebrix/Brick-Configuration-Input-Ordering-b09c9a93c3d64f98b463ddafd6e395fb
- Add support for uiSchema field with `ui:order` in brick definitions and service definitions
- If no `ui:order` provided for a YAML brick, apply default input field order rules
- https://www.loom.com/share/3d199ce41d4146fb9434efc38160c339
- Create an app PR to support uiSchema on bricks and services. (Requires JSON Schema update): https://github.com/pixiebrix/pixiebrix-app/pull/2813
- Update the app front-end to use service uiSchema for the ServiceEditorModal
> Support uiSchema for bricks/services and sort YAML-brick input fields if no uiSchema present

- src/blocks/effects/highlightText.test.ts
- src/blocks/effects/highlightText.ts
- src/blocks/effects/registerEffects.ts
- src/blocks/effects/replaceText.ts
- src/development/headers.ts
- Adds a highlight text brick
- Walks text nodes and wraps matched text in `mark` tag
- If the text is already an immediate child of a `mark` tag, it does not re-highlight the text
- I'm just calling `sanitize` on the textContent and passing it as instead of manually re-assembling the text nodes. I don't think tags will appear in textContent on normal sites. (I think they'd have to have to have been programmatically added)
- https://www.loom.com/share/0f929322091e48d98e98c034b06a4e39
- Expose an option for passing an arbitrary style for the element
> Add highlight text brick

- src/auth/authTypes.ts
- src/auth/authUtils.ts
- src/auth/token.ts
- src/background/partnerIntegrations.ts
- src/contrib/automationanywhere/BotOptions.test.tsx
- src/contrib/automationanywhere/BotOptions.tsx
- src/contrib/automationanywhere/RunBot.test.ts
- src/contrib/automationanywhere/RunBot.ts
- src/contrib/automationanywhere/aaTypes.ts
- src/core.ts
- src/types/swagger.ts
- Closes #4142 
- Exposes an `isAttended` flag on the run AA bot brick to run the bot in attended mode using the authenticated user's account
- Depends on server PR: https://github.com/pixiebrix/pixiebrix-app/pull/2817, which includes the control room principal's numeric id in the `/api/me` response that the extension caches
- Adds tests for the AA Run Bot brick
> #4142: add support for running attended AA bot via OAuth2

- contrib/services/greenhouse.yaml
- schemas/service.json
- src/core.ts
- src/services/factory.test.ts
- src/services/factory.ts
- src/types.ts
- src/types/definitions.ts
- Adds support for integrations that use basic auth
- This PR assembles the header manually. Could have probably alternatively have passed in axios's `auth` property
- Create a corresponding PR in the app repository
> Add support for integrations using HTTP basic auth

- src/analysis/analysisVisitors/traceAnalysis.test.ts
- src/analysis/analysisVisitors/traceAnalysis.ts
- src/blocks/transformers/jq.test.ts
- src/blocks/transformers/jq.ts
- Fixes #4815 
- Fixes a bug in the `instanceLocation` of jq compile errors translated to runtime InputValidationErrors
- Fixes bug in TraceAnalysis where if no matching instanceLocations were found, no annotations would be added
> #4815: fix jq compile error annotation and status badge

- src/blocks/effects/wait.ts
- src/components/DelayedRender.tsx
- src/hooks/useTimeoutState.test.ts
- src/hooks/useTimeoutState.ts
- src/pageEditor/ErrorBanner.tsx
- src/pageScript/pageScript.ts
- src/utils.ts
Opening the sidebar causes this warning to appear in the console:
> Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function
I took the opportunity to:
- add `useTimeoutState` to implement this stuff the right way + add tests
- drop a duplicate timeout function
> Fix "unmounted component" warning in sidebar

- src/background/background.ts
- src/background/contentScript.test.ts
- src/background/contentScript.ts
- Closes #4863 
- Fixes `background/contentScript` to consider tab and frame when receiving contentScript ready messages
- One thing I'm not sure about is whether the memoized `ensureContentScript` should have the timeout embedded in it, or if each caller should be responsible for setting its own timeout. It's likely OK as-is -- the only potential downside is it prevents getting lucky on a 2nd call to ensureContentScript that's made at 3.99 seconds
- We may also want validate the origin URL to ensure the message being received is for the correct page altogether
- We may want to remove the entry when a tab is removed. To efficiently do that we'd use a nested map of `tab -> frame -> promise`. The memory leak isn't likely too bad though, because it'd only leak for tabs where …
> #4863: consider tab/frame when handling ENSURE_CONTENT_SCRIPT_READY message

- src/background/contextMenus.test.ts
- Part of #4863: add Jest tests for registering context menus
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/4937 to add some sanity checks in debugging the GitHub issue
- No functional changes
> #4863: add context menu registration tests

- src/chrome.ts
- src/hooks/useDeployments.ts
- src/options/pages/settings/AdvancedSettings.tsx
- src/utils.ts
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/2512/files#r1059708642
- If Chrome hasn't already downloaded the extension by the time they click "Update extension", the extension will no longer reload _the previous version_, it will just inform the user.
Assumptions:
- "available" means it's downloaded and ready, not simply available on CWS
- `requestUpdateCheck` does not wait for the extension to load (in our case it could take a minute), it only waits for the CWS API request to complete.
Here's how I suppose the API the works:
0. Extension is available on CWS, but Chrome hasn't checked
2. `requestUpdateCheck` causes the browser to contact CWS
- if a version is available it will start downloading
3. `requestUpdateCheck`’s returned promise will resolve with `"no_update"` …
> #2512: Only reload the browser if the extension has been updated

- src/options/pages/blueprints/BlueprintActions.tsx
- src/options/pages/blueprints/useInstallableViewItemActions.test.tsx
- src/options/pages/blueprints/useInstallableViewItemActions.ts
- src/options/pages/blueprints/utils/exportBlueprint.ts
- Closes #4921 
- Removes "Export Blueprint" action from blueprint screen
- See comment here: https://github.com/pixiebrix/pixiebrix-extension/issues/4921#issuecomment-1368528626. Now that we have "Make a Copy" in the Page Editor, it's likely time to remove this export action altogether
> #4921: remove export blueprint action

- src/contrib/automationanywhere/BotOptions.tsx
- src/contrib/automationanywhere/RunBot.test.ts
- src/contrib/automationanywhere/RunBot.ts
- Closes #4142 
- Adds an information message about being unable to run a bot in attended mode using a Bot Creator license
- Switches "private" folder bots to use the authenticated user only if isAttended is set. Previously, private folder bots would always run the authenticated user as the runAsUser
- TODO
> #4142: fix AA attended bot behavior for EE

- src/blocks/transformers/jq.ts
- src/runtime/renderers.ts
- Part of #4964 
- For 1.7.16 we're disabling template sandboxing while we investigate the runtime crash
- I left the sandbox in there (including the ping/pong). I just bypassed it for template and jq rendering
- I confirmed the problematic brick is not erroring out with this PR
- Figure out what's causing the issue. Potentially put being a skunkworks flag
> #4964: disable template and jq sandboxing

- src/blocks/effects/forms.ts
- src/blocks/transformers/FormData.ts
- Fixes #4971 
https://www.loom.com/share/1bd0b8e67fa940f69971d40d856a5306
- Tracking the selectors for property _names_ in #4988
> #4971 Form Fill and Form Reader bricks should use selector input types

- jest.config.json
Finding the test error on CI takes too long because Jest outputs a list of _every file_ we have in the project. 
Example: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/3872008390/jobs/6600357244
You might not have noticed due to this noise, but our test is producing a silent error and it's at the top of such list. I opened #4986 
The error is shown right under the PASS list
> Silence Jest coverage CLI 1000-lines noise

- webpack.config.js
This was picked up from the original MV3 PR, initially added because that's how optional permissions were supposed to work.
> Drop mistaken `*://*/*` in MV3

- jest.config.json
- package-lock.json
- package.json
- src/__snapshots__/Storyshots.test.js.snap
- src/components/LinkifiedString.test.tsx
- src/components/LinkifiedString.tsx
- src/components/__snapshots__/LinkifiedString.test.tsx.snap
- src/components/form/FieldTemplate.tsx
- src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
- src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
- src/options/pages/blueprints/modals/convertToRecipeModal/__snapshots__/ConvertToRecipeModal.test.tsx.snap
- src/options/pages/services/__snapshots__/ServiceEditorModal.test.tsx.snap
- src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
- src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
1. Visit https://app.pixiebrix.com/activate?id=@pixies/content-management-demo
2. Click "Configure"
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img src="https://user-images.githubusercontent.com/1402241/211462461-18f4e561-ec08-49ee-be45-870180e877d9.gif">
<td><img src="https://user-images.githubusercontent.com/1402241/211462456-a3a314e7-4058-4908-8fe4-bb01f7885e6b.gif">
</table>
This is the lowest-level place I found. If you know of other parts that would benefit from linkification, let me know.
This change also applies to the page editor. Here it ignores any pre-existing links/dom:
An alternative solution with a broader impact would be to use a barebones "markdown" parser so we don't have to create JSX for this kind of content:
https://github.com/pixiebrix/pixiebrix-extension/blob/9dfc712 …
> #4994: Make links in Field descriptions clickable

- src/blocks/effects/forms.test.ts
- src/blocks/effects/forms.ts
- src/pageEditor/exampleBlockConfigs.ts
- Part of #4910
- Makes `selector` optional for Set Input Value brick if the target element is a field
- Includes an input entry by default when adding the brick
- https://www.loom.com/share/0174c5a1480a45b5a7a21f6e993636d6
> #4910: make selector for Set Input Value optional if root is field

- src/contentScript/contentScript.ts
- src/development/visualInjection.ts
- For #4863
This makes it immediately visible if and when a content script is injected, and whether it's been injected multiple times.
Note: this indicates whether `contentScript/contentScript` was injected, not `contentScriptCore`
Here you can see multiple injections (caused by an extension reload):
This visual indicator could make it easier to detect issues even without opening the console.
Here you can see the indicator in frames too:
https://alt-ephiframe.vercel.app/?iframe=.test
And here you can see that the content screen wasn't injected:
https://alt-ephiframe.vercel.app/Outer?iframe=https://extra-ephiframe.vercel.app/Cross-domain-iframe
> #4863: Make content script injection visible

- src/contrib/automationanywhere/RunBot.test.ts
- src/contrib/automationanywhere/aaApi.ts
- src/contrib/automationanywhere/aaUtils.test.ts
- src/contrib/automationanywhere/aaUtils.ts
- src/contrib/automationanywhere/contract.ts
- Closes #4196 
- Switches to `/v3/activity/list` and `/v3/activity/execution/:activityId` endpoints
- We'll also manually QA once we cut a release build with it
- I confirmed the requests are working against our 0.26 CR
> #4196: update API endpoints for awaiting result

- src/background/deployment.test.ts
- src/background/deployment.ts
- src/baseRegistry.ts
- src/blocks/registry.ts
- src/hooks/useDeployments.ts
- src/hooks/useRefreshRegistries.ts
- src/options/App.tsx
- src/options/pages/brickEditor/useSubmitBrick.ts
- src/pageEditor/EditorContent.test.tsx
- src/pageEditor/Panel.tsx
- src/pageEditor/panes/EditorPane.test.tsx
- Fixes: #5049 
- There was a bug in the registry fetch method where it would remove the items from the cache and save them to IDB, but not re-register them
- Renames useRefresh to useRefreshRegistries
- 😞  Add tests: we don't have unit tests for baseRegistry yet. I'll add some after we cut a beta with this PR
> #5049: ensure YAML bricks are shown in add brick modal

- src/hooks/useExtensionPermissions.test.ts
- src/hooks/useExtensionPermissions.ts
- src/options/pages/settings/PermissionsSettings.tsx
- src/testUtils/testHelpers.tsx
- The permission list in the options page now automatically updates when permissions are added or removed. 
This means we won't show a stale view to the user anymore. This change is akin to the Page Editor’s ability to detect other open sessions.
https://user-images.githubusercontent.com/1402241/213497923-05740793-5e5f-4388-b261-a5337a6cee8b.mov
also on loom: https://www.loom.com/share/84e53912d68a4c0ea09d9a244d893c89
- the permission list is complete again, also showing overlapping permissions
- Partially undoes https://github.com/pixiebrix/pixiebrix-extension/pull/2778
- Lets us see the real permissions list without opening the console https://github.com/pixiebrix/pixiebrix-extension/issues/4863#issuecomment-1380751741
"Overlapping" or _shadowed_ permission is an origin permission …
> Live and complete permission list in options

- package-lock.json
- package.json
- Adds the updated package.json and package-lock.json to the repo after running `npm install @swc/core` 
- Issues with running tests (bindings not found) like shown below do not occur now for M1 Mac users
> Installs swc/core, fixing jest issue for M1 Mac users

- src/options/pages/blueprints/BlueprintsPageLayout.test.tsx
-  Closes #4962 
- I have tried to assert that the console.error function has been called with a string matching part of the error output, but it doesn't match correctly. 
- I believe it's because the error output derives from objects, but I can't match them correctly / I don't think this is the correct way to go.
- I attempted: 
```javascript 
expect(spy).toHaveBeenCalledWith(
expect.stringContaining("A non-serializable value was detected")
);
```
- and received: 
- I also attempted using functions:
- .toThrowError()
- .toHaveErrorMessage()
- .toReturnWith()
- .toContain()
- ... all of which do not work because of what I described above or the fact that console.error() does not throw exceptions or return a value
- ~Any ideas or guidance is much appreciated~
- The above has since been …
> Adds test that redux serializableCheck fails

- src/blocks/renderers/customForm.test.tsx
- src/blocks/renderers/customForm.tsx
- src/pageEditor/fields/FormRendererOptions.tsx
- Closes #5084
- Adds an `autoSave` option to the Custom Form brick to support filtering/search use cases
- When I had originally tried this last week, I was hitting issues with the field losing focus as I type. Now it appears to be working 🤷 
- https://www.loom.com/share/21c4b62a335b4c548a4f9e7d81687fb1
- Get rid of loading indicator flicker. On sub bricks of document reader, likely need way to provide option to keep the old component while waiting for the next value
> #5084: support auto save in custom form brick

- .github/workflows/rainforestqa.yml
- Closes #5126 
- Sets up cron job to run rainforest qa on main nightly(3am EST)
- Sets up running on release branches
> 5126: Update rainforest workflow to run for releases and nightly on main

- src/registry/localRegistry.ts
- Fixes #5160 
- Fixes a type error in localRegistry when timestamp was persisted as a string
Old code saved in registry as date: https://github.com/pixiebrix/pixiebrix-extension/pull/5136/files#diff-ca01f9a58613d030266309c55fc73cf815e9be92274cb3efbf121b1a699b2095L252
Not sure how, but my local machine somehow had string for timestamp:
> #5160: fix type error in localRegistry

- src/baseRegistry.ts
- src/blocks/registry.test.ts
- src/blocks/registry.ts
- src/development/headers.ts
- src/pageEditor/extensionPoints/pipelineMapping.ts
- src/pageEditor/panes/EditorPane.test.tsx
- src/registry/localRegistry.ts
- Closes #5163 
- Fixes bug in baseRegistry/brick registry where it though registry cache was initialized before YAML brick were loaded from the local DB
> #5163: fix brick cache initialization

- src/components/quickBar/QuickBarApp.tsx
- src/components/quickBar/quickBarRegistry.ts
- src/components/quickBar/useActions.test.tsx
- src/components/quickBar/useActions.ts
- Closes #4501: this issue would be caused by the items by the actions being in the wrong order in the actions array
- There was a bug in the `useActions` hook where actions would be removed, only added
- https://www.loom.com/share/770b8dcd0a0145899edc9aebc841f61b
> #5135: remove actions from quick bar on update

- package-lock.json
- package.json
- src/components/quickBar/QuickBarApp.tsx
- Closes #5172 🤞 
- Wraps the Quick Bar in a contentEditable (which the user can't actually target), so hot key libraries see typing in the Quick Bar as input-like events. 
- The contenEditable div is taken up fully by the Quick Bar, so the user can't actually type into the div itself. (At least I wasn't able to when I tried)
- Introduces focus lock library to ensure Quick Bar keeps focus while open
- Tested on GitHub, Zendesk, Trello, Salesforce. Not tested on Notion yet
- https://www.loom.com/share/04b79d48c30e484896d76df8700be51b
> #5172: isolate quickbar from host page hot-keys

- package-lock.json
- package.json
- src/blocks/effects/wait.test.ts
- src/blocks/transformers/tourStep/tourStep.test.ts
- src/extensionPoints/helpers.test.ts
- src/extensionPoints/triggerExtension.test.ts
- src/vendors/initialize.js
- Closes #5176 
- Use requestIdleCallback and requestAnimationFrame to avoid performance regressions when watching whole page for a selector
> #5176: fix await element performance regression

- src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
- src/blocks/transformers/temporaryInfo/EphemeralPanel.test.tsx
- src/blocks/transformers/temporaryInfo/__snapshots__/EphemeralPanel.test.tsx.snap
- src/blocks/transformers/temporaryInfo/temporaryPanelProtocol.test.ts
- src/blocks/transformers/temporaryInfo/temporaryPanelProtocol.ts
- src/blocks/transformers/tourStep/tourStep.ts
- src/contentScript/ephemeralPanelController.tsx
- src/contentScript/sidebarController.tsx
- src/sidebar/Tabs.tsx
- src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx
- src/sidebar/sidebarSlice.test.ts
- src/sidebar/sidebarSlice.ts
- src/sidebar/types.ts
- src/sidebar/utils.test.ts
- src/sidebar/utils.ts
- src/testUtils/factories.ts
- Part of #5072, fixing a bug with the activate recipe sidebar tab when there are other tabs in the sidebar
- Cleans up some stuff with types across the whole sidebar app
Main changes are:
- `type SidebarEntry = PanelEntry | TemporaryPanelEntry | FormEntry | ActivateRecipeEntry`
- `PanelEntry`, `TemporaryPanelEntry`, `FormEntry`, and `ActivateRecipeEntry` have a `type` field now to differentiate them
- Test factories set up to generate SidebarEntry instances, tests refactored
- `mapTabEventKey()` renamed to `eventKeyForEntry()`, updated to handle activate-recipe tabs as well
- In `sidebarSlice`, `eventKeyExists()` updated to include activate-recipe keys to fix activate tab bug in the UI
- `displayTemporaryInfo()`
- Typing fixed to use `TemporaryPanelEntry` instead of `PanelEntry` …
> #5072: Marketplace Activation Followup: bug fix and types cleanup

- webpack.config.js
- Fixes #5197 🤞 
- Ensures Webpack doesn't mangle `*Action` classnames in prod builds
Before:
After:
> #5197: fix submit panel action

- src/components/fields/fieldUtils.ts
- src/options/pages/services/ServiceEditorModal.test.tsx
- src/options/pages/services/ServiceEditorModal.tsx
- Closes #5119 
- Follow-up ticket in the app TBD
- `buildYup` has an `errMessages` options you can pass to `config` to define custom error messages per field. The approach I've taken here is to walk the schema & add generic validation messages for properties with `required` and `pattern` fields
- Alternative implementation is to add an `errMessages` field to the schema itself which get collected via `getValidationErrMessages` (which would allow for more specific validation messages). I originally shied away from doing this, because it wouldn't match the JSONSchema7 type. However, it looks like we're mutating the schema anyways by adding `config`?
https://www.loom.com/share/2affe022ae9848cebdbf336a2276f997
> Add user friendly validation errors for `required` and `pattern` fields on integration modal

- src/pageEditor/extensionPoints/base.test.ts
- src/pageEditor/extensionPoints/base.ts
- Modifies the Page Editor to use Document Context reader for new mods
- This avoids the confusing case when modding SPAs where the trigger sees the original URL
- Modifying the behavior of `@pixiebrix/document-metadata` would not be backward compatible
- See the old URL generation code here: https://github.com/mozilla/page-metadata-parser/blob/master/parser.js#L152
- https://www.loom.com/share/5a929d390d954f1ea8af36af65bc3d58
> Use document context reader for URL in new mods so `@input.url` is the current URL

- src/components/documentBuilder/createNewElement.ts
- src/components/documentBuilder/edit/ListOptions.tsx
- Makes the element key for List Elements in the document builder explicit
- Improves documentation for the List Element fields
> Provide explicit default for list element in document builder

- src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
- src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
- src/analysis/analysisVisitors/varAnalysis/varMap.ts
- src/blocks/PipelineExpressionVisitor.ts
- src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx
- src/contentScript/pageEditor/dynamic.ts
- src/core.ts
- src/extensionPoints/contextMenu.test.ts
- src/extensionPoints/contextMenu.ts
- src/extensionPoints/contextMenuReader.ts
- src/extensionPoints/helpers.ts
- src/extensionPoints/quickBarProviderExtension.tsx
- src/extensionPoints/quickbarProviderExtension.test.ts
- src/extensionPoints/quickbarQueryReader.ts
- src/extensionPoints/triggerEventReaders.ts
- src/extensionPoints/triggerExtension.test.ts
- src/extensionPoints/triggerExtension.ts
- src/extensionPoints/triggerExtensionTypes.ts
- src/extensionPoints/types.ts
- src/options/pages/settings/ExperimentalSettings.tsx
- src/pageEditor/analysisManager.ts
- src/pageEditor/extensionPoints/formStateTypes.ts
- src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
- src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
- src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
- src/pageEditor/utils.ts
- src/store/settingsSlice.ts
- src/store/settingsTypes.ts
- Closes #5255 
- Adds handling for Document Builder List Element to varAnalysis
- Adds reader metadata for Trigger and Dynamic Quick Bar starter bricks
- Modified `setInputVars` to use the defaultReader method from ExtensionPoint instance object
- Adds a `previewReader` method to IExtensionPoint for returning the reader to be user when generating Page Editor previews
- https://www.loom.com/share/0b1ae728b0c448d8a0ced2467b01e6eb
- In List Element, pass through the shape of the list/array element. Right now it just allows anything on the element
- In the For Each brick, pass through the shape of the array items if known. Right now it just allows any prop on the element
> #5255: fix var analysis false positives and enable var analysis

- src/layout/Footer.tsx
- Shows the full version string in the footer to help diagnose user-reported bugs who are using pre-releases
- Bumps the copyright year in the footer
- Add tests: YOLO
> Show full version string in extension console footer

- src/options/pages/workshop/CustomBricksCard.tsx
- src/options/pages/workshop/WorkshopPage.tsx
- src/options/pages/workshop/workshopUtils.test.ts
- src/options/pages/workshop/workshopUtils.ts
- Part of #5210 
- Updates display names in the workshop
- Uses "Starter" instead of Starter Brick for space
> #5210: update display names in the workshop to mod and starter brick

- src/analysis/analysisVisitors/regexAnalysis.ts
- src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
- src/blocks/transformers/ephemeralForm/formTransformer.test.ts
- src/blocks/transformers/ephemeralForm/formTransformer.ts
- src/blocks/transformers/jquery/JQueryReader.test.ts
- src/blocks/transformers/jquery/JQueryReader.ts
- src/blocks/transformers/regex.test.ts
- src/blocks/transformers/regex.ts
- src/core.ts
- src/types.ts
- Part of #5268
- Dynamically generates output schema shape for the following bricks for variable analysis:
- Form Builder
- Extract from Page (JQuery Reader)
- Regex Extractor
- Variable analysis falls back to the static schema if there's an error computing the dynamic output schema
- Handle composite bricks, e.g., If-Else
- Handle complete JQuery configurations. PR currently just covers what you can configure in the Page Editor
- Pass in VarMap for the brick, so bricks have more information for determining output shape when there are variables
- https://www.loom.com/share/ba04679217c148b38938d9220fc091ec
> #5268: infer dynamic output schema for a few bricks

- src/options/pages/InvitationBanner.tsx
- Closes #5242
- At some point, we removed the `/teams` route in the Admin console. Team invitations are now displayed on the root url.
- It would be nice to add a Rainforest test for this feature; this would require some tweaking to test accounts on the app project, however
https://www.loom.com/share/36e01e1a176242a7b9c9e6a65a444446
> #5242 Fix invitation banner url & copy

- src/options/pages/onboarding/partner/ControlRoomOAuthForm.tsx
- Context here: https://pixiebrix.slack.com/archives/C0436P48QHY/p1677610353984379
- This is a quick & dirty fix in order to solve a bug where RTK query was never resolving
The two leads that I haven't had time to follow re this RTK query issue:
1. `hasToken` flickers from `true` to `false`, which also may be flickering the `skip` option on the `useMeQuery` which could be producing unpredictable results
2. I didn't realize until I actually made this hack that we are calling `dispatch(apiUtil.resetApiState());` right before we expect the `useGetMeQuery` to run. I wonder if this is causing unpredictable behavior
https://www.loom.com/share/bcacc59c6ce948c3a0b5499a2b40ffe0
- If we decide to merge this, we should create a follow-up ticket
> Force refresh page after oauth2 authentication to fix perpetual loading screen

- src/components/fields/schemaFields/widgets/TemplateToggleWidget.module.scss
- src/contrib/google/sheets/SheetsFileWidget.tsx
- src/contrib/google/sheets/useCurrentOrigin.ts
- Fixes coming out of developer (me) release testing/QA for the 1.7.20 extension release
- Already had test coverage but the API was being mocked in the test so the syntax bug didn't show up in tests
> Use browser.tabs, not chrome.tabs; fix vertical toggle icon alignment; catch useOrigin errors

- src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx
- src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
- src/contrib/google/sheets/LookupSpreadsheetOptions.test.tsx
- src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
- src/contrib/google/sheets/TabField.tsx
- src/contrib/google/sheets/__snapshots__/AppendSpreadsheetOptions.test.tsx.snap
- src/contrib/google/sheets/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap
- src/contrib/google/sheets/useSpreadsheetId.ts
- More cleanup from QA for 1.7.20 extension release
- Fix tab name dropdown when changing spreadsheet id
> Google sheets - fix tab names and clear row values for sheets

- src/components/form/widgets/AsyncRemoteSelectWidget.test.tsx
- src/components/form/widgets/AsyncRemoteSelectWidget.tsx
- src/contrib/automationanywhere/BotOptions.tsx
- src/contrib/automationanywhere/aaApi.ts
- src/utils/cachePromise.test.ts
- src/utils/cachePromise.ts
- Fixes #5305
- Fix loadOptions for AsyncRemoteSelectWidget to only use `callback(...)` to ensure debouncing works properly
- Fix bug in `cachePromise` where rejections came back as undefined
- Fix corner-case in loadOptions where component could error by trying to spread non-iterable value when using with cachePromise (see bug above)
- Be defensive about `null` query in searchBots
- Fall back to searching "private" workspace during options initialization
- Wow, issues on so many levels... definitely need to improve test coverage of some of this older options code now that we're relying on it more
Screenshot of message if CR license is expired (which results in a 402 error)
> #5305: fix AsyncRemoteSelectWidget and AA bot fetching on empty state

- src/components/fields/schemaFields/widgets/TemplateToggleWidget.module.scss
- Fixes [the papercut UI issue described here](https://www.notion.so/pixiebrix/Release-1-7-20-19105237a54e41ecb33ab4e4144c86df?pvs=4#93f17bc3942040d983fe3d54ef57e899)
- Alignment still looks off on the console pages, but we'll need to figure out a console-specific CSS change to make for that, so it doesn't mess up the page editor as well. The inputs are taller in the console styles, that's why the alignment looks off compared to the page editor.
> Fix vertical alignment of field type toggle icons in the page editor

- src/contrib/automationanywhere/aaApi.test.ts
- Part of #5305 
- Add Jest test coverage that cache varies by workspaceType
- Marking a low priority because this is just an additional test. Didn't expose any problems
> #5305: add test coverage that bot search in Page Editor varies by workspaceType

- src/store/dynamicElementStorage.test.ts
- src/store/dynamicElementStorage.ts
- Fixes a bug where an error occurs if you try to deactivate a mod from the extension console when you have never opened the page editor before
- Fixes #5332 
- This adds more motivation for us to better organize our redux state management across the various contexts where it's used. Dynamically editing the persisted redux state by reading/writing directly to local storage is a sketchy pattern that we should try and refactor at some point.
> #5332 Fix bug when deactivating mods from the console page before opening page editor

- src/background/proxyUtils.test.ts
- src/background/proxyUtils.ts
- src/background/requests.ts
- src/components/errors/ErrorDetail.module.scss
- src/components/errors/RemoteApiErrorDetail.tsx
- src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap
- src/components/errors/getErrorDetails.test.tsx
- src/components/errors/getErrorDetails.tsx
- src/errors/businessErrors.ts
- src/errors/errorHelpers.test.tsx
- src/errors/errorHelpers.ts
- Closes #4558 
- Adds an error view for `ProxiedRemoteServiceError` that shows the payload of the error, shown in Output Panel and in Logs
- Adds `selectRemoteResponseErrorMessage` method to select error message from proxied 3rd party API responses
- Eliminates duplicate error messages in `getErrorMessageWithCauses`
- https://www.loom.com/share/d9a045803e2c42f384bd6f0dc55a1d6b
> #4558: show proxied response error details in Page Editor and Logs

- src/analysis/ReduxAnalysisManager.ts
- src/analysis/analysisSlice.ts
- src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
- src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
- src/analysis/analysisVisitors/varAnalysis/varMap.test.ts
- src/analysis/analysisVisitors/varAnalysis/varMap.ts
- src/blocks/PipelineExpressionVisitor.ts
- src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
- Closes #5343 
- Cleans up `VarAnalysis` internal state to have a single `contextStack` for bookkeeping while recursing and iterating over bricks in a pipeline
- Fixes a bug in where `VarAnalysis.visitDocument` was visiting nested pipelines directly instead of while visting their parent elements in the document
- Updates ReduxAnalysisManager to dispatch an analysis failed action to help with debugging via redux-logger
1. Read the types in `varAnalysis.ts`
2. Look at the internal state of `VarAnalysis`
3. Look at visitPipeline, visitBlock, visitDocument, and visitDocumentElement methods
- https://www.loom.com/share/f6ddd8e592004d8999d34624f1300a50
- List Element in the Document Builder can determine the shape of the element based on the item type of the array. Currently, the analysis is …
> #5343: fix variable analysis false positives for Document Builder list buttons

- src/blocks/effects/clipboard.test.ts
- src/blocks/effects/clipboard.ts
- src/blocks/transformers/screenshotTab.ts
- Closes #5357 
- Adds support for copying image data URI to the clipboard as an image, e.g. for use with our Screenshot Tab brick
- The `copy-text-to-clipboard` library can likely be removed now that the browser clipboard API is stable
- https://www.loom.com/share/8796835cde91401fb435ba3ba215c41a
- See if there's other content types (e.g., rich text, etc.) we should be supporting on the clipboard brick
> #5357: support images in the copy to clipboard brick

- src/blocks/effects/clipboard.test.ts
- src/blocks/effects/clipboard.ts
- Fixes #5361 
- If the clipboard write fails due to the document not having focus, prompt the user to click on the document
- https://www.loom.com/share/c281cf73861b49b0868664462346c2dc
> #5361: add support for copying cropped screenshot to clipboard

- src/options/pages/blueprints/BlueprintActions.tsx
- Modifies the mod action menu to use fixed-width icons
Before: note alignment of the "Delete" action
After
> Use fixed width icons for mod 3-dot menu in Extension Console

- src/blocks/transformers/getAllTransformers.ts
- src/blocks/transformers/selectElement.test.ts
- src/blocks/transformers/selectElement.ts
- src/development/headers.ts
- Closes #5364 
- Adds a brick to prompt the user to select an element
- Selection returned as array of element references. Will allow for multi-select in the future
- The user can escape out of selection mode with `Esc`, which throws a CancelError
- https://www.loom.com/share/19b701da7e994ea5ad998a217346a1b1
- Support multi-select with selection tool
- Allow user to specify which element patterns are valid, e.g., only images
- Allow support for showing instructions while in selection mode
> #5364: add brick to prompt user to select element

- src/services/locator.ts
- Fixes an incorrect warning in the service locator:
Original Warning
> Fix false positive warning in service locator

- .github/workflows/rainforestqa.yml
- scripts/upload-extension.sh
- Closes #5335 
- Corresponds to: Test Independent Rainforest Project Slice: 1
- Created 3 new environments in Rainforest (Main, Release, CWS) and 3 new run groups (same names)
- Placed the existing CI tests in the new run groups
- [Link to specification](https://www.notion.so/pixiebrix/Test-Independent-Rainforest-Environments-67a031a2298547e2835dbccf5d35a5a8?pvs=4#091a70e60fc94aae8eed123e5a329041)
- Filenames for extension uploads should look like this going forward: pixiebrix-extension-[main|release|cws]
- This simplifies the s3 link: https://pixiebrix-extension-builds.s3.us-east-2.amazonaws.com/builds/$filename
- **Question**: how does S3 handle duplicate filenames? For example, will uploading …
> #5335: Update rainforest workflow and upload_extension.sh

- package-lock.json
- package.json
- src/auth/token.ts
- src/options/options.tsx
- src/options/pages/activateExtension/ActivatePage.tsx
- src/pageEditor/pageEditor.tsx
- src/sidebar/sidebar.tsx
- src/telemetry/performance.ts
- webpack.config.js
- Closes #5408 
- Is behind the `telemetry-performance` feature flag
- Monitors the following:
- Extension Console
- Page Editor
- Sidebar  
- I left the default `sessionSampleRate` and `sessionReplaySampleRate`. We'll need to determine what the rates for these need to be
Data in Datadog
Tracing headers included with requests:
- Modify the Page Editor to either: 1) use hash routing, 2) mark page switches to better support navigation timings
- Add action tracking by hooking into report event: https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/
- Consider adding RUM for contentPage startup and tiny pages (modal, etc.)
- Upload source maps to Datadog to improve stack trace analysis
> #5408: add Datadog for performance monitoring/tracing
