public/mockServiceWorker.js, src/auth/authSlice.ts, src/options/pages/blueprints/blueprintsSlice.ts, src/options/pages/settings/FactoryResetSettings.tsx, src/pageEditor/slices/editorSlice.ts, src/recipes/recipesSlice.ts, src/store/commonActions.ts, src/store/extensionsSlice.ts, src/store/servicesSlice.ts, src/store/sessionChanges/sessionChangesSlice.ts, src/store/settingsSlice.ts, src/store/workshopSlice.ts
- Fixes #5403 
- Fixes Factory Reset to reset all persisted state, and reactivate PixieBrix on all tabs
- Calls dispatch on the reducers vs. clearing localStorage for persisted state directly
- https://www.loom.com/share/60646e763a084abdbda8b63bc9eba5b0
=> #5403: fix factory reset to reset all persisted state

src/contrib/google/initGoogle.ts, src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/AppendSpreadsheetOptions.tsx, src/contrib/google/sheets/LookupSpreadsheetOptions.test.tsx, src/contrib/google/sheets/LookupSpreadsheetOptions.tsx, src/contrib/google/sheets/RequireGoogleApi.tsx, src/contrib/google/sheets/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap
- Part of #3914 
- Adds a requireGoogleHOC wrapper for brick configuration
- Shows message of GAPI is unavailable or initialized
=> #3914: require GAPI for GSheets brick configuration

src/components/fields/schemaFields/widgets/TemplateToggleWidget.module.scss, src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/SheetsFileWidget.test.tsx, src/contrib/google/sheets/SheetsFileWidget.tsx, src/pageEditor/extensionPoints/formStateTypes.ts, src/pageEditor/tabs/recipeOptionsValues/RecipeOptionsValues.test.tsx
- Fixes #5444 
- Fix icon spacing/width on the gsheet file icon
=> #5444 - Fix SheetsFileWidget and icon spacing

src/auth/useRequiredPartnerAuth.ts, src/background/deployment.test.ts, src/background/deployment.ts, src/background/installer.ts, src/chrome.ts, src/hooks/useTheme.ts, src/options/pages/onboarding/SetupPage.test.tsx, src/options/pages/onboarding/partner/PartnerSetupCard.tsx, src/services/baseService.ts, src/store/enterprise/managedStorage.test.ts, src/store/enterprise/managedStorage.ts, src/store/enterprise/managedStorageTypes.ts, src/store/enterprise/singleSignOn.test.ts, src/store/enterprise/singleSignOn.ts, src/store/enterprise/useManagedStorageState.test.ts, src/store/enterprise/useManagedStorageState.ts, static/managedStorageSchema.json
- Closes #5450 
- Refactors use of browser IT admin managed storage
- Adds new `store.enterprise` module
- Adds type for storage to avoid ad-hoc constant definitions 
- Introduces a `useManagedStorageState` hook for use in React components/hooks
- Tries to handle quirks in managed storage state initialization time
- Read the `store.enterprise` files first
- Have the app include a success query parameter in the URL on successful SAML linking, so the browser extension can automatically close the tab. Could alternatively just look for the `https://app.pixiebrix.com/accounts/profile/` URL. But we might be getting rid of that URL @johnnymetz  @mnholtz 
- https://www.loom.com/share/7ae375b8bcd04a94b409e34503073b20
=> #5450: automatically launch SSO flow; refactor managed storage usage

src/components/fields/schemaFields/widgets/NumberWidget.tsx, src/components/fields/schemaFields/widgets/PasswordWidget.tsx, src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx, src/components/fields/schemaFields/widgets/TextWidget.tsx
- Fixes #5440 
- Unblocks the first issue in #5451 
- This was written together with the fix for the first issue in #5451 to enable checking the inputRef against document.activeElement to detect focus, but that fix will be committed separately in another PR
=> #5440 Fix inputRef usage in field widgets

src/auth/useRequiredPartnerAuth.test.tsx, src/auth/useRequiredPartnerAuth.ts, src/background/installer.ts, src/background/partnerTheme.ts, src/testUtils/testHelpers.tsx
- Closes #5459 
- Show AA OAuth2 screen if partnerId is set in managed storage
- Sets extension theme to the key in managed storage on startup
- https://www.loom.com/share/d0972947ff284abb9053f0035e4b033f
=> #5459: show partner oauth2 screen on managed partner id

src/blocks/readers/DocumentReader.test.ts, src/blocks/readers/DocumentReader.ts
- Closes #5471 
- Modified `@pixiebrix/document-context` to return the current title of the page
- This change is backward-compatible because it's adding a new prop to the brick
- The mod behavior is slightly backward incompatible, because the title will override the title coming from the `@pixiebrix/document-metadata`. I think that's OK though, because likely no one cares about the original title for SPAs
=> #5471: add current title to document context brick

src/analysis/analysisVisitors/extensionUrlPatternAnalysis.ts, src/manifest.json
- Closes #5476 
- Should not CWS impact review time because it's an optional permission
- https://www.loom.com/share/6178a49ff5d743859e057d3c769c9a2f
- Add analysis rule to show warning if `<all_urls>` not specified and Take Screenshot is in starter brick that doesn't support it
=> #5476: add all_urls as optional permission

src/components/documentBuilder/edit/DocumentEditor.test.tsx, src/components/fields/schemaFields/widgets/ArrayWidget.test.tsx, src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx, src/components/fields/schemaFields/widgets/TextWidget.test.tsx, src/components/form/widgets/RegistryIdWidget.test.tsx, src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/SheetsFileWidget.test.tsx, src/testUtils/testHelpers.tsx
- Makes this function synchronous and doesn't submit the form anymore. If we need form submission behavior we can add it separately but it's not really used for anything
=> Make getFormState() more intuitive

src/pageEditor/NonScriptablePage.tsx, src/pageEditor/panes/__snapshots__/NonScriptablePage.test.tsx.snap
- Removes the playground link from the starter page in the page editor
- Requested by @BrandonPxBx
=> Remove playground link from page editor starter panel

src/components/formBuilder/formBuilderHelpers.ts
- Closes #5448 
- There might be a better way to go about this in the future where we handle all `$ref` schemas in the same way, but for right now this is a quick and easy fix for the issue.
=> Hide default value in field editor for google sheet and database field types

src/background/messenger/api.ts, src/background/messenger/external/_implementation.ts, src/background/messenger/external/api.ts, src/background/messenger/registration.ts, src/background/starterBlueprints.test.ts, src/background/starterBlueprints.ts
- Part of the fix for #5473
- Adds starter blueprint installation to the external messenger api
- Removes the open-playground side effect from starter blueprint installation
- Removes the "should install starter blueprints" check from starter blueprint installation - the app will now decide whether or not to install blueprints & utilize the the messenger framework to do so
- This PR mainly does the following:
- Adds `installStarterBlueprints` to external messaging api
- Removes the "should install" check from the installStarterBlueprints logic
- Removes logic for opening the playground tab
- (The latter two items are now done on the app-side of things)
- See app-side PR referenced above
=> #5473: add installStarterBlueprints to external messenger api

src/blocks/effects/getAllEffects.ts, src/blocks/effects/postMessage.test.ts, src/blocks/effects/postMessage.ts, src/development/headers.ts
- Closes #5508 
- Adds a Post Message brick for sending messages to other frames
- Introduced to support running CKEditor commands on Salesforce
- https://www.loom.com/share/47f2321f24ea4b48b745d9d5a163ac33
=> #5508: add postmessage brick

src/blocks/effects/alert.test.ts, src/blocks/effects/alert.ts
- Closes #5510 
- Reverts marking `type` as required on the Window Alert brick
- The regression was introduced in: https://github.com/pixiebrix/pixiebrix-extension/pull/5483
=> #5510: revert marking `type` as required for alert brick

src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts, src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.ts, src/blocks/transformers/temporaryInfo/EphemeralPanel.tsx, src/blocks/transformers/tourStep/tourStep.ts, src/components/documentBuilder/render/BlockElement.tsx, src/contentScript/pageEditor.ts, src/pageEditor/tabs/effect/ConfigurationTitle.tsx, src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts, src/sidebar/PanelBody.test.tsx, src/sidebar/PanelBody.tsx, src/sidebar/Tabs.tsx, src/sidebar/types.ts, src/testUtils/factories.ts
- Closes #5549 
- Passes `blueprintId` along to temporary panels
- Strengthens the type of prop `PanelBody.context` to ensure callers pass through blueprintId if available
- https://www.loom.com/share/9f54370791c140fdbeaf8c1ab40ae377
=> #5549: track blueprint id for temporary panels

.github/workflows/rainforestqa.yml
- Closes #5527 
- See concern described in ticket for issue above, currently implemented to upload extension to S3 before version is public / approved by CWS
=> upload cws version of extension to s3 in rainforestqa workflow

src/blocks/effects/AddQuickBarAction.test.ts, src/blocks/effects/AddQuickBarAction.tsx, src/components/quickBar/QuickBarApp.test.tsx, src/components/quickBar/quickBarRegistry.ts, src/components/quickBar/quickbarTypes.ts, src/components/quickBar/useActionGenerators.test.tsx, src/components/quickBar/useActionGenerators.ts, src/extensionPoints/quickBarProviderExtension.tsx, src/hooks/useDebouncedEffect.ts, src/hooks/useUndo.ts
- Closes #5512 
- Change dynamic quickbar to use abortSignal to avoid showing stale actions. The original promise chaining approach caused major lag for slow APIs
- Improve parameter signature for `useDebouncedEffect`
- https://www.loom.com/share/2dab54ab85a744a18e1541523699988f
- Show loading indicator while generators are running to provide visual feedback
=> #5512: use abort signal for cancelling pending quickbar action generators

package-lock.json, package.json, src/analysis/analysisVisitors/blockIdVisitor.ts, src/blocks/effects/clipboard.test.ts, src/blocks/effects/clipboard.ts, src/blocks/util.ts, src/components/AsyncButton.tsx, src/components/jsonTree/JsonTree.tsx, src/components/jsonTree/treeHooks.tsx, src/extensionConsole/pages/blueprints/modals/shareModals/ActivationLink.tsx, src/extensionConsole/pages/brickEditor/referenceTab/BrickDetail.tsx, src/extensionConsole/pages/services/ZapierModal.tsx, src/extensionPoints/contextMenu.ts, src/extensionPoints/menuItemExtension.ts, src/extensionPoints/panelExtension.ts, src/extensionPoints/quickBarExtension.tsx, src/extensionPoints/quickBarProviderExtension.tsx, src/extensionPoints/sidebarExtension.ts, src/extensionPoints/tourExtension.ts, src/extensionPoints/triggerExtension.ts, src/permissions/index.ts, src/testUtils/factories.ts, src/types/blockTypes.ts, src/types/extensionPointTypes.ts, src/utils/clipboardUtils.ts
- Closes #5556
- Fixes permissions calculation to recurse all bricks (using visitor)
- Tries to use native API where possible
- Renames `blockList` to `selectAllBlocks`
- See `BlockIdVisitor`
- See definition of selectAllBlocks
- See `clipboard.ts`
- See `clipboardUtils.ts`
- Introduce lint rule to prevent use of navigator.clipboard.writeText directly
=> #5556: fix nested brick permissions calculation and use native clipboard API 

.github/workflows/rainforestqa.yml
- Fixes #5542 
- When I manually tested that the CWS version is uploaded / ran on rainforest, I noticed it wasn't. 
- Fixes the faulty env var use in the bash script for upload CWS step
- Ignore the first commit, I undo those changes in the second as they're not needed.
- [Verification that the CWS Upload works now](https://github.com/pixiebrix/pixiebrix-extension/actions/runs/4735939581/jobs/8406822330?pr=5561) (click Upload Extension step and see what path is used)
=> #5527: Fix faulty regex

src/components/fields/schemaFields/getToggleOptions.tsx, src/components/form/widgets/AsyncRemoteSelectWidget.test.tsx, src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/AppendSpreadsheetOptions.tsx, src/contrib/google/sheets/LookupSpreadsheetOptions.test.tsx, src/contrib/google/sheets/LookupSpreadsheetOptions.tsx, src/contrib/google/sheets/__snapshots__/AppendSpreadsheetOptions.test.tsx.snap, src/contrib/google/sheets/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap, src/pageEditor/tabs/recipeOptionsDefinitions/RecipeOptionsDefinition.tsx
- Closes the loop on the recent GSheets work by removing the feature flag code from the extension
- This will "launch" the gsheets mod inputs change to all users upon the next CWS update (cc @corinnemayans, @BrandonPxBx  )
- We can remove the `gsheets-mod-inputs` feature flag on the back end at some point, although it doesn't really hurt anything to leave it there for now
=> Remove GSheets mod inputs feature flag

.github/workflows/rainforestqa.yml
We currently call all Rainforest runs triggered by our workflow "CI automatic run". This makes it a little hard to see at a glance what caused test failures:
This changes the run name to be `pixiebrix-extension - <branch_name> <job_id>`, e.g. `pixiebrix-extension - release/1.0.0 42`, which includes the branch name & the workflow job id respectively. The commit hash is already uploaded to Rainforest under the `--release` flag.
=> Add branch name & job id to Rainforest run name

src/sidebar/PanelBody.tsx
- Closes: #5566 
- Removes loading indicator when PanelBody content is re-fetching
- https://www.loom.com/share/12dbeb4d9dae442e8fd8af2971b1cbf5
=> #5566: don't show both loader and content while panel content is re-fetching

src/sidebar/activateRecipe/ActivateRecipePanel.module.scss, src/utils/includesQuickBarExtensionPoint.ts
- Quick fix to the text alignment on the final sidebar activate panel view
=> UI paper-cut fix - center-align text on the finish screen of sidebar activate panel

src/components/fields/IconWidget.tsx, src/components/quickBar/QuickBarResults.tsx, src/components/quickBar/utils.ts, src/icons/IconSelector.tsx, src/pageEditor/fields/makeLockableFieldProps.tsx, src/pageEditor/tabs/quickBar/QuickBarConfiguration.tsx, src/utils/stringUtils.test.ts, src/utils/stringUtils.ts
- closes #5538
- _What order should the reviewer review the files in?_
`QuickBarResults.tsx` and `src/components/quickBar/utils.ts` are related to showing the emoji in the quickbar.
The rest is either tests or what I needed to disable the icon selector.
- _Were there multiple approaches you were deciding between?_
I considered setting the emoji itself as the icon but the UX seemed nicer when there was a regular icon as a fallback.
[Loom](https://www.loom.com/share/53cd2cbe7d784b6db2522673b8bfd20b)
=> #5538 use starting emoji as action icon

src/activation/useWizard.test.tsx, src/activation/useWizard.ts, src/auth/authTypes.ts, src/background/starterBlueprints.test.ts, src/components/fields/schemaFields/widgets/ServiceSelectWidget.stories.tsx, src/components/fields/schemaFields/widgets/ServiceWidget.test.tsx, src/components/fields/schemaFields/widgets/ServiceWidget.tsx, src/contrib/automationanywhere/BotOptions.test.tsx, src/contrib/uipath/LocalProcessOptions.test.tsx, src/contrib/uipath/ProcessOptions.test.tsx, src/extensionConsole/pages/activateExtension/ActivatePage.tsx, src/extensionConsole/pages/activateRecipe/ActivateWizard.test.tsx, src/extensionConsole/pages/activateRecipe/ServicesBody.tsx, src/hooks/auth.ts, src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx, src/sidebar/activateRecipe/ActivateRecipePanel.tsx, src/sidebar/activateRecipe/RequireRecipe.tsx, src/sidebar/activateRecipe/__snapshots__/ActivateRecipePanel.test.tsx.snap, src/testUtils/factories.ts
- Closes #5533
- Refactors `canAutoActivate` into a `useCanAutoActivate` hook
- Introduces a `useBuiltInServiceAuthsByRequiredServiceIds` hook
- Adds tests for auto-activating mods with and without built-in service configurations
- Pre-fills services with built-in configurations in `useWizard` (prefers configurations that are already installed)
- Modifies `canAutoActivate` to be truthy if all services have built-in configurations
- Moves `canAutoActivate` to `RequireRecipe` component to reduce complexity around component flickering while fetching built-in auths
- https://www.loom.com/share/4df37c03df1846309738f9f452f7cc1c
=> #5533 Enable in-marketplace one-click activation for mods with built-in service configs

src/pageEditor/pageEditor.tsx, src/sidebar/sidebar.tsx, src/telemetry/performance.ts
- Closes #5430
- 😞  RUM can't work in the Page Editor or Sidebar (see GH issue linked in the code)
- Has to be tested in a production build, as I've seen that the behavior is different locally vs. production
- It's still behind the feature flag `telemetry-performance` that's currently enabled for PixieBrix team members
=> #5430: fix DataDog RUM in extension console

src/__snapshots__/Storyshots.test.js.snap, src/background/telemetry.ts, src/components/ErrorBoundary.tsx, src/extensionConsole/App.tsx, src/extensionConsole/components/IDBErrorDisplay.stories.tsx, src/extensionConsole/components/IDBErrorDisplay.tsx, src/extensionConsole/pages/settings/StorageSettings.tsx, src/telemetry/logging.ts, src/types/browserTypes.ts, src/utils/idbUtils.ts
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/5558
- Closes #5530 
- Adds support for custom error display to ErrorBoundary
- Defines custom error display for IDB errors
- Includes the event buffer DB in clearing/recreating databases
- See Storybook
=> #5530: IDB ErrorBoundary in Extension Console to recover from IDB errors

src/background/telemetry.ts, src/extensionConsole/pages/settings/StorageSettings.tsx, src/registry/localRegistry.ts, src/telemetry/logging.ts, src/telemetry/trace.ts
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/5530
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/5558
- Switching to a singleton IDB instance per context seemed to be slowing down initialization time: https://www.notion.so/pixiebrix/Release-1-7-24-3fa746bb6a5748f6b1f257163d0f00e8?pvs=4
- There is very little guidance floating around on how many connections you can/should use: https://stackoverflow.com/questions/21418954/is-it-bad-to-open-several-database-connections-in-indexeddb. They seem to be very light-weight
- The main thing is the logic we had added previously to close connections when required (i.e., when a page is trying to upgrade/delete the DB)
- It's unlikely the multiple IDB connections are a cause of the rollbar errors we're seeing. …
=> #5600: revert singleton IDB connection PR; use fresh IDB connection for each operation

src/contentScript/marketplace.test.ts, src/contentScript/marketplace.ts, src/contentScript/messenger/api.ts, src/contentScript/messenger/registration.ts, src/sidebar/ConnectedSidebar.test.tsx, src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx, src/sidebar/activateRecipe/ActivateRecipePanel.tsx
- Closes #5532
- Depends on some tweaks to the Marketplace layout: https://github.com/pixiebrix/pixiebrix-www/pull/730 (which can be deployed without waiting for an extension release)
- Adds a method to the content script messenger to reload the marketplace after successful activation (in order to refresh the Activate button)
- Changes the content of the activate button to an "Active" label & reactivate link instead
- https://www.loom.com/share/51f07552a4a14c5cb62f35dbb1c8ea60
=> #5532 Trigger Activate button 'refresh' after successful in-marketplace activation

src/components/quickBar/QuickBarResults.tsx, src/components/quickBar/quickBarTheme.tsx
Fixes emoji size issue in quickbar.
[context](https://www.notion.so/pixiebrix/Release-1-7-24-3fa746bb6a5748f6b1f257163d0f00e8?pvs=4#8f2e97066c7845fba0b41fbaac5278ea)
This sets the font-size for emoji to 14px.
before:
after (updated): 
after (with subtitle):
=> Set emoji size in quickbar

src/utils/stringUtils.test.ts, src/utils/stringUtils.ts
`.trim()` wasn't working on the quickbar name when using certain emojis because apple's version of certain emojis contain an extra `\uFE0F` character which wasn't being captured by the emoji regex. This fixes that.
=> Fix regex to capture apple emoji variation characters in quickbar

src/contentScript/lifecycle.ts
- Fixes the 1.7.24 release blocker where button insertion doesn't work with no extensions installed
=> Insert Button bug - run page script even if no extension points are installed

src/contentScript/marketplace.test.ts, src/contentScript/marketplace.ts
- Part of https://github.com/pixiebrix/pixiebrix-extension/pull/5584
- Marketplace-side PR: https://github.com/pixiebrix/pixiebrix-www/pull/734
- Only targets Activate buttons with data-activate-button boolean data attribute for "Active/Reactivate" label swapout
- Still continues to add onclick handler to all activate links on the page (so that all links can still trigger a reactivation)
=> Only swap-out Activate buttons with data-activate-button attribute

src/recipes/recipesHooks.ts, src/sidebar/activateRecipe/ActivateRecipePanel.tsx, src/sidebar/activateRecipe/RequireRecipe.tsx
=> #5618 Bug fix - Duplicate context menu items after marketplace activation

src/themes/colors.scss, src/vendors/theme/assets/styles/_themes.scss, src/vendors/theme/assets/styles/_variables.scss
- Part of #5573 
- Darkens card headers to `$S30` from the Design System colors on Figma
- Fixes the `body` background color (css variable imports weren't working before, so the base body color was white instead of the proper new surface color)
- https://www.loom.com/share/d16ad12c91db43ad997f9929c5ec74e2
- Proper way to override bootstrap components is to override the scss variable, `$card-cap-bg` in this case
=> Darken card headers and fix body background color

src/sidebar/activateRecipe/ActivateRecipePanel.tsx, src/sidebar/activateRecipe/RequireRecipe.tsx
- Fixes #5629 
- Because `state.needsPermissions` was being set a default value of `false` (before the `needsPermissions` func was ever being called), mods with truthy `canAutoActivate` were being auto-activated despite needing permission confirmation
I still notice some form flashing during this process, but leaving that out of scope for this fix.
- https://www.loom.com/share/78ec0ba5dd144f3b90eb1bd7a7801cbc
=> #5629: set initial needsPermissions state to null

src/background/contextMenus.ts
- Closes #5574 
- The product/marketing team was attempting to use the `ContextMenuClick` event to gain insight into starter brick activity by mod id ([slack context here](https://pixiebrix.slack.com/archives/C0543SZD83F/p1682003479329819)). However, this event is run on the chrome browser event listener we added to context menu item clicks, and we don't have access to the mod information in this context.
- I'm removing this event in favor of directing the team to use `HandleContextMenu` instead, which _does_ have mod information reported along with it. See the updated Lexicon entry for this event here: https://pixiebrix.slack.com/archives/C0543SZD83F/p1682003479329819
- Mixpanel lexicon for deprecated `ContextMenuClick` event: https://mixpanel.com/project/2202701/view/143273/app/lexicon#t …
=> #5574: remove ContextMenuClick telemetry event

src/registry/localRegistry.ts
- Fixes #5657
- See this loom for discussion, PR walkthrough, and demo: https://www.loom.com/share/b1d811fd7a4148cd9d8bf410dd2fcb84
- @BLoe and I would like to start considering shifting from the indexeddb brick registry pattern -> RTK Query
=> #5657 Move indexeddb clear operation in `syncPackages` into a single transaction

src/contentScript/contentScriptCore.ts, webpack.config.js
- Part of #5676 
- We had introduced a sandbox and then turned it off because it caused crashes on certain bricks
- This PR is disabling sandbox iframe injection. I suspect the iframe injection might be causing problems with contentScript injection
- Reintroduce behind a feature flag
=> #5676: disable sandbox iframe injection

src/contentScript/lifecycle.ts, src/registry/internal.ts, src/store/extensionsMigrations.ts, src/store/extensionsStorage.ts
- Part of #4863 
- Add performance timers for page lifecycle to try to diagnose contentScript startup issues
=> #4863: add performance timers to lifecycle

src/background/contextMenus.ts, src/baseRegistry.ts, src/contentScript/lifecycle.test.ts, src/contentScript/lifecycle.ts, src/contentScript/pageEditor/dynamic.ts, src/extensionConsole/pages/blueprints/useInstallables.ts, src/extensionConsole/pages/blueprints/utils/exportBlueprint.ts, src/extensionConsole/pages/workshop/WorkshopPage.tsx, src/pageEditor/extensionPoints/adapter.ts, src/pageEditor/extensionPoints/base.ts, src/pageEditor/hooks/useUpsertFormElement.ts, src/pageEditor/panes/save/saveHelpers.ts, src/pageEditor/slices/editorSlice.ts, src/pageEditor/tabs/editTab/FoundationNodeConfigPanel.tsx, src/permissions/cloudExtensionPermissionsHelpers.ts, src/permissions/extensionPermissionsHelpers.ts, src/recipes/recipePermissionsHelpers.ts, src/registry/internal.ts, src/registry/localRegistry.ts, src/runtime/runtimeUtils.ts, src/types/helpers.ts, src/types/registryTypes.ts, src/utils/includesQuickBarExtensionPoint.ts
- Part of #4863 
- Recreated https://github.com/pixiebrix/pixiebrix-extension/pull/5679 with a correct branch name
- Telemetry from https://github.com/pixiebrix/pixiebrix-extension/pull/5678 indicated that resolving definitions is a bottleneck
- This PR adds some improvements to avoid unnecessary computation and messenger calls
- Refactors isInnerDefinitionRef and INNER_SCOPE to registry types
- The functional changes are in `internal` and `baseRegistry`
- The rest of the changes are from naming improvements
- [] Add tests
=> #4863: improve inner definition resolution perfomance

src/components/addBlockModal/useBlockSearch.ts
- Closes #5656 
- See fuse's documentation for scoring theory here: https://fusejs.io/concepts/scoring-theory.html#scoring-theory
- If `ignoreLocation` is `false` (which it is, by default) it will only consider the first `threshold * distance` number of characters as a match (assuming `location` is `0`)
- I added the `ignoreLocation: true` option because I speculated we might not want to match only the first `n` characters of a given string (maybe google is mentioned in a brick description after the first 20 characters?)
- Aside from this, I erred on the side of a more strict `threshold` value of `0.2` (as opposed to the default of `0.6` that we were using before)
- https://www.loom.com/share/30438de7010548989ec30e87311a6bdd
- Adding the ability to `clear` a search query in the search bar …
=> Narrow threshold of brick search results in the Page Editor add brick modal

src/pageEditor/tabs/editTab/EditTab.module.scss
- fix scrolling bug in data panel that was introduced with the collapse.
before:
after:
=> Fix data-panel scroll

src/activation/useActivateRecipe.test.ts, src/activation/useActivateRecipe.ts, src/activation/useWizard.ts, src/components/fields/schemaFields/widgets/DatabaseWidget.tsx, src/components/formBuilder/edit/FieldEditor.tsx, src/components/formBuilder/formBuilderHelpers.ts, src/components/formBuilder/preview/FormPreview.tsx, src/pageEditor/tabs/recipeOptionsDefinitions/RecipeOptionsDefinition.tsx, src/services/api.ts, src/testUtils/factories.ts
- Closes #5536 
- Look at changes to `useWizard.ts` to set up the initial value for an auto-created personal DB
- Look at how the values are handled and presented in `DatabaseWidget.tsx`
- Look at how the DB is created in `useActivateRecipe.ts`
https://www.loom.com/share/68713c897f1a4b3dabab5d47188eaa38
- Hide the database field during marketplace activation and allow personal DB fields to be auto-activated
- Build a feature to add see data to the personal DB that's created
=> #5536 - Auto-creation of personal mod DBs - Slice 2

.github/dependabot.yml
- Sets the `assignees` field on our dependabot config to make me the default assignee for these PRs
=> Assign dependabot PRs to Ben by default

src/components/fields/schemaFields/widgets/BooleanWidget.tsx, src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx, src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx, src/extensionConsole/pages/brickEditor/EditPage.tsx
=> #5580 - Add omitted field click handlers for the rest of the input types

src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx, src/extensionConsole/pages/deployments/DeploymentsContext.tsx, src/hooks/useRefreshRegistries.ts, src/testUtils/factories.ts
- Part of #5695 
- In the beta build, was seeing the user gesture timeout still occur. This moves all checks outside the callback
=> #5695: move permissions check out of deployments user gesture

src/background/locator.ts, src/extensionConsole/pages/blueprints/InstallableIcon.tsx, src/extensionConsole/pages/blueprints/useInstallablePermissions.ts, src/extensionConsole/pages/blueprints/useInstallableViewItemActions.ts, src/extensionConsole/pages/blueprints/useInstallableViewItems.test.tsx, src/extensionConsole/pages/blueprints/useInstallableViewItems.tsx, src/extensionConsole/pages/blueprints/useInstallables.test.ts, src/extensionConsole/pages/blueprints/useInstallables.ts, src/extensionConsole/pages/blueprints/utils/installableUtils.ts, src/hooks/common.ts, src/services/serviceUtils.ts, src/store/extensionsSlice.ts, src/types/extensionTypes.ts
- Closes #5700
- Main fix: Memoizes the selector that selects the extensions passed to useInstallablePermissions
- Wraps calls to locateWithRetry and refreshServices in memoizeUntilSettled
- Removes unused state property on useInstallable
- Modifies useInstallableViewItems to not show loading indicator during the server call to `useGetMarketplaceListingsQuery`
- Review `useInstallables` and `useInstallableViewItems` and `useInstallableActions`
- I'm still not sure which change triggered the bug. My understanding is that the reference should have always been changing from the selector
- https://www.loom.com/share/52ac8b0d4e4445ad9c23c7bd483c0cfb
- Clean up "installables" code so useInstallableViewItemActions isn't mounted multiple times per installable
- When the marketplace query loads, …
=> #5700: fix blueprints screen infinite messages bug

src/extensionConsole/pages/blueprints/BlueprintsPageLayout.test.tsx, src/extensionConsole/pages/blueprints/BlueprintsPageLayout.tsx, src/extensionConsole/pages/blueprints/BlueprintsPageSidebar.tsx, src/extensionConsole/pages/blueprints/__snapshots__/BlueprintsPageLayout.test.tsx.snap
- Fixes #5703 
- @twschiller and I aren't 100% sure why this was working before without the dependency added
- Adds a unit test to confirm searchQuery responsiveness
- I attempted to add a test with installables populated with test data, but ran into some snags that I think are still out of scope
=> #5703 Add `searchQuery` to Mod Page table dependencies

src/background/starterBlueprints.ts
- Part of https://github.com/pixiebrix/pixiebrix-app/pull/3437 
- See this PR for deployment checklist
- Simply changes the playground url that starter blueprints are installed on to `/welcome`
=> Change playground url to `/welcome`

src/contentScript/contentScript.ts, src/contentScript/contentScriptCore.ts
- Part of #4863 
- Fix bug introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/5743. Can't import auth state in contentScript because it imports the messenger
- The messenger can't be imported in contentScript because it can only be imported once
- See code comments for deeper explanation 
- Figure out how to add lint/dependency analysis to prevent accidentally importing the messenger in contentScript.ts
=> #4863: fix duplicate messenger registration

src/extensionPoints/helpers.ts, src/extensionPoints/menuItemExtension.test.ts, src/extensionPoints/menuItemExtension.ts, src/extensionPoints/panelExtension.ts, src/pageEditor/extensionPoints/formStateTypes.ts, src/pageEditor/extensionPoints/menuItem.ts, src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
- Closes #5753 
- Adds a `watch` mode for the button extension point to watch for new menus on the page
- Cleans up a confusing helper method
- Main changes are in menuItemExtension.ts
- Also look at MenuItemConfiguration
- I closed out issue: https://github.com/pixiebrix/pixiebrix-extension/issues/1811. It might be related, but appeared to be old/stale
- https://www.loom.com/share/d9af09ce4a9b41e184a91759db52de84
=> #5753: add support for watching for new menus

src/auth/useRequiredPartnerAuth.ts, src/background/partnerIntegrations.test.ts, src/background/partnerIntegrations.ts, src/contrib/automationanywhere/BotOptions.test.tsx, src/contrib/automationanywhere/RunBot.test.ts, src/contrib/automationanywhere/RunBot.ts, src/extensionConsole/pages/onboarding/SetupPage.test.tsx, src/extensionConsole/pages/onboarding/SetupPage.tsx, src/extensionConsole/pages/onboarding/partner/ControlRoomTokenForm.tsx, src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx, src/extensionConsole/testHelpers.tsx, src/services/constants.ts, src/store/enterprise/managedStorage.ts, src/testUtils/factories/authFactories.ts
- Closes #5762 
- Bug fixes:
- Fixes bug where hostname from URL wasn't being auto-filled in the form: https://github.com/pixiebrix/pixiebrix-extension/pull/5763/files#r1199244815
- Test Cleanup
- SetupPage.test.tsx: use mocks and add some additional assertions
- Refactoring
- Renames `CONTROL_ROOM_SERVICE_ID` to `CONTROL_ROOM_TOKEN_SERVICE_ID`
=> #5762: clean up partner onboarding state management, names, add tests

src/background/partnerIntegrations.ts
- Part of #5762
- Make a sequential call to the PixieBrix API to ensure the CR principal has been initialized
- Provide an informative error message if JWT verification fails
=> #5762: fix account creation race condition in partner authentication

package-lock.json, package.json, src/sidebar/sidebarSlice.ts, src/utils/asyncStateUtils.ts
- Un-pins Immer
- See: https://github.com/pixiebrix/pixiebrix-extension/pull/5124
- New major version of Immer has been released, the broken patch we avoided with pinning was superseded a while ago
- Updates Immer and Redux-Toolkit to latest npm versions
- Was having trouble dealing with this on the dependabot PRs, so decided to just do it manually for this one
=> Dependency Management - Update Immer & Redux Toolkit to latest versions

src/auth/useRequiredPartnerAuth.ts, src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx, src/sidebar/Tabs.tsx, src/sidebar/sidebar.html, src/sidebar/sidebarSelectors.ts, src/store/servicesSelectors.ts
- Fixes #5646
- Added the React DevTools script tag to the sidebar app
- The main changes that fixed the bug were memoizing the services selector to prevent `RequireAuth` (+children) from re-rendering unnecessarily, and memoizing the temporary panel Tab.Pane components to make sure they don't re-render unless the panel entry actually changes, not just when `Tabs` re-renders in general
- We need to make sure and do a lot of QA on sidebars to make sure I didn't break anything with these changes...
https://www.loom.com/share/bb5ad62bf6ff47dfb23a17ad8ab897dd
- I split up the selector for the `Tabs` content, I anticipate in the future breaking up these components even more granularly to further reduce unneeded panel re-rendering, I think there's still more progress that can be made here in the …
=> #5646 - Fix page state form rerenders

src/store/servicesSelectors.ts
- Fixes #5795
- memoization of the selectConfiguredServices selector prevented useRequiredPartnerAuth from updating and triggering a RequireAuth rerender
- reverting the memoization fixed the bug
- tested the change with @BLoe's "#5646 - Show sidebar form" mod to verify the sidebar fix still worked
=> #5795: restores link button in console when unlinked 

src/extensionConsole/pages/activateRecipe/ActivateRecipeCard.tsx
- Fixes merge conflict with new `InstallableIcon` usage introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/5794#event-9355254735
=> Fix usage of InstallableIcon in ActivateRecipeCard

src/sidebar/PanelBody.test.tsx, src/sidebar/PanelBody.tsx
- Closes #5790 
- `shadow-dom-testing-library`
=> #5790 Add delayed render to `PanelBody` loading indicator

package-lock.json, package.json, scripts/webpack.scripts.js, src/components/formBuilder/ImageCropWidget.tsx
- Bump react-image-crop from 10.0.11 to 10.1.4 (replaces dependabot #5818)
- updates import in ImageCropWidget to use new scss export
- updates webpack.script.js with sass-loader (resolves generate-headers error)
=> Update webpack for react image crop update

src/utils/installableUtils.ts, src/utils/recipeUtils.test.ts, src/utils/recipeUtils.ts
- Fixes #5830
- Handles getting extension point types for the two different states extension points in a `RecipeDefinition` (extension points that reference inner definitions, or entries in the extension point registry)
=> #5830 Fix get extension point types for RecipeDefinitions

src/sidebar/homePanel/ActiveModListItem.module.scss, src/sidebar/homePanel/ActiveModListItem.tsx
- Adds conditional line clamping to the starter bricks information on the Active Mod list item in the Home Panel to prevent list item overflow (list items are a fixed height)
- Starter brick info will be clamped to 1 line if the "Grant Permissions" link is present
- Otherwise, starter brick info will be clamped to 2 lines
- Note that the Mod title is clamped to 1 line in all cases
- These UI decisions were discussed with @BrandonPxBx
=> add conditional line clamping to starter bricks list

src/contrib/google/sheets/SheetsFileWidget.tsx, src/contrib/google/sheets/useGoogleSpreadsheetPicker.ts
- Fixes #5843 
- Adds case for `Action.CANCEL`
- If you cancel out of the Google Auth flow (if you're not already logged into a Google Account) you can also get stuck in a pending state. I'm not aware of any way to detect that though -- it seems the chromeP.identity.getAuthToken doesn't throw it the user closes the new tab that's open with the Google Login
- Add tests: we haven't figured out a good way to write File Picker test mocks/tests yet. I manually QA'd locally
=> #5843: handle cancelling Google File Picker

src/blocks/effects/AddQuickBarAction.tsx, src/blocks/transformers/blockFactory.test.ts, src/blocks/transformers/blockFactory.ts, src/blocks/transformers/controlFlow/ForEach.ts, src/blocks/transformers/controlFlow/ForEachElement.ts, src/blocks/transformers/controlFlow/IfElse.ts, src/blocks/transformers/controlFlow/Retry.ts, src/blocks/transformers/controlFlow/Run.ts, src/blocks/transformers/controlFlow/TryExcept.ts, src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.ts, src/blocks/transformers/tourStep/tourStep.ts, src/runtime/mapArgs.ts, src/runtime/pipelineTests/pipelineTestHelpers.ts, src/runtime/reducePipeline.ts, src/types/runtimeTypes.ts
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/5836
- Captures closure for pipeline args to ExternalBlock. Currently only at the top-level
- Modifies executeBlockWithValidatedProps to use the closure if available when running a pipeline
- Took the simple/naive approach of just dropping the lexical environment onto the pipeline expression that's passed along
- That's less efficient for tracing, because it duplicates part of the tree in traces
- As noted in the PR, technically, mapArgs:renderExplicit would be a better place to capture the closure
- However, it'd be wasteful because ExternalBlock is currently the only brick when tracking the complete requirement is necessary
- The try-catch, for-each bricks technically use a closure. But we didn't need to introduce any …
=> #5835: capture closure for pipeline args to ExternalBlock

src/sidebar/homePanel/ActiveModListItem.tsx, src/utils/recipeUtils.test.ts, src/utils/recipeUtils.ts
- Fixes #5854
- Fixes NPE for mods that have no inner definition defined for the extension point (i.e. if `definitions = {}`, as opposed to `definitions = undefined`)
- Prevents the UI from crashing if `getContainedStaterBrickNames` (called in the `useAsyncState` hook) throws an error (the starter brick feature is not critical to the UI)
- Note the test that I added to demonstrate the fix - it will fail if the changes to `getExtensionPointType` are reverted
- See question here in the engineering channel about the proper way to handle logic errors in `useAsyncState` hooks: https://pixiebrix.slack.com/archives/C023KL47XV4/p1685988221732089
=> #5854 Fix NPE in Home Panel for mods with no inner definition found

src/contentScript/sidebarController.tsx, src/sidebar/ConnectedSidebar.tsx, src/sidebar/sidebarSlice.ts
- Fixes #5855 
Note: In order to reproduce the issue, I added a 3 second delay to the initial panel logic in `ConnectedSidebar - useAsyncState`
Before:
https://www.loom.com/share/ce15f1d366a94adeb3c23445e43cdb1c
After:
https://www.loom.com/share/e9511c99b3ca4daaaf5a0b9e8cd7ffba
- The `Entry` types/methods could use a good amount of cleanup work here
=> #5855 bug fix - Add recipeToActivate to the initial-panels logic

src/sidebar/protocol.tsx
- Part of #5792 
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/5847
- Adds a buffer to protocol.tsx to ensure no messages are dropped during ConnectedSidebar initialization
- Manually QA'd by adding a 4-second sleep in ConnectedSidebar before registering the listener
- This might make https://github.com/pixiebrix/pixiebrix-extension/pull/5863/files unnecessary, because showSidebarActivationForRecipe calls ensureSidebar before calling showActivateRecipeInSidebar (to ensure webext-messenger is listening), so the message will be in the message buffer that's flushed to the react app
- It's probably still a good idea to merge https://github.com/pixiebrix/pixiebrix-extension/pull/5863/files so the panel is reserved though
=> #5792: fix sidebar initialization race by buffering messages during ConnectedSidebar initialization

package-lock.json, package.json, src/blocks/transformers/ParseJson.ts, src/blocks/transformers/parseJson.test.ts
- Closes #5874 
- Add JSON5 parsing support
- Add support for lenient JSON parsing. Currently handles extra text around the JSON array/object. (Sometimes LLMs return extra characters to explain their JSON output)
- Add smarter lenient parsing handling, e.g., try to find the maximal valid JSON object/array
=> #5874: add support for JSON5 and lenient JSON parsing

src/contentScript/sidebarController.tsx, src/contentScript/sidebarDomControllerLite.ts, src/extensionPoints/sidebarExtension.ts
- Part of #5906 
- Try some shot-in-the-dark changes to getSidebar and isSidebarFrameVisible:
- Use `globalThis.document.documentElement` for the querySelect
- Use function form for isSidebarFrameVisible
- Adds logging and pre-condition checks to try to identify what's causing the condition where `isSidebarFrameVisible` is somehow false when the sidebar is run after the ConnectedSidebarApp initializes
- Will cut an alpha/beta build with this PR to try to reproduce and then see the sequence/where the invariant became violated. I haven't been able to reproduce the problem on dev as frequently
=> #5906: side panel lifecycle logging and pre/post-condition checks

src/contrib/google/initGoogle.ts, src/contrib/google/sheets/RequireGoogleApi.tsx, src/contrib/google/sheets/SheetsFileWidget.test.tsx, src/contrib/google/sheets/SheetsFileWidget.tsx, src/contrib/google/sheets/__snapshots__/SheetsFileWidget.test.tsx.snap, src/contrib/google/sheets/useGoogleSpreadsheetPicker.ts
- Part of #3914 
- `SheetsFileWidget`:  (main functional changes)
- Add picker failure error state with retry
- On selection, fetch the sheet metadata via API to verify access
- Refactor to use useAsyncState
- `RequireGoogleApi`: adds telemetry events
- `UnsupportedBrowserGateView`
- `UninitializedGAPIGateView`
- `useGoogleSpreadsheetPicker` add event to help with remote customer support
- Add `SelectGoogleSpreadsheetEnsureTokenStart`
- Add `SelectGoogleSpreadsheetLoadLibraryStart`
- Add `SelectGoogleSpreadsheetShowPickerStart`
- Add `SelectGoogleSpreadsheetCancelled`
=> #3914: google sheets file picker widget error handling and telemetry

src/components/floatingActions/FloatingActions.scss, src/components/floatingActions/QuickbarButton.tsx
- Part of #5888
- Adds hide button to disable the floating action button
- Updates CSS for the FAB to reflect @BrandonPxBx s feedback
- Does not include the modal with information. That will come after the repositioning slice
- Telemetry for the FAB hide button use
Before:
After:
[Loom](https://www.loom.com/share/22288438d9084b67a52f997947d9d5ca?sid=aed8b263-96fb-4c93-ba42-6d54aab21df9)
=> 5888 Add hide option for the FAB, update FAB styles

src/sidebar/sidebarSlice.test.ts, src/sidebar/sidebarSlice.ts
- Closes #5933 
- Fix access before initialization in sidebarSlice
- Not sure why Typescript or Eslint wouldn't have caught this
- Sidebar forms still work without this. I didn't dig much into how they were working
=> #5933: fix access before initialization in sidebarSlice.addForms

src/contentScript/sidebarController.tsx, src/extensionPoints/sidebarExtension.ts
- Part of #5906 
- Add sidebar extension point and sidebar controller debug logging to try to identify root cause of panel getting stuck in loading state
- I haven't been able to reproduce the issue much on development. So I'm adding more logging here to gather more information
- Once I have some better leads, I'll add some pauses to try to force the issue on dev
- Some notes on what I'm trying to get additional logging coverage on: https://www.notion.so/pixiebrix/Panel-Debugging-2023-06-21-40207da119a14514981e05db16e43c37?pvs=4
=> #5906: add sidebar extension point and sidebar controller debug logging

src/background/browserAction.ts, src/contentScript/sidebarController.tsx, src/contentScript/sidebarDomControllerLite.ts
- Fixed #5906 🤞 
- Switches to `browser.tabs.executeScript` to eliminate race with the frame being added to the DOM
- Adds a waitAnimationFrame to rehydrateSidebar to ensure we're seeing the latest DOM state
- I opened a ticket in webext-content-scripts: https://github.com/fregante/webext-content-scripts/issues/22
- Add tests: there's not really much of a test to add here. If we write one, it would just be double-checking we're awaiting the tabs.executeScript promise in _toggleSidebar
=> #5906: await sidebarDomControllerLite.ts load

src/manifest.json
- Closes #5955
- Changes contentScript declaration to load main content script in all frames
- The marketplace enhancement contentScript is still only applied to the top-level frame
- With the permissions change in 1.7.30, we may need to take a look at the bundle size/memory usage of the content script when it's not being used. Injecting in all frames (even ad iframes) could cause memory utilization issues if user has a lot of tabs open
=> #5955: load main content script in all_frames

webpack.config.js, webpack.sharedConfig.js
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/3475
- Move webpack rules to pull simple-icons and bootstrap-icons from shared webpack config to the Extension-only webpack config. This prevents a build error from happening the App project
- Another option is to exclude these two rules from the App webpack config but I couldn't figure out how to do that and this is simpler/better
=> Bundle icons in Extension webpack config

src/background/starterBlueprints.test.ts
- Part of #5962 
- Drops unused `/starter-blueprints/install/` mocks from Jest tests. The code no longer calls that endpoint
- The code was dropped in this PR: https://github.com/pixiebrix/pixiebrix-extension/pull/5500
=> #5962: drop unused `/starter-blueprints/install/` mocks

src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx, src/sidebar/activateRecipe/ActivateRecipePanel.tsx, src/sidebar/sidebarSelectors.test.ts, src/sidebar/sidebarSelectors.ts, src/testUtils/factories/sidebarEntryFactories.ts
- Closes #5919
- I went with a rather specific redux selector, but I had other ideas:
1) create a `selectPanelCount` selector and close the sidebar if the count === 0
2) use the existing `selectIsSidebarEmpty` with a `useAsyncEffect` and close the sidebar if the sidebar is empty after `sidebar.recipeToActivate` is set to null
3) make `selectIsSidebarEmpty` a higher order function and pass in whether to include `sidebar.recipeToActivate` in determining if the sidebar is empty
4) change `ActivateRecipePanel.closeSidebar()` to be an async thunk and check for other panels, dispatch `hideActivateRecipe`, and handle closing the sidebar there
https://www.loom.com/share/3166cb6aa5af4c109a4cb47b69743846?sid=b3c6bcd4-f068-43b3-bf77-a9f1069805da
=> #5919 - Only close sidebar after activation if no remaining panels

contrib/services/google-oauth2-pkce.yaml
- Closes #5965 
- I created two new OAuth2 client in the Google Cloud Console. The prod credentials are currently listed as the default in the YAML definition.
https://www.loom.com/share/3385c712589343f8b12e179c44cb6398
=> #5965: Create google PKCE integration definition

src/components/documentBuilder/documentBuilderTypes.ts, src/components/documentBuilder/documentTree.test.tsx, src/components/documentBuilder/documentTree.tsx, src/components/documentBuilder/edit/getElementEditSchemas.ts, src/components/documentBuilder/preview/elementsPreview/Button.tsx, src/components/documentBuilder/render/ButtonElement.tsx
- Closes #4704 
- Pass disabled field value to the element
- Adds support for passing text, so you can use nunjucks to provide a truthy string
- Can't disable the button in the preview because that prevents it from being selected in the preview
=> #4704: fix `disabled` field on Button element in Document Builder

src/blocks/renderers/customForm.tsx, src/components/documentBuilder/createNewElement.test.ts, src/components/documentBuilder/createNewElement.ts, src/components/documentBuilder/edit/PipelineOptions.tsx, src/components/documentBuilder/preview/AddElementAction.tsx
- Closes #5985 
- Slices 1.1-1.3 here: https://www.notion.so/pixiebrix/Improve-Embedding-of-Form-Fields-in-the-Document-Builder-377a6f634c1641c6a45b9470e5ce23f5?pvs=4#085f771be17c4e18b6b774c091e50ec6
- Adds an affordance for custom forms to pass a className to apply to the parent div. But **does not show the affordance in the Page Editor UI**
- Adds "Form" to the 3-dot menu for elements, which adds the Custom Form brick directly
- When a form is added that way, the padding is set to zero
- To remove the padding in existing forms/mods, people can use the workshop
- What should the default behavior be for "Auto Save" in the added element? Currently, I have it set to show a submit button but without a success message
The alignment with the header looks like a font quirk with how the letter …
=> #5985: remove excess form padding and add to three dot menu in Document Builder

src/__snapshots__/Storyshots.test.js.snap, src/blocks/renderers/documentView/DocumentView.tsx, src/components/documentBuilder/documentTree.test.tsx, src/components/documentBuilder/documentTree.tsx, src/components/documentBuilder/edit/getElementEditSchemas.tsx, src/components/documentBuilder/preview/getPreviewComponentDefinition.tsx, src/components/fields/schemaFields/widgets/CssClassWidget.tsx, src/components/fields/schemaFields/widgets/__snapshots__/ClassClassWidget.test.tsx.snap
- Closes #5989 
- Adds a 'hidden' field to Document Builder elements to conditional hide fields without using Nunjucks conditionals with `d-none` 
- Drops the 'visible` toggle from Style/Layout that has no practical purpose
- We can't put in "Advanced Options" because the advanced options refer to the containing Render Document brick, not the element that's currently being edited
- We could consider starting the field as a toggle in the "off" state instead of excluded
- https://www.loom.com/share/c578c7abb19d4634838c3839e295093b
=> #5989: add field to conditionally hide Document Builder elements

src/components/documentBuilder/allowedElementTypes.ts, src/components/documentBuilder/documentTree.test.tsx, src/components/documentBuilder/documentTree.tsx, src/components/documentBuilder/edit/getElementEditSchemas.ts, src/components/fields/schemaFields/widgets/HeadingStyleWidget.tsx
- Closes #5987: adds h4-h6 headers in the Document Builder
- Add support for switching from a header element to a text element with markdown support that has the header as markdown
=> #5987: add h4-h6 headers in the Document Builder

src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.module.scss
* Per feedback from @BrandonPxBx, removes font-size override from brick name in page editor
* Brick name and docs link should be same size as `Advanced: ` header
=> removes font-size override from brick name in page editor

src/sidebar/sidebarSlice.test.ts, src/sidebar/sidebarSlice.ts
- Fixes #5998 
- Relates to https://github.com/pixiebrix/pixiebrix-extension/pull/6018
=> #5998 - verifies blueprintId is not null in fixActiveTabOnRemove

src/analysis/analysisVisitors/regexAnalysis.ts, src/blocks/readers/jquery.ts, src/blocks/transformers/jquery/JQueryReader.ts, src/blocks/transformers/jquery/JQueryReaderOptions.test.tsx, src/blocks/transformers/jquery/JQueryReaderOptions.tsx, src/pageEditor/fields/SelectorSelectorWidget.tsx, src/runtime/renderers.ts, src/types/runtimeTypes.ts, src/utils/templateUtils.test.ts, src/utils/templateUtils.ts
- Fixes #6021 
- Set `multi: false` so Match All field doesn't get stuck in a loading state
- Handle nunjucks expressions for selectors (these exist from mods where a nested selector was specified via Advanced Options)
- Introduces a SelectorDefinition type that accurately reflects the types that can exist in the JQueryReaderOptions component after normalization
- Have SelectorSelectorWidget fall back to `WorkshopMessageWidget` if it's a nunjucks expression that contains a template expression 
- Using Nunjucks in selectors is an advanced use case. It's OK to point people to the workshop for that
=> #6021: ensure Match All field doesn't get stuck in loading state in Extract from Page brick

schemas/component.json, src/blocks/transformers/brickFactory.test.ts, src/blocks/transformers/brickFactory.ts
- Closes #2933 
- Adds support for providing a `defaultOutputKey` in user-defined bricks
- Helpful so users don't have to rename the default `transformed` name
- In the future, we will add make assigning a brick's output to a variable optional.
- When we do that, we should add support for setting `defaultOutputKey` to `null` to indicate the brick should not set a variable. (I.e., consider null vs. undefined differently)
- The schema needs to be updated in the app too. It's not a blocker, because we don't block on verification failure, but it's good for the files to be consistent
=> #2933: add support for default output keys in brick yaml

src/extensionConsole/pages/brickEditor/Editor.tsx, src/extensionConsole/pages/workshop/CustomBricksCard.tsx, src/extensionConsole/pages/workshop/WorkshopPage.test.tsx, src/extensionConsole/pages/workshop/WorkshopPage.tsx, src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap, src/extensionConsole/pages/workshop/workshopTypes.ts, src/extensionConsole/pages/workshop/workshopUtils.test.ts, src/extensionConsole/pages/workshop/workshopUtils.ts, src/extensionConsole/testHelpers.tsx, src/pageEditor/panes/EditorPane.test.tsx, src/pageEditor/panes/save/saveHelpers.test.ts, src/pageEditor/panes/save/saveHelpers.ts, src/services/api.ts, src/store/workshopSlice.ts, src/testUtils/factories/registryFactories.ts, src/types/contract.ts
- Closes #5526 
- Fixes the type of `EditablePackage.kind` (see contract.ts). The values are the display values here: 
- https://github.com/pixiebrix/pixiebrix-app/blob/be1c486eba393e3c8e2f99401f78af5958b4060b/api/models/registry.py#L210-L210
- https://github.com/pixiebrix/pixiebrix-app/blob/be1c486eba393e3c8e2f99401f78af5958b4060b/api/serializers/brick.py#L65-L65 
- Fixes the workshop filter by mapping the values to not distinguish bricks vs. readers
=> #5526: fix duplicate entries in workshop type filter

src/blocks/errors.ts, src/blocks/transformers/brickFactory.test.ts, src/blocks/transformers/brickFactory.ts, src/components/documentBuilder/render/ButtonElement.tsx, src/contentScript/messenger/api.ts, src/contentScript/messenger/registration.ts, src/contentScript/pipelineProtocol.ts, src/runtime/pipelineTests/component.test.ts, src/runtime/reducePipeline.ts, src/sidebar/PanelBody.tsx, src/sidebar/RendererComponent.test.tsx, src/testUtils/detectPageMock.ts, src/types/runtimeTypes.ts
- Closes #6065 
- Closes #1939
- Fixes the `run` method of `ExternalBrick` (now called UserDefinedBrick) to run the pipeline in the contentScript
- Review changes in `brickFactory.ts`
- Modifies `runEffectPipeline` to `runHeadlessPipeline` and has it return it's value
- The root cause of the bug was an interaction between #1939 and #6052
- Instead of catching the HeadlessModeError, could call inferType and then conditionally call runEffectPipeline or runRendererPipeline based on the result. But would still need the logic to actually run the renderer brick after runRendererPipeline. So as-is, the implementation is the PR is a bit simpler
Added directly to sidebar:
Embedded in Document Builder:
Referencing a `@mod` variable inside of the user-defined brick:
- Update to call the …
=> #6065: fix rendering of user-defined bricks in the sidebar

src/manifest.json
- Closes #6069 
- Adds `match_about_blank` to the main content script in the manifest so the contentScript is loaded in those context
- If testing locally, reload your extension to ensure you have the latest manifest
- https://www.tiny.cloud/docs/demo/full-featured/
- https://www.loom.com/share/d421fba2b409457b9427cee0b2bc78de?sid=ea645e10-a3f0-41d4-a655-8751cfeb1386
=> #6069: add match_about_blank to manifest to run on iframes without src set

src/analysis/analysisVisitors/outputKeyAnalysis.test.ts, src/analysis/analysisVisitors/outputKeyAnalysis.ts, src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
- Closes #6079 
- Adds a warning in Page Editor if you're using a reserved name: mod, options, input
- https://www.loom.com/share/d96e87e33861418cb4c7c23c4c7d97c1?sid=47307dc2-cb08-47ed-ae77-9684faab476f
=> #6079: warn in Page Editor if using reserved name as output variable name

src/sidebar/Tabs.module.scss, src/sidebar/Tabs.tsx, src/sidebar/sidebar.scss, src/themes/colors.scss
- Closes #6056 
- Add missing design system colors to `colors.scss`
- Fix active state class
- Update tab design
~~Because the `Nav.Link` component now has a border radius, `border-right` looks like a shadow.`::after` shows the divider inside the tab rather than next to it. But because bootstrap does a lot of positioning on `Nav.Link` I can't simply give it a container div.~~
By I got around the bootstrap issues by wrapping all the Nav.Links in a `Nav.Item`.
- [loom](https://www.loom.com/share/f43b7fab21324e668b9c70e951344510?sid=e81f8414-1628-4875-b1ac-b065dee1ba53)
Max tabs while hovering on the 3rd:
3 tabs:
Single tab:
=> Update sidebar tab design

src/analysis/analysisVisitors/httpRequestAnalysis.test.ts, src/analysis/analysisVisitors/httpRequestAnalysis.ts, src/bricks/transformers/remoteMethod.ts, src/components/errors/NetworkErrorDetail.tsx, src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap, src/pageEditor/analysisManager.ts
- Closes #6119 
- Fixes the network error error view
- Implements lint rules, but without quick fixes: https://www.notion.so/pixiebrix/Simplifying-Calling-APIs-with-the-HTTP-Request-brick-6e401bd8524b412ebb14423c85fbc850?pvs=4#8a2aa984c58244a694dcc8aa11a755b3
- Implement quick fixes for the lint rules
=> #6119: improve HTTP Brick labelling/lint rules/network error message

src/auth/authTypes.ts, src/auth/authUtils.ts, src/testUtils/factories/authFactories.ts, src/types/swagger.ts
- Counterpart to https://github.com/pixiebrix/pixiebrix-app/pull/3726
- Pulls in swagger and drops reference to compliance token types
- It looks like the compliance token wasn't used anywhere in the extension project
=> Drop references to compliance token field

src/contentScript/lifecycle.test.ts, src/contentScript/lifecycle.ts, src/contentScript/pageEditor/dynamic.ts, src/permissions/extensionPermissionsHelpers.ts, src/starterBricks/contextMenu.test.ts, src/starterBricks/contextMenu.ts, src/starterBricks/menuItemExtension.test.ts, src/starterBricks/menuItemExtension.ts, src/starterBricks/panelExtension.ts, src/starterBricks/quickBarExtension.test.ts, src/starterBricks/quickBarExtension.tsx, src/starterBricks/quickBarProviderExtension.tsx, src/starterBricks/quickbarProviderExtension.test.ts, src/starterBricks/sidebarExtension.test.ts, src/starterBricks/sidebarExtension.ts, src/starterBricks/tourExtension.test.ts, src/starterBricks/tourExtension.ts, src/starterBricks/triggerExtension.test.ts, src/starterBricks/triggerExtension.ts, src/starterBricks/types.ts, src/types/runtimeTypes.ts, src/types/starterBrickTypes.ts
- Refactors names used in starter brick implementations to match new naming
- Improves method names and documentation to better reflect what the methods do:
- addExtension -> registerComponent
- run -> runComponents
- syncExtensions -> synchronizeComponents
- Removes an unused `template` field on StarterBrickABC
- Clean up local variables/private methods in individual starter brick implementations
=> Refactor starter brick interface method names

src/contrib/google/sheets/bricks/append.ts, src/contrib/google/sheets/bricks/lookup.ts
- Closes #5999 
- The new schema properties are optional because they haven't been added to the `required` arrays on the schemas
- _Note: Modifying the brick args is part of slice 3.2 in the spec_
=> #5999 - GSheets slice 3.1 - Modify Google Sheets brick schemas

src/components/floatingActions/FloatingActions.scss
- Closes #6030 
- Adjust z-index and initial offset
- When you're dragging, it's drags under the items too. We might consider showing it as above the elements while dragging
- https://www.loom.com/share/b68c58fcdf854840ab570c9120af2af6?sid=31e258ad-5d09-4290-bef3-97af14d967b3
=> #6030: adjust FAB offset and z-index and avoid chat widget conflicts

src/background/messenger/external/_implementation.ts, src/background/messenger/external/api.ts, src/contentScript/contentScript.ts, src/contentScript/loadActivationEnhancements.test.ts, src/contentScript/loadActivationEnhancements.ts, src/contentScript/sidebarActivation.ts, src/services/baseService.ts, src/store/extensionsStorage.ts, src/utils/strings.ts
- Part of #6139 
- Add support for directly activating multiple 1-click wonder mods from a link if the user has the extension installed
- Follow up to: https://github.com/pixiebrix/pixiebrix-extension/pull/6140, which added support when being triggered from the app
- Main changes are in loadActivationEnhancements
=> #6139: support direct multiple mod activation from single link in sidebar

src/components/floatingActions/FloatingActions.tsx, src/extensionConsole/pages/settings/SettingsPage.tsx
- Changes the FAB feature flag to `floating-quickbar-button-freemium`
- Original is `floating-quickbar-button`
- We have to change the feature flag because old browser extension versions did not have guards for enterprise/partner users. (So we can't flip the feature flag on for everyone.)
=> Change FAB feature flag to `floating-quickbar-button-freemium`

src/sidebar/activateRecipe/RequireMods.test.ts, src/sidebar/activateRecipe/RequireMods.tsx
- Closes #6163 
- Makes it so mod doesn't show configuration if no options are required
- @BLoe do you foresee any problems with this change?
- This is sufficient for what we want to do with 1.7.35
- We'll have a problem when we introduce the Google integration to the mod, as we have no way to mark integration configurations as optional in the mod definition. But we can defer that for now
=> #6163: don't require mod configuration in sidebar if all inputs optional

src/__mocks__/@/background/messenger/api.ts, src/background/messenger/api.ts, src/background/messenger/registration.ts, src/background/telemetry.ts, src/bricks/effects/sidebar.ts, src/bricks/transformers/extensionDiagnostics.ts, src/bricks/transformers/getAllTransformers.ts, src/components/floatingActions/FloatingActions.tsx, src/components/quickBar/quickBarRegistry.ts, src/contentScript/contentScriptCore.ts, src/contentScript/performanceMonitoring.test.ts, src/contentScript/performanceMonitoring.ts, src/contentScript/sidebarController.tsx, src/development/headers.ts, src/extensionConsole/pages/settings/ExperimentalSettings.tsx, src/store/settingsTypes.ts, src/utils.ts
- Adds skunkworks setting to measure ping between content script and background page
- Adds an `Extension Diagnostics` brick that collects relevant performance information. We can use it to build performance reporting mods for internal use
- I was considering hard-coding a quick bar action that'd report an event with the information
- Exposing the information via a brick will allow us to create a mod that collects information and more easily plugs into slack/bug-triage
- Create the performance reporting mod for team use
=> Add performance diagnostics brick

src/activation/useActivateRecipe.test.ts, src/activation/useActivateRecipe.ts, src/sidebar/activateRecipe/ActivateModPanel.tsx, src/sidebar/activateRecipe/ActivateMultipleModsPanel.tsx
- Closes #6139 
- Ignores permissions during multiple mod activation
- Always shows mod options during reactivation in sidebar. (Because reactivation is used for reconfiguration)
- NOTE: for multiple mod activation, mods that are already active are ignored
=> #6139: fix multiple activation permissions check; always show options during reactivation

src/contrib/google/sheets/core/sheetsApi.ts, src/contrib/google/sheets/ui/SheetsFileWidget.test.tsx, src/contrib/google/sheets/ui/SheetsFileWidget.tsx, src/contrib/google/sheets/ui/useGoogleSpreadsheetPicker.ts, src/hooks/useTimeoutState.test.ts, src/hooks/useTimeoutState.ts, src/telemetry/events.ts
- Closes #6176
- Closes #6172
- Shows an error message if there's a delay in getting to Google token
- Reports to Mixpanel when Google auth warning/error is shown to the user
- Calls `clearAllCachedAuthTokens` on retry to try to clear out any bad auth cache state
- `SelectGoogleSpreadsheetViewWarning`
- Add event `SelectGoogleSpreadsheetViewWarning` to the lexicon
=> #6176: add troubleshooting message after delay in getting Google token

src/analysis/analysisVisitors/pageStateAnalysis/modVariableNamesVisitor.test.ts, src/analysis/analysisVisitors/pageStateAnalysis/modVariableNamesVisitor.ts, src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts, src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts, src/bricks/effects/assignModVariable.test.ts, src/bricks/effects/assignModVariable.ts, src/bricks/effects/pageState.test.ts, src/bricks/effects/pageState.ts, src/bricks/transformers/brickFactory.test.ts, src/bricks/transformers/brickFactory.ts, src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx, src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts, src/pageEditor/analysisManager.ts, src/pageEditor/fields/AssignModVariableOptions.tsx, src/runtime/reducePipeline.ts, src/types/brickTypes.ts, src/utils/schemaUtils.test.ts, src/utils/schemaUtils.ts
- Closes #6193 
- Adds a `Brick.getModVariableSchema` method to return mod variables the brick might set
- Tracks known mod variables within a mod for use in variable analysis/popover
- Review implementations of getModVariableSchema
- Review AssignModVariableOptions
- https://www.loom.com/share/2ff5f35ea8ee445f89be0be3bcbc988f?sid=8c9254c7-2d67-4f2c-a576-085e1f63c28b
- Add support for tracking type for literal values
- Add support for tracking type based on variable usage. (Modify getModVariableSchema to accept the known vars for the brick, to dependently type the effect on mod variables)
=> #6193: initial support for mod variable static analysis

src/pageEditor/EditorContent.tsx, src/pageEditor/panes/NoModSelectedPane.tsx, src/pageEditor/panes/NoModsPane.tsx, src/pageEditor/panes/RecipePane.tsx
- Fixes some incorrect copy given that we've removed the "Unavailable" check box in the Page Editor
- Renames some components to use the correct name
=> Fix No Mods Pane copy in Page Editor

src/components/quickBar/QuickBarApp.tsx, src/domConstants.ts
- Fixes a bug where the quick bar container is loaded in iframes
- This causes an extra div to be added in the TinyMCE editor frame
=> Only initialize the quick bar container in top-level frames

src/components/fields/schemaFields/widgets/SchemaSelectWidget.test.tsx, src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx, src/components/form/widgets/SelectWidget.tsx, src/components/form/widgets/useAddCreatablePlaceholder.ts, src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
- Closes #6125 
- Adds a placeholder option to indicate that a user can create new options in both the `SchemaSelectWidget` and the `SelectWidget`. It appears when the search input is empty and creatable === true
- Removed a duplicated test
- ![image](https://github.com/pixiebrix/pixiebrix-extension/assets/10778363/c4813a76-658a-405e-a841-4c5e0f341f61)
- [Loom](https://www.loom.com/share/373b82de4cba41099fb4c9420dbb0d4d?sid=d43d414f-93ac-4796-83a0-f6f746abafdf)
- I started wrapping the `Creatable` react-select component and applying this logic there, but the typing ended up being rather painful to work with so I opted for this instead. If we need to make more common changes in the future we can reconsider.
=> Add indicator for creatable select options

src/components/quickBar/QuickBarApp.tsx, src/contentScript/lifecycle.ts, src/starterBricks/quickBarExtension.tsx, src/starterBricks/quickBarProviderExtension.tsx, src/starterBricks/sidebarExtension.ts, src/types/starterBrickTypes.ts
- Part of #6174
- Modifies `isAvailable` check for Quickbar/Sidebar to report not-available in frame
- Modifies lifecycle.ts to check isAvailable prior to registering/synchronizing components
- Reducing the number of irrelevant starter bricks in sub-frames should speed up frame initialization time
- For mod components using inner starter brick definitions, could avoid the hydration step for sidebar/quickbar/etc. starter brick types. That'd avoid the unnecessary work of registering the starter brick definition in the in-memory registry
=> #6174: mark quickbar/sidebar starter bricks as unavailable in iframes

src/contentScript/contentScript.ts, src/manifest.json, src/pageEditor/NonScriptablePage.tsx, src/pageEditor/panes/NonScriptablePage.test.tsx, src/pageEditor/panes/__snapshots__/NonScriptablePage.test.tsx.snap, src/utils/urlUtils.ts
- Closes #6231: allows the content script to run on HTTP pages
- The restriction for only making HTTPS API calls still applies
- We might consider making this end-user and managed enterprise settings
=> #6231: run content script on http pages

package-lock.json, src/components/floatingActions/FloatingActions.tsx, src/components/floatingActions/initFloatingActions.ts, src/contentScript/contentScriptCore.ts, src/errors/contextInvalidated.ts, src/utils/modUtils.ts
- Part of #6208 
- Lazily load React in the content script
- Lazily load the FAB
- Lazily load the notification toaster
- Drops some dead code from modUtils
- The main thing I was concerned about is the "Context Invalidated" message not showing if the extension context was necessary for dynamic imports. I tested that locally
- There's a decent chance React will still get loaded eagerly (but dynamically) due to brick instances being eagerly loaded in contentScriptCore. React ends up in the same bundle as nunjucks
- The remaining unnecessary code in the contentScript appears to be from broken tree-shaking for lodash-es and semVer
- I'm also not sure what the buffer polyfill is used for (probably being added due to NodePolyfillPlugin usage)
- Lazy load brick entities into memory to lower …
=> #6208: lazily load react in content script

src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx, src/extensionConsole/pages/settings/ExperimentalSettings.tsx, src/telemetry/events.ts
- Adds the following events:
- VarPopoverShow
- VarPopoverSelect
- SettingsExperimentalConfigure
- Indicate in VarPopoverSelect if the mouse or keyboard was used to select it
=> Add basic telemetry for experimental options and popover

package-lock.json, package.json, src/bricks/transformers/getAllTransformers.ts, src/bricks/transformers/readable.test.ts, src/bricks/transformers/readable.ts, src/development/headers.ts
- Closes #1361 
- Adds Mozilla Readability brick as "Extract Article or Readable Content" brick
- Introducing for use in some content moderation use cases
=> #1361: add Mozilla readability brick for extracting page content

src/sidebar/Tabs.test.tsx, src/sidebar/Tabs.tsx, src/sidebar/eventKeyUtils.test.ts, src/sidebar/eventKeyUtils.tsx, src/sidebar/sidebarSelectors.ts, src/sidebar/sidebarSlice.ts, src/types/sidebarTypes.ts
- Closes #6160
- Considered using an async thunk to close the sidebar
- Went with the panel count in an asyncUseEffect instead to keep UI concerns out of redux
- updated close sidebar logic to close the sidebar when any kind of panel is the last panel closed
- updated `defaultEventKey` to account for `closedTabs` when getting the next active key
https://www.loom.com/share/efbbb85e1073446b90a757802e072f29
=> #6160 - slice 3 make persistent tabs closable

src/store/settingsStorage.ts
- Fixes issue where the FAB wasn't showing up after initially installing and linking
- Context: https://pixiebrix.slack.com/archives/C023KL47XV4/p1691584311179569
https://app.rainforestqa.com/runs/1478212/tests/396036/browsers/windows10_chrome?job=51052613
=> defaults getSettingsState to the settingsSlice initialState

src/sidebar/Tabs.module.scss
FIx issue where you can't click through the invisible element that makes the rounded corner on the tabs
context: https://pixiebrix.slack.com/archives/C03CA2M4RCM/p1691607788518789
-[Loom](https://www.loom.com/share/ca022e9923414cd69f1f8355a8eb5753?sid=03ef1d9b-17e7-409e-b4cd-281dbc3dd10e)
-divider fix:
=> Bugfix: click through tab decoration

src/extensionConsole/pages/BrowserBanner.test.tsx, src/extensionConsole/pages/BrowserBanner.tsx, src/extensionConsole/pages/__snapshots__/BrowserBanner.test.tsx.snap, src/store/enterprise/managedStorageTypes.ts, static/managedStorageSchema.json
- Closes #6251 
- Adds a `disableBrowserWarning` flag to enterprise-managed storage
=> #6251: add disableBrowserWarning managed storage option

src/contentScript/contentScript.ts, src/contentScript/contentScriptCore.ts, src/contentScript/lifecycle.ts
- Part of #6245 
- I'm also attempting to figure out how to improve our logic to know when a frame is a child-frame of the background page, but getting blocked by a cross-origin request error:
=> #6245 Handle error in content script navigation init

src/bricks/transformers/ephemeralForm/EphemeralForm.tsx, src/sidebar/Tabs.test.tsx, src/sidebar/Tabs.tsx, src/testUtils/factories/sidebarEntryFactories.ts, src/types/sidebarTypes.ts
- Closes #6167 
- Allows using the X on the tab to close forms in the sidepanel
- Removes the `Cancel` button in sidebar form content dialogs still have the old `Cancel`
- [Loom](https://www.loom.com/share/fe7507e150fe485e8b4dfb54ee9f3784?sid=a2a6d326-745d-423e-a1ec-53b96b54fa46)
=> #6167 Make sidepanel forms closable

src/components/fields/schemaFields/widgets/cssClassWidgets/utils.test.ts, src/components/fields/schemaFields/widgets/cssClassWidgets/utils.ts
- fix the spacing input format so that negative values are entered/parsed correctly.
- e.x. -5 margin should be `m-n5` instead of `m--5`
- [loom](https://www.loom.com/share/062a51ee470d4c99ac78038a863e51e3?sid=8de6bf0e-fd60-4cfc-948b-a30308d91f86)
=> fix negative value inputs and update test

src/pageEditor/tabs/editTab/editTabTypes.ts, src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx, src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.module.scss, src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx, src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.module.scss, src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.tsx, src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
- Closes #6229
- This feature might be a little tricky to review because it involves recursion, and modifying the already-complex `usePipelineNodes` file. Happy to conduct and in-person review if this is helpful.
I clarified/renamed the terms `active`, `nestedActive`, `parentIsActive`, since I found these terms to be confusing. Here is a list of the new terminology and definitions that I am using:
- For `PipelineHeaderNodeProps` and `BrickNodeProps` (UI representations of nodes)
**active**: This is the node that should be appear to the user as "selected" in the UI; the node should be displayed in "cobalt blue"
**parentActive**: The node is a direct child of a node that is active, and should be light baby-blue (if it is a brick node) and dark baby-blue (if it is a header node) …
=> #6229 Add active styling to active pipeline header nodes

src/bricks/effects/customEvent.ts, src/components/documentBuilder/edit/getElementEditSchemas.tsx, src/components/fields/schemaFields/ButtonVariantSchemaField.tsx, src/components/fields/schemaFields/CssClassField.tsx, src/components/fields/schemaFields/CssSpacingField.tsx, src/components/fields/schemaFields/CustomEventField.tsx, src/components/fields/schemaFields/HeadingStyleField.tsx, src/components/fields/schemaFields/SchemaField.tsx, src/components/fields/schemaFields/SchemaFieldContext.tsx, src/components/fields/schemaFields/defaultFieldFactory.tsx, src/components/fields/schemaFields/fieldTypeCheckers.ts, src/components/fields/schemaFields/schemaFieldTypes.ts, src/components/fields/schemaFields/widgets/SchemaCustomEventWidget.tsx, src/contrib/zapier/PushOptions.tsx, src/pageEditor/fields/devtoolFieldOverrides.tsx
- Closes #6286 
- In `@/components/fields/schemaFields/widgets/SchemaCustomEventWidget.tsx`, I'm importing `import { selectExtensionKnownEventNames } from "@/pageEditor/slices/editorSelectors";`. This is throwing a lint warning for `no-restricted-paths`. Is there a different approach I should be taking?
https://www.loom.com/share/f938771e49784ca8a301b7fb46e3ed23?sid=f5238822-6b53-415a-ba9d-608401795077
=> Add dropdown with known events to "Emit Custom Event" brick

src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap, src/pageEditor/tabs/editTab/EditTab.tsx
- Fixes #6274
- The button type for the collapse button wasn't set. Because it existed in a form, pressing enter will treat the first button without a type as the "submit" button, thus toggling the data-panel.
- [Loom](https://www.loom.com/share/0aff56c97a674bae8ac2ba997ff81e2e?sid=7d0d5fd6-4b05-48a6-8f4e-fae56cfacbaf)
=> Stop Toggling Data Panel When Pressing Enter.

src/contentScript/loadActivationEnhancements.ts, src/pageEditor/panes/save/saveHelpers.test.ts, src/pageEditor/panes/save/saveHelpers.ts, src/sidebar/activateRecipe/RequireMods.tsx, src/testUtils/factories/integrationFactories.ts, src/types/integrationTypes.ts, src/utils/deploymentUtils.test.ts, src/utils/deploymentUtils.ts, src/utils/modDefinitionUtils.ts
- Closes #6192 
* Auto-activation works with optional services: https://www.loom.com/share/54d0c23e3644450286288600abc63c91
* Page editor doesn't change the `services` field format now: https://www.loom.com/share/d90cb20321bb4972a315b2510e997a67
=> #6192 - Google Sheets slice 4.3 - Allow auto-activation with optional integrations

src/bricks/readers/ElementReader.test.ts, src/bricks/readers/ElementReader.ts, src/utils/domUtils.ts
- Closes #6332 
- Adds an isVisible field to Element Reader output
- The visibility check doesn't work with jsdom, but leaving in test as documentation
=> #6332: add element visibility flag

src/components/formBuilder/RjsfSelectWidget.tsx, src/sidebar/PanelBody.tsx, src/sidebar/RendererComponent.tsx, src/sidebar/__snapshots__/PanelBody.test.tsx.snap
- Fixes #6331 overflow
- I previously added `overflow: hidden;` to panels as a part of [this bug](https://github.com/pixiebrix/pixiebrix-extension/pull/6289). This was to solve a scrollbar issue for rendered components, but I didn't realize that panels were used for individual bricks so this caused other issues. So I removed that and added the `overflow: hidden;` rule to rendered components exclusively (iframes)
- Also added a `menuPlacement="auto"` to the select widget so the menu options can pop up above the input if it fits better.
- [loom](https://www.loom.com/share/6eed28d5c709478887895052fef54355?sid=52d7bd87-2338-4420-81e4-a6b2fd9ad6e7)
- ![image](https://github.com/pixiebrix/pixiebrix-extension/assets/10778363/9334fb73-ce92-4036-8971-a8ecce651aa8)
- …
=> Fix Overflow for Rendered Components

src/permissions/permissionsUtils.ts
- I happened to notice this background script error while debugging something else:
The implementation in Federico's library is here: https://github.com/fregante/webext-content-scripts/blob/main/index.ts#L289
This obviously will NPE if you pass in an undefined `string`, so I fixed our shim `isScriptableUrl` function to check for this before calling the library.
=> Don't pass undefined urls to the isScriptableUrl() library function

src/components/fields/schemaFields/widgets/ServiceWidget.test.tsx, src/components/fields/schemaFields/widgets/ServiceWidget.tsx, src/services/serviceUtils.test.ts, src/services/serviceUtils.ts
- Closes #6340 
- Arguably, `extractServiceIds` should throw for $refs that don't correspond to integrations ids
=> #6340: fix duplicate service variable introduction

src/utils/modDefinitionUtils.test.ts, src/utils/modDefinitionUtils.ts, src/utils/registryUtils.test.ts
- Fixes #6362 
https://www.loom.com/share/4dae3396a9f641f3a8b3b9738d9fecbc?sid=878bb96f-fb59-4bdf-9e74-a2730a5d5720
=> #6362: only return unique services from getUnconfiguredComponentIntegrations

src/sidebar/Tabs.test.tsx, src/sidebar/useHideEmptySidebar.ts
- Fixes #6363
- In draft while I write some unit test coverage
- For reviewer context, `getReservedSidebarEntries` is a method exposed on the content script API in order to identify panels that will need to be rendered, even if they haven't been rendered yet. 
- The contentScript knows what panels will need to be rendered (because it runs all the bricks active for the current page), but lives in a different context than the sidebar, which doesn't have access to that information. We used to achieve this communication with the [event listeners added to ConnectedSidebar](https://github.com/pixiebrix/pixiebrix-extension/blob/9f004c4770c3a7cff05cdf8fe6cb40227513a019/src/sidebar/ConnectedSidebar.tsx#L52-L52)
- We originally introduced `getReservedSidebarEntries` in order to fix a race condition …
=> #6363 Add reserved sidebar entries to to useHideEmptySidebar logic

src/components/fields/schemaFields/widgets/varPopup/VarMenu.module.scss
- Closes #6322 
- The message at the bottom of the popover was wrapping. Changes the width so it doesn't,
before:
after:
=> Change the popover width so tooltip doesn't wrap

src/telemetry/initRollbar.ts
- Closes #6400 
I wish we could figure out how to reproduce this, but I haven't been able to. I think it's coming from this code: 
https://github.com/pixiebrix/pixiebrix-extension/blob/33db20ef045b78935d37b234fe0ebe66a96b39a7/src/starterBricks/menuItemExtension.ts#L295-L314
- We should see if there's anything we can do to prevent this error from happening
=> #6400 - Filter out ResizeObserver loop errors in the Rollbar config

src/components/form/widgets/RegistryIdWidget.tsx, src/extensionConsole/pages/mods/modals/shareModals/OwnerLabel.tsx, src/extensionConsole/pages/mods/modals/shareModals/PublishContentLayout.tsx, src/extensionConsole/pages/mods/modals/shareModals/ShareRecipeModalBody.tsx, src/extensionConsole/pages/mods/modals/shareModals/useHasEditPermissions.ts, src/extensionConsole/pages/mods/modals/shareModals/useSortOrganizations.ts, src/utils/registryUtils.test.ts, src/utils/registryUtils.ts
- Fixes #6407 
- New files (`OwnerLabel.tsx`, `useHasEditPermissions.ts`, and `useSortOrganization.ts`) were duplicated code pulled from `PublishContentLayout.tsx` and `ShareRecipeModalBody.tsx`.
- I refactored the files to make it easier to understand how `getScopeAndId` was being used.
- The current fix is in `registryUtils.ts`.
=> 6407: fix null pointer exception in Page Editor

src/bricks/util.test.ts, src/bricks/util.ts, src/contrib/google/sheets/bricks/lookup.test.ts, src/contrib/google/sheets/bricks/lookup.ts, src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx, src/contrib/google/sheets/ui/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap
- Adds a new field to the Google Sheets lookup brick that allows looking up all rows in a sheet without using a column/query "hack" on all rows
https://www.loom.com/share/67551718811a42f0a107c431f4d880af
=> Add 'Filter Rows' field to Google sheets lookup brick and fix a bug

src/services/api.test.tsx, src/services/api.ts, src/services/baseQuery.ts
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/3960
- This allows us to alias the import in the App project
See demo in the corresponding App PR.
=> Move RTK base query to separate file to allow webpack aliasing in the app

src/bricks/registry.test.ts, src/registry/memoryRegistry.ts
- Closes https://github.com/pixiebrix/pixiebrix-app/issues/3878
- Handle invalid bricks by skipping the invalid brick instead of failing to load any bricks at all
- Related backend PR for preventing the invalid package from being returned in `GET /api/registry/bricks/`
See demo video in https://github.com/pixiebrix/pixiebrix-app/pull/3941
=> Handle invalid registry bricks

src/components/addBlockModal/AddBlockModal.tsx, src/components/addBlockModal/BlockGridItem.tsx, src/components/addBlockModal/addBlockModalTypes.ts, src/components/addBlockModal/useAddBlock.ts, src/components/annotationAlert/FieldAnnotationAlert.tsx, src/components/form/FieldAnnotation.ts, src/components/form/FieldTemplate.tsx, src/contrib/google/sheets/core/useSpreadsheetId.ts, src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx, src/pageEditor/tabs/editTab/AnalysisResult.tsx, src/pageEditor/tabs/editTab/EditTab.module.scss, src/types/annotationTypes.ts
- Closes #6277 
- Fixes #6530 
https://www.loom.com/share/310a7839fd904b78ad093eb97a5acbc8
=> #6277 - Handle google login errors in Google sheet picker widget

src/pageEditor/exampleBlockConfigs.ts
_Sorry - trying this again from a branch and not a fork._ 
Removes the default `text-success` green coloring on the text element that is added by default on the Render Document brick. 
If someone else can test this locally, that would be awesome since there's clearly something wrong with my environment.
=> Remove green text coloring

src/telemetry/logging.test.ts, src/telemetry/logging.ts
- Closes #6522 
- Add a flag `rollbar-disable-report` to skip reporting errors to Rollbar
- Should the flag name be affirmative (e.g. `report-to-rollbar`) or negative (e.g. `rollbar-disable-report`)? I decided negative to reduce the number of flags applied to each user.
=> #6522: Flag to disable rollbar reporting

src/components/fields/schemaFields/BasicSchemaField.tsx, src/components/fields/schemaFields/fieldInputMode.test.ts, src/components/fields/schemaFields/fieldInputMode.ts, src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx, src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx, src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx, src/hooks/useToggleFormField.tsx
- Fixes #6533 
- Also improves the UX of IntegrationDependencyWidget in a similar way
https://www.loom.com/share/3b33a413aeb04e09bc078de512d35daa
- Here's the ticket for similar changes to the (separate) integration auth widget during activation: [Slice 4.2: support optional integration configurations during activation](https://github.com/pixiebrix/pixiebrix-extension/issues/6311)
=> #6533 Exclude/omit optional schema select value by default

src/components/ConfirmationModal.tsx
- Fixes `ModalProvider` so it has a default message for the confirmation modal and doesn't return `null`, because that breaks the page editor
=> Fix `ModalProvider` to not return `null`

package-lock.json
- Relates to https://github.com/pixiebrix/pixiebrix-extension/security/dependabot/59
- Dependabot is not able to open a PR
- Possibly because it's not a dependency or devDependency? 
- Used `npm update` to update the packages where possible
- Many dependencies still pin v7 of postcss
- We may not be able to resolve this fully until postcss is updated by those dependencies
=> updates postcss dependency where possible

src/manifest.json
This should avoid unnecessary bugs and confusing logging in unrelated contexts. Mentioned in https://github.com/pixiebrix/pixiebrix-extension/issues/6596#issuecomment-1746746672 and https://pixiebrix.slack.com/archives/C023KL47XV4/p1696421570974149
It also appears to fix https://github.com/pixiebrix/pixiebrix-extension/issues/6596, at least for this specific instance. I'm sure it will still appear on other sites with similar CSP.
=> Avoid injecting into API-only frames

.github/dependabot.yml
- Closes #6449 
- Automates https://github.com/pixiebrix/pixiebrix-extension/issues/4436
- Replaces https://github.com/pixiebrix/pixiebrix-extension/pull/4886 
- This PR may enable https://github.com/pixiebrix/pixiebrix-extension/issues/5570
=> #6449: Restore and group storybook updates

src/background/partnerIntegrations.ts
- Fixes #6603 
- Still need to confirm the token expires every 24 hours: https://pixiebrix.slack.com/archives/C042T2TBZ17/p1696957614998249
=> refresh AA token every 10 hours to avoid 24 hour expiration

src/auth/authConstants.ts, src/background/auth/authStorage.ts, src/contrib/google/sheets/core/useSpreadsheetId.ts, src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx, src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx, src/contrib/google/sheets/ui/RequireGoogleSheet.tsx, src/contrib/google/sheets/ui/TabField.test.tsx, src/contrib/google/sheets/ui/TabField.tsx, src/extensionConsole/pages/integrations/IntegrationEditorModal.tsx
- Fixes #6531 
* I tried to figure out a way to fire the listeners from the background script when `setCachedAuthData()` is called, but couldn't figure anything out that wasn't a giant hairy mess of messenger code back and forth, so I went with the simple-if-slightly-hacky method of monitoring local storage directly from the React component
=> #6531 Fix tab names field for gsheets

package-lock.json, package.json
- I think this closes #6624 
- Includes https://github.com/pixiebrix/webext-messenger/pull/163
- Follows #6626
=> #6624: Don't retry sending messages to discarded tabs

src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
- Closes #6687 
- This fixes the bug because `configId` is used later in the func (see `collectIntegrationOriginPermissions`) so we need to set it to the variable correctly
https://www.loom.com/share/051fb7e9f59c4a309dcb6eb61eeffacf
=> #6687: Fix Control Room OAuth error

src/analysis/analysisVisitors/eventNameAnalysis/checkEventNamesAnalysis.test.ts, src/analysis/analysisVisitors/eventNameAnalysis/checkEventNamesAnalysis.ts, src/analysis/analysisVisitors/eventNameAnalysis/collectEventNamesVisitor.test.ts, src/analysis/analysisVisitors/eventNameAnalysis/collectEventNamesVisitor.ts, src/bricks/PipelineVisitor.ts, src/bricks/blockFilterHelpers.ts, src/contentScript/pageEditor/types.ts, src/pageEditor/PanelContent.tsx, src/pageEditor/baseFormStateTypes.ts, src/pageEditor/exampleExtensionConfig.ts, src/pageEditor/pageEditorTypes.ts, src/pageEditor/panes/insert/InsertPane.tsx, src/pageEditor/panes/insert/useAutoInsert.ts, src/pageEditor/sidebar/ExtensionIcons.tsx, src/pageEditor/slices/editorSlice.ts, src/pageEditor/starterBricks/adapter.ts, src/pageEditor/starterBricks/base.test.ts, src/pageEditor/starterBricks/base.ts, src/pageEditor/starterBricks/elementConfig.ts, src/pageEditor/starterBricks/formStateTypes.ts, src/starterBricks/starterBrickModUtils.ts, src/starterBricks/types.ts, src/testUtils/factories/modDefinitionFactories.ts, src/testUtils/factories/pageEditorFactories.ts, src/types/starterBrickTypes.ts
- Closes #6519 
https://www.loom.com/share/e0ae7cbd42a74d828071d58961d8916a
=> 6519: adds trigger events to known names

src/background/telemetry.ts, src/telemetry/events.ts, src/tinyPages/devtools.ts, src/tsconfig.strictNullChecks.json
- Part of #6694
- Per [chrome developer documentation](https://developer.chrome.com/docs/extensions/mv3/devtools/#devtools-page):
> When a DevTools window opens, a DevTools extension creates an instance of its DevTools page that exists as long as the window is open.
- i.e. the instance is created even if the DevTools extension panel (the Page Editor, in this case) is not open
https://www.loom.com/share/1683c39d36984bbfa96e353ce7981932
=> Report DevToolsOpen event when dev tools are opened

src/pageEditor/EditorContent.tsx, src/pageEditor/utils.ts, src/telemetry/events.ts, src/tinyPages/devtools.ts
- Closes #6694 
- Also fixes #6732
- I've identified that determining docking orientation of the devtools is too hacky/convoluted for the amount of value that we'd get from adding the event. @BrandonPxBx and I identified that adding the PageEditor dimensions to `PageEditorSession` events will provide similar value for less effort & complexity
- Also adds `DevToolsClose` event for extra insight into users being potentially unsuccessful with getting to the Page Editor
- https://www.loom.com/share/1454475fe10a48cebcc5d6e74665737b
=> Add Page Editor dimension properties to `PageEditorSession` events

jest.config.js, src/bricks/effects/highlightText.test.ts, src/bricks/registry.ts, src/bricks/transformers/brickFactory.test.ts, src/bricks/transformers/brickFactory.ts, src/contentScript/contentScriptCore.ts, src/extensionConsole/pages/brickEditor/referenceTab/BrickDetail.stories.tsx, src/extensionConsole/pages/settings/useDiagnostics.test.ts, src/registry/internal.ts, src/registry/memoryRegistry.ts, src/runtime/pipelineTests/component.test.ts, src/runtime/reducePipeline.ts, src/starterBricks/triggerExtension.test.ts, src/testUtils/injectRegistries.ts, src/testUtils/loggingMock.ts, src/testUtils/testAfterEnv.ts
- Part of #6690 
- De-couples the brick registry and the runtime
- I took two different approaches
- For UserDefinedBrick, I passed the registry into the constructor
- For ReducePipeline, I'm using a module-level variable that's initialized by the contentScript/testing framework
- Introducing a class + constructor for ReducePipeline would be a pain. We'd need to start passing a dependency/registry context around nearly every
- Because the brick registry is a singleton instance, injecting the dependency into the reducePipeline module seemed like the most straightforward approach
- Splitting up the cycle does not appear to have an impact on bundle size
- Introducing injectRegistries in the jest setup required me to adjust a few test's mocks/assumptions
- Decouple starter bricks and other …
=> #6690: split up brick registry and runtime dependency cycle

src/errors/businessErrors.ts, src/errors/contextInvalidated.ts, src/errors/errorHelpers.ts, src/errors/knownErrorMessages.ts, src/starterBricks/starterBrickTestUtils.ts, src/tsconfig.strictNullChecks.json, src/utils/domUtils.ts
- Closes #6690 
- Eliminates the cycle in the error subfolder by extracting out the error message constants
- How might we prevent cycles from being introduced in the future? We run `madge` as part of CI, but it was missing this cycle. Unfortunately, the lint rule is likely to slow to run as part of CI?
=> #6690: eliminate remaining cycle in error code

src/contentScript/pageEditor/elementPicker.ts, src/contentScript/pageEditor/insertButton.tsx, src/contentScript/pageEditor/insertPanel.tsx, src/utils/inference/selectorInference.ts
- Part of #6784 
- Dynamically import `js-beautify` so it's not included in the end-user content script. The library is 130kb minified
- The content script size is likely not the main source of problems. So we can be opportunistic in trimming down the size, but need to focus on investigating potential memory leaks, etc.
=> #6784: remove `js-beautify` from end-user content script

src/background/telemetry.ts, src/registry/packageRegistry.ts, src/telemetry/logging.test.ts, src/telemetry/logging.ts, src/telemetry/trace.ts, src/tours/tourRunDatabase.ts
- Part of #6786 
- Calls `db.close()` on all IDB methods to explicitly close the DB connection
- The close method knows how to wait for transactions to finish, so technically, we could call it without using finally in some methods: https://buildandexecute.blogspot.com/2015/07/close-connections-to-your-indexeddb.html
- This should also allow the associated events to be GC'd
- Our tests might be running slow on CI due to the memory leak:
1.8.2-beta.2: After restarting, and clicking around to the Extension Console/Sidebar/Quick Bar:
After (Local)
- Rewrite using the new `using` operator: https://github.com/pixiebrix/pixiebrix-extension/pull/6788#issuecomment-1788265108. NOTE: can't destructure in binding pattern: https://github.com/microsoft/TypeScript/issues/55527
- Speed up composite DB …
=> #6786: explicitly close IDB connections

src/extensionConsole/App.tsx, src/sidebar/Tabs.test.tsx, src/sidebar/Tabs.tsx, src/sidebar/staticPanelUtils.tsx
- Part of #4000
- Lazy load sidebar content/modules as-needed to reduce de-facto memory footprint
- Puts the following sidebar content behind lazy load/suspense:
- Don't mount tab content in sidebar until they become active for first time
- Mod Launcher: important because it hydrates modDefinitions slice and makes call to marketplace
- Persistent Mod Panels (i.e., Sidebar Starter Brick): important because panels may re-import bootstrap, etc.
- Previously this PR also split out the Extension Console screens. See future work
- The sidebar loads a lot of content into memory (e.g., complete Mod Definitions for all mods available to the user) that doesn't end up getting used
- Module split the Extension Console Screens. I was getting aa Chrome errors in the background for "Uncaught (in …
=> #4000: lazy load sidebar content/modules

src/sidebar/Tabs.tsx
- Part of #4000 
- Fixes regression from: https://github.com/pixiebrix/pixiebrix-extension/pull/6780
- Mod panels getting stuck in the loading state
- Mod launcher missing panel heading for some panels
- I still haven't been able to reproduce the bug in my local environment
- I created https://github.com/pixiebrix/pixiebrix-extension/issues/6801 for the longer term performance fix
=> #4000: eager mount mod panels

webpack.config.js
- Adds a setting to TerserPlugin to strip console logs from production builds
=> #6797 - Drop console logs using TerserPlugin

src/sidebar/Tabs.tsx, src/starterBricks/helpers.ts, src/starterBricks/sidebarExtension.test.ts, src/starterBricks/sidebarExtension.ts
- Closes #6804 
- Closes #6801 
- Fixes a bug where state changes in another mod could denial of service the state change trigger for a sidebar
- Moves the statechange event filter outside the debounce
- Modifies the sidebar starter brick to debounce each mod component separately
- Re-introduces `mountOnEnter` for sidebar panels in the sidebar to improve memory footprint when a panel isn't visible
- To enable the change, the "read" for the starter brick is now performed per mod component instead of once per trigger. I don't think there's a simple way around that because mod components are now independently debounced
- I was also considering keeping a single debounce for the starter brick, but only running the debounced refresh if _any_ mod component needed to be updated. That wouldn't …
=> #6804: debounce sidebar panels independently

.github/workflows/ci.yml, src/testUtils/testEnv.js
- For #6815
CI may start failing and stall for hours. I think that it should have a timeout, even if this specific issue is eventually resolved.
=> #6815: Add timeout to Jest tests on CI

.github/workflows/release.yaml
- Extends the retention of release builds from 5 days to 30
- Requested by @MMirandi to make it easier to test/install releases
=> Extend production build retention

package-lock.json, package.json
- Addresses an `npm install` issue encountered by @BLoe 
It seems that the lockfile was somehow generated incorrectly, this PR is the result of:
```sh
npm rm eslint-config-pixiebrix
npm install eslint-config-pixiebrix -D
```
=> Bump eslint-config-pixiebrix to 0.31.0 correctly

src/components/formBuilder/TextAreaWidget.test.tsx, src/components/formBuilder/TextAreaWidget.tsx
- Fixes #6895 
- Our other custom widgets have FormLabels
- This appears to be due to the fact that the custom FieldTemplate used by the Custom Form brick doesn't include a label
- It appears that only custom widgets use the custom FieldTemplate
=> #6895: rjsf custom textarea missing labels

src/background/requests.ts, src/errors/assertProtocolUrl.ts, src/errors/assertUrlProtocol.ts, src/extensionConsole/pages/settings/AdvancedSettings.tsx, src/manifest.json, src/tsconfig.strictNullChecks.json, src/utils/enrichAxiosErrors.ts, src/utils/urlUtils.test.ts, webpack.config.js
- Closes #6902 
- Relaxes the CSP
- Fixes error enrichment that assumed http API calls aren't allowed
- In MV2, the CSP applies to all extension pages and the background script
- This may impact our https://crxcavator.io/ score
- Consider disabling by default, and exposing a toggle in the Settings > Developer Settings. (We'd block in our API call method vs. HTTP)
- In MV3, make the extension page CSP stricter: https://developer.chrome.com/docs/extensions/mv3/manifest/content_security_policy/
=> #6902: relax connect-src CSP to allow `http:` API calls

src/contentScript/messenger/api.ts, src/contentScript/messenger/registration.ts, src/contentScript/pageEditor.ts, src/pageEditor/sidebar/AddStarterBrickButton.tsx, src/pageEditor/sidebar/SidebarExpanded.tsx, src/telemetry/events.ts
- Closes #6897 
- Adds a link to the template gallery to the "Add" dropdown
- Adds a `PageEditorViewTemplates` event to track the button being clicked
- We didn't have a way to redirect the tab from the Page Editor, so I added a method to navigate the inspected tab
=> #6897: add page editor link to template gallery

package-lock.json, package.json, src/background/browserAction.ts, src/tinyPages/restrictedUrlPopup.html
- Continues #6947 
There were two situations that the previous code did not catch. All the changes:
- Catch window focus changes:
1. Open `chrome://something` in a window
2. Open `https://example.com` in another window
3. Switch between the two and see the popup not being updated
- Catch first extension/browser load and successive reloads. If no "tab change" event is fired, no popup was set
- Limit `tab.onUpdated` events to URL changes (the event fires a lot more than we need)
- Make the pop slightly wider to reduce wrapping
- I liked this API, so I added it to [webext-tools](https://github.com/fregante/webext-tools#setactionpopupgetpopupurl) and used it here as a high-level API. I can revert the last commit here if you prefer.
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="288" …
=> #6947: Support first load and window focus changes in restricted URL popover

.github/workflows/dependabot-auto-merge.yml
Related to #7000 
- Missed a required token permission: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
=> updates permissions to allow github actions to auto-merge some prs

.eslintrc.js, package-lock.json, package.json, src/bricks/available.test.ts, src/bricks/readers/jquery.ts, src/bricks/transformers/tourStep/overlay.ts, src/contentScript/ready.ts, src/contrib/google/sheets/core/useCurrentOrigin.test.ts, src/errors/errorHelpers.test.tsx, src/globals.d.ts, src/hooks/common.ts, src/utils/injectIframe.test.tsx, src/utils/postMessage.test.ts
- Enables `jest/no-snapshots` rule as warning as discussed
- https://pixiebrix.slack.com/archives/C023KL47XV4/p1700369600717069
- https://pixiebrix.slack.com/archives/C023KL47XV4/p1700494177288439
- Enables https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/prefer-module-scope-constants.md
- Enables https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/react-hooks-strict-return.md
- Reported only in one (deprecated) hook. It makes sense as a rule, but should we keep it enabled?
Full list: https://github.com/Shopify/web-configs/tree/main/packages/eslint-plugin#plugin-provided-rules
I also tried a couple more rules but they aren't great:
- `prefer-class-properties`: [buggy](https://github.com/Shopify/web-configs/issues/387)
- …
=> Lint warning for snapshots 

src/__snapshots__/Storyshots.test.js.snap, src/bricks/transformers/IdentityOptions.test.tsx, src/bricks/transformers/IdentityOptions.tsx, src/bricks/transformers/identity.test.ts, src/bricks/transformers/identity.ts, src/components/errors/getErrorDetails.test.tsx, src/components/errors/getErrorDetails.tsx, src/components/fields/schemaFields/schemaUtils.test.ts, src/components/fields/schemaFields/schemaUtils.ts, src/components/logViewer/LogTable.stories.tsx, src/contrib/editors.ts, src/pageEditor/exampleBlockConfigs.ts
- Fixes Page Editor field(s) for Identity Brick
- The Identity brick should be used instead of jq/javascript for constructing a value from other values
- Fixes identity brick to work with non-object values
- Adds variable popover hints for object/array form of input
- https://www.loom.com/share/f1f3dbd9b6b54b30a8b0f97f365fc707?sid=8ab71fa6-ec0d-4a70-b671-82c7d878b77f
=> Fix Identity Brick options in Page Editor and allow any value

src/pageEditor/sidebar/modals/CreateRecipeModal.tsx, src/pageEditor/slices/editorSlice.test.ts, src/pageEditor/slices/editorSlice.ts
- Closes #6943 
- Also changes copied extension suffix from `- copy` to `(Copy)` for consistency
- https://www.loom.com/share/ee4c342d430e46bb9198718361d4db89?sid=5cba6e0a-0c2c-4a22-b8d3-a1fa3780a6f3
=> #6943: add (Copy) suffix to copied mod name by default

src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx, src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx, src/components/fields/schemaFields/widgets/varPopup/menuFilters.ts, src/components/fields/schemaFields/widgets/varPopup/useAttachPopup.ts, src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.test.ts, src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.ts
- Closes #7006 
- The fix is contained in `useKeyboardNavigation`
- The additional memoization was from the early investigation that led to demonstrably improved performance 
- see the screenshots in the Demo section
- Not that the renders are both fewer in number _and_ shorter in duration
https://www.loom.com/share/fbcffcae3a924e459bc25bce2ed090de?sid=0fee0137-4744-4826-b4da-685a59bb08f6
**Before memoization**
**After memoization**
=> #7006: variable popoover reset selection for sub property

src/__snapshots__/Storyshots.test.js.snap, src/components/fields/fieldUtils.test.ts, src/components/fields/fieldUtils.ts, src/components/fields/schemaFields/BasicSchemaField.test.tsx, src/components/fields/schemaFields/SchemaField.test.tsx, src/components/fields/schemaFields/widgets/__snapshots__/FixedInnerObjectWidget.test.tsx.snap, src/extensionConsole/pages/integrations/IntegrationConfigEditorModal.test.tsx, src/pageEditor/panes/EditorPane.test.tsx, src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap, src/pageEditor/tabs/effect/__snapshots__/BlockConfiguration.test.tsx.snap, src/pageEditor/tabs/recipeOptionsValues/RecipeOptionsValues.test.tsx, src/pageEditor/tabs/recipeOptionsValues/__snapshots__/RecipeOptionsValues.test.tsx.snap, src/sidebar/activateRecipe/__snapshots__/ActivateModPanel.test.tsx.snap
- Automatically start case field names in brick configuration
- Includes hard-coded list of acronyms to capitalize
- Bricks can provide a `title` that overrides the default
- Some of our brick titles use sentence case, so there's still a bit of inconsistency
=> Automatically start case default field labels

src/pageEditor/starterBricks/pipelineMapping.test.ts, src/pageEditor/starterBricks/pipelineMapping.ts
- Fixes #7021 
* I don't know what the full implications are for this change. I initially just filtered out `prop !== "onSubmit"` on the same LOC, but the current change feels more robust to me. I don't know if there are other situations where we would have a missing pipeline prop and need to "normalize" it 🤷
=> #7021 Don't normalize onSubmit pipeline fields

src/modDefinitions/registry.ts, src/pageEditor/hooks/useSaveRecipe.test.ts, src/pageEditor/hooks/useSaveRecipe.ts, src/pageEditor/panes/save/saveHelpers.test.ts, src/pageEditor/panes/save/saveHelpers.ts, src/pageEditor/slices/editorSelectors.ts, src/pageEditor/starterBricks/base.ts, src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx, src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx, src/services/api.ts, src/tsconfig.strictNullChecks.json, src/utils/modUtils.test.ts, src/utils/modUtils.ts, src/utils/schemaUtils.ts
- Closes #7054
- Fixes a bug where options would be cleared if there were no dirty options because the new options would default to an empty options shape
- Consolidates mod normalization code into `normalizeModOptionsDefinition`
- Adds basic test file for `useSaveRecipe`
- Increase test coverage useSaveRecipe (e.g., mod metadata dirty/clean scenarios, etc.)
- Rename the useSaveRecipe hook and related hooks. I didn't re-name because I wanted to make the function code changes clearer because this is a regression bugfix PR
=> #7054: fix mod options saving regression

src/pageEditor/fields/FormModalOptions.test.tsx, src/pageEditor/fields/FormModalOptions.tsx, src/pageEditor/fields/FormRendererOptions.tsx
- Organizes temporary form builder fields into sections
- Moves form-level fields above the field definitions. Previously they were split above/below the field configuration section
- Adds section around field definition to embedded form editor for consistency
- Adds a smoke test for FormModalOptions
- There's only 1 field in the Location section. But it's not like the others
- https://www.loom.com/share/3561cf5676ee445b84779542d0c1bbe9?sid=9000c191-00b1-4701-aea7-650d1f212ba4
=> Organize form builder fields into sections

src/pageEditor/brickSummary.module.scss, src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNodeContent.module.scss
- Part of https://github.com/pixiebrix/pixiebrix-extension/pull/7028#event-11160215568
- I accidentally forgot to add this final commit to the PR referenced above, which included this vertical margin in the demo
**Before**
**After**
=> Add margin between Comment Brick brick title and summary

src/manifest.json
- Closes #7071 
- Drops gapi-related entries from CSP
- I think we still want to include `https://*.googleapis.com/*` in exclude matches because we know our content script should never run in that frame?
=> #7071: drop gapi requirements from CSP

src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
=> #7076 Fix GSheets Append row options so variable expressions aren't cleared from rowValues

src/__snapshots__/Storyshots.test.js.snap, src/analysis/analysisVisitors/templateAnalysis.ts, src/components/errors/NetworkErrorDetail.tsx, src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap, src/components/errors/getErrorDetails.test.tsx, src/components/fields/schemaFields/WorkshopMessage.tsx, src/components/quickBar/defaultActions.tsx, src/errors/networkErrorHelpers.ts, src/extensionConsole/pages/activateMod/PermissionsBody.tsx, src/extensionConsole/pages/mods/GetStartedView.tsx, src/extensionConsole/pages/mods/__snapshots__/ModsPageLayout.test.tsx.snap, src/extensionConsole/pages/mods/onboardingView/OnboardingView.tsx, src/pageEditor/NonScriptablePage.tsx, src/pageEditor/panes/EditorPane.test.tsx, src/pageEditor/panes/__snapshots__/NonScriptablePage.test.tsx.snap, src/pageEditor/tabs/editTab/UnsupportedApiV1.tsx, src/pageEditor/tabs/editTab/UpgradedToApiV3.tsx, src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.tsx, src/pageEditor/tabs/editTab/dataPanel/tabs/__snapshots__/PageStateTab.test.tsx.snap, src/sidebar/DefaultPanel.tsx
The existing link in docs was not migrated to gitbook. I've created the new page in Gitbook in the how-to/troubleshooting folder and updated the link. 
Only consideration is if we hate how long this link is, or if we think we will change the structure in the future, Gitbook will change the slug, so we may want to think through if we're happy with this sitting in the `troubleshooting` folder in `how-to` or if we want to put somewhere else. cc @twschiller if you have a preference?
Otherwise should be good to go!
=> Fix broken link in "troubleshooting network errors"

src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts, src/bricks/transformers/IdentityOptions.test.tsx, src/bricks/transformers/IdentityTransformer.test.ts, src/bricks/transformers/IdentityTransformer.ts, src/bricks/transformers/IdentityTransformerOptions.test.tsx, src/bricks/transformers/IdentityTransformerOptions.tsx, src/bricks/transformers/getAllTransformers.ts, src/contrib/editors.ts, src/pageEditor/exampleBrickConfigs.ts, src/tsconfig.strictNullChecks.json
- Changes the default brick configuration for the Identity Brick to use "property" vs. value
- https://pixiebrix.slack.com/archives/C042CA15AKS/p1702498096687359
- Refactoring
- Refactors filename to be `IndentityTransformer`
- Refactors file to use default export
=> Make default identity brick configuration use property to match column header in UI

src/bricks/transformers/controlFlow/MapValues.ts, src/pageEditor/utils.ts
- Fixes missing element key in brick outline for map values brick
- Also fixes the variable being missing in the variable popover
- We'll probably want to refactor getVariableKeyForSubPipeline to use the brick definition instead of defining in a separate method. Classic https://en.wikipedia.org/wiki/Expression_problem
=> Fix missing element key for map values brick

src/bricks/effects/sidebar.ts, src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx, src/types/schemaTypes.ts
- Make the show sidebar panel heading field title match the starter brick configuration terminology
- https://pixiebrix.slack.com/archives/C042CA15AKS/p1702492971546379
- I didn't want to introduce a constant because I didn't want to couple the files
=> Match show sidebar panel heading field title to starter brick field title

src/runtime/renderers.ts
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/5676
This was added last year but was disabled due to issues with JQ (https://github.com/pixiebrix/pixiebrix-extension/issues/4964). JQ has since been removed from the sandbox (https://github.com/pixiebrix/pixiebrix-extension/pull/6579).
In any case the memory issue didn't appear to be solvable via Transferable objects (because only ArrayBuffer is transferable, and we'd need to **duplicate** the object into it before transferring it, voiding any possible memory savings)
- Is this all that's needed here?
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3665a088-a557-498f-b088-70c098e8ecc9
- https://github.com/pixiebrix/pixiebrix-extension/issues/6580
=> #5676: Restore sandbox for nunjucks and handlebars

src/bricks/transformers/RunMetadataTransformer.test.ts, src/bricks/transformers/RunMetadataTransformer.ts, src/bricks/transformers/getAllTransformers.ts, src/development/headers.ts
- Adds an experimental Run Metadata brick
- We have some user-defined bricks for auditing/alerting use-cases (e.g., `@pixiebrix/deployments/message`) that would benefit from being deployment aware. Currently the deploymentId has to be hard-coded or passed in as a mod option
- Other PR with reflection related bricks: https://github.com/pixiebrix/pixiebrix-extension/pull/7125
- Uses `mod` vs. `blueprint` terminology
- Uses `componentId` vs. `extensionId` terminology
- Uses a transformer vs. a reader, because we're moving away from the the reader brick type
=> Add experimental Run Metadata brick

src/components/fields/schemaFields/widgets/varPopup/useAttachPopup.ts
- Closes #7143 
- Disables the variable popover in contexts where expressions are not allowed
- The mod options editor uses: https://github.com/pixiebrix/pixiebrix-extension/blob/c0a22d7025a82894e2170b0d9011c23c5dd363f8/src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx#L50-L50
- I considered adding a "allowVariablePopover" to the React Context. But using a combination of allowExpressions and the presence of the analysisSlice seems to cover our bases well
- NOTE: this bug still impacts the Current Inputs form: https://github.com/pixiebrix/pixiebrix-extension/issues/7148
=> #7143: disable variable popover trigger in mod options to prevent crash when typing `@`

.github/workflows/stale-issue.yml
- Creates a regularly scheduled action to automatically label/close stale issues and prs after the configured timeframe
- Issues and PRs marked stale will be closed after 7 days if there is no activity (updates, comments, stale label removed, etc.)
- Issues are marked stale after 365 days of inactivity (will likely narrow that window over time)
- PRs are marked stale after 30 days of inactivity (will likely also narrow this window over time)
=> automatically mark stale issues and prs weekly

src/pageEditor/pageEditor.tsx, src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx, src/sidebar/sidebar.tsx, src/telemetry/performance.ts
- Enables Datadog RUM in the Page Editor and Sidebar
- https://app.datadoghq.com/rum/sessions
=> Enable RUM in the Page Editor and Sidebar frames

src/activation/useActivateRecipeWizard.test.tsx, src/bricks/effects/tabs.ts, src/bricks/renderers/HtmlRenderer.ts, src/bricks/transformers/parseCsv.ts, src/bricks/transformers/parseDataUrl.ts, src/bricks/transformers/prompt.ts, src/bricks/transformers/randomNumber.ts, src/bricks/transformers/readable.ts, src/bricks/transformers/selectElement.ts, src/bricks/transformers/traverseElements.ts, src/contrib/google/geocode.ts, src/pageEditor/starterBricks/upgrade.test.ts, src/pageEditor/tabs/effect/BrickConfiguration.test.tsx, src/runtime/pipelineTests/pipelineTestHelpers.ts, src/runtime/pipelineTests/root.test.ts, src/sidebar/activateMod/ActivateModPanel.test.tsx, src/starterBricks/tourExtension.ts, src/starterBricks/triggerExtension.ts, src/utils/modUtils.ts, src/validators/generic.ts
- Fixes #7157 
- The problem was caused by not passing the `required` arg to `propertiesToSchema`. We default the args to all be required in that case. 
- By making the arg required, we remove the possibility of this mistake being made again
=> #7157: fix regression in required field for HtmlRenderer

.github/workflows/stale-issue.yml
- Increases the number of operations from 30 -> 100 (There's a GitHub rate limit, but we're well under the daily limit)
- Increases frequency of the run to daily at midnight
- Once we have gotten the number of stale issues under control, we'll look at reducing the number of operations and the frequency of the run
- Start running the action in our other repos
=> increase operations limit to 100, run nightly

src/bricks/transformers/convertDocument.test.ts, src/bricks/transformers/convertDocument.ts
- Add support to the `@pixiebrix/convert` brick to convert markdown to text
- Another option would be to use a library like https://github.com/ejrbuss/markdown-to-txt#readme which uses a special marked configuration vs. chaining
=> Support markdown to plain text conversion in `@pixiebrix/convert` brick

src/extensionConsole/pages/brickEditor/Editor.test.tsx, src/extensionConsole/pages/brickEditor/Editor.tsx
- Closes #7152
- It seems like this was the only place we use `fetch` in React code?
- https://www.loom.com/share/45310d7368d74bb2b47cdd7f92eae554
=> #7152 Replace instance of fetch for `/api/bricks` with RTK Query Hook

jest.config.js, package-lock.json, package.json, src/background/background.ts, src/background/navigation.ts, src/contentScript/contentScriptCore.ts, src/contentScript/lifecycle.ts
- Part of #6649 
- Follows #7030
=> #6649: Exclude navigation events that should not trigger page updates

src/components/form/useFieldAnnotations.test.tsx, src/components/form/useFieldAnnotations.ts
- Fixes #7167
Alternative approach I considered:
- Creating a dedicated prop on `AnalysisAnnotation` that contains the data that the annotation was produced for
- This would cause us to make a change to all of the places we create annotation objects, so I decided to favor this simple fix over that approach for now
- https://www.loom.com/share/1189868335994dfba1ab8577fb12a32b
=> #7167 Fix missing brick config warnings

.github/workflows/release.yaml
- Closes #7171
I forgot an ENV on that specific build. I also verified the other 2 builds (build-staging-3, build-for-store-3) and they're fine
- https://github.com/pixiebrix/pixiebrix-extension/actions/runs/7309509823
- https://github.com/pixiebrix/pixiebrix-extension/actions/runs/7309521743
=> #7171: Correctly build the production version for MV3

.github/workflows/ci.yml, .github/workflows/release.yaml
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/7196
I think this makes it clear that the mv3 version is a beta/future/testing version and that mv2 is "normal"
=> #7196: Improve build artifacts naming for MV3

.github/workflows/ci.yml, knip.mjs, scripts/env.mjs, scripts/manifest.test.js, webpack.config.mjs
I ran into the usual ESM issues in the previous PR (https://github.com/pixiebrix/pixiebrix-extension/pull/7211#issuecomment-1870465183), I thought it might be easier to just switch more files to ESM instead. Thankfully it was pretty straightforward 😮‍💨 
_Switching to .ts is harder/more involved: https://github.com/swc-project/register/issues/12_
=> #7211: Use ESM in webpack config

src/contentScript/sidebarDomControllerLite.ts, src/globals.d.ts, src/utils/extensionUtils.ts
This method and its types were wrong and it has likely been returning the wrong result for a while. I wrote the previous code a long time ago so it's possible that something has changed in the meanwhile (potentially in the polyfill)
This resulted in the button always showing "No updates available", and never "Too many requests" (throttled) for example. Now you can correctly see the second message on the second click.
I also dropped some outdated global types while I was there.
=>  Fix `Check Updates` button in options

scripts/manifest.mjs
This was mentioned as a possible solution to:
- #7174
Appended. Looks good?
=> #7174: Include "mv3" in package version

scripts/__snapshots__/manifest.test.js.snap, src/manifest.json, src/testUtils/factories/modDefinitionFactories.ts, src/utils/extensionUtils.ts
Mentioned in the previous PR, this PR cleans up some patterns left behind during the `all_urls` change. See review for details.
If left unsolved, it could cause trouble with:
- https://github.com/pixiebrix/pixiebrix-extension/pull/6851
=> #7211: Drop overlapping URL patterns

src/mv3/SessionStorage.ts, src/utils/storageUtils.ts
- Extracted from https://github.com/pixiebrix/pixiebrix-extension/pull/7216
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/6742
This PR also drops the now-unused and deprecated `setStorage`/`readStorage`
=> Drop `readStorage`/`setStorage`

src/sidebar/modLauncher/ActiveSidebarModsList.tsx, src/sidebar/modLauncher/ModLauncher.test.tsx
- Closes #7225 
- Sorts panels in launcher in alphabetical order (ignoring emoji)
- Consider adding matcher for asserting relative position: https://github.com/testing-library/jest-dom/issues/459
=> #7225: sort mod launcher panels in alphabetical order

src/components/documentBuilder/documentTree.tsx
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7057
- This was initially defined in https://github.com/pixiebrix/pixiebrix-extension/pull/3655
=> #7057: Fix image sizing bug in builder

src/pageEditor/sidebar/HomeButton.module.scss, src/pageEditor/sidebar/HomeButton.tsx, src/pageEditor/sidebar/ReloadButton.tsx, src/pageEditor/sidebar/Sidebar.module.scss, src/pageEditor/sidebar/SidebarCollapsed.tsx, src/pageEditor/sidebar/SidebarExpanded.tsx
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7268
- Prevents further size mismatches
| Before | After |
|--------|--------|
| <img width="67" alt="Screenshot 10" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/5d1b87b4-9350-483e-b0a9-a266ad871934"> | <img width="67" alt="Screenshot 11" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/9f5e2e49-315d-40ba-a9ce-8116a8c2e9cd"> |
In the collapsed sidebar, I dropped the house icon altogether because it doesn't really match the behavior of the button. Also it was the easiest solution instead of keeping the awkward dual-icon dual-color button.
The expanded sidebar is unchanged (except some sizing improvements that reduce the code require for all of this)
=> #7268: Fix editor sidebar logo sizing

src/pageEditor/sidebar/Sidebar.module.scss
- Caused by https://github.com/pixiebrix/pixiebrix-extension/pull/7269
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="305" alt="Screenshot 8" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/8985e455-722d-48e4-97a8-d49f753e526d">
<td><img width="305" alt="Screenshot 7" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/6b61f25e-8076-4b62-a9d7-1ff114a64a31">
</table>
=> #7269: Fix pageEditor sidebar buttons style

knip.mjs, src/services/api.ts
- Removes an unused api export
- Adds an exception for `contentScriptCore` since the `init()` function is dynamically imported
=> Fix dead-code-check failures in CI

src/modDefinitions/modDefinitionHooks.ts, src/starterBricks/contextMenu.ts, src/starterBricks/menuItemExtension.ts, src/starterBricks/panelExtension.ts, src/starterBricks/quickBarExtension.tsx, src/starterBricks/quickBarProviderExtension.tsx
While looking into https://pixiebrix.slack.com/archives/C0436P48QHY/p1705451796174779, I realized that some notifications don't really say what's wrong. Generic errors can be frustrating, we should always include more information if available.
This PR only affects the brick run notification error, but ideally we'd want to enforce the `error` prop in `notify.error`. There's only a handful of situations where we trigger `notify.error()` without an actual error.
=> Include details in mod error notifications 

.github/workflows/rainforestqa.yml
- Closes #7362
- Our hypothesis is that Datadog errors with broken source maps are from Rainforest builds + runs (see [example](https://app.datadoghq.com/logs/error-tracking/issue/2a2e1d28-b599-11ee-96d2-da7ad0900002?refresh_mode=sliding&view=spans&from_ts=1705521578700&to_ts=1705607974940&live=true)). This PR sets certain env vars so `SOURCE_MAP_PUBLIC_PATH` is properly set in the Rainforest build and source maps work for errors generated during Rainforest runs.
- See [slack discussion](https://pixiebrix.slack.com/archives/C06DUA1HU75/p1705599443633379)
=> #7362: Set sourcemaps value in rainforest build

.github/workflows/rainforestqa.yml
- Part of #7362 
- See [slack](https://pixiebrix.slack.com/archives/C06DUA1HU75/p1705677566610569?thread_ts=1705631686.175459&cid=C06DUA1HU75)
- I think we should be okay to continue using `github.hash`. The [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context:~:text=github.com.-,github.sha,-string) define it as:
> The commit SHA that triggered the workflow. The value of this commit SHA depends on the event that triggered the workflow. For more information, see "[Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows)." For example, ffac537e6cbbf934b08745a378932722df287a53.
We'll have to test it to be sure.
=> #7362: Fix source map path

src/components/tabLayout/EditorTabLayout.module.scss, src/pageEditor/ElementWizard.module.scss, src/pageEditor/sidebar/HomeButton.module.scss, src/pageEditor/sidebar/Sidebar.module.scss
Minor UI improvement for the page editor, plus a couple of bugfixes.
- Adds single "editor pane" soft shadow, replacing the border/shadow combo
- Fixes  ([again](https://github.com/pixiebrix/pixiebrix-extension/pull/7269)) the home button `border-radius` on the collapsed version
- Realigns the Edit/Logs tab bar (wrong height, especially in the `EditorTabLayout` component)
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="372" alt="Screenshot 12" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/7fc0ca3d-9925-4b46-bca3-4c0295c9eb41">
<td><img width="372" alt="Screenshot 10" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/0d78805e-90b2-4581-94f4-dcf438332ded">
</table>
<table>
<tr>
<th>Before
<th>After ✨ 
<tr>
<td><img width="399" alt="Screenshot …
=> Page Editor: Improve shadow and fix sizing of tabs

src/__mocks__/@/utils/expectContext.ts, src/background/executor.ts, src/contrib/google/sheets/core/useCurrentOrigin.test.ts, src/contrib/google/sheets/core/useCurrentOrigin.ts, src/contrib/uipath/LocalProcessOptions.tsx, src/pageEditor/hooks/useCurrentUrl.ts, src/pageEditor/utils.ts, src/telemetry/BackgroundLogger.ts, src/testUtils/detectPageMock.ts, src/utils/expectContext.ts
> [!NOTE]
> This PR's `base` branch is https://github.com/pixiebrix/pixiebrix-extension/pull/7378
See issues in:
- https://github.com/pixiebrix/eslint-config-pixiebrix/pull/192
- https://github.com/pixiebrix/pixiebrix-extension/pull/7378
=> #7378: Fix page editor detection

src/bricks/util.ts, src/pageEditor/starterBricks/trigger.ts, src/pageEditor/tabs/trigger/TriggerConfiguration.tsx, src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap, src/starterBricks/contextMenu.ts, src/starterBricks/menuItemExtension.ts, src/starterBricks/panelExtension.ts, src/starterBricks/quickBarExtension.tsx, src/starterBricks/quickBarProviderExtension.tsx, src/starterBricks/sidebarExtension.ts, src/starterBricks/tourExtension.ts, src/starterBricks/triggerExtension.test.ts, src/starterBricks/triggerExtension.ts, src/utils/domUtils.test.ts, src/utils/domUtils.ts, src/utils/injectIframe.tsx, src/utils/promiseUtils.test.ts, src/utils/promiseUtils.ts
- Closes #7380 
- Context: https://www.notion.so/pixiebrix/Phase-3-Add-support-for-only-running-trigger-on-visible-tab-on-mod-activation-79fcd0ee5569428c9a7b46a69a9945a4?pvs=4
- Adds support for "background" option to all triggers
- For backward compatibility, `background: true` for non-interval triggers if not provided/nullish
- Shows the "Allow in Background" option in Page Editor for all trigger types
- Refactoring:
- `selectAllBlocks` -> `collectAllBricks`
- `extension` -> `modComponent`
- There's a discrepancy in which screens call `reactivateEveryTab`. I think it's OK to address the discrepancy later:
- Standalone Mod Component: `ActivateExtensionCard` does not call `reactivateEveryTab`
- Mods: `useActivateRecipe` calls `reactivateEveryTab`
- Functional change is in …
=> #7380: support background option for all triggers

src/pageEditor/sidebar/filterSidebarItems.test.ts, src/pageEditor/sidebar/filterSidebarItems.ts
- Fixes #6839
- We should consider reviewing usages of lodash lowerCase we should replace throughout the App, as it actually
behaves differently than the native toLowerCase (namely, it splits up a camelcased word, ex. `LinkedIn` -> `linked in`)
=> Fix case sensitive search in the mods sidebar #6839

src/bricks/transformers/component/TableReader.ts, src/pageEditor/sidebar/SidebarExpanded.tsx, src/pageEditor/sidebar/arrangeSidebarItems.ts
- Removes usage of the lodash lowerCase method which has weird behavior for camelCased strings, splitting them. This is a follow-up to:  https://github.com/pixiebrix/pixiebrix-extension/pull/7418
=> Removing usage of lodash lowerCase

src/__mocks__/@/telemetry/logging.ts, src/hooks/logging.ts, src/runtime/reducePipeline.ts, src/telemetry/logging.ts
I can't reproduce it anymore, but I was seeing issues where `chrome.storage` was not defined after a context invalidation, sending the background logger in a loop.
This makes sure that we don't throw errors while throwing errors
=> Avoid errors in `loggingConfig` getter

src/bricks/transformers/selectElement.ts, static/background.worker.js
- Prevents some DOM access from breaking the MV3 extension altogether
- Lets us more easily debug such issues
The MV3 extension is failing to load due to an unchecked DOM access by the bricks. The dev tools make it difficult to find the source of this error.
- https://github.com/pixiebrix/pixiebrix-extension/issues/7185#issuecomment-1870804167
- https://github.com/pixiebrix/pixiebrix-extension/pull/7381
=> Make worker more resilient to DOM API usage attempts

src/background/browserAction.ts, src/contentScript/sidebarDomControllerLite.ts
- Fixes the first piece of https://github.com/pixiebrix/pixiebrix-extension/issues/7420
- https://github.com/pixiebrix/pixiebrix-extension/pull/7354
=> #7420: Drop updateSidebar call from `browserAction.onClick`

src/__snapshots__/Storyshots.test.js.snap, src/components/formBuilder/edit/FieldEditor.tsx, src/components/formBuilder/edit/FormEditor.test.tsx, src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
- Closes #7432 
https://www.loom.com/share/9c0a387205a94073b36ffe0a692eb8a8
=> #7432: support placeholder text in form builder

.github/workflows/ci.yml, knip.mjs, package.json, src/__mocks__/@/hooks/useContextInvalidated.ts, src/hooks/useContextInvalidated.ts, src/tsconfig.strictNullChecks.json
- Enables JSDoc tags in order to preserve single exports where necessary: 
- https://knip.dev/reference/cli#--experimental-tags
- Moves the CI command into package.json so we can run the same version locally
- Restores the file as proposed in
- https://github.com/pixiebrix/pixiebrix-extension/pull/7419#discussion_r1464775088
The new `@knip` tag does not work for unused files, to exclude those we have to keep adding files to the config
=> Allow exclusion from knip via `@knip` JSDoc tag

static/background.worker.js
I've had the background dev tools throw an error regarding `chrome.runtime.getManifest` being undefined and wondering how that could be possible.
It turns out that when switching between MV2 and MV3 versions, Chrome may decide to not unregister the worker, so both stay registered.
This is purely a DX fix that serves to avoid confusion and time waste.
=> Clarify MV3 zombie worker error

src/tinyPages/RestrictedUrlPopupApp.tsx
When on the **extension console**, the user should not be asked if they want to visit the **extension console**.
This conflict was the reason why I had inadvertently dropped the link here https://github.com/pixiebrix/pixiebrix-extension/pull/7354#discussion_r1463863618
This works correctly now:
Also verified on MV2
<table>
<tr>
<td><img width="444" alt="Screenshot 17" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/3d785201-339f-48ad-8910-65f96b698e5f">
<td><img width="444" alt="Screenshot 16" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/dbdacbc8-ed59-4d44-b82f-e01ad41e3c51">
</table>
=> Drop self-referencing extension console link in sidePanel

.github/workflows/stale-issue.yml
- Continues the effort to bring the stale issue check down to every 90 days (eventual goal)
- Not doing all at once because we still have nearly 200 issues and I don't want to flood people's inboxes with issues to validate
=> Reduce stale days count to 150

src/__snapshots__/Storyshots.test.js.snap, src/extensionConsole/pages/mods/GetStartedView.module.scss, src/extensionConsole/pages/mods/GetStartedView.tsx, src/extensionConsole/pages/mods/__snapshots__/ModsPageLayout.test.tsx.snap
Here are some views from the extension console, currently:
- It brings that Get Started view up to par with the other views
- Drops some unnecessary micro-adjustments made to its style (e.g. the CSS was changing the padding of the keyboard shortcuts from 5px to 4.5px)
- Adds a maximum width so that the text doesn't get too long
Note that the keyboard shortcut color matches what we have elsewhere. If we don't like that, it should be changed across the extension
- Extracted from https://github.com/pixiebrix/pixiebrix-extension/pull/7443
=> Make Extension Console "Get Started" view consistent with other views

scripts/__snapshots__/manifest.test.js.snap, src/manifest.json
=> Document Builder custom styles Slice 1: Change CSP to allow remotely hosted CSS files from our S3 bucket

src/bricks/renderers/document.ts, src/bricks/renderers/documentView/DocumentView.tsx, src/bricks/renderers/documentView/DocumentViewProps.tsx, src/sidebar/PanelBody.test.tsx
- Closes #7493 
https://www.loom.com/share/c9f441bfb11146118920b3816a5328e8
- I spent a while trying to get a document render test working with a nested document and stylesheets applied, but couldn't figure out how to get rid of the "delayed render" effect. I tried fake timers, `await tick()`, `sleep`, and mocking out various hooks and components, but nothing seemed to work, the rendered test always had the content hidden and a loading indicator showing. So, future work is to figure that out and actually get a test working to show that the stylesheet link is rendered in the document view. I verified this manually for now.
=> #7593 Document Builder custom styles Slice 3: Attach stylesheets to the rendered document

src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.test.ts, src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.ts, src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts, src/bricks/renderers/customForm.ts, src/bricks/renderers/document.ts, src/bricks/renderers/documentView/DocumentView.tsx, src/components/formBuilder/FormBuilder.test.tsx, src/contrib/editors.ts, src/pageEditor/exampleBrickConfigs.ts, src/pageEditor/fields/FormRendererOptions.tsx, src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx, src/pageEditor/utils.ts
- Closes #7494 
- Updates DocumentView so that custom stylesheets override bootstrap, if set
- document brick throws a BusinessError if there's an invalid stylesheet url
=> #7494 Document Builder custom styles Slice 4: Update CustomFormRenderer brick input schema and config UI

src/__snapshots__/Storyshots.test.js.snap, src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
- Part of #7511 
- This change increases the width for the label using our custom `widerLabel` prop (for more context see: https://github.com/pixiebrix/pixiebrix-extension/blob/a8d392018f377779a34e5a5236be5d586db205d7/src/components/form/FieldTemplate.tsx#L92
https://www.loom.com/share/624ebf490d8a49559280b0a119658b73
- _Work for the issue/ticket that will be in a follow-up PR_
=> fix visually-broken label in Control Room Oauth

src/contentScript/messenger/registration.ts
This issue was introduced the last PR:
- https://github.com/pixiebrix/pixiebrix-extension/pull/7519
In short: the same method was registered in both the strict and non-strict messenger registration files.
This wouldn't be an issue, but I forgot I had made the Messenger throw when the same method was registered twice (even if TypeScript already prevents incompatible registrations)
=> Restore content script due to duplicate Messenger registration

src/bricks/renderers/CustomFormComponent.test.tsx, src/bricks/renderers/CustomFormComponent.tsx, src/components/formBuilder/TextAreaWidget.test.tsx, src/components/formBuilder/TextAreaWidget.tsx, src/testUtils/testHelpers.tsx
- Fixes #7543
- Allows users to press enter without submitting in textarea with other modifier keys (control and alt)
- Fixes an issue with the wrapper in the shared render util method
=> submit on enter works properly when form is externally updated

src/extensionConsole/App.tsx
- Mentioned in https://pixiebrix.slack.com/archives/C0436P48QHY/p1706247634107659
- Saves several seconds on load
- Avoids a duplicate `fetch` of the bricks
The before/after demos are self-explanatory. They show a page reload:
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/55d55f04-2142-427d-8c2c-7de2e882b7de
<td>
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/fd01e8a4-a175-4135-ae68-4ff128217109
</table>
Note that this does not affect the Mods page, which still loads, and loads faster because it does not load the bricks twice.
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="587" alt="Screenshot 12" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/0be2665c-e6e1-44aa-af80-d5730e16cb0a"> …
=> Remove redundant/unnecessary brick refresh on extension console (speeds up by several seconds)

.github/workflows/stale-issue.yml
- Reduces the number of days until an issue can be considered stale to 120
- Part of the iterative reduction to 90 days.
=> reduce days until stale to 120

src/background/background.ts, src/background/backgroundDomWatcher.ts, src/tsconfig.strictNullChecks.json
This change warns us of unexpected changes to the background "page".
Why:
- we had issues in the past with iframes unexpectedly being added into the background page
- https://github.com/pixiebrix/pixiebrix-extension/pull/6598
- the background worker in MV3 will throw hard errors when this happens
- we're seeing a "This target is not a frame" errors on DataDog, which might point to another iframe being added to the background page
This is the current situation already, some component is injecting some unnecessary (but innocuous) CSS
=> Warn of DOM changes in background page

src/components/documentBuilder/createNewElement.test.ts, src/components/documentBuilder/createNewElement.ts
- Fixes #7019
Note that this does not affect mods created before this change
=> #7019: Fix "Selecting one of multiple forms in a Render Document selects all of them"

src/components/ellipsisMenu/EllipsisMenu.module.scss, src/components/ellipsisMenu/EllipsisMenu.tsx
- medium size option for ellipsis menu
- Part of #4700
- I overlooked adding a medium size option in the last PR which the app website uses for its buttons. This adds an option to specify a medium size for the menu which is the case when neither "btn-sm" nor "btn-lg" class is present.
https://www.loom.com/share/650990bf918c4669b86f0dc16664ee29
- Consider relying on the container to specify the height for components in the future rather than specifying them per component.
=> ellipsis md size

.eslintrc.js, eslint-local-rules/noCrossBoundaryImports.js, eslint-local-rules/noCrossBoundaryImports.test.js, knip.mjs, package-lock.json, package.json, src/extensionConsole/components/IDBErrorDisplay.tsx, src/utils/notify.tsx
- Closes https://github.com/pixiebrix/eslint-config-pixiebrix/issues/35
- Closes https://github.com/pixiebrix/eslint-config-pixiebrix/issues/123
👆 😅 it was so slow that I opened two issues for the same thing over the years. 
```
Rule                                            | Time (ms) | Relative
:-----------------------------------------------|----------:|--------:
import/no-restricted-paths                      | 50222.336 |    49.1%
@typescript-eslint/no-unsafe-assignment         |  8793.188 |     8.6%
unicorn/no-unnecessary-polyfills                |  4247.493 |     4.1%
@typescript-eslint/no-floating-promises         |  3331.880 |     3.3%
@typescript-eslint/no-confusing-void-expression |  2293.998 |     2.2%
@typescript-eslint/no-unsafe-argument           |  1524.524 |     1.5% …
```
=> Hand-roll faster and safer version of `import/no-restricted-paths`

src/background/contextMenus.ts
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7100
The code has a default for `["all"]` in a couple of places, but that default is not applied when the `contexts` is `[]`
This PR simply enforces that default at the last possible moment, in order to avoid errors at the chrome API level.
I think that ideally the brick should be in an "invalid" state but this solution:
- is quick
- avoids repeating errors when the page loads and one of the context menus is invalid
- still needs to be there to catch all existing invalid mods
Before this PR, the content script would immediately show a notification error after removing the last context.
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/da183e11-ecf2-4a89-8f31-3e13ed4f636a
=> #7100: Don't show error if context menu "contexts" isn't specified

src/contentScript/lifecycle.ts
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/4258
PixieBrix is pretty good at updating the extension points that were installed in a previous run of the extension, but this is done after the content script has finished loading.
This means that the page will keep unclickable "menu items" on the page until that process finishes (if it finishes without errors)
After this PR, the menu items will be removed immediately, and they will also be removed if the user disables the extension.
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/880bec87-35b0-4bda-b583-0be4f53e42fc
=> #4258: Remove extension points on context invalidated

.github/workflows/stale-issue.yml
- Reduces the stale issue days to 90
- This should be the last time this number changes
=> reduces days-before-issue-stale to 90

scripts/__snapshots__/manifest.test.js.snap, src/manifest.json, static/background.worker.js, static/backgroundCanary.js
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7233
- Removes some code to simplify the upcoming https://github.com/pixiebrix/pixiebrix-extension/issues/7555
This logic was created to support `web-ext run`'s loading mechanism, which involves toggling the extension on and off. When that happens, Chrome preserve's the last `setIcon` value, so this file was needed.
Full extension reloads and browser closing/reopening already work well without this (i.e. the icon starts `inactive` as defined in the manifest, and then it's activated)
This upcoming PR will eventually render `web-ext run`'s auto-reloading unnecessary:
- https://github.com/pixiebrix/pixiebrix-extension/pull/7598
=> #7233: Avoid flash of gray icon on MV3 worker restart

src/sidebar/Header.tsx
- Centers the sidebar logo in MV3 builds
Before
---
After 
---
=> centers the sidebar logo in MV3 builds

package-lock.json, package.json, src/background/removeExtensionForEveryTab.ts, src/contentScript/messenger/api.ts, src/pageEditor/PanelContent.tsx, src/pageEditor/hooks/useAddElement.ts, src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx, src/pageEditor/panes/insert/useAutoInsert.ts, src/pageEditor/protocol.ts, src/pageEditor/toolbar/ReloadToolbar.tsx, src/pageEditor/utils.ts
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/6648
- Includes  https://github.com/pixiebrix/webext-messenger/pull/209
Pretty straightforward change both in the Messenger and here. It comes "free" from the browser because "message all frames" is actually the default behavior of `tabs.sendMessage`
Test URL: https://ephiframe.vercel.app/Outer?iframe=https://extra-ephiframe.vercel.app/Cross-domain-iframe%3Fiframe%3D./nested
Supports:
- Added after permission change
- Removed after permission change
- Updated after mod change
- Removed after mod removal
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/510317ff-b4bc-4cac-8151-3f8a40268965
=> #6648: Update iframes from page editor without full page reload

src/sidebar/Header.tsx, src/sidebar/__snapshots__/Header.test.tsx.snap, src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7617
It's hard to see, but the classes that were altered changed the vertical alignment, not the expected one.
=> #7617: Fix sidebar header aligment

src/background/deploymentUpdater.test.ts, src/background/deploymentUpdater.ts, src/background/installer.test.ts, src/background/installer.ts, src/store/enterprise/managedStorageTypes.ts, static/managedStorageSchema.json
- Closes #7619
- Adds a `disableLoginTab` option to managed storage that prevents the extension from opening a login tab on install and heartbeat
- Login page will still show if the user hits a URL the organization has restricted
- See Jest tests
=> #7619: add disableLoginTab option to disable automatically opening login tab

src/background/background.ts, src/background/deploymentUpdater.test.ts, src/background/deploymentUpdater.ts, src/background/installer.ts, src/store/enterprise/managedStorage.test.ts, src/store/enterprise/managedStorage.ts, src/store/enterprise/useManagedStorageState.ts, src/utils/promiseUtils.ts
- Closes #7618 
- Bumps initialization delay to 4.5s, which is what Privacy Badger uses for Chrome
- Adds an interval to watch for delayed managed policy initialization
- Modifies `handleInstall` to call `openInstallPage` immediately if the installation appears to be an end-user installation
- Fixes a bug where extension console + login page would be opened if managedOrganizationId was set in policy, but ssoUrl was not set in policy
- This PR causes some tests that are using real timers with managed storage to time out. We need to shift those tests over to using fake timers in future DevEx work
- It would be nice to re-write uses of managed storage (e.g., restricted URLs) to recover from delayed policy initialization. But it's much simpler to assume the policy at profile startup is the …
=> #7618: increase managed storage delay and link extension immediately for CWS installs

jest.config.js, src/__mocks__/webext-messenger.js, src/bricks/transformers/ephemeralForm/formTransformer.test.ts, src/bricks/transformers/ephemeralForm/formTransformer.ts, src/contentScript/ephemeralFormProtocol.ts
- Closes #7631 
- Fixes bug where createFrameSource for form running in iframe was passing the top-level frame as the opener
- Modifies the Show Form brick to throw a `BusinessError` if `location: sidebar` and brick is running in a frame
- @fregante are there any other places we need to watch out for? It looks like Display Temporary information is working OK
- https://www.loom.com/share/13a223ac82ef42d7a54104836a54216e
- This will be a good candidate for Playwright in the future
=> #7631: fix iframed modal form regression

src/components/form/FieldTemplate.module.scss
- Fixes #7640
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7464
Before my last PR, it looked like this (sizing varied based on the viewport, even if the modal size was unchanged)
<table>
<tr>
<td valign=top><img width="525" alt="Screenshot 18" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/aad6ff4c-69ee-45be-b6ae-e58fcab4fe39">
<td valign=top><img width="525" alt="Screenshot 17" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/b149ff6f-9a13-4a88-acab-f07dd43beaa0">
<td valign=top><img width="525" alt="Screenshot 19" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/94a4f82f-1535-4317-b70a-e9e1e14fdaf1">
</table>
Now it looks exclusively like this. We could widen the modal itself too, but it seems to be …
=> #7640: Reduce form label size

src/background/backgroundDomWatcher.ts, src/background/messenger/strict/api.ts, src/background/messenger/strict/registration.ts, src/background/restrictUnauthenticatedUrlAccess.test.ts, src/background/restrictUnauthenticatedUrlAccess.ts, src/components/documentBuilder/edit/DocumentOptions.test.tsx, src/components/documentBuilder/edit/DocumentOptions.tsx, src/contentScript/messenger/strict/api.ts, src/contentScript/messenger/strict/registration.ts, src/extensionConsole/App.tsx, src/layout/Footer.tsx
- Automatically bumps the copyright year in the footer
=> Bump copyright year in footer

src/background/initTheme.ts
Organization icon/logo take precedence. (Conceptually, partner branding just changes the base theme)
- Fixes #7641
=> #7641: Organization toolbarIcon takes precedence over partner id theme

src/bricks/effects/forms.ts, src/tsconfig.strictNullChecks.json, src/utils/domFieldUtils.test.ts, src/utils/domFieldUtils.ts
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7630
The actual bug fix can be seen in [`e436878` (#7644)](https://github.com/pixiebrix/pixiebrix-extension/pull/7644/commits/e4368786b87da58567bc0b1d904c4899f82784c6). The rest of the changes are to extract the utility functions and test some
Tested on https://draftjs.org
Some fields are available on https://ghosttext.fregante.com/test/ (but not DraftJS at this point)
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/2cc02864-8e78-46c0-acfd-9e9929ea8f86
=> #7630: Fix DraftJS support on empty fields

src/background/background.ts, src/background/backgroundPlatform.ts, src/contrib/google/sheets/core/sheetsApi.test.ts
- Closes #7693 
- Adds/sets a platform for the background page/worker to fix bug where Google Sheets (and AA calls) were erroring
=> #7693: add background platform for http requests to fix Google API calls

src/components/quickBar/QuickBarApp.tsx
- Fixes #7695
Pretty straightforward bug and fix
=> #7695: QuickBar: Avoid dark scrollbar on dark websites

.eslintrc.js, src/background/auth/codeGrantFlow.ts, src/bricks/effects/clipboard.ts, src/components/Alert.tsx, src/contentScript/contentScriptPlatform.ts, src/contentScript/pageEditor.ts, src/contentScript/pageEditor/elementPicker.ts, src/contrib/automationanywhere/aaUtils.ts, src/pageEditor/panes/save/saveHelpers.ts, src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx, src/platform/state/stateController.ts, src/runtime/runtimeUtils.ts, src/starterBricks/contextMenu.ts, src/starterBricks/factory.ts, src/starterBricks/panelExtension.ts, src/starterBricks/quickBarExtension.tsx, src/starterBricks/triggerExtension.ts, src/testUtils/factories/sidebarEntryFactories.ts
- Enforces rule (previously set to warn)
- No longer need to eslint disable when passing type `never` to a template literal
- This change does require us to make an exhaustive check intermediary variable, so whether this is something we desire is up for debate.
- I prefer this style because it is more explicit and because I would rather rely on ts throwing an error than on the linter flagging an unnecessarily disabled rule.
=> Improve @typescript-eslint/restrict-template-expressions

src/contentScript/selectionTooltip/SelectionToolbar.scss, src/contentScript/selectionTooltip/tooltipController.tsx, src/types/inputTypes.ts, src/utils/textAreaUtils.ts
- Part of #7707 
- UI Improvements
- Fix placement bug due to textarea scroll position
- Set popover z-index (actually implementing popover API will be more work to get positioning correct)
- Add flip/shift floating ui middleware to ensure visible on top line of editor iframe
- Hides the popover on scroll (document and/or active element) to avoid the popover moving with the scroll
- Add CSS to popover to make style consistent across sites
- Refactoring
- Use RepeatableAbortController for floating-ui autoUpdate cleanup
- When multiple iframes are on the page with selections, each selection will have a popover in its frame. We might consider using messenger to ensure only latest selection has a popover shown even before implementing top-frame popover approach mentioned in #7707 
- See the …
=> #7707: text selection popover placement fixes/UI improvements

src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNodeContent.module.scss
- Fixes #7736 
- See changes to BrickIcon here: https://github.com/pixiebrix/pixiebrix-extension/pull/7637/files#diff-827ad6c6bf920a269198235a7043dc546042a417e68494e76278694744df9a50
- FontAwesomeIcons need to be 2x, but img tags for external logos need to be sized down. 
Before 
---
After
---
- _Work for the issue/ticket that will be in a follow-up PR_
=> override font-size for img BrickIcons

src/components/floatingActions/FloatingActions.tsx, src/components/floatingActions/QuickbarButton.tsx, src/components/floatingActions/store.ts, src/integrations/store/integrationsSlice.test.ts, src/pageEditor/slices/editorSlice.test.ts, src/store/settings/settingsSlice.test.ts, src/store/settings/settingsStorage.ts, src/tsconfig.strictNullChecks.json
- Fixes https://pixiebrix.slack.com/archives/C0436P48QHY/p1709050927627719
- Main fix was adding the PersistGate to FloatingActionsContainer
- Noticed we had the wrong migrations version for one of the persistor configs. Added tests to keep them in sync with the latest migration versions
https://www.loom.com/share/56c0eea9677d4cc8b3707bfb5cfbb4e4
=> persists hiding of FAB when user manually hides it

src/starterBricks/triggerExtension.ts
- Use debug instead of trace to avoid cluttering console
- The trace call is expanded by default in the Chrome Dev Tools
=> Use `console.debug` instead of `console.trace` in trigger cancelObserver method

src/contentScript/contentScriptCore.ts
- Throws an error in the content script if you try to make an API call with `axios`
- The content script is subject to the CSP of the host site
- The current approach ends up importing axios into the content script. (Whereas before it might only transitively be imported, but is probably already being imported at somepoint). Axios is ~19kb so not a major deal: https://bundlephobia.com/package/axios@0.27.2 
Added this code to the contentScriptCore to test:
```
try {
await axios.create().get("https://httpstat.us/200");
} catch (error) {
console.warn(error);
}
```
=> Throw an error on axios call from content script

.github/workflows/dependabot-auto-merge.yml, .github/workflows/pr.yml
This keeps happening and it seems that it's wasting the team's time to fix it.
> From https://github.com/pixiebrix/pixiebrix-extension/pull/7734
This should raise concerns:
This is a normal PR/fixed:
=> Warn of wrong lockfile changes in PR

.github/workflows/pr.yml, src/background/messenger/strict/registration.ts
Instead of having to ask around, I figured I'd encode these instructions into the CI. Similar to:
- https://github.com/pixiebrix/pixiebrix-extension/pull/7746/files
See the hidden message below for an example. It's hidden automatically when the issue is resolved.
=> Add CI instructions when strictNullChecks fails due to Messenger

src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.module.scss
- Fixes https://pixiebrix.slack.com/archives/C0436P48QHY/p1709067617250069
=> Avoid shrinking drawn pipeline with long output names

src/__snapshots__/Storyshots.test.js.snap, src/components/formBuilder/FieldTemplate.tsx, src/components/formBuilder/preview/__snapshots__/FormPreview.test.tsx.snap
- Fixes https://pixiebrix.slack.com/archives/C023KL47XV4/p1708983799071599
This matches the spacing we have in the page editor:
=> Add spacing below form builder fields

.eslintrc.js, .pre-commit-config.yaml, eslint-local-rules/noRestrictedSyntax.ts, package-lock.json, package.json, src/bricks/readers/jquery.ts, src/components/EmotionShadowRoot.ts, src/components/StopPropagation.test.tsx, src/components/quickBar/QuickBarResults.tsx, src/contentScript/selectionTooltip/ActionRegistry.test.ts, src/extensionConsole/pages/onboarding/SetupPage.test.tsx, src/globals.d.ts, src/types/reactDragAndDropNext.d.ts, src/utils/inference/selectorInference.ts, src/utils/nullishUtils.ts, src/utils/stringUtils.ts
- Follows https://github.com/pixiebrix/eslint-config-pixiebrix/pull/228
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/7703
=> Update local ESLint config to match shared config + apply new rules

src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
- Fixes #7735
- Tried adding the file to `tsconfig.strictNullChecks.json`, but that threw 500+ errors (not surprising since it imports from editorSelectors)
=> #7735: adds very basic null checks to prevent NPE

src/background/deploymentUpdater.test.ts, src/background/starterMods.test.ts, src/extensionConsole/pages/settings/ExperimentalSettings.tsx, src/starterBricks/contextMenu.ts
- Adds a feature flag `text-selection-popover-force` to remotely enable text selection popover
- We're going to be piloting the feature with some enterprise clients and don't want to require their users to enable manually via the experimental settings 
- Flag is here: https://app.pixiebrix.com/admin/waffle/flag/175/change/
=> Add feature flag to remotely enable text selection popover

src/starterBricks/menuItemExtension.ts, src/types/runtimeTypes.ts
- Drops support for experimental "dependencies" feature for menu item that enabled re-rendering of menu items when another element on the page changed
- I verified the feature wasn't in use by searching for occurrences of the dependencies property in packages: `$..*[?(@=="dependencies")]`
- We might be able to drop the `if:` functionality too. That one might still be used in some customer deployments though, and is a bit harder to search for
=> Drop experimental menu item dependencies feature

src/hooks/useAsyncState.test.ts, src/hooks/useIsMounted.ts
- Memoizes the return function from `useIsMounted()`, which in turn allows the async state `refetch` function to memoize properly
=> Fix bug in `useAsyncState` -- memoize the `refetch` function properly

src/components/ConfirmationModal.tsx, src/extensionConsole/pages/brickEditor/EditPage.tsx, src/extensionConsole/pages/brickEditor/useSubmitBrick.test.tsx, src/extensionConsole/pages/brickEditor/useSubmitBrick.ts
- Closes #7775
- Adds confirmation modal when deleting a brick in the workshop
- Move the "Delete" button behind a 3-dot menu to prevent accidental clicks
- Add a text entry box, to have the user type the id of the brick to confirm deletion
- Update language in Workshop UI to "package" instead of "brick" to be less confusing when working with mods and integration definitions
=> #7775: confirm delete in the workshop

src/background/deploymentUpdater.test.ts, src/background/deploymentUpdater.ts, src/extensionConsole/pages/deployments/DeploymentsContext.tsx, src/modDefinitions/modDefinitionPermissionsHelpers.ts, src/permissions/deploymentPermissionsHelpers.ts
- Closes #7772
- By default, make `clipboardWrite` optional for deployment activation.
- Add a `deployment-permissions-strict` flag to make `clipboardWrite` required in case this breaks certain deployments
- I chose to make the flag make the requirement strict vs. relaxed, because feature flags are easier to opt people into vs. out of in Django/Waffle
- Improve the deploymentUpdater tests to move the mock boundary to `browser.` APIs vs. mocking PixieBrix methods
=> #7772: feature flag to make `clipboardWrite` optional in automatic deployment activation

src/contentScript/selectionTooltip/tooltipController.tsx
- Tries swaps the border for a box-shadow -- based on feedback from @MMirandi 
- Trying the same box shadow as Notion's text toolbar. It's very faint (see demo), or I might not be using it correctly (maybe missing a border somewhere?)
- I prefer having the border because it provides contract across more color background situations
- I'm not particularly knowledgeable about how to create good box shadows on my own, so will need to pull someone else in if we're trying to play around with it
Before:
After:
=> Box shadow for text selection popover

src/__mocks__/browserMock.mjs, src/auth/useLinkState.ts, src/auth/usePartnerAuthData.ts, src/auth/useRequiredPartnerAuth.ts, src/background/background.ts, src/background/deploymentUpdater.test.ts, src/background/installer.test.ts, src/background/installer.ts, src/background/restrictUnauthenticatedUrlAccess.test.ts, src/background/telemetry.ts, src/components/logViewer/LogTable.stories.tsx, src/extensionConsole/Navbar.tsx, src/extensionConsole/pages/BrowserBanner.test.tsx, src/extensionConsole/pages/onboarding/SetupPage.test.tsx, src/mv3/SessionStorage.test.ts, src/mv3/SessionStorage.ts, src/store/enterprise/managedStorage.test.ts, src/store/enterprise/managedStorage.ts, src/store/enterprise/useManagedStorageState.test.ts, src/store/enterprise/useManagedStorageState.ts, src/testUtils/testAfterEnv.ts, src/testUtils/testEnv.js, src/themes/themeStore.test.ts, src/utils/promiseUtils.test.ts, src/utils/promiseUtils.ts
- Closes #7784 
- Adds a timestamp to local storage to enable contexts to skip waiting for managed storage after the initial delay
- Fixes use of onStartup handler in favor of a method that runs once per browser session
```
/Users/tschiller/projects/pixiebrix-extension/node_modules/webext-storage/distribution/storage-item.js:39
chrome.storage.onChanged.addListener(changeHandler);
^
TypeError: Cannot read properties of undefined (reading 'onChanged')
```
- Review `managedStorage.ts`
- Review `installer.ts`
- Figure out how to use jest fake timers during tests to avoid incurring the delay
- Submit PR to split storages in the jest-webextension-mock project: https://github.com/clarkbw/jest-webextension-mock/issues/183
- After switch to MV3, can just store the flag/timestamp in session storage …
=> #7784: skip waiting for managed storage after initial wait

src/auth/RequireScope.tsx, src/extensionConsole/Navbar.tsx, src/store/settings/settingsSlice.ts, src/store/settings/settingsTypes.ts
- Drops unused `mode` code, given that only `remote` had been a valid value for a long time
- Drops the property without a migration on settingsSlice because it doesn't hurt to have the value from other versions floating around
=> Drop unused `mode` code

src/components/integrations/IntegrationConfigEditorModal.tsx, src/extensionConsole/Sidebar.tsx, src/extensionConsole/pages/integrations/IntegrationsPage.tsx
- Use consistent "Local Integration"s terminology in the Extension Console to help avoid confusion with Team Integrations in the Admin Console
- Match terminology in documentation: https://docs.pixiebrix.com/integrations/configuring-integrations
=> Use "Local Integration" terminology in Extension Console

src/vendors/theme/assets/styles/_variables.scss, src/vendors/theme/assets/styles/components/_forms.scss
- Fixes #7788
-  Relates to #7764 
- Override the border color of _only_ form controls.
- Might find that there are other places we also need to update the border color for, but this covers the initial ask for $7764
Inputs still fixed:
Workshop Table fixed:
Mods Page hr:
Password:
=> #7788: preserve input border color without changing non-inputs

.eslintrc.js, src/extensionConsole/pages/brickEditor/SharingTable.tsx, src/extensionConsole/pages/settings/FactoryResetSettings.tsx, src/extensionConsole/pages/settings/SettingToggle.tsx, src/pageEditor/fields/SelectorMatchField.tsx, src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap, src/pageEditor/panes/insert/InsertMenuItemPane.tsx, src/pageEditor/panes/insert/InsertPanelPane.tsx, src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap, src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
- Part of https://github.com/pixiebrix/eslint-config-pixiebrix/issues/194
- Only violations for `no-unstable-nested-components` were for renderProp components for 3rd party libraries
- Also implemented `forbid-elements` to use `<strong>` and `<em>` instead of `<b>` and `<em>`
- See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b
- Migrate rules to `eslint-config-pixiebrix`
=> EsLint: add no-unstable-nested-components and forbid-elements

.eslintrc.js, src/auth/RequireAuth.test.tsx, src/background/auth/getToken.test.ts, src/background/deploymentUpdater.test.ts, src/bricks/available.test.ts, src/bricks/effects/InsertAtCursorEffect.test.ts, src/components/fields/schemaFields/SchemaField.test.tsx, src/components/fields/schemaFields/widgets/CodeEditorWidget.test.tsx, src/components/fields/schemaFields/widgets/PasswordWidget.module.scss, src/components/integrations/AuthWidget.test.tsx, src/contrib/google/sheets/core/sheetsApi.test.ts, src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx, src/extensionConsole/pages/activateMod/IntegrationsBody.test.tsx, src/extensionConsole/pages/deployments/DeploymentModal.test.tsx, src/pageEditor/sidebar/ActivatedModComponentListItem.test.tsx, src/pageEditor/sidebar/ModListItem.test.tsx, src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx, src/sidebar/activateMod/ActivateModPanel.test.tsx, src/themes/colors.scss, src/utils/deploymentUtils.test.ts, src/utils/inference/inferSingleElementSelector.test.ts, src/utils/promiseUtils.test.ts
- Part of https://github.com/pixiebrix/eslint-config-pixiebrix/issues/194
- See the case for the rule here: https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/prefer-expect-resolves.md
- ~Only manual change was adding the rule~
- Had to change `src/components/fields/schemaFields/SchemaField.test.tsx` to support `.renders`.
- See: https://github.com/pixiebrix/pixiebrix-extension/pull/7816#issuecomment-1979226360
- All other changes was from running lint with the `--fix` flag
- Migrate rule to eslint-config-pixiebrix next time we merge over rules
=> implement jest/prefer-expect-resolves

src/registry/packageRegistry.test.ts, src/registry/packageRegistry.ts
- Closes #7822 
- Awaits the initial remote registry population attempt
- Does not await any pending/in-flight `syncPackages` call. I think we'd have to be careful there about delaying requests that are OK with seeing slightly stale data.
- The `count` method does not await the registry being populated
=> #7822: await initial remote registry sync on packageRegistry read operations

src/extensionConsole/options.tsx, src/pageEditor/pageEditor.tsx, src/sidebar/sidebar.tsx, src/telemetry/dnt.ts, src/telemetry/performance.test.ts, src/telemetry/performance.ts, src/tsconfig.strictNullChecks.json
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/4858
- This change set ensures that we initialize datadog (taking only about 10-15 ms) before we continue in initializing the rest of the UI. This makes it so that the initial requests (ex the `/me` requests) are measured and traced by datadog.
Note the datadog headers on the first request.
Check that the tracing is being picked up by the backend app.
=> 4858 connect datadog rum and traces

.eslintrc.js
Turns on warn for the `require-description` lint rule to start enforcing comments when we intentionally ignore a lint rule. Currently we have 133 instances of lint rules ignored without a comment.
=> enforce comments when we ignore lint rules

src/bricks/effects/InsertAtCursorEffect.ts, src/contentScript/contentScriptCore.ts, src/contentScript/sidebarController.tsx, src/contentScript/sidebarDomControllerLite.ts, src/contentScript/textEditorDom.ts, src/utils/focusController.ts
- Closes #7774
- Saves focused element when mouses into the MV2 sidebar, so we can use the element from actions the user clicks on in the sidebar
- Fix insertion position on DraftJS
=> #7774: save host page element focus when clicking into MV2 sidebar

.eslintrc.js, src/components/fields/schemaFields/BasicSchemaField.test.tsx, src/components/fields/schemaFields/ChildObjectField.test.tsx, src/components/fields/schemaFields/SchemaField.test.tsx, src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx, src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/ui/TabField.test.tsx, src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx, src/pageEditor/panes/EditorPane.test.tsx, src/utils/inference/selectorInference.test.ts
~~- This removes the need for ignoring this specific rule (expect-expect) in a few places.~~
- Adding comments for all overrides of the expect-expect rule
=> ESLint: fix missing comments for expect-expect eslint rule

.idea/.gitignore, src/types/contract.ts, src/types/modDefinitionTypes.ts, src/validators/schemaValidator.test.ts, src/validators/schemaValidator.ts
- Fixes #7837
- Adds support for updated_at and sharing props on the definition body getting validated
=> #7836: fix package definition validation due to updated_at and sharing metadata

src/contentScript/sidebarController.tsx
- Fixes #7835 
- Saves focus via focusController automatically when the sidebar is shown to handle case where user `mouseenter`s the sidebar before the React App fires the ready event
- https://www.loom.com/share/eb5c700c97644eb9bde31bbc2a312560
- Zendesk/CKEditor is still impacted by: https://github.com/pixiebrix/pixiebrix-extension/issues/7779
- 😞: Add tests: will require E2E test due to reliance on focus/editors
=> #7835: save focus on sidebar load

src/__mocks__/@/telemetry/telemetryHelpers.ts, src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx, src/extensionConsole/pages/deployments/DeploymentsContext.tsx, src/extensionConsole/pages/deployments/useAutoDeploy.ts, src/hooks/useBrowserIdentifier.ts, src/hooks/useFlags.ts, src/telemetry/telemetryHelpers.ts, src/tsconfig.strictNullChecks.json
- Closes #7844 
- Main functional change is to refactor DeploymentContext to use useDeriveAsyncState
- Exposes async state from useFlags hook 
- Extracts out useBrowserIdentifier hook
- Have a version of useFlags that uses AsyncState (not a good fit since it returns functions though)
- Have a FlagsContext in the tree?
- It's because I'm an admin
- https://www.loom.com/share/e75f586bbf0e4375b87f80a043beb52a
=> #7844: fix NPE in deployments async state

contrib/readers/empty-jquery-reader.yaml, schemas/reader.json, src/validators/schemaValidator.test.ts
- Fixes #7840
- Allows legacy JQuery reader definitions saved with the Page Editor that don't contain any selectors
- JQuery reader will just return empty object in these cases
- App PR is here: https://github.com/pixiebrix/pixiebrix-app/pull/4894
=> #7840: Allow legacy JQuery reader definitions with no selectors

src/bricks/effects/AddTextCommand.test.ts, src/bricks/effects/AddTextCommand.ts, src/bricks/effects/AddTextSnippets.test.ts, src/bricks/effects/AddTextSnippets.ts
- Also strip leading backslash (`\`) in command definition because we've switched to `\` as the default, but anticipate allowing the user to choose in the future
- As a reminder, to use the bricks, enable Text Command Popover in Settings > Skunkworks
=> Automatically strip leading backslash in text snippet/command definition

src/components/DatabaseUnresponsiveBanner.tsx, src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.ts, src/hooks/usePrevious.ts, src/hooks/usePreviousValue.ts, src/hooks/useReportError.ts, src/pageEditor/tabs/editTab/useReportTraceError.test.tsx, src/pageEditor/tabs/editTab/useReportTraceError.ts, src/tsconfig.strictNullChecks.json
In a couple of places we employ a useEffect where we could
instead simplify the logic by checking the previous value. This PR
simplifies a couple of these usages through the use of the shared
`usePrevious` util hook.
For motivation see: 
https://react.dev/learn/you-might-not-need-an-effect
- Does the original intended behavior still line up with this refactor?
- Consider more places where we can remove the need for useEffects
=> Refactoring useEffects to usePreviousValue

end-to-end-tests/example.spec.ts, end-to-end-tests/fixtures.ts, playwright.config.ts
- Part of #7690
This change now allows us to write a test that loads up the extension console that is linked.
=> #7690: load extension console after linking extension

src/extensionPages/extensionPagePlatform.ts, src/tinyPages/ephemeralPanel.tsx
- Fixes #7885 
- Set platform to `ExtensionPagePlatform` on ephemeral panel
=> #7885: fix panels in modals/popovers

src/utils/openAllLinksInPopups.ts
=> #7809: Fix Edge sidePanel links crash bug

end-to-end-tests/auth.setup.ts, end-to-end-tests/pageObjects/constants.ts, end-to-end-tests/pageObjects/modsPage.ts, end-to-end-tests/tests/modsPageSmoke.spec.ts, src/tsconfig.strictNullChecks.json
- Part of #7690
This change introduces pageObjects to group our locator / navigation logic following best practices:
https://playwright.dev/docs/pom
This change also improve the original smoke test for the options mod page.
=> introducing pageObjects and improving first smoke test

end-to-end-tests/tests/modsPageSmoke.spec.ts, end-to-end-tests/utils.ts, package-lock.json, package.json
Introduces using axe-core in our playwright system tests to analyze our pages for accessibility violations.
This first set of changes only analyzes the mods page in the extension console, and I wrote some
utility code to specifically list out the current critical a11y issues.
Related issue: https://github.com/pixiebrix/pixiebrix-extension/issues/7900
How do we want to prioritize fixing these a11y issues?
Fixing the critical issues, one at a time.
=> #7900: introducing axe-core to track a11y issues

end-to-end-tests/fixtures/extensionBase.ts, end-to-end-tests/pageObjects/modsPage.ts
Fixes flakiness where sometimes the expected header is not attached to the dom (but still present).
See: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8267597585/job/22618402796
=> #7690: reduce flakiness of page fixture

package-lock.json, package.json, src/bricks/effects/InsertAtCursorEffect.test.ts, src/bricks/effects/InsertAtCursorEffect.ts, src/bricks/effects/attachAutocomplete.ts, src/contentScript/commandPopover/commandUtils.ts, src/contentScript/textEditorDom.ts, src/contrib/ckeditor/ckeditorDom.ts, src/utils/domFieldUtils.ts, src/utils/focusController.ts
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/7813#issuecomment-1983367821
The root-aware part was mentioned in https://github.com/pixiebrix/pixiebrix-extension/issues/7813#issuecomment-1983367821
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/21d46e84-f199-44ec-aff7-ed1a6dc66486
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/576deac5-94fc-4f29-be4a-9e3725c2953c
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/977be720-b198-455c-bc68-6e954c732503
- ❌  Add tests: can't test execCommand in JSDom
=> #7813: Remove `rootAware` support from insert-text brick and improve focus logic

src/contentScript/commandPopover/CommandPopover.tsx, src/contentScript/commandPopover/commandUtils.test.ts, src/contentScript/commandPopover/commandUtils.ts, src/tsconfig.strictNullChecks.json
- Fixes #7823 
- Fixes missing return statement in branch for native inputs
=> #7823: fix missing return in replaceAtCommand

end-to-end-tests/fixtures/extensionBase.ts, playwright.config.ts
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/7691
- After manually linking the extension, the extensionBase fixture will wait for the Extension Console to be available (essentially ensure that the Extension console is done reloading) before proceeding with the test
- Also increases the test assertion timeout to 10s, because I was seeing flakiness with the Extension Console taking longer than 5s to load in some cases
=> #7691: Address e2e test flakiness due to Extension reload and Extension Console loading times

src/bricks/effects/AddTextCommand.test.ts, src/bricks/effects/AddTextCommand.ts, src/bricks/effects/AddTextSnippets.test.ts, src/bricks/effects/AddTextSnippets.ts, src/contentScript/commandPopover/CommandPopover.scss, src/contentScript/commandPopover/CommandPopover.tsx, src/contentScript/commandPopover/commandUtils.test.ts, src/contentScript/commandPopover/commandUtils.ts, src/pageEditor/exampleBrickConfigs.ts, src/platform/platformTypes/commandPopoverProtocol.ts, src/utils/expressionUtils.ts
- Closes #7857 
- Adds preview to text command popover
- QoL: Adds example brick configuration for add text command brick
- https://www.loom.com/share/a2ad66e551f9476b84a0fdd076e5317f?sid=bbd811ce-f51d-4d8b-8fa8-4dfd5f34f52a
- CSS/styling: will do holistically for popover in a PR for: https://github.com/pixiebrix/pixiebrix-extension/issues/7856
=> #7857: add preview to text command popover

end-to-end-tests/fixtures/extensionBase.ts, end-to-end-tests/pageObjects/modsPage.ts, end-to-end-tests/tests/extensionConsoleActivation.spec.ts, end-to-end-tests/tests/modsPageSmoke.spec.ts
A quick refactor of the activate mod e2e test that extracts the activate mod page logic into a re-usable page object
model.
=> refactor activate mod logic into page object

src/contentScript/commandPopover/CommandPopover.scss, src/contentScript/commandPopover/CommandPopover.tsx
- Closes #7858 
- CSS/styling: will do holistically for popover in a PR for: https://github.com/pixiebrix/pixiebrix-extension/issues/7856. Just trying to get the main affordances in first
=> #7858: add text command popover navigation footer

src/contentScript/commandPopover/CommandPopover.scss, src/contentScript/commandPopover/CommandPopover.test.tsx, src/contentScript/commandPopover/CommandPopover.tsx, src/themes/colors.scss, src/tsconfig.strictNullChecks.json
- Closes: #7855
- @BrandonPxBx is a red a little harsh for a no results state vs. an error?
- @BrandonPxBx see the icon - our FA5 pack only has the solid/filled version. Seems OK?
- CSS/styling: will adjust font family size  in a PR for: https://github.com/pixiebrix/pixiebrix-extension/issues/7856 to work out the consistent styles. Just trying to get the main affordances in first
=> #7855: add no matches state for text command popover

.github/workflows/ci.yml, end-to-end-tests/fixtures/extensionBase.ts, playwright.config.ts
- Part of #7839
This change adds a custom project parameter, chromium channel which is used msedge
=> add msedge playwright project

src/__mocks__/@/background/messenger/api.ts, src/background/auth/authStorage.ts, src/background/messenger/api.ts, src/background/messenger/registration.ts, src/background/messenger/strict/api.ts, src/background/messenger/strict/registration.ts, src/contrib/google/sheets/bricks/append.test.ts, src/contrib/google/sheets/bricks/append.ts, src/contrib/google/sheets/bricks/lookup.test.ts, src/contrib/google/sheets/bricks/lookup.ts, src/contrib/google/sheets/core/sheetsApi.ts, src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx, src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx, src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx, src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx, src/contrib/google/sheets/ui/RequireGoogleSheet.tsx, src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx, src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx, src/extensionPages/extensionPagePlatform.ts, src/integrations/autoConfigure.ts, src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx, src/tsconfig.strictNullChecks.json
- Pre-req for https://github.com/pixiebrix/pixiebrix-extension/pull/7958 - without this PR the API calls are made via the background platform, not the content script platform
- Implements `request` in the ExtensionPagePlatform for Google Sheets calls made from the sidebar/page editor
- Removes the Google Sheets methods from the background API. We had previously use gapi in the background, but now that we're making normal API calls, there's no reason make the whole function call via background worker vs. just the API call
- Refactor the isLoggedIn check to `hasCachedAuthData` to the more generic check given that it works for any token-based authentication. (The name is also more accurate, given that the token may be expired)
- Review `ExtensionPagePlatform`
- The rest of the changes are …
=> #7956: only route google sheets API calls through the background worker (1/3)

src/components/InvalidatedContextGate.tsx, src/hooks/useDocumentVisibility.test.ts, src/hooks/useDocumentVisibility.ts, src/pageEditor/Panel.tsx, src/tsconfig.strictNullChecks.json
Minor UX/DX: reload page editor on invalidation.
Currently this only happens when the document is hidden, just to limit the PR blast radius. If there are no issues with this behavior we can consider just reloading it.
https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/2e99814a-398e-48be-9c25-d6ee1ddad4f2
=> Automatically reload inactive page editors on invalidation

src/runtime/pipelineTests/validateInput.test.ts, src/validators/schemaValidator.test.ts, src/validators/schemaValidator.ts
- Closes #7963 
- There's a quirk I had overlooked with integrations where:
- When generating UI, we want the properties
- When validating brick inputs, we want an integration configuration 
- Implemented as a "mode" option instead of as a separate resolver
- I don't think this is related to https://github.com/pixiebrix/pixiebrix-extension/issues/7895 given the dereference behavior was already correct, but including @BLoe as reviewer for visibility/FYI
=> #7963: fix brick input validation for integrations with required properties

src/contentScript/commandPopover/commandController.tsx, src/contentScript/selectionTooltip/tooltipController.tsx, src/tsconfig.strictNullChecks.json, src/utils/a11yUtils.ts
- Adds a subtle fade-in animation for the text and command popover
- We should probably disable this animation if the user has `prefers-reduced-motion` enabled
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
https://www.loom.com/share/db31e1d3e55046b1b260be2a8813586b
- [NA] Add tests and/or storybook stories
=> animate fade-in for the command and selection menus

src/contentScript/commandPopover/CommandPopover.tsx
- See discussion: https://pixiebrix.slack.com/archives/C06G212E3U1/p1710876417599169?thread_ts=1710874748.453389&cid=C06G212E3U1
- Changes snippet shortcut menu to show "INSERT ENTER" instead of "SELECT TAB"
- Both TAB and ENTER still work for submission
=> Use insert/enter instructions for snippet shortcut menu

.eslintrc.js, .github/workflows/ci.yml, eslint-local-rules/noRestrictedSyntax.tsx, src/contentScript/commandPopover/commandController.tsx, src/contentScript/commandPopover/commandUtils.ts, src/contentScript/commandPopover/useKeyboardQuery.ts, src/contentScript/selectionTooltip/tooltipController.tsx, src/utils/domUtils.ts, src/utils/selectionController.ts, src/vendors/page-metadata-parser/url-utils.js
- Fixes #7882
It seems like the sticky popover menus were being caused by unhandled errors being thrown because we
tried calling `.getSelection` when there was no Range`s in the selection (`rangeCount === 0`)
Demo of the fixed issue:
https://www.loom.com/share/65f41d1c89d14df7907ad8dd83425794
The popovers no longer get reset to coordinates 0,0.
=> #7882: Avoid errors on `Selection#getRangeAt()`

src/contentScript/commandPopover/CommandPopover.scss
- Fixes #7990
- Eslint rule to prevent use of `rem`?
- [x ] Designate a primary reviewer @grahamlangford
=> use em instead of rem in snippet shortcut menu

src/contentScript/integrations/LoginBanners.scss, src/contentScript/integrations/LoginBanners.test.tsx, src/contentScript/integrations/LoginBanners.tsx, src/contentScript/integrations/bannerDomController.tsx, src/contentScript/integrations/deferredLoginController.test.tsx, src/contentScript/integrations/deferredLoginController.ts
- Fixes #7979 
https://www.loom.com/share/11c37f4a30c9484ba7924c80bde104f5
- The Login Banner shows on the Google Auth window when logging in. This should be addressed in a future ticket. (See Loom)
- There's a Bootstrap Alert state update happening after we call `unmountComponentAtNode`
=> #7979: allow users to dismiss the login banner and fix z-index issues

src/__snapshots__/Storyshots.test.js.snap, src/contentScript/commandPopover/CommandPopover.tsx, src/contentScript/selectionTooltip/SelectionToolbar.tsx
- Fixes #8003 
- Tried applying the styles in EmotionShadowRoot, decided to hold off in case it negatively impacts other components
- Standardize the `all: initial` logic. See: https://github.com/pixiebrix/pixiebrix-extension/issues/7670
=> #8003: prevent page styles from leaking into menus

src/components/EmotionShadowRoot.ts, src/contentScript/integrations/LoginBanners.tsx, src/contentScript/integrations/bannerDomController.tsx, src/contentScript/integrations/deferredLoginController.test.tsx, src/contentScript/integrations/deferredLoginController.ts, src/contentScript/messenger/registration.ts, src/contentScript/sidebarDomControllerLite.ts
- Fixes #8009
- Replaces and closes https://github.com/pixiebrix/pixiebrix-extension/pull/8012
https://pbx.vercel.app/style-conflicts/ after removing the unrelated `notifier` div
https://www.nespresso.com/us/en/
To create a banner, I use append this to `/bannerDomController.tsx`
```is
import {uuidv4} from "@/types/helpers";
showLoginBanner(
{
config: { label: "Heaven" },
integration: {
name: "d",
},
},
() => uuidv4(),
);
```
=> #8009: LoginBanners: Reduce chance of style conflicts

src/bricks/effects/AddTextCommand.test.ts, src/bricks/effects/AddTextCommand.ts, src/bricks/effects/AddTextSnippets.ts, src/pageEditor/exampleBrickConfigs.ts
- Updates snippet shortcut brick names
- Names:
- Add Text Snippets
- [Experimental] Add Dynamic Text Snippet
- Will key up discussion on if we want to call Dynamic Text Snippet vs. Text Command: https://pixiebrix.slack.com/archives/C02RAMRDF0R/p1711115211568019
- I'm keeping experimental on dynamic text snippet, as we may want to change the structure of the variable passed into the text generation brick
- DevEx work to clean up the names in the code
=> Update snippet shortcut brick names

src/data/model/UserPartner.ts, src/extensionConsole/Sidebar.test.tsx, src/extensionConsole/Sidebar.tsx
- Hides the community link in extension console for restricted users
- There isn't a specific flag for hiding the community, so rely on the `restricted-marketplace` flag
=> Hide community link in extension console for restricted users

src/analysis/analysisVisitors/selectorAnalysis.test.ts, src/analysis/analysisVisitors/selectorAnalysis.ts, src/analysis/analysisVisitors/templateAnalysis.ts, src/globals.d.ts, src/pageEditor/analysisManager.ts, src/utils/domUtils.test.ts, src/utils/domUtils.ts, src/utils/schemaUtils.ts, src/vendors/jQueryInitialize.js
- Closes #8030 
- Adds selector analysis warnings:
- Invalid selector: Error
- Selector with random characters: Warning
- Selector that might slow down the page: Warning
- Vendor check fails due to fixed typo. That particular file is one we've made some modifications to
- Strict null checks not possible due to dependency on the registry
- Uses the pre-existing randomness detection we had prototyped for the "Exclude Random Classes" skunkworks feature (which has never been turned on for all users)
- JQuery doesn't report what's invalid about the selector when it throws its error. Otherwise it'd be nice to explain where the syntax/invalid selector is
- Based on dogfooding, we might choose to make the randomness check an info instead of warning
- Generalize the schema recursion to be …
=> #8030: add slow/bad selector analysis warnings

end-to-end-tests/pageObjects/workshopPage.ts, end-to-end-tests/tests/modsPageSmoke.spec.ts, end-to-end-tests/tests/workshopPageSmoke.spec.ts
- Adds support for running single test from IntelliJ (fixes test detection for existing tests)
- Adds a workshop smoke test if username doesn't have alias defined
- We probably should give our test user an scope/username so we can write workshop/page editor mod save/copy tests
- Workshop smoke tests for user with an alias
- Improve ergonomics of checkForCriticalViolations. Right now there's no quick way to create a new baseline given that you get a diff of 600+ lines of the detailed report when it fails. `absentAllowedViolations` should likely also be an error to force us to keep these lists up-to-date
=> Add playwright test type detection in IntelliJ; add workshop smoke test

src/data/service/errorService.test.ts, src/data/service/errorService.ts
- Closes #7174 
- Adds `manifestVersion` and `runtimeId` to shared utility method for extracting context for errors sent to DataDog and our in-house error telemetry
=> #7174 add manifest version and runtime id to error telemetry

end-to-end-tests/tests/workshopPageSmoke.spec.ts
- Part of https://github.com/pixiebrix/pixiebrix-extension/issues/8057
- We need to add a scope to our test user in order to write e2e tests for standalone mod components (needed for issue referenced above)
- This test will fail in CI if we modify the test user as-is, so let's temporarily modify it in order to update the test user scope
=> Temporarily modify workshop smoke test to prep for adding scope to test user account

.eslintrc.js, end-to-end-tests/tests/workshopPageSmoke.spec.ts
- Adds a lint rule for checking that toPass includes a timeout value to avoid tests taking forever to time out.
=> lint rule for playwright expect.toPass matcher

src/contentScript/shortcutSnippetMenu/ShortcutSnippetMenu.scss, src/contentScript/shortcutSnippetMenu/shortcutSnippetMenuController.tsx
- Fixes #8084
Adds a little bonus - onhover will now highlight the snippet item to make it more clear you can click on it.
https://github.com/pixiebrix/pixiebrix-extension/assets/3498063/61e70a49-f383-4b0d-a4e1-6c89b81a5490
=> #8084 fix not being able to click on command snippets

src/bricks/renderers/documentView/DocumentViewLazy.tsx, src/bricks/transformers/controlFlow/WithAsyncModVariable.ts, src/contentScript/sidebarController.tsx, src/contentScript/sidebarDomControllerLite.ts, src/pageEditor/PanelContent.tsx, src/pageEditor/protocol.ts, src/starterBricks/tourController.ts, src/types/helpers.ts
- Removes some outdated comments I should have removed in https://github.com/pixiebrix/pixiebrix-extension/pull/7340
- Removes some old logging related to the sidebar, related to https://github.com/pixiebrix/pixiebrix-extension/pull/7354
- Fixes a couple of `prefer-await-to-then`-related eslint comments
=> Drop some comments and logging

src/contentScript/textSelectionMenu/selectionMenuController.tsx
- Fixes #8075
- https://www.loom.com/share/e1a27b1e822d4d22a95c52390a53491c
=> #8075 ensure we capture events in selection menu handlers

end-to-end-tests/tests/extensionConsoleActivation.spec.ts
- To kick off eliminating manual regression checklist tests, rename our existing extensionConsoleActivation test to be consistent with the first test under the "Extension Console Activation" test group on our checklist https://www.notion.so/pixiebrix/Release-1-8-12-fd8e5be965b6477fba9c06455c082dd2
=> Refactor rename extensionConsoleActivation test

src/background/telemetry.test.ts, src/background/telemetry.ts, src/tsconfig.strictNullChecks.json, src/vendors/mixpanelBrowser.ts
- Closes #8065
- Adds browser version to event telemetry
- Followed existing pattern observed with the `$browser` property by copying the vendor code utility from `mixpanel-browser`
=> #8065 Add browser version to event telemetry

src/background/deploymentUpdater.test.ts, src/background/deploymentUpdater.ts, src/store/settings/settingsTypes.ts
- Part of #7475 (preliminary refactor before starting)
- Renames instances of extension -> modComponent
- Renames instances of install -> activate
- Consolidates redundant abstraction for resetting the updatePromptTimestamp
=> #7475 Refactor deploymentUpdater

end-to-end-tests/tests/runtime/srcdocFrames.spec.ts, src/validators/schemaValidator.ts
- Closes #8143
- Fixes invalid URL error on `about:srcdoc` iframes
- Playground: https://pbx.vercel.app/frame-src/
- Test mod: https://app.pixiebrix.com/activate?id%5B%5D=%40pixies%2Ftest%2F8143-repro
- https://www.loom.com/share/b7feb1426cea4fafa81a4e5fb8161bc3?sid=47c5f2fa-dd88-4093-94a9-8b59eef884d0
=> #8143: pass explicit base URL in validateBrickInputOutput to support srcdoc iframes

scripts/__snapshots__/manifest.test.js.snap, scripts/manifest.mjs
- Fixes #8152 
Sets the manifest name to `PixieBrix BETA` for beta cws builds
=> #8152: change manifest name for beta builds

src/background/contentScript.test.ts, src/bricks/renderers/CustomFormComponent.test.tsx, src/bricks/renderers/CustomFormComponent.tsx, src/bricks/renderers/customForm.test.tsx, src/bricks/renderers/customForm.ts, src/components/formBuilder/edit/FieldEditor.tsx, src/pageEditor/fields/FormRendererOptions.test.tsx, src/pageEditor/fields/FormRendererOptions.tsx, src/pageEditor/fields/PipelineToggleField.tsx, src/testUtils/extendedExpectations.ts, src/testUtils/factories/pageEditorFactories.ts, src/testUtils/userEventHelpers.ts, src/utils/objectUtils.test.ts, src/utils/objectUtils.ts
- Closes #8147
- Adds an affordance to reset a form when using the custom submit handler
- Field naming, call it "After Submit Action" action instead of "Post Submit Action"?
- For simplicity, the field type is not toggle-able, and user can't pass a variable in via the Page Editor
- The Jest tests can cover the behavior well because it's by and large React behavior
- https://github.com/pixiebrix/pixiebrix-extension/blob/7ae135304fff2a3604e1d2d8c34984e16b34aa10/src/pageEditor/fields/FormRendererOptions.test.tsx#L67-L67
=> #8147: add custom form submit reset affordance

src/contrib/automationanywhere/aaUtils.test.ts, src/contrib/automationanywhere/aaUtils.ts, src/contrib/automationanywhere/contract.ts
=> #8066 Handle TABLE data type in AA api responses

end-to-end-tests/tests/runtime/insertAtCursor.spec.ts, src/contentScript/textEditorDom.ts, src/contrib/draftjs/draftJsDom.ts, src/tsconfig.strictNullChecks.json, src/utils/domFieldUtils.ts
- Closes #8157 
- Consolidates draftjs-specific logic
- Always use paste event to insert text into draftjs
- See playwright test
=> #8157: fix insert at cursor for draftjs editors

end-to-end-tests/tests/runtime/setInputValue.spec.ts, src/contentScript/textEditorDom.ts, src/contrib/draftjs/draftJsDom.ts, src/utils/domFieldUtils.ts
- Closes #8166
- Refactors/fixes logic for setting draftjs field value
- Adds test mod for regression testing with playwright: `@pixies/test/field-set-value`
- We might try using the Draft.js API instead of sending browser events
=> #8166: fix draftjs set value

src/analysis/analysisVisitors/selectorAnalysis.test.ts, src/analysis/analysisVisitors/selectorAnalysis.ts, src/utils/detectRandomString.test.ts, src/utils/detectRandomString.ts
- Closes #8161 
- Don't flag on tag names (h1, etc.) that have bad character/number ratios
- Improve warning to accommodate utility classes being flagged
- New language is "Selector appears to contain generated or utility values. This may indicate a value that changes across page reloads or application updates."
- Improve analysis for utility classes (e.g., `.mt-3`) - they should be flagged as suspicious, not random?
=> #8161: fix selector analysis false positives and improve warning text

src/vendors/theme/assets/styles/components/_dropdowns.scss
- Fixes #8068
- this css was hiding it, and now it can once again be displayed
Let me know if there are any other placesI should check these particular uses of the dropdown (seems like the Deployment modal uses it as well). 
I checked these in the PageEditor and it seems like it uses a different set of css sourced from `bootstrapWithoutRem.css`
=> #8068: removing unnecessary css override for the button dropdown caret

.github/pull_request_template.md, end-to-end-tests/tests/runtime/insertAtCursor.spec.ts, src/contentScript/textSelectionMenu/SelectionMenu.tsx
- Fixes #8154
- Clicking on the selection menu item shouldn't cause the focus of the underlying element to be lost and reset to the document.
See included playwright test (I verified it failed when the `preventDefault` wasn't included)
=> 8154: fix selection menu causing lost focus of selected element

src/auth/authTypes.ts, src/auth/authUtils.ts, src/auth/selectAuthUserOrganizations.ts, src/tsconfig.strictNullChecks.json
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/4877
- Add `AuthUserOrganization.control_rool` which is set in `selectOrganizations`
=> Add control room to AuthUserOrganization

.eslintrc.js, end-to-end-tests/fixtures/extensionBase.ts, playwright.config.ts
- Makes local development faster by skipping auth if the auth file is still available locally
=> skip auth setup when developing e2e tests locally

end-to-end-tests/README.md, end-to-end-tests/fixtures/extensionBase.ts, package-lock.json, package.json, playwright.config.ts
- Updates the readme with more accurate setup step info
- Removes the skip local auth functionality in the config. Instead, you can use the filter functionality in UI mode. This makes skipping the auth project more intentional to avoid issues with lingering auth profiles.
- Adds better error logging when the auth profile directory files are missing
Why does UI mode not show the latest results??? 🤬
=> Improve e2e test docs and error handling

src/components/IsolatedComponent.tsx
- Fixes a regression within https://github.com/pixiebrix/pixiebrix-extension/pull/8151
I mistakenly broke the stylesheet listener in one of the last commits there. This reverts the commit.
=> #7670: Ensure stylesheets are removed in `IsolatedComponent`

src/contentScript/pageEditor/dynamic.ts, src/pageEditor/toolbar/ReloadToolbar.tsx
- Fixes https://github.com/pixiebrix/pixiebrix-extension/issues/8141
As suggested in https://github.com/pixiebrix/pixiebrix-extension/pull/8225, maybe all we need is to _not_ message the iframes. This is a quicker change than to change all the behaviors related to the page editor sidebar, "Render Panel", auto-run, etc. which I had initially suggested.
This is tested and it appears to work:
1. Open https://ephiframe.vercel.app/Pixie?iframe=https://extra-ephiframe.vercel.app/Brix%3Fiframe%3Dhttps%3A%2F%2Fephiframe.vercel.app%2FPixie
2. Open page editor
3. Click on an existing Sidebar Panel in the page editor sidebar
Expected: the sidebar should open, no modals should appear
=> #8141: Ignore `updateDynamicElement` in iframes for `actionPanel`

src/components/IsolatedComponent.scss, src/contentScript/modalDom.tsx, src/store/optionsStore.ts
- Fixes some styling regressions from #8200 
* Font face fix
* opacity fix
=> Sidebar and modal styling fixes

src/components/IsolatedComponent.scss
- #8237 
- It looks like the `:host: { all: initial }` broke some of the styling, but setting it to `body: { all initial }` gets us the resets we want without losing the ones we want to keep
=> #8237: fix visual regressions from IsolatedComponent

src/extensionConsole/options.html, src/sidebar/sidebar.html, src/tinyPages/walkthroughModal.html, static/loadFonts.js
- Part of 8168
This change ensures that loading the fonts does not block rendering the
sidebar by moving the font link to be loaded dynamically in a script.
I don't think this fully solves the root cause of #8168, but this will slightly improve
the speed in which we render the sidebar as shown in the below reports.
Both reports have a 1.5s delay for all calls (via devtools)
With current code (notice the warning of render blocking request and the slight wait on the scss to start loading before the `api/me` call gets kicked off).
Report With the deferred script approach:
No visible impact on font rendering.
- Continue digging into other possible ways to improve the loading time of the sidebar. Performance Insights on Chrome points out a couple of long tasks that are executed before the DOM …
=> 8168: Defer loading fonts in script in sidebar to avoid render blocking

end-to-end-tests/README.md, end-to-end-tests/env.ts, end-to-end-tests/fixtures/utils.ts
- Makes it so that tests don't fail if you don't happen to have MV defined in your env (as we suggest you can do in our wiki setup guide)
=> Default MV to 3 in e2e tests

src/contentScript/sidebarController.tsx
- Potentially fixes an issue where the side panel would hang in a loading state with the reserved panels showing
- I've never been able to reproduce the issue (on Mac or Windows via Parallel)
- When the width check ever returns false, side panel hangs
- In customer calls, we were able to determine that  the sidebar was being reported as not visible
- I'm not sure about the performance implications of always pinging
- `SIDEBAR_PING` is a `noop`, but we're still increasing the number of messenger calls
- We always ping using the messenger when we think the side panel might be open, though, so it's probably ok
- Alternatively, we could try reducing the `MINIMUM_SIDEBAR_WIDTH`, but as it is already 300, I don't think that would help. It's possible that something is going wrong with the inner …
=> Sidepanel open check failing in some browsers

src/mv3/api.ts
- Closes #8273
- Instead of using optional chaining we could use `isExtensionContext()`. But @grahamlangford and I decided to use optional chaining because it's simpler. Plus we will delete the `src/mv3/api.ts` file when the MV3 transition is complete so no need to create a robust solution here.
https://www.loom.com/share/6884cee3ed74460799897b9c855b318e
- Bump Extension version in App. Will need to go from 1.8.11 -> 1.8.13
=> #8273: Fix App crashing when chrome runtime is undefined

src/activation/modOptionsHelpers.ts, src/activation/useActivateModWizard.test.tsx, src/activation/useActivateModWizard.ts, src/activation/useActivateRecipe.test.ts, src/activation/useActivateRecipe.ts, src/background/starterMods.test.ts, src/background/starterMods.ts, src/components/fields/schemaFields/fieldTypeCheckers.ts, src/store/sidebar/sidebarStorage.ts
- Closes #8222 
- Extracts DB creation logic from useActivateRecipe into a helper function
- DB names general come from [the activation link](https://github.com/pixiebrix/pixiebrix-extension/blob/a9edeb6a92531aecdc775733256cbf1d20c66d2a/src/activation/activationLinkUtils.ts#L165). We need to figure out a way to pass DB names for starter mods
- Rename useActivateRecipe to useActivateMod
=> #8222: support auto-create databases for starter mods

src/contentScript/sidebarController.tsx
- Fixes issue introduced in #8271
- This was exposed by the toggle sidebar brick
https://www.loom.com/share/d6b96b187b2741d18eab4a9c35e99eb7
=> fix for lag when opening sidebar using toggle sidebar brick

.github/workflows/release.yaml
- Removes the beta build from regular release build runs to reduce number of artifacts
- Beta builds have their own github action now
=> regular release no longer creates beta build

src/components/quickBar/QuickBarApp.test.tsx, src/components/quickBar/QuickBarApp.tsx
- This change fixes a small regression introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/7686 where the escape key onKeydown no longer closes the quickbar modal.
=> Quickbar closes on Escape

end-to-end-tests/auth.setup.ts, end-to-end-tests/tests/runtime/sidebarNavigation.spec.ts, end-to-end-tests/utils.ts, playwright.config.ts, src/contentScript/contentScriptCore.ts, src/contentScript/lifecycle.ts
- Closes #8292
- This change ensures that navigating to a new tab does not cause the current sidebar to sometimes close.
- Added a couple of unrelated changes to improve e2e flakiness.
See inline notes in code.
=> #8292: MV3 sidebar is less flaky about staying open during navigation

src/errors/businessErrors.ts
- Improve documentation / guidelines for business errors: clarify when to use BusinessError vs. Error subclass
- Call out any places where clarification would be helpful
- Feel free to make commits, etc. directly to this PR
=> Improve guideline documentation for business errors

end-to-end-tests/tests/runtime/sidebarPanelTheme.spec.ts, src/bricks/renderers/CustomFormComponent.tsx, src/bricks/renderers/documentView/DocumentView.tsx, src/bricks/renderers/documentView/DocumentViewProps.tsx, src/bricks/transformers/ephemeralForm/EphemeralFormContent.tsx, src/components/StylesheetsContext.ts, src/tsconfig.strictNullChecks.json
- Closes #8347 
- Replaces logic introduced in https://github.com/pixiebrix/pixiebrix-extension/pull/7550 and accidentally removed in https://github.com/pixiebrix/pixiebrix-extension/pull/8200
- In draft because I want to make sure that I understand the relationship between this feature and IsolatedComponent before opening
- But, see Playwright test for demonstration that this fixes the regression
- See playwright test
=> #8347 Fix custom document stylesheets nested stylesheet inheritance

src/bricks/effects/exportFileEffect.test.ts, src/bricks/effects/exportFileEffect.ts, src/bricks/effects/getAllEffects.ts, src/development/headers.test.ts, src/tsconfig.strictNullChecks.json
- Closes #8383
- Adds brick to export data URL as a file
- https://www.loom.com/share/65d54774fffe4fe5b17c52ca69eec8a8
=> #8382: brick to export data url as file

scripts/__snapshots__/manifest.test.js.snap, scripts/manifest.mjs, src/manifest.json
- Removes the invalid `offscreen` permission from mv2 manifests
- Ensures the `offscreen` permission is still added to mv3 manifests
=> Fix mv2 permissions

.github/workflows/ci.yml
- Makes it so that we don't run the CI workflow twice for every PR. Now it just runs when a PR is cut against master, or when a push is made to any other branch.
=> Avoid running CI workflow twice for PRs

.github/workflows/ci.yml, .github/workflows/rainforestqa.yml
- Ensures CI wf only runs on PR and when pushed to a release branch
- Doesn't run on simple changes that don't affect the code
=> Fix ci running twice

src/components/formBuilder/RjsfSelectWidget.test.tsx, src/components/formBuilder/RjsfSelectWidget.tsx
- Closes #8418
- Make RJSF select widget clearable if the field is not required
- See Jest test. Can't record Loom from plane
- https://github.com/pixiebrix/pixiebrix-extension/issues/8422
=> #8418: make RJSF select clearable in Form Builder

src/utils/canvasUtils.ts
This will allow us to load PNGs in MV3, while still being
backwards compatible to load SVGs in MV2
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/5185
- This makes it so we don't throw an undefined error when running: `image instanceof HTMLImageElement;`
- I manually verified these changes against my app changes here: https://github.com/pixiebrix/pixiebrix-app/issues/5174
- mv2 + svg, mv2 + png, mv3 + png
=> Add isMV3 to blobToImageData

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts, end-to-end-tests/pageObjects/pageEditorPage.ts, end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts, end-to-end-tests/utils.ts, src/contentScript/lifecycle.ts
- Closes #8104
- reading `lifecycle.ts` and trying to understand all the different code execution paths gives me a migraine.
- I'm not a fan of the check for sidebar kind equals "actionPanel" that we do in many different places. 
- I manually verified that the regression fixed in this PR with trigger mods running multiple times after save doesn't happen: https://github.com/pixiebrix/pixiebrix-extension/pull/5505
=> #8104 Do not automatically close the sidebar when saving in the Page Editor

src/mv3/api.ts, src/tinyPages/offscreen.ts
- Follow-up of https://github.com/pixiebrix/pixiebrix-extension/pull/8275
- It looks like optional chaining that we added was not enough to prevent import errors. 
- For some reason, the changes made in the previous PR were passing cypress tests in headless mode (and local builds looked fine) but Misha's cypress tests are failing in UI mode, and staging is down
- We should seriously consider adding smoke tests to dev and staging
=> Add additional optional chaining to prevent import errors when chrome api not available

src/contrib/slack/message.ts
- Removes the content type header hack on the slack bricks, looks like we don't need it anymore, and it also started breaking for some reason after our Axios upgrade in v1.8.14
=> Fix the richly formatted, webhook-based Slack bricks - remove header content type hack

.github/dependabot.yml
- Reduce the number of dependabot PR runs that run every Sunday by grouping all patch updates into a single PR
- Patch updates are very unlikely to cause an issue, and running fewer action runs will reduce the number of flaky Playwright runs
- We already auto-approve and auto-merge patch dependency updates every week
=> group all patch updates into single PR

.eslintrc.js, end-to-end-tests/pageObjects/extensionConsole/modsPage.ts, end-to-end-tests/tests/extensionConsoleActivation.spec.ts, end-to-end-tests/tests/runtime/insertAtCursor.spec.ts, eslint-local-rules/preferUsingStepsForLongTests.js
This rule will encourage us to break up long tests using refactored page methods or `test.step`
Primary reviewer @grahamlangford
=> custom eslint rule for e2e test length

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
This PR introduces changes to the `ModsPage` class in the `end-to-end-tests/pageObjects/extensionConsole/modsPage.ts` file. The changes include:
- Adding a mechanism to wait for the registry request to finish before interacting with the mods table. This ensures that the table is fully loaded and stable.
- Adding a check to ensure that the page content has finished loading.
- Refactoring the `deleteModByName` method to improve the handling of the mod deletion process. This includes better handling of the dropdown menu and the deletion confirmation modal.
The reviewer should review the changes in the `end-to-end-tests/pageObjects/extensionConsole/modsPage.ts` file.
The changes were made to improve the stability and reliability of the end-to-end tests, particularly when interacting with the …
=> fix e2e flakiness with deleting mods cleanup

src/contrib/automationanywhere/aaFrameProtocol.ts
- AA changed the structure of their copilot app to have two nested iFrames now, and the receiver for our message is apparently now in the _outer_ frame and not the inner copilot one that _sends_ the message, so we need to post to the parent of the source instead
=> Fix AA CoPilot sidebar window messaging

src/background/installer.test.ts, src/background/installer.ts
- Fixes `Invalid Version` error from datadog
- See https://app.datadoghq.com/logs/error-tracking/issue/d3606bc4-07c1-11ef-ad7a-da7ad0900002?from_ts=1715616006615&to_ts=1715702406615&live=true
=> fix invalid semver version error

src/components/form/ConnectedFieldTemplate.tsx, src/components/form/Form.stories.tsx, src/utils/stringUtils.test.ts, src/utils/stringUtils.ts
This PR enhances the error handling in the Pixiebrix extension's form fields. It introduces the ability to include a Markdown link in the error message, which is then extracted and displayed as a button link. This allows users to be directed to relevant documentation or resources directly from the error message. The changes are demonstrated in the form story by adding a link to an age calculator in the error message for the age field.
Part of: https://github.com/pixiebrix/pixiebrix-app/issues/5213
The main approach was to use a regular expression to extract a Markdown link from the error message, if present. The link is then used to create a button that opens the link in a new window when clicked.
Ideally we could have defined the button link as a separate property on the validation …
=> form validation errors support showing a button link

end-to-end-tests/tests/extensionConsoleActivation.spec.ts, src/contentScript/sidebarController.tsx, src/sidebar/sidebar.tsx
Fixes #8376
It removes a temporary hack that was used to reload the sidebar in the extensionConsoleActivation.spec.ts file. The hack was used to handle a situation where the sidebar was not automatically reloaded. The PR also introduces changes in the sidebarController.tsx file to ensure that the sidebar is refreshed when the "Show Sidebar brick" is triggered, even if the sidebar is already open.
Theres's a small chance of a race condition where the ping to check if the sidebar was initially open happens after the sidebar is actually opened, but in this case the only outcome would be that the panel modComponent would be run twice, which shouldn't really be an issue.
=> #8376 Fix show sidebar brick not refreshing panel

src/tinyPages/devtools.ts
- Adds `BETA` suffix to the dev tools panel title for the beta extension build
=> DX - Add BETA to dev tools panel title for the beta extension build

package-lock.json, package.json, src/contentScript/sidebarController.tsx
- Closes #8287 
- p-retry was already a dependency through webext-messenger
- This implementation emulates the way the messenger retries: https://github.com/pixiebrix/webext-messenger/blob/33b2549687da205587deb4715240a6afaf001de0/source/sender.ts#L76
- ~I've not been able to get the original timeout to throw on my machine, so this isn't tested beyond verifying it doesn't break typical open/close behavior~
- Tested with a mix of sleep and throwing errors
=> #8287: Improve UX for long sidebar open times

.github/workflows/beta-release.yaml
- The beta-release action was running the e2e tests against main instead of the branch being published
- Also simplified the input for the version
=> Fix beta release Github action

.github/workflows/rainforestqa.yml
- Follows https://github.com/pixiebrix/pixiebrix-extension/pull/8482
- Previous PR was meant to update Rainforest but was somehow missed
=> Rainforest - switch from mv2 to mv3

src/background/messenger/external/_implementation.ts
- Fixes #8496 
- Issue caused by #8469
- Previously defaulted to `[]`  https://github.com/pixiebrix/pixiebrix-extension/pull/8469/files#diff-8c5c6da446cff9fc924710d7913f17f53fc94e3abe23d05cca2d83176d5a6c50L58-L60:~:text=if%20(!value,%7D
- Resolved by adding the default value
- Confirmed that this is not the cause of #8497
=> #8496: add default value to handle empty storage

src/background/starterMods.test.ts, src/background/starterMods.ts
- Fixes #8497 
- As discussed in standup, we also considered creating an upsert endpoint
- Decided to list the databases then create if needed because we're assuming new users will have few databases anyway
- and this way we don't have to also create and deploy an App change
https://www.loom.com/share/797923270f844f1f92cc79358c64603c
=> #8497: when installing starter mods, check existing databases before creating a new one

src/integrations/components/RequireIntegrationConfig.test.tsx, src/integrations/components/RequireIntegrationConfig.tsx
- Closes #8504 
- Create Admin Console affordance for deep linking to a specific integration config without knowing if it's a personal or team config (and handling lack of edit permissions). We need to eventually do the same for databases too
=> #8504: link to admin console for remote config error

src/bricks/effects/AddDynamicTextSnippet.test.ts, src/bricks/effects/AddDynamicTextSnippet.ts, src/bricks/effects/AddTextSnippets.test.ts, src/bricks/effects/AddTextSnippets.ts, src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.stories.tsx, src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.test.tsx, src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.tsx, src/contentScript/snippetShortcutMenu/snippetShortcutMenuController.test.tsx, src/contentScript/snippetShortcutMenu/snippetShortcutMenuSlice.test.ts, src/platform/platformTypes/snippetShortcutMenuProtocol.ts
- Closes #8516 
- Includes mod metadata with TextCommandRun event so deployment managers can see snippet shortcut engagement for their mods
=> #8516: include mod metadata with TextCommandRun event

end-to-end-tests/tests/telemetry/errors.spec.ts, src/telemetry/logging.test.ts, src/telemetry/logging.ts, src/tinyPages/offscreen.ts
- Fixes datadog payload for offscreen error reporting
- Error has to be serialized before passing between contexts
- We weren't serializing/deserializing for the offscreen doc
=> Fix offscreen errors

src/extensionConsole/pages/onboarding/SetupPage.test.tsx, src/extensionConsole/pages/onboarding/SetupPage.tsx
Closes #8239
This PR introduces error handling for the scenario where fetching service definitions fails for OAuth2 partner user with required service id in settings. It also modifies the test file to include a test case for this scenario.
=> show improved warn toast on error in partner setup page

.pre-commit-config.yaml, .secrets.baseline
- Closes #8543
The new pre-commit hook should auto-install on next commit
=> #8543: Adding detect-secrets precommit

end-to-end-tests/pageObjects/floatingActionButton.ts, end-to-end-tests/tests/extensionConsoleActivation.spec.ts, end-to-end-tests/tests/smoke/floatingActionButton.spec.ts, src/components/floatingActions/ActionButton.tsx, src/components/floatingActions/FloatingActions.scss, src/components/floatingActions/FloatingActions.tsx, src/telemetry/events.ts, src/tsconfig.strictNullChecks.json
- Closes #8548 
- Adds Playwright tests and POM for the FAB 
https://www.loom.com/share/0209389a01e548598daece92c04f91d3
- Move the FAB out of `src/components`
- Didn't do it during this PR to preserve history/make the changes obvious
=> #8548: switch fab to open the sidebar instead of quick bar

src/pageEditor/tabs/trigger/TriggerConfiguration.tsx, src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap, src/runtime/pipelineTests/pipelineTestHelpers.ts, src/starterBricks/triggerExtension.test.ts, src/starterBricks/triggerExtension.ts, src/starterBricks/triggerExtensionTypes.ts
- Closes #8546
This PR introduces changes to the trigger reporting options. It adds two new options for the `ReportMode` in the `TriggerConfig`:
- `error-once`: Only errors are reported once per extension per page.
- `never`: Never reports events.
The changes are reflected in the `TriggerConfiguration.tsx` file where the options for telemetry reporting are defined. The PR also includes updates to the corresponding test files to ensure the new options are working as expected.
=> #8546: Add an error-once, and never report mode for trigger extensions

src/extensionConsole/pages/mods/hooks/useActivateAction.ts, src/extensionConsole/shared/routeHelpers.ts, src/extensionConsole/shared/routeHelpers.tsx, src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx, src/tsconfig.strictNullChecks.json
- Closes #8605 
- Links directly to mod re-activation from the Page Editor
- The activation page adds the `reactivate=1` onto the URL if it detects it's a reactivation
- Extracts the url construction method to a `shared` folder. (A `shared` folder will allow us to support cross-module imports to files in that folder more easily)
- @fungairino would you recommend using the helper in the playwright code too?: https://github.com/pixiebrix/pixiebrix-extension/blob/aba3dfe639ac2461bc21e5856b6b5160a7e85c44/end-to-end-tests/pageObjects/extensionConsole/modsPage.ts#L135-L135
=> #8605: link directly to mod re-activation from Page Editor version warning

src/bricks/effects/pageState.ts
=> #8601: drop legacy label copy from data binding locations

src/components/fields/schemaFields/widgets/TextWidget.test.tsx, src/components/fields/schemaFields/widgets/TextWidget.tsx
- Closes #8404
- Closes #8241
- Fixes variable detection logic to support optional chaining to prevent auto-switching to text entry mode
- Fix variable popover filtering logic to support optional chaining: https://github.com/pixiebrix/pixiebrix-extension/issues/8636
=> #8404: fix variable path regex to not switch to text entry mode during optional chaining

src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx, src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.test.ts, src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.ts, src/components/fields/schemaFields/widgets/varPopup/menuFilters.test.ts, src/components/fields/schemaFields/widgets/varPopup/menuFilters.ts, src/runtime/pathHelpers.test.ts, src/runtime/pathHelpers.ts
- Closes #8636
- Follow up to https://github.com/pixiebrix/pixiebrix-extension/pull/8635
- Ignores `?` during filtering
- Attempts to preserve existing `?` when a value is selected from the popover
- Eventually we probably want to do real lexing/parsing to generate an AST that can also be used to re-generate the expression
- https://github.com/pixiebrix/pixiebrix-extension/issues/8638
=> #8636: fix search/insert for variable popover using optional chaining

package-lock.json, package.json
Fixes #8283
This PR updates the version of the `webext-messenger` package from `0.27.0` to `0.28.0` in the Pixiebrix browser extension. It also introduces a new dependency, `p-event` version `6.0.1`.
I verified that this upgraded dependency fixes the issue linked above by using a mod that shows a temporary form on page load. With this change, preloading the page (by typing the url in search bar and waiting a sec) does not cause the `FORM_GET_DEFINITION` to pop up.
The new dependency, p-event is MIT license.
=> #8283: webext-messenger -> 0.28.0

src/__snapshots__/Storyshots.test.js.snap, src/extensionConsole/pages/activateExtension/ActivateExtensionPage.tsx, src/extensionConsole/pages/activateMod/ActivateModPage.tsx, src/extensionConsole/pages/activateMod/__snapshots__/ActivateModCard.test.tsx.snap, src/extensionConsole/pages/brickEditor/CreatePage.tsx, src/extensionConsole/pages/brickEditor/EditPage.tsx, src/extensionConsole/pages/integrations/IntegrationsPage.tsx, src/extensionConsole/pages/settings/SettingsPage.tsx, src/extensionConsole/pages/workshop/WorkshopPage.tsx, src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap, src/layout/Page.stories.tsx, src/layout/Page.tsx, src/vendors/theme/assets/styles/_misc.scss
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/5003
- Add affordance for documentation link to `Page` component
- Modifies the CSS in the vendored admin/extension console theme
- User interface
- Includes external link icon to indicate link will open in a new tab. Might not be necessary. (It was not in the original design: https://github.com/pixiebrix/pixiebrix-app/issues/5003#issuecomment-2037489500). 
- We might instead consider https://fontawesome.com/v5/icons/question-circle?f=classic&s=regular
- Or just leaving off the icon, as in the original design. (Might be best given it's next to the page icon)
- @brittanyjoiner15 are there certain UTM tags we should be using here? Or do we not use since it's coming from within our ecosystem?
See Storybook:
- Add links in Admin …
=> Add documentation link to pages

src/background/deploymentUpdater.ts, src/background/modUpdater.ts, src/pageEditor/hooks/useDeactivateMod.tsx, src/pageEditor/hooks/useRemoveModComponentFromStorage.test.ts, src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx, src/pageEditor/hooks/useResetExtension.ts, src/pageEditor/hooks/useSaveMod.ts, src/pageEditor/panes/save/useSavingWizard.ts, src/pageEditor/sidebar/DynamicModComponentListItem.test.tsx, src/pageEditor/slices/editorSlice.ts, src/pageEditor/slices/editorSliceHelpers.test.ts, src/pageEditor/slices/editorSliceHelpers.ts, src/pageEditor/utils.ts, src/store/editorStorage.ts, src/store/sessionChanges/sessionChangesListenerMiddleware.ts
- Part #8607
- Another small chunk of replacing instances of "element" where mod component form state is meant
- See commit history for a nice summary of what I changed
=> #8607 Refactor rename "element" in editor slice actions 

.pre-commit-config.yaml, end-to-end-tests/fixtures/modDefinitions.ts, end-to-end-tests/pageObjects/extensionConsole/workshop/modEditor.ts, end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts, end-to-end-tests/tests/extensionConsole/activation.spec.ts, end-to-end-tests/tests/workshop/createMod.spec.ts, end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/simple-sidebar-panel-chrome-can create a new mod from a yaml definition, end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/simple-sidebar-panel-edge-can create a new mod from a yaml definition, src/tsconfig.strictNullChecks.json
Closes #8582
This PR introduces changes to the Pixiebrix extension's end-to-end testing suite. It implements snapshot testing for mod definitions, normalizing uuid strings for consistency. It also includes changes to the WorkshopModEditor and WorkshopPage classes to improve test reliability. Additionally, it removes two pre-commit hooks from the .pre-commit-config.yaml file.
=> #8582 e2e fixture method for verifying mod definition yaml

src/utils/modUtils.test.ts, src/utils/modUtils.ts, src/utils/objectUtils.ts
- Extension change for https://github.com/pixiebrix/pixiebrix-app/issues/5396
- Fixes `normalizeModOptionsDefinition` so that it doesn't mutate its input
=> Don't mutate uiSchema in normalizeModOptionsDefinition

src/data/service/api.ts, src/extensionConsole/pages/activateMod/ActivateModCard.test.tsx, src/extensionConsole/pages/activateMod/ActivateModCard.tsx, src/extensionConsole/pages/activateMod/ActivateModPage.tsx, src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx, src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx, src/extensionConsole/pages/mods/modals/shareModals/CancelPublishContent.tsx, src/extensionConsole/pages/mods/modals/shareModals/PublishModContent.tsx, src/extensionConsole/pages/mods/modals/shareModals/ShareModModalBody.tsx, src/modDefinitions/modDefinitionsListenerMiddleware.ts, src/pageEditor/hooks/useCreateModFromMod.ts, src/pageEditor/hooks/useCreateModFromModComponent.ts, src/pageEditor/hooks/useSaveMod.ts, src/pageEditor/panes/save/useSavingWizard.test.tsx, src/pageEditor/panes/save/useSavingWizard.ts, src/pageEditor/sidebar/ActivatedModComponentListItem.tsx, src/pageEditor/sidebar/ModListItem.tsx, src/types/contract.ts
- Rename RTK Query endpoints for mod CRUD to use mod definition terminology
- Main change in the RTK Query API definition: https://github.com/pixiebrix/pixiebrix-extension/pull/8668/files#diff-f9c820753f8e1322c98cc85c45858cac684e36b22d054caa13c829a4a6f63893
- Stop using the `/api/recipes/:id/` endpoint for retrieval: https://github.com/pixiebrix/pixiebrix-app/issues/4355
=> Rename RTK Query endpoints for mod definition CRUD

src/background/initTheme.ts, src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx, src/extensionConsole/pages/settings/AdvancedSettings.tsx, src/hooks/useTheme.ts, src/store/settings/settingsSlice.ts
- Introduces `useActivatePartnerTheme` hook to address the assumption that the partner theming is broken/flaky due to the background script handling `activateTheme` before the partner theme value being available in the redux settings store
- Refactors the `PartnerSetupCard` component in `PartnerSetupCard.tsx` to use a new `useActivatePartnerTheme` hook instead of dispatching an action directly. 
- The same change is applied to the `AdvancedSettings` component in `AdvancedSettings.tsx`. 
- Some light variable name refactoring
- We're not 100% convinced that the delay between the `partnerId` being available in the store and the background script handling `activateTheme` is the race condition (nor are we sure what caused the test to be more flaky than it was before)
- However, in the …
=> Fix flaky partner theming

src/__snapshots__/Storyshots.test.js.snap, src/components/banner/Banner.module.scss, src/components/banner/Banner.stories.tsx, src/themes/colors.scss
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/5426
- See `Banner` component storybook
Before:
After:
=> Update danger banner colors

src/pageEditor/panes/EditorPane.tsx, src/pageEditor/sidebar/AddStarterBrickButton.tsx, src/pageEditor/sidebar/arrangeSidebarItems.test.ts, src/pageEditor/sidebar/modals/CreateModModal.tsx, src/pageEditor/sidebar/modals/MoveFromModModal.tsx, src/pageEditor/starterBricks/adapter.ts, src/pageEditor/starterBricks/base.ts, src/pageEditor/starterBricks/modComponentFormStateAdapter.ts, src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx, src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
- Closes #8607
- This should be the rest (to the best of my ability) to replace remaining instances of "element" when referring to mod component form state
=> #8607 Replace remaining occurrences of mod component form state "elements"

src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx, src/pageEditor/documentBuilder/edit/DocumentOptions.tsx, src/pageEditor/documentBuilder/edit/ElementEditor.tsx, src/pageEditor/documentBuilder/edit/RemoveElement.tsx, src/pageEditor/documentBuilder/hooks/useDeleteElement.ts, src/pageEditor/documentBuilder/hooks/useMoveElement.ts, src/pageEditor/documentBuilder/hooks/useMoveWithinParent.ts, src/pageEditor/documentBuilder/hooks/useSelectParentElement.ts, src/pageEditor/documentBuilder/preview/ElementPreview.test.tsx, src/pageEditor/fields/FormModalOptions.tsx, src/pageEditor/fields/FormRendererOptions.tsx, src/pageEditor/slices/editorSelectors.ts, src/pageEditor/slices/editorSlice.test.ts, src/pageEditor/slices/editorSlice.ts, src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx, src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx, src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx, src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
- Closes #8609
- Also reverts naming choice of `activeDocumentOrFormPreviewElement` -> `activeBuilderPreviewElement`
=> #8609 Rename nodePreviewElement -> builderPreviewElement

src/mods/useModViewItems.test.tsx, src/mods/useMods.test.ts, src/mods/useMods.ts
- Prevent retired starter bricks from crashing mods screen if the user has the retired starter brick saved to server as a standalone mod definition
- The runtime and Page Editor likely can't handle mod components with retired starter bricks. There more easy workaround for those situations, though. The user just needs to de-activate those mods. In practice, it will only be our internal developers who might have retired starter bricks active
- For example, a retired starter brick in an activated mod will cause not mod components to load: https://github.com/pixiebrix/pixiebrix-extension/blob/e343d6a02a59e8990ac429b5fe24deb7434c6d0c/src/contentScript/lifecycle.ts#L450-L450
[code review principles …
=> Prevent retired starter bricks in saved standalone mods from crashing mods screen

package-lock.json, package.json, src/background/navigation.ts, src/permissions/permissionsUtils.ts
A function used by pixiebrix was moved from `webext-tools` to `webext-content-scripts`
- https://github.com/fregante/webext-tools/pull/9
- https://github.com/fregante/webext-content-scripts/pull/37
=> Update `webext-tools` usage

end-to-end-tests/setup/utils.ts, end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts, src/background/starterMods.test.ts, src/background/starterMods.ts
Fixes #8740
This PR modifies the method for activating the starter mods in the background script so that it immediately reloads the mods in the tab, rather than on the next navigation. This fixes the issue where the mods were not completely loaded on the page, and not showing properly in the sidebar.
Also included is a new end-to-end test for viewing the starter mods on the pixiebrix.com/welcome page.
Additionally, this PR also refactors the method for opening the extension console from the admin page in the end-to-end test setup to reduce flakiness.
=> #8740 fix welcome starter mods not loading in welcome page

end-to-end-tests/pageObjects/pageEditor/brickActionsPanel.ts, end-to-end-tests/pageObjects/pageEditor/brickConfigurationPanel.ts, end-to-end-tests/pageObjects/pageEditor/dataPanel.ts, end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts, end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts, end-to-end-tests/pageObjects/pageEditor/utils.ts, end-to-end-tests/tests/modLifecycle.spec.ts, end-to-end-tests/tests/pageEditor/saveMod.spec.ts, end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
This PR introduces several new classes in the `end-to-end-tests/pageObjects/pageEditor` directory, including `brickActionsPanel.ts`, `brickConfigurationPanel.ts`, `dataPanel.ts`, `modEditorPane.ts`, and `utils.ts`. These classes provide methods for interacting with different parts of the page editor in the PixieBrix extension. 
The PR also modifies the `pageEditorPage.ts` class to use these new classes and their methods. The changes include replacing direct interactions with the page editor (such as filling in fields) with calls to the new methods, and adding a `ModifiesModState` decorator to methods that modify the state of the mod.
In addition, the PR updates several test files to use the new methods in `pageEditorPage.ts`.
The PR is part of a larger effort to provide a more structured …
=> #8581: More page editor poms

src/pageEditor/hooks/useCreateModFromModComponent.ts, src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx, src/pageEditor/utils.ts
- Improve Page Editor utils method names
- Avoid using `select` outside of Redux context
- foundation -> starter brick
- block -> brick
=> Improve Page Editor utils method names

src/types/modComponentTypes.ts, src/types/registryTypes.ts, src/types/runtimeTypes.ts, src/types/stringTypes.ts
- Use type-fest's `Tagged` type for simple nominal typing
- Figure out how to use with complex objects that are generated with cooky-cutter factories. Currently for those we pass the prop as undefined: https://github.com/pixiebrix/pixiebrix-extension/blob/dc5eac7507feada1c06f03b1427ad3014b001825/src/starterBricks/quickBar/quickBarStarterBrick.test.ts#L82-L82
=> Use type-fest's `Tagged` type for simple nominal types

src/components/fields/schemaFields/fieldTypeCheckers.ts, src/contrib/google/sheets/bricks/append.ts, src/contrib/google/sheets/bricks/lookup.ts, src/integrations/constants.ts, src/integrations/util/getModDefinitionIntegrationIds.test.ts, src/integrations/util/getUnconfiguredComponentIntegrations.test.ts, src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx, src/pageEditor/documentBuilder/hooks/useDeleteElement.ts, src/pageEditor/fields/FormRendererOptions.tsx, src/pageEditor/panes/save/saveHelpers.test.ts, src/pageEditor/panes/save/saveHelpers.ts, src/pageEditor/store/editor/editorSlice.test.ts, src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts, src/sidebar/activateMod/ActivateModPanel.test.tsx
- Renames most instances of `service` -> `integration` in the Page Editor
- Rename the form fields from `service` -> `integration` (likely requires service layer transform)
=> Rename service -> integration in Page Editor

end-to-end-tests/pageObjects/pageEditor/utils.ts, end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
- Adds a 200ms delay to avoid a race condition between the formik state sync with redux and the save function being called, when playwright is able to click the Render Panel and then Save buttons in very quick succession
- Is there a better way to fix this other than a hacky "sleep" call?
=> DX - Fix flaky sidebar playwright test

src/utils/domUtils.ts, src/utils/injectIframe.tsx
- Part of #8220
- Injects the sandbox iframe into the document root instead of the document body
- This is to address the hypothesis that web pages are removing the iframe from the DOM before the mod has the chance to use it (the assumption is that it is less likely for webpages to wipe things in the document root vs. the body)
- I'm able to consistently confirm that in the case of Docusign, the sandbox is always removed from the page after a certain point, causing a race with the mod component runtime: https://www.loom.com/share/e9ec1521b66e46fab93457a6ae391699
- This change resolves the issue in the case of Docusign, at least
- The next PR I'm preparing 
- will remove [injectIframe memoization](https://github.com/pixiebrix/pixiebrix-extension/blob/7a6e3f620e10f1e3181a503cce95e82a9627eb36 …
=> #8220: Inject sandbox into document root instead of body

src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts, src/components/quickBar/quickBarRegistry.ts, src/contentScript/ephemeralPanel.ts, src/contentScript/pageEditor/runRendererBrick.ts, src/contentScript/sidebarController.tsx, src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts, src/platform/forms/formController.ts, src/platform/panels/panelController.ts, src/sidebar/Tabs.tsx, src/sidebar/TemporaryPanelTabPane.tsx, src/sidebar/modLauncher/ActiveSidebarModsList.tsx, src/sidebar/sidebarSelectors.ts, src/starterBricks/sidebar/sidebarStarterBrick.test.ts, src/starterBricks/sidebar/sidebarStarterBrick.ts, src/store/sidebar/eventKeyUtils.test.ts, src/store/sidebar/eventKeyUtils.tsx, src/store/sidebar/sidebarSlice.test.ts, src/store/sidebar/sidebarSlice.ts, src/store/sidebar/thunks/addFormPanel.ts, src/store/sidebar/thunks/addTemporaryPanel.ts, src/telemetry/telemetryHelpers.test.ts, src/testUtils/factories/modComponentFactories.ts, src/types/modComponentTypes.ts, src/utils/modUtils.ts
- Closes #8783
- `ModComponentRef` can't be used directly for MessageContext because `MessageContext` expects `undefined` for `modId` instead of `Nullishable`. So we can't get rid of `mapModComponentRefToMessageContext` uses
- We can't get rid of `mapMessageContextToModComponentRef` uses because it contains the nullish assertions
- Finish updating messenger APIs and controllers to use `ModComponentRef` (e.g., `waitForTemporaryPanel`)
- Clean up local variable names
=> #8783: update `ModComponentRef` property names

src/background/contextMenus/ensureContextMenu.ts, src/background/contextMenus/initContextMenus.ts, src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts, src/bricks/transformers/temporaryInfo/temporaryPanelProtocol.test.ts, src/contentScript/contentScriptPlatform.ts, src/contentScript/contextMenus.ts, src/contentScript/ephemeralPanel.ts, src/contentScript/lifecycle.ts, src/contentScript/pageEditor/runRendererBrick.ts, src/contentScript/sidebarController.tsx, src/platform/panels/panelController.ts, src/platform/platformTypes/contextMenuProtocol.ts, src/platform/platformTypes/panelProtocol.ts, src/starterBricks/button/buttonStarterBrick.ts, src/starterBricks/contextMenu/contextMenuStarterBrick.test.ts, src/starterBricks/contextMenu/contextMenuStarterBrick.ts, src/starterBricks/sidebar/sidebarStarterBrick.ts, src/testUtils/platformMock.ts, src/types/runtimeTypes.ts
- Update naming in panel, context menu, and starter brick API
- @BLoe this PR touches `removeStarterBrick`/`unregisterStarterBrick`, which might be involved in the panel save bug you're seeing: https://github.com/pixiebrix/pixiebrix-extension/pull/8785/files#diff-0ae99f17a1e6025b6ede6522e2a25c18a671f67daf1bc65c9f305789d36deafeR43
- Use `modComponentRef` in the protocol state API. (Not urgent given that it's already using `modComponentId` and `modId` terminology, but would be good for clarifying modId nullness in the future)
- Finish update naming in runtime
=> Update naming in panel and starter brick API

src/bricks/types.ts, src/pageEditor/store/editor/uiStateTypes.ts, src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx, src/pageEditor/tabs/effect/BrickConfiguration.tsx
- Fixes #8781
- Tried to run the `syncBrickConfigurationUIStates` function in a migration, but that pulled code into the `loadActivationEnhancements.js` bundle that is banned. Tried to work around but wasn't able, so I reverted to this solution.
- In the process of debugging and fixing this issue, I fixed the only mod that I could reproduce the issue with
- This issue can only happen with mods installed before the previous state migration (and then only sometimes), so I can't get the editor back into a bad state to demo
=> #8781: fix the error using a hook during runtime instead of a migration

src/telemetry/reportEvent.ts, src/telemetry/telemetryHelpers.ts
Fixes #8789
This PR introduces error handling in the `reportEvent` function in the `reportEvent.ts` file. It wraps the `_record` function call in a try-catch block and reports any errors that occur using the `reportError` function. 
It also modifies the `mapEventDataToDeprecatedTerminology` function in the `telemetryHelpers.ts` file to avoid mutating the input data object. It creates a deep clone of the input data object and performs the mapping operations on the cloned object.
=> #8789 object extensibility error

src/data/service/api.ts, src/pageEditor/hooks/useCreateModFromModComponent.ts, src/pageEditor/hooks/useSaveMod.ts, src/pageEditor/hooks/useUpsertModComponentFormState.test.ts, src/pageEditor/hooks/useUpsertModComponentFormState.ts
=> #8739 Package standalone mods on save - Slice 3

.eslintrc.js, src/components/formBuilder/formBuilderHelpers.ts
Enables the `no-param-reassign` eslint rule to improve our chances of avoiding mutation related bugs such as https://github.com/pixiebrix/pixiebrix-extension/issues/8789
57 warnings currently reported.
=> Enabling warn for no-param-reassign eslint rule

.github/workflows/ci.yml, .secrets.baseline
Saves us some money on unnecessary workflow runs. 🤑🤑🤑
See: https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency
=> prevent concurrent workflow runs in prs

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
This PR fixes the flakiness handling for issue #8458 by modifying the `click()` function in the `ModTableItem` class within the `modsPage.ts` file, by adding a timeout parameter to the `click()` function to handle retrying in the `toPass` block.
=> fix flakiness handling

.github/workflows/ci.yml
It adds a useful comment and link to our readme for devs to find how to view and debug our e2e test report.
See: https://github.com/daun/playwright-report-summary
=> Adding a link to our readme from the PR e2e report comment

.github/workflows/end-to-end-tests.yml, .secrets.baseline
This PR introduces changes to the end-to-end testing workflow in the Pixiebrix extension repository. It adds sharding to the testing process, dividing the tests into three separate shards for parallel execution. This is done by adding two new matrix parameters, `shardIndex` and `shardTotal`, to the GitHub Actions workflow file. The PR also modifies the naming and uploading of the test reports to reflect the sharding. 
Future work may include adjusting the number of shards based on the number and duration of the tests, or further optimizing the test reporting process. 
In particular we spend a lot of overhead time that is repeated in each shard building the extension, and running the same setup tests. We could potentially break these out further before running the sharded tests.
=> Shard e2e tests

src/utils/postMessage.ts
- Part of #8220 
- When creating a fix for this PR, I decreased the timeout for postMessage to 1s since we were increasing the number of retries. This PR sets the timeout back to 3s, which would create a worst-case response time of 9s when retrying sending messages to the sandbox
- This is to address the hypothesis that 1s isn't enough time for some sites, e.g. in this situation here: https://app.datadoghq.com/logs/error-tracking/issue/07c45ab2-4050-11ef-93eb-da7ad0900002?query=service%3Apixiebrix-browser-extension%20version%3A2.0.5-beta.1&fromUser=false&refresh_mode=sliding&view=spans&from_ts=1720721077477&to_ts=1720807457885&live=true
=> Increase postMessage timeout for sandbox back to 3s

src/sandbox/messenger/api.ts
- Closes https://github.com/pixiebrix/pixiebrix-extension/issues/8821
- We were retrying the sandbox message for for e.g. failed javascript errors instead of throwing the original error
=> Only retry sandbox postMessage on TimeoutErrors

src/analysis/analysisTypes.ts, src/analysis/analysisVisitors/conditionAnalysis.test.ts, src/analysis/analysisVisitors/conditionAnalysis.ts, src/bricks/types.ts, src/components/form/makeFieldActionForAnnotationAction.test.tsx, src/components/form/makeFieldActionForAnnotationAction.ts, src/pageEditor/store/analysisManager.ts, src/pageEditor/tabs/effect/AdvancedLinks.test.tsx, src/pageEditor/tabs/effect/AdvancedLinks.tsx, src/runtime/runtimeUtils.test.ts, src/runtime/runtimeUtils.ts, src/tsconfig.strictNullChecks.json
- Closes #8828
- Add lint rules for constant brick conditions
- 🐛 Fixes bug in `makeFieldActionForAnnotationAction` where state wasn't being updated
- 🐛 Fixes bug in brick condition summary where literal values were not being displayed properly
- The warning shows when the user first toggles into the field to write a text template. It's a bit annoying as the warning shifts the field down
- https://www.loom.com/share/96ad75e0bf804bca85660069b2c461e5?sid=d8e5b36f-2b5a-4c84-8628-afc422ab023f
=> #8828: constant brick condition lint and analysis action bug fixes

.github/workflows/ci.yml, end-to-end-tests/tests/pageEditor/brickActions.spec.ts
- This PR adds a flag to slow down a test in the `brickActions.spec.ts` file. This was the cause for some flaky tests since it was right on the edge of 60s.
- Also fixes the concurrency setting on the github CI workflow so it only cancels workflows on the same PR.
=> mark brickActions as a slow test

src/pageEditor/layout/EditorLayout.tsx, src/pageEditor/panes/insert/InsertPane.tsx, src/pageEditor/store/editor/editorSelectors.ts
- Quick followup to https://github.com/pixiebrix/pixiebrix-extension/pull/8820
- Related to the `inserting` --> `insertingStarterBrickType` property name change on the `editor` redux slice
- Slight refactoring to make code at call sites more clear with intentions, split into two different selectors
=> DX - Quick followup to clean up `insertingStarterBrick` call site

pixiebrix-extension.iml, src/analysis/analysisVisitors/conditionAnalysis.test.ts, src/analysis/analysisVisitors/httpRequestAnalysis.test.ts, src/analysis/analysisVisitors/httpRequestAnalysis.ts, src/analysis/analysisVisitors/outputKeyAnalysis.test.ts, src/analysis/analysisVisitors/requestPermissionAnalysis.test.ts, src/analysis/analysisVisitors/requestPermissionAnalysis.ts, src/analysis/analysisVisitors/templateAnalysis.test.ts, src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts, src/bricks/effects/AddQuickBarAction.tsx, src/bricks/effects/tourEffect.ts, src/bricks/transformers/remoteMethod.ts, src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts, src/components/form/makeFieldActionForAnnotationAction.test.tsx, src/pageEditor/tabs/editTab/editHelpers.test.ts, src/runtime/pipelineTests/pipelineTestHelpers.ts, src/testUtils/factories/traceFactories.ts
- Rename BLOCK_ID to BRICK_ID
- Exclude `scripts/bin` from search
=> Rename `BLOCK_ID` to `BRICK_ID` and exclude `scripts/bin` from IDE search

end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts, end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts-snapshots/mod-editor-pane-behavior/updated-metadata.diff
- Part of #8853
- This PR introduces a new end-to-end test for the mod editor pane behavior in the page editor. The test checks the visibility of the mod editor pane, and the modification of mod metadata. The test also verifies the updated mod metadata against a snapshot.
- Editing the mod input options
=> #8853: mod editor pane metadata e2e tests

src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.test.ts, src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.ts, src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.tsx, src/pageEditor/tabs/editTab/dataPanel/tabs/__snapshots__/ModVariablesTab.test.tsx.snap
- Part of #8856 
- 🐛  Fixes bugs in https://github.com/pixiebrix/pixiebrix-extension/pull/8857
- Don't show standalone mod warning in the Mod Variables tab
- Don't generate analysis warnings for page state use in standalone mod components 
=> #8856: fix display of mod variables and page state warnings for standalone mod components

src/analysis/analysisVisitors/selectorAnalysis.test.ts, src/analysis/analysisVisitors/selectorAnalysis.ts
- Closes #8875
- Show info annotation if selector literal contains template
- Consider making it a warning annotation. Is currently "info" because `{{` could theoretically appear in the attribute strings or in a `:contains` selector if it's actually in the value being matched
=> #8875: show info annotation if selector literal contains template characters

src/components/selectionToolPopover/SelectionToolPopover.tsx
- #8864: fixes select similar
- Inference was failing because the multi-select tool was passing a click event with the elements
- Playwright POM/tests for selection tool: https://github.com/pixiebrix/pixiebrix-extension/issues/8878
=> #8864: fix select similar in selection tool

scripts/manifest.mjs, src/activation/getActivatedModComponentFromDefinition.ts, src/bricks/readers/DocumentReader.ts, src/contentScript/lifecycle.test.ts, src/contrib/automationanywhere/RunApiTask.test.ts, src/data/service/errorService.ts, src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx, src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx, src/extensionConsole/pages/settings/useDiagnostics.ts, src/mods/useMods.test.ts, src/pageEditor/hooks/useUpsertModComponentFormState.ts, src/runtime/reducePipeline.ts, src/sidebar/DefaultContent.test.tsx, src/store/enterprise/managedStorage.test.ts, src/store/enterprise/managedStorage.ts, src/store/extensionsMigrations.ts, src/testUtils/factories/databaseFactories.ts, src/testUtils/factories/deploymentFactories.ts, src/testUtils/factories/modComponentFactories.ts, src/testUtils/factories/modDefinitionFactories.ts, src/testUtils/factories/stringFactories.ts, src/types/helpers.ts, src/types/modComponentTypes.ts, src/utils/deploymentUtils.test.ts, src/utils/modUtils.test.ts, src/utils/timeUtils.ts
- Standardize timestamp creation
- Refine timestamp types on `ActivatedModComponentBase`
- Prep work for https://github.com/pixiebrix/pixiebrix-extension/pull/8891
=> Standardize timestamp creation

src/__mocks__/connected-react-router.js, src/background/deploymentUpdater.ts, src/contentScript/lifecycle.ts, src/extensionConsole/pages/UpdateBanner.tsx, src/extensionConsole/pages/deployments/DeploymentModal.test.tsx, src/extensionConsole/pages/deployments/DeploymentModal.tsx, src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx, src/extensionConsole/pages/deployments/DeploymentsContext.tsx, src/extensionConsole/pages/deployments/activateDeployments.ts, src/extensionConsole/pages/deployments/useAutoDeploy.test.ts, src/extensionConsole/pages/deployments/useAutoDeploy.ts, src/utils/deploymentUtils.ts
- Closes #8744
- Closes #8158
This change fixes a bug related to mod deployments not properly reflecting the new deployed mod immediately in open tabs. It ensures the mod state is persisted before continuing after activating in the extension console so the content script can immediately pick up the changes 
Some renaming and added documentation was done for clarity surrounding related code.
- E2E test coverage
=> 8744: fix: Deactivated Sidepanel deployments not removed from Mod Launcher

end-to-end-tests/tests/runtime/insertAtCursor.spec.ts, src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx, src/extensionConsole/pages/deployments/activateDeployments.ts, src/extensionConsole/pages/deployments/useDeactivateUnassignedDeploymentsEffect.ts
- Fixes #8925 
This behavior change will automatically reload all tabs when the user loads the extension console with activated mods which should be removed.
https://www.loom.com/share/a4459c4bba704a29af1226d8bf54ffcc
- playwright test
=> 8925: fix sidebar not being updated on deployment group membership removal

src/contentScript/focusCaptureDialog.ts
- Part of #8933
- Allows clicking the button for the focus capture dialog (partial mitigation for https://pixiebrix.slack.com/canvas/C07DGPVQJKH)
=> #8933: adds mousedown handler to solve document mousedown handler bug

src/background/browserAction.ts, src/background/toolbarBadge.ts, src/bricks/effects/setToolbarBadge.test.ts, src/bricks/effects/setToolbarBadge.ts, src/platform/platformTypes/badgeProtocol.ts, src/sidebar/ConnectedSidebar.tsx, src/sidebar/Tabs.test.tsx, src/sidebar/sidebarSelectors.ts, src/store/sidebar/sidebarSlice.ts, src/store/sidebar/sidebarUtils.ts, src/store/sidebar/utils.ts, src/tsconfig.strictNullChecks.json, src/types/modComponentTypes.ts, src/utils/modUtils.ts, src/utils/sidePanelUtils.ts
- Closes #8421 
- Defaults the open/active panel when the user opens the sidebar panel with a badge set by a mod
- Does not use `SessionMap` which persists across background worker reloads because it was causing Chrome to lose the user gesture
- Uses the sidebar tab URL search param to set the initial panel vs. attempting to get the `webext-messaging` sequence correct. The Show Sidebar brick uses `showSidebar` and `updateSidebar` which isn't available to the background service worker
- Can't write Playwright test because we can't click the toolbar icon?
- https://www.loom.com/share/36ec55d8a4c54c3cb7c68579d6aa824d
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad8 …
=> #8421: default sidebar to a panel for mod that set the badge

.eslintrc.js, src/auth/featureFlagStorage.ts, src/components/quickBar/QuickBarApp.tsx, src/hooks/useFlags.test.tsx, src/hooks/useFlags.ts, src/pageEditor/hooks/useAddNewModComponent.ts, src/pageEditor/modListingPanel/AddStarterBrickButton.tsx
- Fix starter brick feature flag detection. Bug was preventing beta users from creating the dynamic quick bar starter brick
- Add eslint rule to force using useFlags in an React context
- Fix `useFlags` to return `async` methods for flag checks vs. potentially relying on uninitialized state
- Have `useFlags` fallback to the cached flags while the remote query is fetching / if the remote query fails. (Not possible because the methods are synchronous 🤷 )
- Introduce a constants file for feature flags similar to `Events` constant
=> Fix beta starter brick feature flag detection

src/data/service/errorService.ts, src/tinyPages/offscreen.ts
- Avoids calling the broken chrome api `runtime.getContexts()` that is crashing the browser
- Fixes a `window` reference in the `reportError` code chain that is now being executed in the service worker, which does not have `window` available
_Example debug logs showing behavior for two errors in a row_:
_Example logs for two errors in quick succession to force the promise concurrency handling_:
=> Prevent crash with `getContexts` and fix the window reference in `reportError`

src/components/ellipsisMenu/EllipsisMenu.module.scss, src/components/ellipsisMenu/EllipsisMenu.tsx
- Closes #8924 
- Makes the styling on EllipsisMenu consistent with our bootstrap dropdown menus
- I don't agree with this approach of implementing this via CSS module (it's not future-proof); I would have implemented this by tweaking the global theme. But going with this approach for now for speed & since other approaches I can think of would be equally-gross
=> #8924: Override styling on EllipsisMenu

src/analysis/analysisVisitors/conditionAnalysis.test.ts, src/analysis/analysisVisitors/conditionAnalysis.ts, src/bricks/exampleBrickConfigs.ts, src/bricks/transformers/controlFlow/IfElse.test.ts, src/bricks/transformers/controlFlow/IfElse.ts
- If Else brick allows undefined condition at runtime (required for passing potentially undefined variable directly as condition)
- Warn on constant if-else conditions
=> Allow undefined condition value and warn on constant if-else conditions

src/components/fields/schemaFields/widgets/ArrayWidget.module.scss, src/components/fields/schemaFields/widgets/ArrayWidget.test.tsx, src/components/fields/schemaFields/widgets/ArrayWidget.tsx, src/components/fields/schemaFields/widgets/__snapshots__/ArrayWidget.test.tsx.snap, src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap, src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap, src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap, src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap, src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
- Closes #8827
- Add support for re-ordering array items
- Modifies `ArrayWidget`, so works in Brick Configuration, Form Builder, etc.
=> #8827: add support for re-ordering array items in the Page Editor

src/icons/duplicate.svg, src/pageEditor/documentBuilder/hooks/useDuplicateElement.test.ts, src/pageEditor/documentBuilder/hooks/useDuplicateElement.ts, src/pageEditor/documentBuilder/preview/flaps/ActiveElementFlap.tsx, src/pageEditor/starterBricks/pipelineMapping.ts, src/tsconfig.strictNullChecks.json
- Add duplicate element button to document builder design view. Duplicates the element within the container
- Copy/paste is significantly harder, due to needing to provide a paste target and handling pasting bricks across mods
- See note on why we can't auto-select the new element. (It's the same reason we don't auto-select new elements added via the ellipsis dropdown; and probably why we don't auto-select the new element when pasting a brick)
- For "duplicate" vs. "clone" terminology. Prior art seems to indicate "duplicate" should be used for creating a copy that's independent of the original. Whereas clone sometimes is used to mean it's linked to the original
- https://www.loom.com/share/708199f4265a46e2a59e1af1860e6639?sid=cfafcdf6-c808-4225-aa5d-7f6fe24727fd
For more information on …
=> Add "duplicate" element button to document builder

end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts, end-to-end-tests/tests/pageEditor/logsPane.spec.ts, src/components/logViewer/LogCard.tsx, src/components/logViewer/logSlice.ts, src/components/logViewer/logViewerTypes.ts, src/extensionConsole/pages/mods/modals/modLogsModal/ModLogsModal.tsx, src/extensionConsole/pages/packageEditor/useLogContext.ts, src/pageEditor/panes/EditorPane.tsx, src/pageEditor/panes/ModEditorPane.tsx, src/types/loggerTypes.ts
- Closes #8587 
- Fixes a bad MessageContext state pushed to the store in EditorPane
https://www.loom.com/share/018fd74069ef4e6298124ab912983cf8
=> #8587: Fix bad logging MessageContext

src/components/jsonTree/JsonTree.tsx, src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap, src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.module.scss, src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.tsx, src/pageEditor/tabs/editTab/dataPanel/__snapshots__/BrickDataPanel.test.tsx.snap, src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataTabJsonTree.test.tsx.snap, src/pageEditor/tabs/editTab/dataPanel/__snapshots__/StarterBrickDataPanel.test.tsx.snap, src/pageEditor/tabs/editTab/dataPanel/dataPanelTabs.module.scss
=> #8962: scope label width CSS to fix visual regression

src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
- Renames "Preview" tab name to "Design" in Mod Options form in Page Editor for consistency with the data panel
- FLUP to https://github.com/pixiebrix/pixiebrix-extension/pull/8895
- Not required for 2.0.7, but low risk if we want to pull it in
=> Update mod options form tab name to match form builder

src/auth/authUtils.ts, src/background/deploymentUpdater.test.ts, src/background/starterMods.test.ts, src/contentScript/loadActivationEnhancementsCore.test.ts, src/mods/utils/mapStandaloneModDefinitionToModDefinition.ts, src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.ts, src/pageEditor/layout/EditorLayout.tsx, src/pageEditor/modListingPanel/ModListingPanel.tsx, src/store/extensionsMigrations.test.ts, src/store/extensionsMigrations.ts, src/store/extensionsStorage.test.ts, src/store/extensionsStorage.ts, src/store/extensionsTypes.ts, src/tsconfig.strictNullChecks.json
- Closes #8979 
We'll change the `_recipe` field to `modMetadata`, and make the field required in both form states and activated mod components, in the next PR
=> #8979 Migrate standalone mod components

src/runtime/renderers.test.ts, src/runtime/renderers.ts, src/starterBricks/button/buttonStarterBrick.test.ts, src/starterBricks/button/buttonStarterBrick.ts, src/tsconfig.strictNullChecks.json, src/utils/domUtils.test.ts, src/utils/domUtils.ts
- Closes #8526 
- Modifies renderers to return blank if nullish template provided
- I was unable to replicate the browser crash, so this is just trying to avoid the likely cause
- Related to https://github.com/pixiebrix/pixiebrix-extension/pull/8981
- The configs produced by the Page Editor are not validated, and the Page Editor removes empty values so the nullness annotations on the definition types might are not accurate: https://github.com/pixiebrix/pixiebrix-extension/blob/a7603b8f1ebf43762d3adeb4befebbcc58866784/src/pageEditor/starterBricks/base.ts#L377-L377
=> #8526: fallback button starter brick on invalid template

src/components/AsyncStateGate.tsx, src/pageEditor/tabs/MatchRulesSection.test.tsx, src/pageEditor/tabs/modMetadata/ModMetadataEditor.test.tsx, src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx, src/tsconfig.strictNullChecks.json, src/types/modComponentTypes.ts
- Closes #8860
- Fixes bug where initial values in mod metadata form were being set to the latest metadata, not the metadata from the activated mod
=> #8860: show activated mod metadata in mod metadata form

src/auth/featureFlags.ts, src/sidebar/sidebar.tsx, src/telemetry/performance.ts, src/utils/urlUtils.ts
- Closes #9028
- Stacked on https://github.com/pixiebrix/pixiebrix-extension/pull/9018 (review that PR first)
- See discussion of checking for PixieBrix domain vs. attempting to be more precise about if the sidebar is in the onboarding flow
- If the user redirects the tab to another page, it will still be recorded. Behavior is OK because UI recordings are masked: https://github.com/pixiebrix/pixiebrix-extension/blob/4b6f2ed5e81e8941e69f4e9606f16a3cf128d0a1/src/telemetry/performance.ts#L88-L88
=> #9028: flag to force sidebar RUM recording during onboarding

src/auth/useRequiredPartnerAuth.test.tsx, src/auth/useRequiredPartnerAuth.ts, src/data/model/UserMilestone.ts, src/extensionConsole/pages/activateMod/ActivateModCard.tsx, src/hooks/useMilestones.test.ts, src/hooks/useMilestones.ts, src/testUtils/factories/milestoneFactories.ts, src/tsconfig.strictNullChecks.json
- Introduce milestone constant
- Next PR in sequence of moving magic constants to enums and centralizing values that correspond to constants in external services
- Compare to structure in `pixiebrix-app`: https://github.com/pixiebrix/pixiebrix-app/blob/b780441b130d7bd138498efbeffa5358495dd5bb/pixiebrix-app/src/pages/onboarding/milestones.ts#L4-L4
- The app has its own useMilestones hook: https://github.com/pixiebrix/pixiebrix-app/blob/b780441b130d7bd138498efbeffa5358495dd5bb/pixiebrix-app/src/hooks/useMilestones.tsx#L6-L6
=> Introduce milestones constant

src/__mocks__/@/auth/featureFlagStorage.ts, src/activation/useActivateModWizard.test.tsx, src/activation/useActivateModWizard.ts, src/activation/useOrganizationActivationPolicy.ts, src/background/welcomeMods.test.ts, src/background/welcomeMods.ts, src/hooks/useFlags.ts, src/tsconfig.strictNullChecks.json, src/utils/asyncStateUtils.ts
- Closes #9039 
- Restricts public marketplace mod activation in activation wizard and welcome mods
- I just used the existing error handling because the situation should be uncommon so doesn't need a special UX
=> #9039: restrict public marketplace activation

src/pageEditor/layout/ModComponentFormStateWizard.tsx
- Makes a small TS improvement by removing a unnecessary non null assertion.
=> remove a non-null assertion for ModComponentFormStateWizard

src/auth/RequireAuth.tsx, src/extensionConsole/App.tsx, src/extensionConsole/pages/settings/AdvancedSettings.tsx
- Follow up to #9047
- Attempting to fix the broken rainforest tests involved with clearing the token
- We'll still need to update the rainforest test because it won't be necessary anymore to click the mods tab
=> Bug fix - Navigate to mods tab when extension token is cleared

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts, end-to-end-tests/tests/extensionConsole/activation.spec.ts, end-to-end-tests/tests/pageEditor/copyMod.spec.ts
- Part of #9087
- Noticed a race with some of the flaky tests where the test runner would click the activation button before the form was pre-populated with the built-in integration
- The proper way to fix would be to disable the button before the form is valid, but I found that to be non-trivial
- This does not address all of #9087
=> #9087 Wait for built-in integration before activating mod in e2e test

src/extensionConsole/pages/mods/ModsPageSidebar.tsx, src/extensionConsole/pages/mods/listView/ListView.tsx
- Fixes the bug describe in #9095 
=> #9095 Fix Mods page table filters (other than active)

src/sidebar/ConnectedSidebar.test.tsx, src/sidebar/ConnectedSidebar.tsx, src/sidebar/sidebar.tsx, src/sidebar/telemetryConstants.ts, src/telemetry/performance.test.ts, src/telemetry/performance.ts
- Fixes #9093
This change also includes adding more global context to sidebar rum events, noting what the connected url for the sidebar and when navigation events occur.
I didn't record a demo, but just to note I did verify that recordings are forced to start on a fresh session when opening the sidebar on the welcome, even after having previously opened an extension console page (thus having already started the session recording)
Check out this datadog session I recorded in testing for this behavior + the new context props
https://app.datadoghq.com/rum/sessions?query=%40type%3Asession%20%40application.id%3Ac343faf6-bbdf-4a12-8793-40af69f75b69%20%40usr.email%3Aeduardo%2Btest%40pixiebrix.com&agg_m=count&agg_m_source=base&agg_t=count&cols=&event=AgAAAZHHxFulrXSX7gAAAAAAAAAYAAAAAEFaSEh4RnVsQUF …
=> #9093 force session replay recording in sidebar welcome page

src/bricks/effects/assignModVariable.test.ts, src/bricks/effects/assignModVariable.ts, src/bricks/effects/pageState.test.ts, src/bricks/renderers/customForm.test.tsx, src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts, src/bricks/transformers/controlFlow/WithAsyncModVariable.ts, src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts, src/contentScript/contentScriptPlatform.ts, src/contentScript/messenger/registration.ts, src/contentScript/stateController.test.ts, src/contentScript/stateController.ts, src/platform/platformTypes/stateProtocol.ts, src/runtime/extendModVariableContext.test.ts, src/runtime/extendModVariableContext.ts, src/runtime/pipelineTests/modVariableContext.test.ts, src/starterBricks/sidebar/sidebarStarterBrick.test.ts
- Part of #9105
- Move state controller to content script folder in anticipation of content script-specific logic coming out of https://github.com/pixiebrix/pixiebrix-extension/pull/9106
- Tests use the content script platform by default
- Make get/set async
=> #9105: move state controller to content script

src/bricks/effects/assignModVariable.test.ts, src/bricks/effects/assignModVariable.ts, src/bricks/renderers/customForm.test.tsx, src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts, src/bricks/transformers/controlFlow/WithAsyncModVariable.ts, src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts, src/contentScript/pageEditor/runBrickPreview.ts, src/contentScript/pipelineProtocol/runMapArgs.ts, src/contentScript/stateController.test.ts, src/contentScript/stateController.ts, src/extensionConsole/pages/mods/ModsPage.tsx, src/platform/platformTypes/stateProtocol.ts, src/runtime/extendModVariableContext.test.ts, src/runtime/extendModVariableContext.ts, src/runtime/pipelineTests/modVariableContext.test.ts, src/runtime/reducePipeline.ts, src/starterBricks/sidebar/sidebarStarterBrick.test.ts
- Part of #9105 
- FLUP to https://github.com/pixiebrix/pixiebrix-extension/pull/9120
- Makes the getState/setState methods async in anticipation of https://github.com/pixiebrix/pixiebrix-extension/pull/9106
- The main consideration is that page state could be updated between get + set calls. So WithAsyncModVariable's logic needed to be rewritten to ensure a valid async state shape
=> #9105: make getState and setState async

end-to-end-tests/pageObjects/extensionsShortcutsPage.ts, end-to-end-tests/tests/extensionConsole/activation.spec.ts, end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts, end-to-end-tests/tests/pageEditor/copyMod.spec.ts, end-to-end-tests/tests/pageEditor/liveEditing.spec.ts, end-to-end-tests/tests/regressions/sidebarLinks.spec.ts, end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts, end-to-end-tests/tests/runtime/sidebar/sidebarAuth.spec.ts, end-to-end-tests/utils.ts
- Part of #9087
- Temporarily skip the list of tests that are failing on the pre-release browser workflow for some reason. Follow-up ticket to investigate and fix is here: https://github.com/pixiebrix/pixiebrix-extension/issues/9125
=> #9087 Skip tests for pre-release e2e workflow on msedge/msedge-beta

src/activation/PersonalDeploymentField.tsx, src/activation/SynchronizeBody.tsx, src/activation/useActivateModWizard.test.tsx, src/activation/useActivateModWizard.ts, src/activation/wizardTypes.ts, src/auth/featureFlags.ts, src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx, src/extensionConsole/pages/activateMod/ActivateModPage.test.tsx, src/extensionConsole/pages/activateMod/IntegrationsBody.tsx, src/extensionConsole/pages/activateMod/__snapshots__/ActivateModPage.test.tsx.snap, src/hooks/auth.test.ts, src/hooks/auth.ts, src/sidebar/activateMod/ActivateMultipleModsPanel.tsx, src/testUtils/appApiMock.ts
- Part of #9091
- This set of changes includes the UI for the new personal synchronize settings section in the mod activation page
- Includes feature flag gating
- Includes validation to display an error if the user attempts to activate with a local integration selected
- No actual functionality to create the personal deployment, just focusing on the UI and that the form state is correct in this change
- wizardStateFactory is getting a bit unwieldy with this change adding two new prop arguments. Is now a good time to consider refactoring? 
- Actually making the API request to the backend to create the personal deployment when this option is true.
- UI for the sidebar mod panel activation (not done in this PR)
For more information on …
=> #9091: Create user deployment UI

.github/workflows/ci.yml, .pre-commit-config.yaml, .secrets.baseline, package.json
I keep forgetting to run eslint before pushing up my commits and then fix them after realizing they failed the PR CI. Let's catch eslint errors at precommit by checking the staged files.
Linting a few staged files takes about 8 seconds, which I think is worth the cost.
=> precommit eslint hook

src/extensionConsole/pages/mods/Status.test.tsx, src/extensionConsole/pages/mods/Status.tsx, src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.ts, src/extensionConsole/pages/mods/utils/buildModViewItems.ts, src/testUtils/factories/modViewItemFactory.ts, src/types/modTypes.ts
- Closes #9103
- Also refactors hasUpdate logic in buildGetModVersionStatus
https://www.loom.com/share/a16175dd5bb945309f325b110ef78559
=> #9103 No update button for pinned deployments

src/components/AsyncButton.tsx
- Part of https://github.com/pixiebrix/pixiebrix-app/issues/5766
- Need to be able to use AsyncButton in the TrialAwareComponent button in App to support prevent admins of expired teams deleting the expired team
- The TrialAwareComponent needs to be able to pass a ref to the AsyncButton
=> Allow AsyncButton to accept a ref

src/sandbox/messenger/api.ts, src/utils/injectIframe.tsx, src/utils/postMessage.ts
- Part of #9150 
- While we haven't identified root cause of #9150, this PR
1. Increases the timeout associated with injecting & sending messages to the sandbox from 3s to 5s (to address the hypothesis that this error is happening on slow machines) and
2. Introduces a more specific `SandboxInjectionError` to be explicit about the cause of the sandbox errors we are seeing (to rule out the less-strong hypothesis that the sandbox is getting removed from the page more often than before)
- See notion document for context and bug triage notes https://www.notion.so/pixiebrix/Nunjucks-Error-Spike-0283abe59c6a48ad96f5f84715516ec3?showMoveTo=true&saveParent=true
=> #9150 Introduce SandboxInjectionError and increase sandbox timeouts to 5s

src/auth/featureFlags.ts, src/background/messenger/api.ts, src/contentScript/contentScriptPlatform.ts, src/extensionPages/extensionPagePlatform.ts, src/starterBricks/trigger/triggerStarterBrick.ts, src/telemetry/logging.test.ts, src/telemetry/logging.ts
- Part of #9169
- Adds some additional logging to idb logging database operations
- Adds a feature flag for disabling idb logging
- Method renaming for clarity
https://github.com/pixiebrix/pixiebrix-extension/issues/9169
=> 9169 indexeddb logging disable flag + more debug logging

src/auth/featureFlags.ts, src/telemetry/logging.ts
- Part of #9169
- adds abort timeout to sweep idb function
- adds blocked handling to openDB method
- Tested by intentionally removing db.close() methods everywhere, and by adding an infinite loop in sweep
The rest of the checklist in https://github.com/pixiebrix/pixiebrix-extension/issues/9169
=> 9169 idb log durability and timeout changes

end-to-end-tests/tests/runtime/modVariables/variableSync.spec.ts, end-to-end-tests/utils.ts, src/background/background.ts, src/contentScript/contentScriptPlatform.ts, src/contentScript/stateController.test.ts, src/contentScript/stateController.ts, src/platform/platformTypes/stateProtocol.ts, src/platform/state/stateTypes.ts, src/starterBricks/types.ts, src/testUtils/platformMock.ts
- Closes #9154 
- Stacked on: https://github.com/pixiebrix/pixiebrix-extension/pull/9138
- See E2E test
- Delete a mod session's variables when the a mod is deactivated. That will require providing event contexts can listen to for when a mod is deactivated
=> #9154: mod variable session sync (2/3)

src/telemetry/logging.test.ts, src/telemetry/logging.ts
- Fixes a bug with the abort timeout in the sweepLogs function where it was not being executed due to improper `this` scope.
- See [this datadog trace](https://app.datadoghq.com/logs?query=service%3Apixiebrix-browser-extension%20%40session_id%3Adaa570c4-9748-43b6-a6ad-740cedf97e05%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZIgFWNRAACDYisbDwODfQAA&event=AgAAAZIgEFbPdc-MfAAAAAAAAAAYAAAAAEFaSWdFTTlKQUFETDB0QTBzNS0zZGdBQQAAACQAAAAAMDE5MjIwMTMtZmMxOC00OWM0LTkxNTMtODQ2OTc2OWE0OWZl&fromUser=true&issueId=b79d14fc-776d-11ef-8147-da7ad0900002&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1727100836571&to_ts=1727115236571&live=true)
- Tested by manually introducing an infinite loop in the sweeplogs and verifying it is …
=> fix sweepLogs abort functionality

end-to-end-tests/tests/runtime/localIntegrations.spec.ts, end-to-end-tests/tests/telemetry/errors.spec.ts, src/components/errors/NetworkErrorDetail.tsx, src/data/service/errorService.ts, src/data/service/requestErrorUtils.ts, src/errors/clientRequestErrors.ts, src/errors/networkErrorHelpers.ts, src/telemetry/logging.ts, src/telemetry/reportError.test.ts, src/telemetry/reportError.ts, src/utils/enrichAxiosErrors.ts
- Closes of #9198
- This PR was reviewed synchronously with @grahamlangford
=> #9198: properly serialize axios errors in report error, and skip non mod logs for idb

src/store/enterprise/managedStorageTypes.ts
- Fix JSON Schema documentation for `disableBrowserWarning` because MS Edge is now officially supported
=> Fix managed schema JSON Schema documentation for `disableBrowserWarning`

src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts, src/bricks/transformers/controlFlow/WithCache.test.ts, src/bricks/transformers/controlFlow/WithCache.ts, src/bricks/transformers/getAllTransformers.ts, src/development/headers.test.ts, src/runtime/pipelineTests/pipelineTestHelpers.ts
- Closes #9202 
- PR for demos/deciding if we like the technical approach and brick ergonomics: https://www.notion.so/pixiebrix/Mod-variable-syncing-across-Page-Load-and-all-Frames-in-runtime-and-workshop-c533b56bc9ed4f6ea7aa8502439c632a?pvs=4#10143b21a25380b2aae2ef4d29b6eb82
- For reference/prior art, the Django cache framework API for `get_or_set`: https://docs.djangoproject.com/en/5.1/topics/cache/#django.core.cache.cache.get_or_set
- Open question on expiresAt behavior (should it be set on the leading edge of the request, or after the value comes back): https://www.notion.so/pixiebrix/Mod-variable-syncing-across-Page-Load-and-all-Frames-in-runtime-and-workshop-c533b56bc9ed4f6ea7aa8502439c632a?pvs=4#10c43b21a2538056adc1c23ee89238e4
Potential …
=> #9202: add with cache brick with memoization/expiry

end-to-end-tests/pageObjects/extensionConsole/modsPage.ts, src/registry/packageRegistry.ts, src/telemetry/logging.test.ts, src/telemetry/logging.ts, src/telemetry/reportToApplicationErrorTelemetry.test.ts, src/telemetry/reportToApplicationErrorTelemetry.ts, src/telemetry/trace.ts, src/utils/idbUtils.ts
- Closes #9221 
- Still rethrows the errors, which means some errors will likely be double-reported
- In `logging.ts`, we swallow some of the errors but not others
- @fungairino, what criteria did you use to determine which errors should be swallowed?
=> #9221: Attach db name and operation name to idb errors

src/contentScript/contentScriptPlatform.test.ts, src/contentScript/contentScriptPlatform.ts, src/extensionPages/extensionPagePlatform.test.ts, src/extensionPages/extensionPagePlatform.ts, src/platform/platformTypes/debuggerProtocol.ts, src/runtime/reducePipeline.ts
- Part of #9211 
- `logValues` only impacts whether we append debug logs to the LOG idb database, so we still need to clear traces
- Do we really need to clear traces in the content script platform? 
- I left it in because I wasn't certain if it's necessary
=> Only clear mod component debug logs if logValues is enabled

src/background/telemetry.ts, src/utils/idbUtils.ts
=> Implement withIdbErrorHandling for telemetry database

src/background/telemetry.ts, src/registry/packageRegistry.ts, src/telemetry/logging.test.ts, src/telemetry/logging.ts, src/telemetry/trace.ts, src/utils/idbUtils.ts
=> #9211 Retry on failed to read large indexeddb value

src/telemetry/lexicon.ts
=> Add lexicon entries for BrickCommentsUpdate, BrowserActionRestrictedUrl, and CustomUserEvent

src/pageEditor/hooks/useClearModChanges.ts, src/pageEditor/hooks/useClearModComponentChanges.ts, src/pageEditor/hooks/useCreateModFromUnsavedMod.ts, src/pageEditor/hooks/useSaveMod.test.ts, src/pageEditor/hooks/useSaveMod.ts, src/pageEditor/modListingPanel/ActionMenu.stories.tsx, src/pageEditor/modListingPanel/ActionMenu.tsx, src/pageEditor/modListingPanel/DraftModComponentListItem.tsx, src/pageEditor/modListingPanel/ModComponents.tsx, src/pageEditor/modListingPanel/ModListItem.test.tsx, src/pageEditor/modListingPanel/ModListItem.tsx, src/pageEditor/modListingPanel/ModListingPanel.test.tsx, src/pageEditor/store/editor/editorSlice.ts, src/store/modComponents/modComponentSlice.ts, src/store/sessionChanges/sessionChangesListenerMiddleware.ts, src/telemetry/events.ts, src/telemetry/lexicon.ts
- Closes #9239
- Rename "Reset" to "Clear Changes" (include internal uses of reset)
- Always show, but show as disabled for mods/mod components that have never been saved before
- The "Clear Changes" terminology is better than "Reset". In the future, we might consider "Rollback" or different single word action in the future. (e.g., the Git plugin for IntelliJ uses Rollback)
=> #9239: rename "reset" to "clear changes" in the Page Editor

src/pageEditor/modListingPanel/DraftModComponentListItem.tsx, src/pageEditor/modListingPanel/ModActionMenu.tsx, src/pageEditor/modListingPanel/ModComponentActionMenu.stories.tsx, src/pageEditor/modListingPanel/ModComponentActionMenu.tsx, src/pageEditor/modListingPanel/ModComponents.tsx, src/pageEditor/modListingPanel/ModListItem.test.tsx, src/pageEditor/modListingPanel/ModListItem.tsx, src/pageEditor/modListingPanel/ModListingPanel.test.tsx, src/pageEditor/store/editor/editorSlice.test.ts, src/pageEditor/store/editor/editorSlice.ts
- Closes #9241
- Stacked on https://github.com/pixiebrix/pixiebrix-extension/pull/9240
- Add "Duplicate" action to mod component 3-dot menu in the Page Editor
- Refactoring:
- Splits `ModActionsMenu` and `ModComponentActionsMenu` to make it easier to reason about which actions appear in each menu
- Removes unused `disabled` prop, and mark props as required where possible
- Playwright tests aren't run on CI because this is stacked on another PR. There might be bugs the Playwright will catch
=> #9241: add "Duplicate" action to mod components

src/activation/useActivateModWizard.test.tsx, src/background/deploymentUpdater.test.ts, src/background/modUpdater.test.ts, src/extensionConsole/pages/mods/ModsPage.test.tsx, src/extensionConsole/pages/mods/modsPageSelectors.ts, src/extensionConsole/pages/mods/utils/buildGetModActivationStatus.test.ts, src/extensionConsole/pages/mods/utils/buildGetModActivationStatus.ts, src/extensionConsole/pages/mods/utils/buildGetModSharingSource.test.ts, src/extensionConsole/pages/mods/utils/buildGetModSharingSource.ts, src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.test.ts, src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.ts, src/extensionConsole/pages/mods/utils/buildModsList.test.ts, src/extensionConsole/pages/mods/utils/buildModsList.ts, src/extensionConsole/pages/settings/useDiagnostics.ts, src/modDefinitions/modDefinitionsSelectors.ts, src/mods/hooks/useModPermissions.ts, src/sidebar/activateMod/RequireMods.tsx, src/store/modComponents/modComponentSelectors.ts, src/store/modComponents/modInstanceUtils.ts, src/testUtils/factories/modComponentFactories.ts, src/testUtils/factories/modDefinitionFactories.ts, src/testUtils/factories/modInstanceFactories.ts, src/testUtils/factories/registryFactories.ts, src/types/deploymentTypes.ts, src/types/modInstanceTypes.ts, src/utils/modUtils.ts, src/validators/schemaValidator.test.ts
- Context: https://www.notion.so/pixiebrix/Return-mod-instance-from-slice-selectors-instead-of-returning-activated-mod-components-fff43b21a25381269578d4845535e37e?pvs=4
- Stacked on https://github.com/pixiebrix/pixiebrix-extension/pull/9190
- Use `ModInstance` type on the mods screen
- Other refactoring:
- Split the sharing metadata factory to make usage clearer
Future work before hitting the Page Editor / migrating the state:
1. Update modUpdater code: https://github.com/pixiebrix/pixiebrix-extension/pull/9192
Other future work:
- Review selectors to ensure using reselect or returning null/undefined instead of a fresh object: https://github.com/pixiebrix/pixiebrix-extension/issues/9251#issue-2571936038
[code review …
=> Slice 3: Use `ModInstance` type on the mods screen (3/3)

src/background/deploymentUpdater.ts, src/background/modUpdater.test.ts, src/background/modUpdater.ts, src/background/utils/deactivateMod.test.ts, src/background/utils/deactivateMod.ts
- Context: https://www.notion.so/pixiebrix/Return-mod-instance-from-slice-selectors-instead-of-returning-activated-mod-components-fff43b21a25381269578d4845535e37e?pvs=4
- Stacked on https://github.com/pixiebrix/pixiebrix-extension/pull/9191
- Refactors mod updater code to use `ModInstance` type
Continue gradual work toward eliminating mod components on the slice boundary:
- Replace remaining occurrences of `selectActivatedModComponents`, `selectGetModComponentsForMod`, `selectModHasAnyActivatedModComponents`, etc.
- Replace component slice actions taking mod components with actions taking mod instances
[code review principles doc](https://www.notion.so/pixiebrix/Code-Review-Principles-1ce7276b82a84d2a995d55ad85e1310d?pvs= …
=> Slice 4: Use `ModInstance` type in mods updater

src/utils/idbUtils.test.ts, src/utils/idbUtils.ts
- Fixes an unrecoverable idb error
- See: https://www.notion.so/pixiebrix/SLC-IDB-Hypercare-2024-10-08-11943b21a25380679973e73faa948ad9?pvs=4
- It seems like it's safe to delete the database if this error occurs, but we have yet to actually confirm if this change fixes the issue the users are experiencing.
- We took a look at the source code for this error. see discussion in this slack thread: https://pixiebrix.slack.com/archives/C07MJ3LJ66B/p1728403288315069
=> Add idb error handling for Internal error opening backing store

src/types/contract.ts, src/types/helpers.test.ts, src/types/registryTypes.ts, src/utils/deploymentUtils.test.ts, src/utils/deploymentUtils.ts
- Closes #9257
- Fix type safety of `ModDefinition.metadata.version`: https://github.com/pixiebrix/pixiebrix-extension/issues/9259
=> #9257: fix heartbeat telemetry regression

src/pageEditor/modListingPanel/ModActionMenu.tsx, src/pageEditor/modListingPanel/ModComponents.tsx, src/pageEditor/modListingPanel/ModListItem.test.tsx, src/pageEditor/modListingPanel/ModListItem.tsx
- Part of #9250 (preliminary refactor)
- Removes the majority of props on ModActionItem that are better suited to instead be defined within the scope of the component itself
- No functional changes to the product
=> #9250 Refactor ModActionItem remove unnecessary props

src/utils/idbUtils.ts
- Fixes a minor type error preventing pinning the extension version in app: https://github.com/pixiebrix/pixiebrix-app/pull/5846
- Confirmed this fixes the type issue in app by pinning the version in this branch using `❯ npm run update-extension -- pin-2.1.4`
- Didn't investigate too deeply as to why this type error didn't pop up earlier in extension, likely due to slight tsconfig differences.
=> Fix type error when pinning 2.1.4 extension to app

src/components/IsolatedComponent.scss
- Fixes bug in our IsolatedComponents css caused by a change in how Chrome handles CSS Highlight Inheritance
- See https://chromestatus.com/feature/5090853643354112 for further details
https://www.loom.com/share/576b7a8eee5341ec961e3a37b4f06194?sid=baf1edb4-8308-4309-be66-1b9ee4513591
=> Fix text highlighting bug in IsolatedComponents starting in Chrome 131

src/telemetry/lexicon.ts
- Part of #9151 
- Adds deployment event entries to the lexicon
=> Add deployment event descriptions to lexicon

src/__mocks__/@/store/deactivateModHelpers.ts, src/activation/useActivateMod.test.ts, src/activation/useActivateMod.ts, src/extensionConsole/pages/deployments/DeploymentsContext.tsx, src/extensionConsole/pages/deployments/activateDeployments.ts, src/extensionConsole/pages/deployments/useAutoDeploy.test.ts, src/extensionConsole/pages/deployments/useAutoDeploy.ts, src/extensionConsole/pages/mods/ModsPageActions.test.tsx, src/extensionConsole/pages/mods/ModsPageActions.tsx, src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts, src/extensionConsole/pages/mods/utils/useReactivateMod.ts, src/extensionConsole/store.ts, src/pageEditor/hooks/updateReduxForSavedModDefinition.ts, src/pageEditor/hooks/useCreateModFromMod.ts, src/pageEditor/hooks/useCreateModFromModComponent.ts, src/pageEditor/hooks/useCreateModFromUnsavedMod.ts, src/pageEditor/hooks/useSaveMod.ts, src/pageEditor/store/store.ts, src/sidebar/ConnectedSidebar.tsx, src/sidebar/Tabs.tsx, src/sidebar/TemporaryPanelTabPane.tsx, src/sidebar/store.ts, src/store/deactivateModHelpers.ts
- Refactors our action helpers that take dispatch as an arg and refactored to be higher order functions
=> Make action helpers use the dispatch(actionCreator()) pattern

src/components/floatingActions/FloatingActions.tsx, src/telemetry/events.ts, src/telemetry/lexicon.ts
- Part of #9151
- In addition to adding entries for FAB events and FactoryReset, deletes an apparently unused and never reported FAB event for toggling the setting on the settings page
=> #9151 Add FAB events to lexicon

src/pageEditor/store/editor/editorSlice.test.ts, src/pageEditor/store/editor/editorSlice.ts, src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx, src/store/sessionChanges/sessionChangesListenerMiddleware.ts
- Closes #9358
- Filter by modId when assigning new options args
=> #9358: fix regression in options args assignment

end-to-end-tests/tests/telemetry/errors.spec.ts, src/telemetry/initErrorReporter.ts
- Closes #8348 
- Considered making datadog `allowUntrustedEvents` depend on a env variable to be set to true, but I don't think there's any real harm in just always setting it to true (and avoids having to fuss with CI/e2e specific env vars)
=> 8348: making telemetry e2e tests faster

end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts, src/components/tabLayout/EditorTabLayout.tsx, src/components/tabLayout/__snapshots__/EditorTabLayout.test.tsx.snap, src/pageEditor/panes/ModEditorPane.tsx, src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts, src/pageEditor/store/editor/editorSliceHelpers.test.ts, src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx, src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
- Closes #9376: the root cause was the mod editor pane including the form sequence number in its key
- Closes #7148: the root cause was the editorSlice selector returning a fresh options definition object
- :bug: Mod Options Args are buggy: https://github.com/pixiebrix/pixiebrix-extension/issues/9378
- Finish making selector naming and calling conventions consistent
=> #9376: fix options args focus/active subtab resetting

package-lock.json, package.json, src/components/logViewer/LogCard.tsx, src/components/logViewer/logSlice.ts, src/components/logViewer/usePollModLogs.ts, src/extensionConsole/App.tsx, src/extensionConsole/pages/deployments/useDeactivateUnassignedDeploymentsEffect.ts, src/modDefinitions/modDefinitionHooks.ts, src/modDefinitions/modDefinitionsSlice.ts, src/pageEditor/hooks/useAddNewModComponent.ts, src/pageEditor/layout/EditorLayout.tsx, src/pageEditor/layout/PanelContent.tsx, src/pageEditor/modListingPanel/ActivatedModComponentListItem.tsx, src/pageEditor/modListingPanel/ModComponentActionMenu.tsx, src/pageEditor/modListingPanel/modals/MoveOrCopyToModModal.tsx, src/pageEditor/panes/ModComponentEditorPane.tsx, src/pageEditor/store/editor/editorSelectors/editorAnalysisSelectors.ts, src/pageEditor/store/editor/editorSelectors/editorErrorSelectors.ts, src/pageEditor/store/editor/editorSelectors/editorModComponentSelectors.ts, src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts, src/pageEditor/store/runtime/runtimeSelectors.ts, src/pageEditor/tabs/editTab/dataPanel/tabs/StarterBrickOutputTab.tsx, src/sidebar/sidebarSelectors.ts
- Stepping stone to #7462
- Bump react-redux from 7 to 8
- Closes #9251 (react-redux 8 seems to be better about logging console warnings for unmemoized selectors). I opened the Page Editor/Extension Console/Sidebar and looked for console warnings
- `react-redux` 9 (and therefore RTK 2) depends on React 18 because it drops the `useSyncExternalStore` polyfill (and others). We might be able to keep using that shim and bypass the requirement. But IMO we should likely bump to React 18 first
- Brownbag lightening talk on memoizing selectors
=> #7462: Bump react-redux from 7 to 8 and memoize remaining selectors

.github/workflows/upload-mixpanel-lexicon.yml, tsconfig.json
- The Upload Mixpanel Lexicon workflow broke due to a dependabot update, see context here: https://pixiebrix.slack.com/archives/C023KL47XV4/p1730746145290529
- This PR adds the `es2022` setting to the compile command, and
- Sets the workflow to run on every pull_request to main (but only actually upload the file on merge) so that we can catch breaking changes in the future
=> Fix Upload Mixpanel Lexicon workflow & set to run in CI

scripts/__snapshots__/manifest.test.js.snap, src/contentScript/contentScriptCore.ts, src/manifest.json
- Removes the hack we were using to work-around the issue of the content script not running in sandbox srcdoc iframes since the underlying chromium bug is now fixed.
- https://issues.chromium.org/issues/355256366?pli=1
- Clean up the unused feature flag once this is released and stable.
- [N/A] Added jest or playwright tests and/or storybook stories (Already covered by existing test)
=> removing srcdoc sandbox iframe hack

src/activation/useActivateMod.ts, src/telemetry/events.ts, src/telemetry/lexicon.ts
- Part of #9151
- Also alphabetizes events.ts and lexicon.ts
- Deprecates `MarketplaceActivate` in favor of `ModActivate` (see description)
- Renames display name `MarketplaceActivate` -> `ExtensionConsoleModActivate`
=> #9151 Add MarketplaceActivate and LinkExtension events to lexicon

.eslintrc.js, src/bricks/transformers/getAllTransformers.ts, src/bricks/transformers/selectElement.test.ts, src/bricks/transformers/selectElement.ts, src/contentScript/contentScriptPlatform.ts, src/contentScript/platform/contentScriptPlatformProtocol.ts, src/platform/platformBase.ts, src/platform/platformProtocol.ts, src/testUtils/platformMock.ts
- Part of #9419
- Defines an extended content script platform protocol type
- Move `userSelectElementRefs` method into an extended content script platform
- There are other bricks that reference the `contentScript` module:
- Some of these affordances need to be moved to platform protocol, e.g.: re-initializing mods: https://github.com/pixiebrix/pixiebrix-extension/blob/a4812c9a2cc022c74856220a0d39de33694fd266/src/bricks/effects/reactivate.ts#L20-L20 
- Some of these utilities need to be moved out of the `contentScript` module as they'd be relevant to any context with `dom` access/capabilities
- As noted in https://github.com/pixiebrix/pixiebrix-extension/pull/9420, a lot of we'll defer until monorepo  / web platform as it will be easier to reliably spot problems
For more information on …
=> #9419: move userSelectElementRefs into extended content script platform

src/activation/useActivateMod.test.ts, src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts, src/extensionConsole/pages/settings/useDeploymentKeySetting.test.ts, src/hooks/useAsyncState.test.ts, src/pageEditor/documentBuilder/hooks/useDuplicateElement.test.ts, src/pageEditor/hooks/useBuildAndValidateMod.test.ts, src/pageEditor/hooks/useCreateModFromMod.test.ts, src/pageEditor/hooks/useCreateModFromModComponent.test.ts, src/pageEditor/hooks/useDeleteDraftModComponent.test.ts, src/pageEditor/hooks/useSaveMod.test.ts, src/pageEditor/testHelpers.ts, src/testUtils/testHelpers.tsx
- Part of #3164
- Drops `act` from wrapper in favor of importing from `@testing-library/react-hooks` so it's easier to find/replace during `testing-library/react` upgrade. (React 18 drops separate `@testing-library/react-hooks` library, so there's a single `act` hook)
- Alternative would be to continue to export `hookAct` from `testHelpers` and rename/replace uses during React 18/testing library upgrade
- Drop/rework other hooks: https://github.com/testing-library/react-hooks-testing-library/blob/chore/migration-guide/MIGRATION_GUIDE.md 
=> #3164: drop deprecated `act` hook wrapper method

src/hooks/useIsMounted.ts
- Fix bug in `useIsMounted` uncovered by strict mode in React 18 testing library behavior
- On the 2nd render/useEffect the component was considered unmounted
=> Fix `useIsMounted` for strict mode

knip.mjs, package-lock.json, package.json, src/components/richTextEditor/RichTextEditor.module.scss, src/components/richTextEditor/RichTextEditor.test.tsx, src/components/richTextEditor/RichTextEditor.tsx, src/components/richTextEditor/toolbar/BulletedListButton.tsx, src/components/richTextEditor/toolbar/HorizontalRuleButton.tsx, src/components/richTextEditor/toolbar/NumberedListButton.tsx, src/components/richTextEditor/toolbar/RemoveTextFormattingButton.tsx, src/components/richTextEditor/toolbar/StrikethroughButton.tsx, src/components/richTextEditor/toolbar/Toolbar.tsx, src/components/richTextEditor/toolbar/UnderlineButton.tsx
- Part of #9338
- Adds the following buttons to the Rich Text Editor toolbar:
- Underline
- Strikethrough
- Numbered List
- Bulleted List
- Horizontal rule
- I'm aware that the button toolbar actions have some obvious repetition that can be extracted. I propose we focus on doing that in a future slice, per sake of time.
- The following buttons need to be added to a follow-up slice:
- Link button 
- Url insertion dialog was more complicated than I anticipated. [See this branch here for progress on that](https://github.com/pixiebrix/pixiebrix-extension/compare/main...feature/9338_add_link_toolbar_action)
- Please ask me for a sync update on this one
- Blockquote button
- Blockquote doesn't seem to have any styling applied to it in any of our document renderers. We might considering adding …
=> #9338 Add Rich Text Editor toolbar buttons

src/background/deploymentUpdater.test.ts, src/pageEditor/modListingPanel/ModListingPanel.tsx, src/pageEditor/store/editor/editorSelectors/editorModSelectors.test.ts, src/pageEditor/store/editor/editorSelectors/editorNavigationSelectors.ts, src/pageEditor/store/editor/editorSlice.test.ts, src/pageEditor/store/editor/editorSlice.ts, src/pageEditor/store/editor/editorSliceHelpers.test.ts, src/pageEditor/store/editor/pageEditorTypes/editorStateEphemeral.ts, src/pageEditor/store/editor/pageEditorTypes/editorStateMigrated.ts, src/pageEditor/store/editor/pageEditorTypes/editorStateSynced.ts, src/pageEditor/store/editor/pageEditorTypes/index.ts, src/pageEditor/tabs/editTab/useReportTraceError.test.tsx, src/store/editorInitialState.ts, src/store/editorMigrations.test.ts, src/store/editorMigrations.ts
- Part of Page Editor State low-hanging fruit 
- See https://www.notion.so/pixiebrix/DevEx-Priorities-13543b21a253807283b4fae891dab992
- Splits Editor State into a union of three types based on usage (Migrated, Synced, Ephemeral)
- Renames `isModListExpanded` -> `isModListingPanelExpanded`
- Creates a migration to align the persisted state with the improved shape
=> Refactor page editor state types

.pre-commit-config.yaml
- Disables the linting pre-commit hook due to it taking too long to run
=> Disable linting pre commit hook

src/bricks/effects/pageState.test.ts, src/bricks/effects/pageState.ts
- Fixes bug where `__value__` and `__type__` appear as mod variables (in var popover and mod variables pane) when passing a variable to the `@pixiebrix/state/set` brick
=> Ignore variable expression in get variable schema

pixiebrix-extension.iml
- Mark extension `dist` directory as excluded from IntelliJ search/find
- @fungairino this would be a good step to add in our monorepo migration guide
=> Mark extension `dist` directory as excluded in IntelliJ

.github/workflows/ci.yml, applications/browser-extension/package.json, applications/browser-extension/src/pageEditor/store/editor/editorSlice.test.ts, applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts, libraries/utils/jest.config.js, libraries/utils/package.json, libraries/utils/src/debugUtils.test.ts, libraries/utils/src/debugUtils.ts, libraries/utils/tsconfig.json, package-lock.json, package.json
- Part of #9430
- As part of the monorepo trailblazing, this PR sets up the first extracted utils library, extracting some debugging util that isn't used anywhere else (namely `pixiebrix-app`) and doesn't have any other dependencies
- This will make it easier for us to properly set up `nx` and catch any potential issues.
- Initial set up with some duplicated jest and tsconfig
- Follow-up will extract common base configuration to the root, and add linting
- For ease of starting this out, this new utils library is build-less, but we will likely want to move towards each library project producing its compiled js so we can take advantage of `nx`'s build and caching mechanisms. I will look into this in the next set of changes alongside creating a root common ts config.
- For reference see Nx's …
=> #9430: extracting first util lib

.github/workflows/ci.yml, libraries/utils/.eslintrc.js, libraries/utils/package.json, libraries/utils/src/debugUtils.ts, libraries/utils/src/globals.d.ts, package.json
- Add eslint config for `libraries/utils`
- Current enforces base `eslint-config-pixiebrix`. There are some rules (e.g., about nullish, etc. that aren't enforced)
- Improve lint command naming: https://pixiebrix.slack.com/archives/C080KB9R76G/p1731429258921059. E.g., `lint` should likely run all checks (instead of having to run `lint:full`)
- Move main eslint config into the monorepo so we can iterate on configuration sharing across workspaces: https://pixiebrix.slack.com/archives/C080KB9R76G/p1731429207637519
=> Add eslint config for `libraries/utils`

.github/workflows/ci.yml
- Fixes an issue where the final e2e report isn't including all the html report of all the shard runs. Ex: https://github.com/pixiebrix/pixiebrix-extension/actions/runs/11806403707/job/32891692321?pr=9490
- Verified by checking that the "Password protect merged Playwright report" step in the Create report job produces a file larger than 15kb
=> fix uploading the complete e2e test report

.github/workflows/beta-release.yaml, applications/browser-extension/scripts/upload-extension.sh, applications/browser-extension/scripts/upload-sourcemaps.sh
- Fixes path in upload scripts to account for workspace
=> fix rainforest and sourcemaps upload scripts

.idea/nx-angular-config.xml
- Add IntelliJ nx console plugin settings file to git
- Plugin: https://plugins.jetbrains.com/plugin/21060-nx-console
- Developers still have to grab the pluigin themselves
- Not sure why nx is create an Angular-framework configuration file. Perhaps that's their default if you don't have: https://nx.dev/nx-api/react
=> Add IntelliJ nx console plugin settings file to git

applications/browser-extension/scripts/upload-extension.sh
-  Prevents zipping the full `/applications/browser-extension/dist` path
- Fixes [Rainforest failures](https://app.rainforestqa.com/runs/1992118)
- Considered `pushd` and `popd` instead of `cd`, but wasn't certain it was guaranteed to be available (sh vs bash)
=> Only upload the dist directory to AWS

.github/workflows/ci.yml, .github/workflows/end-to-end-tests.yml, .gitignore, applications/browser-extension/tsconfig.json, knip.mjs, libraries/utils/.eslintrc.js, libraries/utils/package.json, libraries/utils/src/debugUtils.test.ts, libraries/utils/src/debugUtils.ts, libraries/utils/tsconfig.json, libraries/utils/tsconfig.lib.json, libraries/utils/tsconfig.test.json, nx.json, package-lock.json, package.json, tsconfig.base.json, tsconfig.json
- Closes #9430
- Sets up incremental TS builds for our monorepo to speed up typescript compilation and development. See: https://www.typescriptlang.org/docs/handbook/project-references.html
- We could go with a "buildless" approach for our TS configuration but this over the long run will make our type checking a lot slower
- Verified that `tsc --build --watch` recompiles only the utils directory when changes are made to it, and leaves the whole extension project untouched
- Add @nx/js plugin to handle ts tasks and auto updating tsconfig references
- Make our eslint config situation better
=> #9430: tsconfig references refactor

applications/browser-extension/src/components/richTextEditor/ErrorToast.tsx, applications/browser-extension/src/components/richTextEditor/RichTextEditor.module.scss
- Quickfix for an issue that @Pashaminkovsky noticed were the toast notification for displaying rich text editor errors was getting the wrong display property when hidden, preventing mouse-clicking into the editor in the bottom-left corner
=> Fix display property on RichTextEditor error toast

applications/browser-extension/src/components/formBuilder/formBuilderHelpers.ts, applications/browser-extension/src/components/formBuilder/widgets/RichTextWidget.tsx
- Adds Default Value to the Rich Text field
- We had originally disabled it due to requirements for validation, but forgot to add it back in as acceptance criteria for the Image Upload feature
- As discussed with @Pashaminkovsky, follow-up work is to validate and properly throw errors if default value is not compatible with the Rich Text editor; we are leaving it up to the Mod Developer to make sure that they're passing html
https://www.loom.com/share/c9af0bf99ba54c9a8f815bb4fd7a7c11
=> Add default value to Rich Text field

applications/browser-extension/src/pageEditor/modListingPanel/ModListItem.tsx
- Fixes bug with the logic to set the alternate background in ModListItem
- <img width="305" alt="image" src="https://github.com/user-attachments/assets/28be3678-8126-44cd-ac42-9a51034ae2c1">
=> fix logic for setting alternate background in mod list items

.idea/nx-angular-config.xml, applications/browser-extension/src/modDefinitions/modDefinitions.test.tsx
- Fix flaky mod definitions test to prevent "Mod definitions not loaded yet. Try again." error
=> Fix flaky mod definitions test

applications/browser-extension/src/components/formBuilder/widgets/RichTextWidget.tsx, applications/browser-extension/src/components/richTextEditor/RichTextEditor.tsx
- Fixes an issue where the FormPreview will throw if a Rich Text field specifies an asset database via mod option, but the option has not be configured (e.g. under "current inputs")
=> Bugfix: Don't throw error in FormPreview if assetDatabase is not a UUID
